### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by xMSHAKSxg** [bensku/Skript#1003]
[19:20:57 ERROR]: #!#! [Skript] Severe Error:
[19:20:57 ERROR]: #!#!
[19:20:57 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[19:20:57 ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[19:20:57 ERROR]: #!#! and check whether this error has already been reported.
[19:20:57 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[19:20:57 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[19:20:57 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[19:20:57 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[19:20:57 ERROR]: #!#!
[19:20:57 ERROR]: #!#! Stack trace:
[19:20:57 ERROR]: #!#! java.lang.IllegalStateException: Unregistered scoreboard component
[19:20:57 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.scoreboard.CraftTeam.checkState(CraftTeam.java:217)
[19:20:57 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.scoreboard.CraftTeam.getName(CraftTeam.java:25)
[19:20:57 ERROR]: #!#!     at com.gmail.thelimeglass.Stylishboards.StyleManager.getTeamValue(StyleManager.java:151)
[19:20:57 ERROR]: #!#!     at com.gmail.thelimeglass.Stylishboards.StyleManager.shouldUpdate(StyleManager.java:98)
[19:20:57 ERROR]: #!#!     at com.gmail.thelimeglass.Stylishboards.StyleManager.updateScore(StyleManager.java:122)
[19:20:57 ERROR]: #!#!     at com.gmail.thelimeglass.Stylishboards.StyleManager.updateScore(StyleManager.java:134)
[19:20:57 ERROR]: #!#!     at com.gmail.thelimeglass.Stylishboards.ExprStylishSlotText.change(ExprStylishSlotText.java:60)
[19:20:57 ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:271)
[19:20:57 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[19:20:57 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[19:20:57 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[19:20:57 ERROR]: #!#!     at ch.njol.skript.effects.Delay$1.run(Delay.java:94)
[19:20:57 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[19:20:57 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[19:20:57 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
[19:20:57 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[19:20:57 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[19:20:57 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[19:20:57 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[19:20:57 ERROR]: #!#!
[19:20:57 ERROR]: #!#! Version Information:
[19:20:57 ERROR]: #!#!   Skript: 2.2-dev27
[19:20:57 ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[19:20:57 ERROR]: #!#!   Minecraft: 1.8.8
[19:20:57 ERROR]: #!#!   Java: 1.8.0_151 (Java HotSpot(TM) Client VM 25.151-b12)
[19:20:57 ERROR]: #!#!   OS: Windows 10 x86 10.0
[19:20:57 ERROR]: #!#!
[19:20:57 ERROR]: #!#! Running CraftBukkit: false
[19:20:57 ERROR]: #!#!
[19:20:57 ERROR]: #!#! Current node: null
[19:20:57 ERROR]: #!#! Current item: set [skellett] (text|name|display|data|string) [of] id [based] [score] [(with [id]|named)] %string% to "د8? د7Rank دe%coloured the prefix of loop-player%"
[19:20:57 ERROR]: #!#!
[19:20:57 ERROR]: #!#! Thread: Server thread
[19:20:57 ERROR]: #!#!
[19:20:57 ERROR]: #!#! End of Error.
[19:20:57 ERROR]: #!#!
[19:20:58 ERROR]: #!#!

[19:40:13 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
[19:40:13 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[19:40:13 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[19:40:13 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)

**Comment by TheBentoBox** [comment]
1. This is an add-on error related to one of Lime's add-ons, as you can see in the stack trace. I assume it's Skellett since I believe it has scoreboard support.
2. Don't open issues if you're not using the latest version. You're on dev27, not dev32.
3. You're on 1.8, which this fork isn't compatible with any longer. Don't open issues if you're not using at least 1.9.
