### ISSUE TITLE
Error on Spigot 1.12.2. (Task #84).

### ISSUE THREAD

**Issue by TheIntelloBox** [bensku/Skript#1004]
[22:00:47] [Server thread/INFO]: [Skript] Loading variables...
[22:00:47] [Server thread/INFO]: [Skript] Loaded 3341 variables in 0.3 seconds
[22:00:47] [Server thread/INFO]: [Skript] All scripts loaded without errors.
[22:00:47] [Server thread/WARN]: [Skript] Task #84 for Skript v2.2-dev32c generated an exception
java.lang.NoSuchMethodError: ch.njol.skript.command.Commands.loadCommand(Lch/njol/skript/config/SectionNode;Z)Lch/njol/skript/command/ScriptCommand;
	at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:571) ~[Skript%20(1).jar:?]
	at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:347) ~[Skript%20(1).jar:?]
	at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:359) ~[Skript%20(1).jar:?]
	at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:289) ~[Skript%20(1).jar:?]
	at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:319) ~[Skript%20(1).jar:?]
	at ch.njol.skript.Skript$2.run(Skript.java:446) ~[Skript%20(1).jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.2-R0.1-SNAPSHOT-b1472.jar:git-Spigot-00128b5-d063cd0]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.2-R0.1-SNAPSHOT-b1472.jar:git-Spigot-00128b5-d063cd0]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2-R0.1-SNAPSHOT-b1472.jar:git-Spigot-00128b5-d063cd0]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2-R0.1-SNAPSHOT-b1472.jar:git-Spigot-00128b5-d063cd0]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2-R0.1-SNAPSHOT-b1472.jar:git-Spigot-00128b5-d063cd0]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2-R0.1-SNAPSHOT-b1472.jar:git-Spigot-00128b5-d063cd0]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

**Comment by Syst3ms** [comment]
Please provide the full error

**Comment by bensku** [comment]
Your Skript jar might be corrupted. Please reinstall it.
