### ISSUE TITLE
Tooltip internal error 1.12 (dev29)

### ISSUE THREAD

**Issue by Goetheus** [bensku/Skript#1023]
Hi Bensku!
I have bad news for you :p
I get an error message and an error console with the tooltip.
Script:
```
command /tooltip:
	trigger:
		send "<tooltip:test>test<reset>" to player
```
In game message error: An internal error occurred while attempting to perform this command.
Console error:
```
19.12 00:07:42 [Server] ERROR #!#! Stack trace:
19.12 00:07:42 [Server] ERROR #!#! java.lang.NullPointerException
19.12 00:07:42 [Server] ERROR #!#!     at ch.njol.skript.util.chat.BungeeConverter.convert(BungeeConverter.java:51)
19.12 00:07:42 [Server] ERROR #!#!     at ch.njol.skript.util.chat.BungeeConverter.convert(BungeeConverter.java:59)
19.12 00:07:42 [Server] ERROR #!#!     at ch.njol.skript.effects.EffMessage.execute(EffMessage.java:88)
19.12 00:07:42 [Server] ERROR #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
19.12 00:07:42 [Server] ERROR #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
19.12 00:07:42 [Server] ERROR #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
19.12 00:07:42 [Server] ERROR #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
19.12 00:07:42 [Server] ERROR #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:220)
19.12 00:07:42 [Server] ERROR #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:182)
19.12 00:07:42 [Server] ERROR #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:268)
19.12 00:07:42 [Server] ERROR #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:163)
19.12 00:07:42 [Server] ERROR #!#!     at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
19.12 00:07:42 [Server] ERROR #!#!     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19.12 00:07:42 [Server] ERROR #!#!     at java.lang.reflect.Method.invoke(Method.java:498)
19.12 00:07:42 [Server] ERROR #!#!     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
```

All other json format works! (link, command and suggest)

Thank you for help! :)
Kiss <3

**Comment by Snow-Pyon** [comment]
You must use the latest version to report a bug, it's invalid otherwise.

**Comment by TheBentoBox** [comment]
What @Snow-Pyon said.
