### ISSUE TITLE
Some error upon starting Skript.

### ISSUE THREAD

**Issue by Boii1** [bensku/Skript#1029]
This error appears:
`[19:06:04 INFO]: [Skript] Enabling Skript v2.2-dev32c
[19:06:04 ERROR]: Error occurred while enabling Skript v2.2-dev32c (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.Effect.getName()Ljava/lang/String;
        at ch.njol.skript.util.VisualEffect$Type.<init>(VisualEffect.java:196) ~[?:?]
        at ch.njol.skript.util.VisualEffect$Type.<clinit>(VisualEffect.java:63) ~[?:?]
        at ch.njol.skript.util.VisualEffect.<clinit>(VisualEffect.java:269) ~[?:?]
        at ch.njol.skript.classes.data.SkriptClasses.<clinit>(SkriptClasses.java:889) ~[?:?]
        at ch.njol.skript.Skript.onEnable(Skript.java:319) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[craftbukkit.jar:git-Bukkit-45c8386]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) [craftbukkit.jar:git-Bukkit-45c8386]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [craftbukkit.jar:git-Bukkit-45c8386]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:368) [craftbukkit.jar:git-Bukkit-45c8386]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:329) [craftbukkit.jar:git-Bukkit-45c8386]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:412) [craftbukkit.jar:git-Bukkit-45c8386]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:373) [craftbukkit.jar:git-Bukkit-45c8386]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:328) [craftbukkit.jar:git-Bukkit-45c8386]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:248) [craftbukkit.jar:git-Bukkit-45c8386]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:522) [craftbukkit.jar:git-Bukkit-45c8386]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]`
Any ideas?

**Comment by Snow-Pyon** [comment]
Skript doesn't support CraftBukkit, use Spigot.

**Comment by Boii1** [comment]
Alright, I kinda got that after checking Issue #700 only after posting this.
Anyways I cannot find spigot from the build tools result.

**Comment by Snow-Pyon** [comment]
it should be on the main folder (the spigot-(minecraft version).jar)

**Comment by Boii1** [comment]
I'm building the revision instead as apparently it is finding things missing. Thank you for the help.

**Comment by HYPExMon5ter** [comment]
Just go to getbukkit.org
