### ISSUE TITLE
Script doesn't work

### ISSUE THREAD

**Issue by Professor-Dragon** [bensku/Skript#1035]
I had an issue when putting this script in my script files.

[19:48:23 ERROR]: #!#!
[19:48:23 ERROR]: #!#! [Skript] Severe Error:
[19:48:23 ERROR]: #!#! Could not load Tesla.sk
[19:48:23 ERROR]: #!#!
[19:48:23 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[19:48:23 ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[19:48:23 ERROR]: #!#! and check whether this error has already been reported.
[19:48:23 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[19:48:23 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[19:48:23 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[19:48:23 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[19:48:23 ERROR]: #!#!
[19:48:23 ERROR]: #!#! Stack trace:
[19:48:23 ERROR]: #!#! java.lang.IllegalStateException: Cannot use classinfos until registration is over
[19:48:23 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.checkAllowClassInfoInteraction(Classes.java:242)
[19:48:23 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfos(Classes.java:247)
[19:48:23 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:416)
[19:48:23 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.parse(Classes.java:451)
[19:48:23 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:359)
[19:48:23 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:418)
[19:48:23 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1132)
[19:48:23 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1084)
[19:48:23 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1123)
[19:48:23 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:221)
[19:48:23 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[19:48:23 ERROR]: #!#!     at ch.njol.skript.lang.Condition.parse(Condition.java:83)
[19:48:23 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:833)
[19:48:23 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:513)
[19:48:23 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:271)
[19:48:23 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:167)
[19:48:23 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[19:48:23 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[19:48:23 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646)
[19:48:23 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchServerCommand(CraftServer.java:632)
[19:48:23 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.DedicatedServer.aM(DedicatedServer.java:353)
[19:48:23 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:317)
[19:48:23 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634)
[19:48:23 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537)
[19:48:23 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[19:48:23 ERROR]: #!#!
[19:48:23 ERROR]: #!#! Version Information:
[19:48:23 ERROR]: #!#!   Skript: 2.2-dev22f
[19:48:23 ERROR]: #!#!   Bukkit: 1.8-R0.1-SNAPSHOT
[19:48:23 ERROR]: #!#!   Minecraft: 1.8
[19:48:23 ERROR]: #!#!   Java: 1.8.0_151 (Java HotSpot(TM) 64-Bit Server VM 25.151-b12)
[19:48:23 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[19:48:23 ERROR]: #!#!
[19:48:23 ERROR]: #!#! Running CraftBukkit: false
[19:48:23 ERROR]: #!#!
[19:48:23 ERROR]: #!#! Current node: player has permission "tesla.admin": (Tesla.sk, line 11)
[19:48:23 ERROR]: #!#! Current item: null
[19:48:23 ERROR]: #!#!
[19:48:23 ERROR]: #!#! Thread: Server thread
[19:48:23 ERROR]: #!#!
[19:48:23 ERROR]: #!#! End of Error.
[19:48:23 ERROR]: #!#!

**Comment by TheBentoBox** [comment]
You're using an outdated version and are on 1.8 which is not supported by the current most up-to-date version of Skript, so we can't help you.

**Comment by Professor-Dragon** [comment]
What is the dated version then?

**Comment by TheBentoBox** [comment]
The updated version will not work on your server since it is 1.8, like I said. Your best bet is [dev25](https://github.com/bensku/Skript/releases/tag/dev25) but if that doesn't solve this error we cannot help you further at the moment.

**Comment by Professor-Dragon** [comment]
It Worked!
Thank You so much :)
