### ISSUE TITLE
Entity: play raw sound "" \ is not working

### ISSUE THREAD

**Issue by MoneyAlpha** [bensku/Skript#1056]
[11:49:00 INFO]: MoneyAlpha issued server command: /sk reload AutoSell
[11:49:09 ERROR]: #!#! 
[11:49:09 ERROR]: #!#! [Skript] Severe Error:
[11:49:09 ERROR]: #!#! Could not load OtoSat.sk
[11:49:09 ERROR]: #!#! 
[11:49:09 ERROR]: #!#! Something went horribly wrong with Skript.
[11:49:09 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[11:49:09 ERROR]: #!#! Your Minecraft version or server software appears to be unsupported by Skript (bensku's version).
[11:49:09 ERROR]: #!#! Currently only supported servers are Spigot and its forks for Minecraft 1.9 or newer.
[11:49:09 ERROR]: #!#! Other versions might work, but since you're getting this error message something is NOT working,
[11:49:09 ERROR]: #!#! nor it will work, unless you switch to supported platform.
[11:49:09 ERROR]: #!#! Issue tracker: https://github.com/bensku/Skript/issues (only if you know what you're doing!)
[11:49:09 ERROR]: #!#! 
[11:49:09 ERROR]: #!#! Stack trace:
[11:49:09 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for visualeffect
[11:49:09 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[11:49:09 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.createExprInfo(SkriptParser.java:1788)
[11:49:09 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1755)
[11:49:09 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1503)
[11:49:09 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1476)
[11:49:09 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:225)
[11:49:09 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:180)
[11:49:09 ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:59)
[11:49:09 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:919)
[11:49:09 ERROR]: #!#!     at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:54)
[11:49:09 ERROR]: #!#!     at ch.njol.skript.lang.Conditional.<init>(Conditional.java:44)
[11:49:09 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1005)
[11:49:09 ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:450)
[11:49:09 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:571)
[11:49:09 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:347)
[11:49:09 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:359)
[11:49:09 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:392)
[11:49:09 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:188)
[11:49:09 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[11:49:09 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146)
[11:49:09 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666)
[11:49:09 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189)
[11:49:09 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001)
[11:49:09 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[11:49:09 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[11:49:09 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[11:49:09 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[11:49:09 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
[11:49:09 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[11:49:09 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774)
[11:49:09 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[11:49:09 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[11:49:09 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[11:49:09 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[11:49:09 ERROR]: #!#! 
[11:49:09 ERROR]: #!#! Version Information:
[11:49:09 ERROR]: #!#!   Skript: 2.2-dev32d
[11:49:09 ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[11:49:09 ERROR]: #!#!   Minecraft: 1.8.8
[11:49:09 ERROR]: #!#!   Java: 1.8.0_151 (Java HotSpot(TM) 64-Bit Server VM 25.151-b12)
[11:49:09 ERROR]: #!#!   OS: Windows Server 2016 amd64 10.0
[11:49:09 ERROR]: #!#! 
[11:49:09 ERROR]: #!#! Running CraftBukkit: false
[11:49:09 ERROR]: #!#! Running Spigot (or compatible): true
[11:49:09 ERROR]: #!#! Running Paper (or compatible): true
[11:49:09 ERROR]: #!#! 
[11:49:09 ERROR]: #!#! Current node: play "BAT_DEATH" to player at volume 10 (OtoSat.sk, line 37)
[11:49:09 ERROR]: #!#! Current item: null
[11:49:09 ERROR]: #!#! Thread: Server thread
[11:49:09 ERROR]: #!#! 
[11:49:09 ERROR]: #!#! Language: english
[11:49:09 ERROR]: #!#! Link parse mode: DISABLED
[11:49:09 ERROR]: #!#! 
[11:49:09 ERROR]: #!#! End of Error.
[11:49:09 ERROR]: #!#! 

Why does it give such an error ?

Please help solve.

Thanks.

**Comment by Syst3ms** [comment]
You forgot `sound` after `play`. Right now, it's conflicting with the `play %visualeffect%` effect, which is disabled in this version in order for it to work on 1.8.

**Comment by bensku** [comment]
I do not support 1.8
