### ISSUE TITLE
Error on Paper Spigot 1.12.2, Using Java 8.

### ISSUE THREAD

**Issue by TheIntelloBox** [bensku/Skript#1061]
[23:51:55] [Server thread/INFO]: [Skript] Loading variables...
[23:51:56] [Server thread/INFO]: [Skript] Loaded 3341 variables in 0.1 seconds
[23:51:56] [Server thread/INFO]: [Skript] All scripts loaded without errors.
[23:51:56] [Server thread/WARN]: [Skript] Task #82 for Skript v2.2-dev32c generated an exception
java.lang.NoSuchMethodError: ch.njol.skript.command.Commands.loadCommand(Lch/njol/skript/config/SectionNode;Z)Lch/njol/skript/command/ScriptCommand;
	at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:571) ~[Skript%20(1).jar:?]
	at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:347) ~[Skript%20(1).jar:?]
	at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:359) ~[Skript%20(1).jar:?]
	at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:289) ~[Skript%20(1).jar:?]
	at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:319) ~[Skript%20(1).jar:?]
	at ch.njol.skript.Skript$2.run(Skript.java:446) ~[Skript%20(1).jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.2.jar:git-Paper-1310]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [patched_1.12.2.jar:git-Paper-1310]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [patched_1.12.2.jar:git-Paper-1310]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1310]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1310]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1310]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

**Comment by Snow-Pyon** [comment]
Your Skript jar is corrupted or something, try with dev32d

**Comment by TheIntelloBox** [comment]
Same bug with dev32d.

**Comment by Snow-Pyon** [comment]
Well, you'll have to check your server because I cannot reproduce it in any way, kinda weird error.

**Comment by bensku** [comment]
Try without other plugins, just in case they mess something up.

**Comment by NoysHunka** [comment]
I have same problem, what can i do? I tried reinstall my server, but it still doesn't work.

**Comment by bensku** [comment]
Again, try with freshly downloaded Skript and no other plugins.

**Comment by xXAndrew28Xx** [comment]
Also make sure you're not replacing the jar while it's running on the server.
