### ISSUE TITLE
Najnowsza wersja skript nie działa

### ISSUE THREAD

**Issue by VenomPCPL** [bensku/Skript#1067]
Witam.
Po pobraniu najnowszej wersji skript nie działają mi żadne komendy oraz sama komenda /skript
Informacje:
        Wersja: Spigot 1.12.2
        Java: 8
Błąd przy ładowaniu skryptów::
[08:07:15 INFO]: [Skript] Loaded 941 variables in 0.0 seconds[08:07:15 ERROR]: #!#! at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)[08:07:15 ERROR]: #!#! at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:571)[08:07:15 ERROR]: #!#! at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:359)[08:07:15 ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:180)[08:07:15 ERROR]: #!#! Stack trace:[08:07:15 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.[08:07:15 ERROR]: #!#! Link parse mode: DISABLED

**Comment by Syst3ms** [comment]
Only English here, sorry.
