### ISSUE TITLE
WorldGuard error Task #42

### ISSUE THREAD

**Issue by MrNygus** [bensku/Skript#108]
[21:52:07] [Server thread/WARN]: [Skript] Task #42 for Skript v2.2-dev16 generated an exception
java.lang.NoSuchMethodError: com.sk89q.worldguard.protection.flags.DefaultFlag.fuzzyMatchFlag(Ljava/lang/String;)Lcom/sk89q/worldguard/protection/flags/Flag;
	at uk.co.umbaska.Managers.Enums$10.parse(Enums.java:425) ~[?:?]
	at uk.co.umbaska.Managers.Enums$10.parse(Enums.java:422) ~[?:?]
	at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:415) ~[?:?]
	at ch.njol.skript.registrations.Classes.parse(Classes.java:444) ~[?:?]
	at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:97) ~[?:?]
	at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:86) ~[?:?]
	at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:1) ~[?:?]
	at ch.njol.skript.conditions.CondCompare.init(CondCompare.java:180) ~[?:?]
	at ch.njol.skript.conditions.CondCompare.init(CondCompare.java:131) ~[?:?]
	at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:249) ~[?:?]
	at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176) ~[?:?]
	at ch.njol.skript.lang.Condition.parse(Condition.java:83) ~[?:?]
	at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:833) ~[?:?]
	at ch.njol.skript.command.Commands.loadCommand(Commands.java:467) ~[?:?]
	at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:472) ~[?:?]
	at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:247) ~[?:?]
	at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:201) ~[?:?]
	at ch.njol.skript.Skript$2.run(Skript.java:406) ~[?:?]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.10-R0.1-SNAPSHOT-latest.jar:git-Spigot-c55900f-9856d8a]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.10-R0.1-SNAPSHOT-latest.jar:git-Spigot-c55900f-9856d8a]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:741) [spigot-1.10-R0.1-SNAPSHOT-latest.jar:git-Spigot-c55900f-9856d8a]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.10-R0.1-SNAPSHOT-latest.jar:git-Spigot-c55900f-9856d8a]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [spigot-1.10-R0.1-SNAPSHOT-latest.jar:git-Spigot-c55900f-9856d8a]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot-1.10-R0.1-SNAPSHOT-latest.jar:git-Spigot-c55900f-9856d8a]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]

**Comment by bensku** [comment]
It seems WorldGuard had API break; can you use older version?

If not, you'll need to wait for me to update Skript's WG support.

**Comment by bloggy** [comment]
Please update it, I get a similar error (null point exception):
http://hastebin.com/yirudefidu.profile

**Comment by bensku** [comment]
Of course, I said that latest WorldGuard doesn't work. That means it won't work for anyone using that version, and downgrading always fixes the issue.

As said, update is planned but not high priority unless someone absolutely can't use old WorldGuard.

**Comment by bensku** [comment]
Please try again with next build. If WorldEdit had ABI incompatibility, then it is fixed now. I didn't touch code, but updated linked version.

**Comment by bloggy** [comment]
This error still does exist, just reloaded a skript and got this:

http://hastebin.com/qijocagaju.profile

**Comment by Nicofisi** [comment]
It's an error from SkStuff, it overrides the default Skript effect, you need to talk to its author or remove it @bloggy
