### ISSUE TITLE
Error while loading command

### ISSUE THREAD

**Issue by vodawen** [bensku/Skript#1086]
[16:28:19 ERROR]: #!#!
[16:28:19 ERROR]: #!#! [Skript] Severe Error:
[16:28:19 ERROR]: #!#! Could not load exange.sk
[16:28:19 ERROR]: #!#!
[16:28:19 ERROR]: #!#! Something went horribly wrong with Skript.
[16:28:19 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[16:28:19 ERROR]: #!#! You should report it at https://github.com/bensku/Skript/issues. Please copy paste this report there (or use paste service).
[16:28:19 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[16:28:19 ERROR]: #!#!
[16:28:19 ERROR]: #!#! Stack trace:
[16:28:19 ERROR]: #!#! java.lang.IllegalStateException: No match found
[16:28:19 ERROR]: #!#!     at java.util.regex.Matcher.group(Unknown Source)
[16:28:19 ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:332)
[16:28:19 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:571)
[16:28:19 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:347)
[16:28:19 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:359)
[16:28:19 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:289)
[16:28:19 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:319)
[16:28:19 ERROR]: #!#!     at ch.njol.skript.Skript$2.run(Skript.java:444)
[16:28:19 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
[16:28:19 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[16:28:19 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
[16:28:19 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[16:28:20 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[16:28:20 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[16:28:20 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[16:28:20 ERROR]: #!#!
[16:28:20 ERROR]: #!#! Version Information:
[16:28:20 ERROR]: #!#!   Skript: 2.2-dev32d
[16:28:20 ERROR]: #!#!   Bukkit: 1.12.1-R0.1-SNAPSHOT
[16:28:20 ERROR]: #!#!   Minecraft: 1.12.1
[16:28:20 ERROR]: #!#!   Java: 1.8.0_151 (Java HotSpot(TM) 64-Bit Server VM 25.151-b12)
[16:28:20 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[16:28:20 ERROR]: #!#!
[16:28:20 ERROR]: #!#! Running CraftBukkit: false
[16:28:20 ERROR]: #!#! Running Spigot (or compatible): true
[16:28:20 ERROR]: #!#! Running Paper (or compatible): false
[16:28:20 ERROR]: #!#!
[16:28:20 ERROR]: #!#! Current node: command /exange : (exange.sk, line 1)
[16:28:20 ERROR]: #!#! Current item: null
[16:28:20 ERROR]: #!#! Thread: Server thread
[16:28:20 ERROR]: #!#!
[16:28:20 ERROR]: #!#! Language: english
[16:28:20 ERROR]: #!#! Link parse mode: DISABLED
[16:28:20 ERROR]: #!#!
[16:28:20 ERROR]: #!#! End of Error.
[16:28:20 ERROR]: #!#!

**Comment by Syst3ms** [comment]
Could you show the code ?

**Comment by vodawen** [comment]
it's the first time i try something so i'm pretty sure the code is wrong, but it says "This issue is NOT your fault! You probably can't fix it yourself, either."

**Comment by jaylawl** [comment]
@vodawen it still might be, despite skript's feedback being a nice guy. post your code and we may be able to help!

**Comment by bensku** [comment]
Nah. If Skript gives an error message, it is very rare that it is an actual user error. Could always be corrupted jar file or something like that, but an that is not really an user's fault.

I mean, in this case, it is likely that there is something wrong with the script in question. That does not make it any less an issue of Skript; bad user input (script) should not actually result in an uncaught exception. Exceptions like this usually cause some fallout, making unrelated parts to work unexpectedly or not at all. What should happen is a clear error message that causes no side effects and if possible, helps user to fix their script.

We need the script to find out what Skript is doing wrong, not to point out your mistakes. But we need the script.

**Comment by Pikachu920** [comment]
I think better wording might be `The issue is NOT your fault, but you may have caused it.`

**Comment by xXAndrew28Xx** [comment]
I might PR once I get the chance but here is the regex it matches against: `(?i)^command /?(\\S+)(\\s+(.+))?$`.

**Comment by vodawen** [comment]
I just understood the problem. I had addons of skrip that weren't compatible with this version. my fault . Sorry to have waste your time. And sorry for my bad english.

**Comment by bensku** [comment]
That is very interesting. Skript did not detect any addons while reporting the error. I guess the check might be not as reliable as I had thought.

**Comment by Pikachu920** [comment]
@Snow-Pyon @TheBentoBox can this be reopened? I'm able to reproduce it on a server with just Skript.

**Comment by TheBentoBox** [comment]
Sure @Pikachu920 , can you provide the code that reproduces it?

**Comment by Snow-Pyon** [comment]
Can reproduce; most likely fixed for the next release.
