### ISSUE TITLE
Exception occurred in Skript's main command

### ISSUE THREAD

**Issue by CBM1014** [bensku/Skript#1087]
> [10:46:40 ERROR]: #!#!
[10:46:40 ERROR]: #!#! [Skript] Severe Error:
[10:46:40 ERROR]: #!#! Exception occurred in Skript's main command
[10:46:40 ERROR]: #!#! Used command: /sk reload ariesffa
[10:46:40 ERROR]: #!#!
[10:46:40 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[10:46:40 ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[10:46:40 ERROR]: #!#! and check whether this error has already been reported.
[10:46:40 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[10:46:40 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[10:46:40 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[10:46:40 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[10:46:40 ERROR]: #!#!
[10:46:40 ERROR]: #!#! Stack trace:
[10:46:40 ERROR]: #!#! java.lang.NullPointerException
[10:46:40 ERROR]: #!#!     at ch.njol.skript.lang.function.Functions.clearFunctions(Functions.java:264)
[10:46:40 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.removeTriggers(SkriptEventHandler.java:255)
[10:46:40 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.unloadScript_(ScriptLoader.java:713)
[10:46:40 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.unloadScript(ScriptLoader.java:706)
[10:46:40 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:165)
[10:46:40 ERROR]: #!#!     at pw.yumc.Yum.inject.CommandInjector.onCommand(CommandInjector.java:106)
[10:46:40 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412)
[10:46:40 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375)
[10:46:40 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[10:46:40 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[10:46:40 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[10:46:40 ERROR]: #!#!
[10:46:40 ERROR]: #!#! Version Information:
[10:46:40 ERROR]: #!#!   Skript: 2.2-dev19
[10:46:40 ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[10:46:40 ERROR]: #!#!   Minecraft: 1.8.8
[10:46:40 ERROR]: #!#!   Java: 1.8.0_152 (Java HotSpot(TM) 64-Bit Server VM 25.152-b16)
[10:46:40 ERROR]: #!#!   OS: Windows Server 2016 amd64 10.0
[10:46:40 ERROR]: #!#!
[10:46:40 ERROR]: #!#! Running CraftBukkit: false
[10:46:40 ERROR]: #!#!
[10:46:40 ERROR]: #!#! Current node: null
[10:46:40 ERROR]: #!#! Current item: null
[10:46:40 ERROR]: #!#!
[10:46:40 ERROR]: #!#! Thread: Server thread
[10:46:40 ERROR]: #!#!
[10:46:40 ERROR]: #!#! End of Error.
[10:46:40 ERROR]: #!#!

**Comment by TheBentoBox** [comment]
You're on a very old version of Skript, please update to the latest version before reporting bugs (and your server while you're at it since we don't properly support 1.8 or below).
