### ISSUE TITLE
Error while loading Skript

### ISSUE THREAD

**Issue by GamingGeek** [bensku/Skript#1114]
When I try reload one of my scripts, I get this:
[16:59:44 ERROR]: #!#!
[16:59:44 ERROR]: #!#! [Skript] Severe Error:
[16:59:44 ERROR]: #!#! Could not load teleport.sk
[16:59:44 ERROR]: #!#!
[16:59:44 ERROR]: #!#! Something went horribly wrong with Skript.
[16:59:44 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[16:59:44 ERROR]: #!#! Your Minecraft version or server software appears to be unsupported by Skript (bensku's version).
[16:59:44 ERROR]: #!#! Currently only supported servers are Spigot and its forks for Minecraft 1.9 or newer.
[16:59:44 ERROR]: #!#! Other versions might work, but since you're getting this error message something is NOT working,
[16:59:44 ERROR]: #!#! nor it will work, unless you switch to supported platform.
[16:59:44 ERROR]: #!#! Issue tracker: https://github.com/bensku/Skript/issues (only if you know what you're doing!)
[16:59:44 ERROR]: #!#!
[16:59:44 ERROR]: #!#! Stack trace:
[16:59:44 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for particle
[16:59:44 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[16:59:44 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.createExprInfo(SkriptParser.java:1788)
[16:59:44 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1755)
[16:59:44 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1503)
[16:59:44 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1449)
[16:59:44 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:225)
[16:59:44 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:180)
[16:59:44 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:493)
[16:59:44 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:810)
[16:59:44 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1519)
[16:59:44 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:225)
[16:59:44 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:180)
[16:59:44 ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:59)
[16:59:44 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:919)
[16:59:44 ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:480)
[16:59:44 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:571)
[16:59:44 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:347)
[16:59:44 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:359)
[16:59:44 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:392)
[16:59:44 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:188)
[16:59:44 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[16:59:44 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146)
[16:59:44 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666)
[16:59:44 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:629)
[16:59:44 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:416)
[16:59:44 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:379)
[16:59:44 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[16:59:44 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[16:59:44 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[16:59:44 ERROR]: #!#!
[16:59:44 ERROR]: #!#! Version Information:
[16:59:44 ERROR]: #!#!   Skript: 2.2-dev33
[16:59:44 ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[16:59:44 ERROR]: #!#!   Minecraft: 1.8.8
[16:59:44 ERROR]: #!#!   Java: 1.8.0_161 (Java HotSpot(TM) 64-Bit Server VM 25.161-b12)
[16:59:44 ERROR]: #!#!   OS: Windows Server 2016 amd64 10.0
[16:59:44 ERROR]: #!#!
[16:59:44 ERROR]: #!#! Running CraftBukkit: false
[16:59:44 ERROR]: #!#! Running Spigot (or compatible): true
[16:59:44 ERROR]: #!#! Running Paper (or compatible): true
[16:59:44 ERROR]: #!#!
[16:59:44 ERROR]: #!#! Current node: teleport player to {spectral.limbo} (teleport.sk, line 12)
[16:59:44 ERROR]: #!#! Current item: null
[16:59:44 ERROR]: #!#! Thread: Server thread
[16:59:44 ERROR]: #!#!
[16:59:44 ERROR]: #!#! Language: english
[16:59:44 ERROR]: #!#! Link parse mode: DISABLED
[16:59:44 ERROR]: #!#!
[16:59:44 ERROR]: #!#! End of Error.
[16:59:44 ERROR]: #!#!

**Comment by Snow-Pyon** [comment]
Skript doesn't register any particle type so this is an issue of an addon, closing.
