### ISSUE TITLE
error.

### ISSUE THREAD

**Issue by UzumakiYT** [bensku/Skript#1130]
`[02:00:14 WARN]: [Skript] Task #167 for Skript v2.2-dev33 generated an exception
java.lang.NoSuchMethodError: net.md_5.bungee.api.chat.BaseComponent.setInsertion(Ljava/lang/String;)V
        at ch.njol.skript.util.chat.BungeeConverter.convert(BungeeConverter.java:45) ~[?:?]
        at ch.njol.skript.util.chat.BungeeConverter.convert(BungeeConverter.java:60) ~[?:?]
        at ch.njol.skript.effects.EffMessage.execute(EffMessage.java:88) ~[?:?]
        at ch.njol.skript.lang.Effect.run(Effect.java:52) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[?:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:55) ~[?:?]
        at ch.njol.skript.events.EvtChat$1.execute(EvtChat.java:72) ~[?:?]
        at ch.njol.skript.events.EvtChat$1$1.call(EvtChat.java:91) ~[?:?]
        at ch.njol.skript.events.EvtChat$1$1.call(EvtChat.java:1) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftFuture.run(CraftFuture.java:89) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]`

code 
on chat:	
	cancel event
	send "<tooltip:§a➜ §7CLICK TO SEND A MSG TO §e%player%> <suggest command:/msg %player% > %player's prefix% %player% &8&l» &7 %message%" to all players

**Comment by Snow-Pyon** [comment]
Please stop making issues if you're using 1.8, it isn't to be rude but we only support 1.9+, meaning that if your server is outdated then you'll have to deal with these kind of errors yourself.

**Comment by Nicofisi** [comment]
Pikachu has already answered your issue in #1128
