### ISSUE TITLE
Unknown cause - Invalid looping and lots of strange ArrayStore errors

### ISSUE THREAD

**Issue by TheLimeGlass** [bensku/Skript#1163]
I was getting these errors when trying to use @Snow-Pyon's new InventoryInfo expression added in dev34 (https://github.com/bensku/Skript/blob/master/src/main/java/ch/njol/skript/expressions/ExprInventoryInfo.java)
```
loop integers between 0 and rows of current inventory of player * 9
```
I also tried
```
set {_rows} to rows of current inventory of player
loop numbers between 0 and ({_rows} * 9):
```
And this one above actually caused some ItemType issues for some reason. All that is getting within the loop is the slot item, which may be conflicting because the number is invalid. Here are both the errors I got. I have no clue where they're coming from and why.

```
[02:41:47] [Server thread/ERROR]: #!#! Stack trace:
[02:41:47] [Server thread/ERROR]: #!#! java.lang.ArrayStoreException: ch.njol.skript.aliases.ItemType
[02:41:47] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Converters.convert(Converters.java:305)
[02:41:47] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Converters.convertUnsafe(Converters.java:294)
[02:41:47] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:104)
[02:41:47] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.ExprNamed.get(ExprNamed.java:78)
[02:41:47] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:75)
[02:41:47] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:104)
[02:41:47] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:268)
[02:41:47] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[02:41:47] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[02:41:47] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[02:41:47] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
[02:41:47] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:279)
[02:41:47] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:236)
[02:41:47] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:255)
[02:41:47] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:170)
[02:41:47] [Server thread/ERROR]: #!#!     at sun.reflect.GeneratedMethodAccessor68.invoke(Unknown Source)
[02:41:47] [Server thread/ERROR]: #!#!     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[02:41:47] [Server thread/ERROR]: #!#!     at java.lang.reflect.Method.invoke(Unknown Source)
[02:41:47] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[02:41:47] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[02:41:47] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[02:41:47] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[02:41:47] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1389)
[02:41:47] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232)
[02:41:47] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[02:41:47] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[02:41:47] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[02:41:47] [Server thread/ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[02:41:47] [Server thread/ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
[02:41:47] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[02:41:47] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[02:41:47] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[02:41:47] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[02:41:47] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[02:41:47] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[02:41:47] [Server thread/ERROR]: #!#! 
[02:41:47] [Server thread/ERROR]: #!#! Version Information:
[02:41:47] [Server thread/ERROR]: #!#!   Skript: 2.2-dev34
[02:41:47] [Server thread/ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[02:41:47] [Server thread/ERROR]: #!#!   Minecraft: 1.12.2
[02:41:47] [Server thread/ERROR]: #!#!   Java: 1.8.0_161 (Java HotSpot(TM) 64-Bit Server VM 25.161-b12)
[02:41:47] [Server thread/ERROR]: #!#!   OS: Windows 10 amd64 10.0
[02:41:47] [Server thread/ERROR]: #!#! 
[02:41:47] [Server thread/ERROR]: #!#! Server platform: Spigot
[02:41:47] [Server thread/ERROR]: #!#! 
[02:41:47] [Server thread/ERROR]: #!#! Current node: null
[02:41:47] [Server thread/ERROR]: #!#! Current item: set {_item}(as java.lang.Object) to {_item}(as java.lang.Object) named "§a§l%{_item}% §7@@ §6$§l%{_cost}%"
[02:41:47] [Server thread/ERROR]: #!#! Thread: Server thread
[02:41:47] [Server thread/ERROR]: #!#! 
[02:41:47] [Server thread/ERROR]: #!#! Language: english
[02:41:47] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
```
Second error:

```
[02:40:50] [Server thread/ERROR]: #!#! Stack trace:
[02:40:50] [Server thread/ERROR]: #!#! java.lang.ArrayStoreException: [Ljava.lang.Number;
[02:40:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Converters.convert(Converters.java:305)
[02:40:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Converters.convertUnsafe(Converters.java:294)
[02:40:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:104)
[02:40:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.base.SimplePropertyExpression.get(SimplePropertyExpression.java:55)
[02:40:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:75)
[02:40:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:104)
[02:40:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getSingle(SimpleExpression.java:62)
[02:40:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.ExprArithmetic.get(ExprArithmetic.java:172)
[02:40:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.ExprArithmetic.get(ExprArithmetic.java:1)
[02:40:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:104)
[02:40:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getSingle(SimpleExpression.java:62)
[02:40:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.ExprNumbers.iterator(ExprNumbers.java:91)
[02:40:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Loop.walk(Loop.java:79)
[02:40:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[02:40:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
[02:40:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:151)
[02:40:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:109)
[02:40:50] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[02:40:50] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[02:40:50] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[02:40:50] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1889)
[02:40:50] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33)
[02:40:50] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10)
[02:40:50] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[02:40:50] [Server thread/ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[02:40:50] [Server thread/ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
[02:40:50] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[02:40:50] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[02:40:50] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[02:40:50] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[02:40:50] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[02:40:50] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[02:40:50] [Server thread/ERROR]: #!#! 
[02:40:50] [Server thread/ERROR]: #!#! Version Information:
[02:40:50] [Server thread/ERROR]: #!#!   Skript: 2.2-dev34
[02:40:50] [Server thread/ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[02:40:50] [Server thread/ERROR]: #!#!   Minecraft: 1.12.2
[02:40:50] [Server thread/ERROR]: #!#!   Java: 1.8.0_161 (Java HotSpot(TM) 64-Bit Server VM 25.161-b12)
[02:40:50] [Server thread/ERROR]: #!#!   OS: Windows 10 amd64 10.0
[02:40:50] [Server thread/ERROR]: #!#! 
[02:40:50] [Server thread/ERROR]: #!#! Server platform: Spigot
[02:40:50] [Server thread/ERROR]: #!#! 
[02:40:50] [Server thread/ERROR]: #!#! Current node: null
[02:40:50] [Server thread/ERROR]: #!#! Current item: loop numbers from [[long:0]] to the (1¦holder[s]|2¦viewers|3¦[amount of] rows) of current inventory of the player * [[long:9]]
[02:40:50] [Server thread/ERROR]: #!#! Thread: Server thread
[02:40:50] [Server thread/ERROR]: #!#! 
[02:40:50] [Server thread/ERROR]: #!#! Language: english
[02:40:50] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
```
Reloads fine, says was reloaded successfully, but when you try to execute it, it will error. If it's used within a command the command will say an internal error happened.

The part that is being said in the error is this
```
if {selly::shop::%argument 2%::items::*} is set:
	loop {selly::shop::%argument 2%::items::*}:
		add 1 to {_slot}
		set {_item} to "%loop-value-2%" parsed as item
		set {_spot} to {_slot} - 1
		set {_cost} to {selly::shop::%argument 2%::cost::%{_spot}%}
#says error	set {_item} to {_item} named "&a&l%{_item}% &7@@ &6$&l%{_cost}%"
		set slot {_spot} of {_inventory} to {_item}
```
Which is unrelated as this error only happens when I add anything from the InventoryInfo expression.

My assumption is the returning of something in the InventoryInfo not being proper.

**Comment by bensku** [comment]
Probably a mistake with Java generics or something like that.

**Comment by Snow-Pyon** [comment]
Already fixed this, going to push the changes later.

**Comment by bensku** [comment]
@Snow-Pyon Make sure it is before the next release. Which is not in *few* days, but might be quite soon.
