### ISSUE TITLE
Doesn't load

### ISSUE THREAD

**Issue by Firjen** [bensku/Skript#1165]
Using Spigot git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
```
[19:03:22] [Server thread/WARN]: [Skript] Task #6 for Skript v2.2-dev34 generated an exception
java.lang.NoSuchMethodError: net.md_5.bungee.api.chat.BaseComponent.setInsertion(Ljava/lang/String;)V
	at ch.njol.skript.util.chat.BungeeConverter.convert(BungeeConverter.java:45) ~[?:?]
	at ch.njol.skript.util.chat.BungeeConverter.convert(BungeeConverter.java:60) ~[?:?]
	at ch.njol.skript.effects.EffMessage.execute(EffMessage.java:88) ~[?:?]
	at ch.njol.skript.lang.Effect.run(Effect.java:52) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[?:?]
	at ch.njol.skript.lang.Trigger.execute(Trigger.java:55) ~[?:?]
	at ch.njol.skript.events.EvtScript.register(EvtScript.java:61) ~[?:?]
	at ch.njol.skript.ScriptLoader$3.call(ScriptLoader.java:675) ~[?:?]
	at ch.njol.skript.ScriptLoader$3.call(ScriptLoader.java:1) ~[?:?]
	at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:694) ~[?:?]
	at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:347) ~[?:?]
	at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:359) ~[?:?]
	at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:289) ~[?:?]
	at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:319) ~[?:?]
	at ch.njol.skript.Skript$2.run(Skript.java:489) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by bensku** [comment]
You're missing Bungeecord chat library. Get it or update your MC version.

**Comment by Firjen** [comment]
I already have the highest version of MC. I don't really see why I am mission a bungeecord chat library as it's installed on a Spigot server?

**Comment by Firjen** [comment]
Minecraft 1.9+ isn't compatible with the server currently, however what version of Skript should I use that has armor stands in them and supports the latest version of 1.8.*? The main reason I updated my Skript version was that trying to spawn an armor stand told me it didn't understand the expression "spawn 1 armor stand at player".

**Comment by Pikachu920** [comment]
use paperspigot
