### ISSUE TITLE
En internal error occurred while attempting to perform this command

### ISSUE THREAD

**Issue by xThijs** [bensku/Skript#1169]
When I reload my skript, this is popping up in the chat:
En internal error occurred while attempting to perform this command

Minecraft server:
1.10.2

`Error in console:
[13:01:46 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'sk' in plugin Skript v2.1.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
        at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class me.mjolnir.mineconomy.internal.MCCom
        at net.milkbowl.vault.economy.plugins.Economy_MineConomy.currencyNameSingular(Economy_MineConomy.java:103) ~[?:?]
        at ch.njol.skript.hooks.economy.classes.Money.parse(Money.java:146) ~[?:?]
        at ch.njol.skript.hooks.economy.classes.Money$1.parse(Money.java:59) ~[?:?]
        at ch.njol.skript.hooks.economy.classes.Money$1.parse(Money.java:1) ~[?:?]
        at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:398) ~[?:?]
        at ch.njol.skript.registrations.Classes.parse(Classes.java:437) ~[?:?]
        at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:543) ~[?:?]
        at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:294) ~[?:?]
        at ch.njol.skript.lang.SkriptParser.parseObjectExpression(SkriptParser.java:396) ~[?:?]
        at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:286) ~[?:?]
        at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:990) ~[?:?]
        at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:915) ~[?:?]
        at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:942) ~[?:?]
        at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:942) ~[?:?]
        at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:942) ~[?:?]
        at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:942) ~[?:?]
        at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:981) ~[?:?]
        at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:942) ~[?:?]
        at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:209) ~[?:?]
        at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:164) ~[?:?]
        at ch.njol.skript.lang.Condition.parse(Condition.java:80) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:694) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:489) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:239) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:193) ~[?:?]
        at ch.njol.skript.Skript.reload(Skript.java:548) ~[?:?]
        at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:130) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.10.2.jar:git-Spigot-1e4dd71-5e5cf84]
        ... 15 more`

**Comment by TheBentoBox** [comment]
You're not using our version of Skript. You need to upgrade to the latest version of our fork before reporting errors. Releases can be found [here](https://github.com/bensku/Skript/releases).

**Comment by xThijs** [comment]
@TheBentoBox That's not true! I downloaded the lastest version!

**Comment by TheBentoBox** [comment]
@xThijs as @HYPExMon5ter said, it clearly says in the error log which version you're using. You're on an **incredibly** old version of Skript that hasn't been used much by anyone since something like Minecraft 1.7.

**Comment by Syst3ms** [comment]
@xThijs You downloaded the latest version *from Bukkit*. For your information, the bukkit page lists the latest download from the original author of Skript, Njol, who quit a couple years ago.
