### ISSUE TITLE
skellet mysql

### ISSUE THREAD

**Issue by xbxymax** [bensku/Skript#1173]
I upgraded skript today, from dev29 to dev34
Then the following code is invalidated
**on load:
	$ thread 
	set {_x1} to mysql result of query "SELECT Nick FROM xbxy_skin_now WHERE Nick='test'"
	set {_x2::*} to mysql string "Nick" in {_x1}
	send "%{_x2::1}%" to console**

This is an error in the background. When I didn't upgrade, this code is no problem. The error code comes from Skellett.

sk reload 1
[22:23:20 INFO]: [Skript] Reloading 1.sk...
[22:23:20 ERROR]: There's no player in an on script load/unload event (1.sk, line 3: set {_x1} to mysql result of query "SELECT Nick FROM xbxy_skin_now WHERE Nick='%player%'"')
[22:23:20 ERROR]: #!#! 
[22:23:20 ERROR]: #!#! [Skript] Severe Error:
[22:23:20 ERROR]: #!#! Could not load 1.sk
[22:23:20 ERROR]: #!#! 
[22:23:20 ERROR]: #!#! Something went horribly wrong with Skript.
[22:23:20 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[22:23:20 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[22:23:20 ERROR]: #!#! Here is full list of them:
[22:23:20 ERROR]: #!#! skRayFall (http://sk.rayfall.net/) TuSKe (github.com/Tuke-Nuke/TuSKe) skUtilities (https://tim740.github.io/) SkStuff MundoSK (https://forums.skunity.com/resources/mundosk.69/) SkQuery Skellett (https://forums.skunity.com/resources/skellett-the-addon-with-a-beast-name.24/) SharpSK 
[22:23:20 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[22:23:20 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[22:23:20 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[22:23:20 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[22:23:20 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[22:23:20 ERROR]: #!#! Only if the author tells you to do so, report it as Skript issue (url below)
[22:23:20 ERROR]: #!#! Issue tracker: https://github.com/bensku/Skript/issues (only if you know what you're doing!)
[22:23:20 ERROR]: #!#! 
[22:23:20 ERROR]: #!#! Stack trace:
[22:23:20 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for resultset
[22:23:20 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[22:23:20 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.createExprInfo(SkriptParser.java:1790)
[22:23:20 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1757)
[22:23:20 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1505)
[22:23:20 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1478)
[22:23:20 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1517)
[22:23:20 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1451)
[22:23:20 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1451)
[22:23:20 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:225)
[22:23:20 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:180)
[22:23:20 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:495)
[22:23:20 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:812)
[22:23:20 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1521)
[22:23:20 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1517)
[22:23:20 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:225)
[22:23:20 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:180)
[22:23:20 ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:59)
[22:23:20 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:919)
[22:23:20 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:612)
[22:23:20 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:347)
[22:23:20 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:359)
[22:23:20 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:392)
[22:23:20 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:188)
[22:23:20 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[22:23:20 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[22:23:20 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:675)
[22:23:20 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchServerCommand(CraftServer.java:638)
[22:23:20 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.DedicatedServer.aM(DedicatedServer.java:441)
[22:23:20 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:404)
[22:23:20 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:763)
[22:23:20 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:661)
[22:23:20 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[22:23:20 ERROR]: #!#! 
[22:23:20 ERROR]: #!#! Version Information:
[22:23:20 ERROR]: #!#!   Skript: 2.2-dev34
[22:23:20 ERROR]: #!#!   Bukkit: 1.11.2-R0.1-SNAPSHOT
[22:23:20 ERROR]: #!#!   Minecraft: 1.11.2
[22:23:20 ERROR]: #!#!   Java: 1.8.0_141 (OpenJDK 64-Bit Server VM 25.141-b16)
[22:23:20 ERROR]: #!#!   OS: Linux amd64 2.6.32-431.el6.x86_64
[22:23:20 ERROR]: #!#! 
[22:23:20 ERROR]: #!#! Server platform: Paper
[22:23:20 ERROR]: #!#! 
[22:23:20 ERROR]: #!#! Current node: set {_x2::*} to mysql string "Nick" in {_x1} (1.sk, line 4)
[22:23:20 ERROR]: #!#! Current item: null
[22:23:20 ERROR]: #!#! Thread: Server thread
[22:23:20 ERROR]: #!#! 
[22:23:20 ERROR]: #!#! Language: english
[22:23:20 ERROR]: #!#! Link parse mode: DISABLED
[22:23:20 ERROR]: #!#! 
[22:23:20 ERROR]: #!#! End of Error.
[22:23:20 ERROR]: #!#! 
[22:23:20 INFO]: [Skript] Encountered 1 error while reloading 1.sk!

**Comment by Pikachu920** [comment]
This issue tracker is for skript issues, and is a duplicate anyways. Skellett's sql support is unsafe anyways
