### ISSUE TITLE
Umbaska not working

### ISSUE THREAD

**Issue by Itunarlis** [bensku/Skript#1244]
Hello! My Problem is: When reloading my server Umbaska disables itselfs. I am running the current version of Umbaska on 1.8.8 Paperspigot. I tried Umbaska 3.3 and 3.2 but both didn't work.

Error:

[22:34:19 INFO]: [Umbaska] Enabling Umbaska v3.3
[22:34:19 INFO]: [Umbaska] Creating directory /home/gameserver/kd12942/4/games/minecraftspigot/plugins/Umbaska
[22:34:19 INFO]: [Umbaska] Creating/updating the config file /home/gameserver/kd12942/4/games/minecraftspigot/plugins/Umbaska/config.yml
[22:34:19 INFO]: [Umbaska] Config file successfully found
[22:34:19 INFO]: [Umbaska] Creating directory /home/gameserver/kd12942/4/games/minecraftspigot/plugins/Umbaska/modules
[22:34:19 INFO]: [Umbaska Module Manager] You don't have any modules in the folder of Umbaska, why don't you download one? Try the command /umb modules
[22:34:19 INFO]: [Umbaska Module Manager] WE ARE INSTALLING THE MODULE CORE FOR YOU, HOLD ON!
[22:34:19 ERROR]: Error occurred while enabling Umbaska v3.3 (Is it up to date?)
java.lang.NullPointerException
at java.io.Reader.<init>(Reader.java:78) ~[?:1.8.0_161]
at java.io.InputStreamReader.<init>(InputStreamReader.java:113) ~[?:1.8.0_161]
at org.apache.commons.io.IOUtils.copy(IOUtils.java:1906) ~[spigot.jar:git-PaperSpigot-"4c7641d"]
at org.apache.commons.io.IOUtils.toString(IOUtils.java:778) ~[spigot.jar:git-PaperSpigot-"4c7641d"]
at org.apache.commons.io.IOUtils.toString(IOUtils.java:759) ~[spigot.jar:git-PaperSpigot-"4c7641d"]
at uk.co.umbaska.utils.ModuleUtil.getAllAvailableModules(ModuleUtil.java:42) ~[?:?]
at uk.co.umbaska.utils.ModuleUtil.installModule(ModuleUtil.java:66) ~[?:?]
at uk.co.umbaska.modules.ModuleManager.enableModules(ModuleManager.java:101) ~[?:?]
at uk.co.umbaska.modules.ModuleManager.loadAndEnableModules(ModuleManager.java:53) ~[?:?]
at uk.co.umbaska.Umbaska.onEnable(Umbaska.java:125) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [spigot.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [spigot.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [spigot.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [spigot.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [spigot.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [spigot.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [spigot.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [spigot.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [spigot.jar:git-PaperSpigot-"4c7641d"]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[22:34:19 INFO]: [Umbaska] Disabling Umbaska v3.3

**Comment by HYPExMon5ter** [comment]
1. Don’t use umbaska
2. This isn’t the place to report addon errors/bugs, contact the developer
