### ISSUE TITLE
Trouble with new WorldGuard

### ISSUE THREAD

**Issue by Pilvinen** [bensku/Skript#155]
[11:32:30] [Server thread/WARN]: [Skript] Task #11 for Skript v2.2-dev18c generated an exception
java.lang.NoSuchMethodError: com.sk89q.worldguard.protection.flags.DefaultFlag.fuzzyMatchFlag(Ljava/lang/String;)Lcom/sk89q/worldguard/protection/flags/Flag;
        at me.TheBukor.SkStuff.SkStuff$4.parse(SkStuff.java:244) ~[?:?]
        at me.TheBukor.SkStuff.SkStuff$4.parse(SkStuff.java:1) ~[?:?]
        at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:422) ~[?:?]
        at ch.njol.skript.registrations.Classes.parse(Classes.java:451) ~[?:?]
        at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:97) ~[?:?]
        at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:86) ~[?:?]
        at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:1) ~[?:?]
        at ch.njol.skript.conditions.CondCompare.init(CondCompare.java:180) ~[?:?]
        at ch.njol.skript.conditions.CondCompare.init(CondCompare.java:131) ~[?:?]
        at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:249) ~[?:?]
        at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176) ~[?:?]
        at ch.njol.skript.lang.Statement.parse(Statement.java:60) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:754) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:513) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:247) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:201) ~[?:?]
        at ch.njol.skript.Skript$2.run(Skript.java:406) ~[?:?]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:723) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]

**Comment by bensku** [comment]
SkStuff problem, it seems. I'd recommend removing it but last time we did so, bad things happened...

Still, there is not much what I can do on Skript side.

**Comment by Nicofisi** [comment]
Same as #108
