### ISSUE TITLE
Could not load MySkript.sk

### ISSUE THREAD

**Issue by DreamTexX** [bensku/Skript#156]
Hello,
my problem is that skript doesn't load any script. The Skript i wrote worked great in 1.9 than I updated my server to 1.10 and ist doesn't work anymore.
Here is the Error:

[18:57:38 ERROR]: #!#!
[18:57:38 ERROR]: #!#! [Skript] Severe Error:
[18:57:38 ERROR]: #!#! Could not load broadcast.sk
[18:57:38 ERROR]: #!#!
[18:57:38 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[18:57:38 ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[18:57:38 ERROR]: #!#! and check whether this error has already been reported.
[18:57:38 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[18:57:38 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[18:57:38 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[18:57:38 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[18:57:38 ERROR]: #!#!
[18:57:38 ERROR]: #!#! Stack trace:
[18:57:38 ERROR]: #!#! java.lang.IllegalStateException: Cannot use classinfos until registration is over
[18:57:38 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.checkAllowClassInfoInteraction(Classes.java:242)
[18:57:38 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfoFromUserInput(Classes.java:337)
[18:57:38 ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:372)
[18:57:38 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:472)
[18:57:38 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:247)
[18:57:38 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:201)
[18:57:38 ERROR]: #!#!     at ch.njol.skript.Skript.reload(Skript.java:683)
[18:57:38 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:135)
[18:57:38 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[18:57:38 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140)
[18:57:38 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:625)
[18:57:38 ERROR]: #!#!     at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1299)
[18:57:38 ERROR]: #!#!     at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1159)
[18:57:38 ERROR]: #!#!     at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(SourceFile:37)
[18:57:38 ERROR]: #!#!     at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(SourceFile:9)
[18:57:38 ERROR]: #!#!     at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[18:57:38 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[18:57:38 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
[18:57:38 ERROR]: #!#!     at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45)
[18:57:38 ERROR]: #!#!     at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:690)
[18:57:38 ERROR]: #!#!     at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:360)
[18:57:38 ERROR]: #!#!     at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:646)
[18:57:38 ERROR]: #!#!     at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:550)
[18:57:38 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[18:57:38 ERROR]: #!#!
[18:57:38 ERROR]: #!#! Version Information:
[18:57:38 ERROR]: #!#!   Skript: 2.2-dev18c
[18:57:38 ERROR]: #!#!   Bukkit: 1.10-R0.1-SNAPSHOT
[18:57:38 ERROR]: #!#!   Minecraft: 1.10
[18:57:38 ERROR]: #!#!   Java: 1.7.0_71 (Java HotSpot(TM) 64-Bit Server VM 24.71-b01)
[18:57:38 ERROR]: #!#!   OS: Linux amd64 4.4.15-nitradoV3-MC-1000-nH-dP-d-i
[18:57:38 ERROR]: #!#!
[18:57:38 ERROR]: #!#! Running CraftBukkit: false
[18:57:38 ERROR]: #!#!
[18:57:38 ERROR]: #!#! Current node: command /smessage <text>: (broadcast.sk, line 1)
[18:57:38 ERROR]: #!#! Current item: null
[18:57:38 ERROR]: #!#!
[18:57:38 ERROR]: #!#! Thread: Server thread
[18:57:38 ERROR]: #!#!
[18:57:38 ERROR]: #!#! End of Error.
[18:57:38 ERROR]: #!#!

**Comment by Nicofisi** [comment]
Did you use /reload or any other plugin reloader before?

**Comment by DreamTexX** [comment]
Yes, but i have fixed the Problem. I replaced Craftbukkit with Spigot and it works fin. :D

**Comment by Nicofisi** [comment]
Good job xD so why did you reopen the issue?

**Comment by DreamTexX** [comment]
I clicked on the wrong button, but I think I can close it xD
