### ISSUE TITLE
Villager Spawn bug

### ISSUE THREAD

**Issue by Bruno4tc** [bensku/Skript#168]
```
[18:43:19 ERROR]: #!#! Stack trace:
[18:43:19 ERROR]: #!#! java.lang.IllegalArgumentException: Profession is reserved for Zombies: NORMAL
[18:43:19 ERROR]: #!#!     at org.apache.commons.lang.Validate.isTrue(Validate.java:71)
[18:43:19 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_10_R1.entity.CraftVillager.setProfession(CraftVillager.java:47)
[18:43:19 ERROR]: #!#!     at ch.njol.skript.entity.VillagerData.spawn(VillagerData.java:76)
[18:43:19 ERROR]: #!#!     at ch.njol.skript.entity.VillagerData.spawn(VillagerData.java:1)
[18:43:19 ERROR]: #!#!     at ch.njol.skript.effects.EffSpawn.execute(EffSpawn.java:88)
[18:43:19 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:54)
[18:43:19 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:65)
[18:43:19 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93)
[18:43:19 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
[18:43:19 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:222)
[18:43:19 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:184)
[18:43:19 ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:270)
[18:43:19 ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:165)
[18:43:19 ERROR]: #!#!     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:43:19 ERROR]: #!#!     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[18:43:19 ERROR]: #!#!     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[18:43:19 ERROR]: #!#!     at java.lang.reflect.Method.invoke(Unknown Source)
[18:43:19 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[18:43:19 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[18:43:19 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[18:43:19 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[18:43:19 ERROR]: #!#!     at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1343)
[18:43:19 ERROR]: #!#!     at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186)
[18:43:19 ERROR]: #!#!     at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[18:43:19 ERROR]: #!#!     at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[18:43:19 ERROR]: #!#!     at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[18:43:19 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[18:43:19 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
[18:43:19 ERROR]: #!#!     at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45)
[18:43:19 ERROR]: #!#!     at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:733)
[18:43:19 ERROR]: #!#!     at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399)
[18:43:19 ERROR]: #!#!     at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672)
[18:43:19 ERROR]: #!#!     at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571)
[18:43:19 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[18:43:19 ERROR]: #!#!
[18:43:19 ERROR]: #!#! Version Information:
[18:43:19 ERROR]: #!#!   Skript: 2.2-dev19
[18:43:19 ERROR]: #!#!   Bukkit: 1.10-R0.1-SNAPSHOT
[18:43:19 ERROR]: #!#!   Minecraft: 1.10
[18:43:19 ERROR]: #!#!   Java: 1.8.0_91 (Java HotSpot(TM) 64-Bit Server VM 25.91-b14)
[18:43:19 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[18:43:19 ERROR]: #!#!
[18:43:19 ERROR]: #!#! Running CraftBukkit: false
[18:43:19 ERROR]: #!#!
[18:43:19 ERROR]: #!#! Current node: null
[18:43:19 ERROR]: #!#! Current item: spawn [[entitytype:villager]] at the location of (the player >> ch.njol.skript.classes.data.DefaultConverters$10@5fbb269: org.bukkit.entity.Player->org.bukkit.Location)
[18:43:19 ERROR]: #!#!
[18:43:19 ERROR]: #!#! Thread: Server thread
[18:43:19 ERROR]: #!#!
[18:43:19 ERROR]: #!#! End of Error.
```

**Comment by JKGamerxD** [comment]
You can show the code?

**Comment by Bruno4tc** [comment]
`command /svll:
	trigger:
		spawn 1 villager at player's location
		loop 10 times:
			set {_health.%loop-integer%} to "&4❤"
		set display name of last spawned villager to "%{_health.1}%%{_health.2}%%{_health.3}%%{_health.4}%%{_health.5}%%{_health.6}%%{_health.7}%%{_health.8}%%{_health.9}%%{_health.10}%"
`

**Comment by Bruno4tc** [comment]
- [x] @mentions, #refs, [links](), **formatting**, and <del>tags</del> supported
- [x] list syntax required (any unordered or ordered list supported)
- [x] this is a complete item
- [ ] this is an incomplete item

**Comment by bensku** [comment]
Soon fixed.
