### ISSUE TITLE
Error entering region (GriefPrevention)

### ISSUE THREAD

**Issue by BalconyBeardedLady** [bensku/Skript#188]
I was testing the region triggers with a simple script shown below. It triggers an error when entering administrative claims. If the property is claimed by any other player, it produces no error.

Script
```
on region enter:
    wait 1 tick #You need this to get the region the player has entered
    message "Entering %region at player%, owned by: %owner of region at player%."

on region exit:
    wait 1 tick
    message "Leaving %region%, and entering a region owned by: %owner of region at player%."
```

Error:

```
04.09 02:53:29 [Server] ERROR #!#! 
04.09 02:53:29 [Server] ERROR #!#! [Skript] Severe Error:
04.09 02:53:29 [Server] ERROR #!#! 
04.09 02:53:29 [Server] ERROR #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
04.09 02:53:29 [Server] ERROR #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
04.09 02:53:29 [Server] ERROR #!#! and check whether this error has already been reported.
04.09 02:53:29 [Server] ERROR #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
04.09 02:53:29 [Server] ERROR #!#! and describe what you did before it happened and/or what you think caused the error.
04.09 02:53:29 [Server] ERROR #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
04.09 02:53:29 [Server] ERROR #!#! By following this guide fixing the error should be easy and done fast.
04.09 02:53:29 [Server] ERROR #!#! 
04.09 02:53:29 [Server] ERROR #!#! Stack trace:
04.09 02:53:29 [Server] ERROR #!#! java.lang.IllegalArgumentException: UUID cannot be null
04.09 02:53:29 [Server] ERROR #!#!     at org.apache.commons.lang.Validate.notNull(Validate.java:192)
04.09 02:53:29 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_10_R1.CraftServer.getOfflinePlayer(CraftServer.java:1329)
04.09 02:53:29 [Server] ERROR #!#!     at org.bukkit.Bukkit.getOfflinePlayer(Bukkit.java:763)
04.09 02:53:29 [Server] ERROR #!#!     at ch.njol.skript.hooks.regions.GriefPreventionHook$GriefPreventionRegion.getOwners(GriefPreventionHook.java:174)
04.09 02:53:29 [Server] ERROR #!#!     at ch.njol.skript.hooks.regions.expressions.ExprMembersOfRegion.get(ExprMembersOfRegion.java:75)
04.09 02:53:29 [Server] ERROR #!#!     at ch.njol.skript.hooks.regions.expressions.ExprMembersOfRegion.get(ExprMembersOfRegion.java:1)
04.09 02:53:29 [Server] ERROR #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:103)
04.09 02:53:29 [Server] ERROR #!#!     at ch.njol.skript.lang.VariableString.toString(VariableString.java:383)
04.09 02:53:29 [Server] ERROR #!#!     at ch.njol.skript.lang.VariableString.getArray(VariableString.java:488)
04.09 02:53:29 [Server] ERROR #!#!     at ch.njol.skript.lang.VariableString.getArray(VariableString.java:1)
04.09 02:53:29 [Server] ERROR #!#!     at ch.njol.skript.effects.EffMessage.execute(EffMessage.java:69)
04.09 02:53:29 [Server] ERROR #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:54)
04.09 02:53:29 [Server] ERROR #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:65)
04.09 02:53:29 [Server] ERROR #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93)
04.09 02:53:29 [Server] ERROR #!#!     at ch.njol.skript.effects.Delay$1.run(Delay.java:84)
04.09 02:53:29 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
04.09 02:53:29 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
04.09 02:53:29 [Server] ERROR #!#!     at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:728)
04.09 02:53:29 [Server] ERROR #!#!     at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399)
04.09 02:53:29 [Server] ERROR #!#!     at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:673)
04.09 02:53:29 [Server] ERROR #!#!     at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:572)
04.09 02:53:29 [Server] ERROR #!#!     at java.lang.Thread.run(Thread.java:745)
04.09 02:53:29 [Server] ERROR #!#! 
04.09 02:53:29 [Server] ERROR #!#! Version Information:
04.09 02:53:29 [Server] ERROR #!#!   Skript: 2.2-dev19
04.09 02:53:29 [Server] ERROR #!#!   Bukkit: 1.10.2-R0.1-SNAPSHOT
04.09 02:53:29 [Server] ERROR #!#!   Minecraft: 1.10.2
04.09 02:53:29 [Server] ERROR #!#!   Java: 1.8.0_66 (Java HotSpot(TM) 64-Bit Server VM 25.66-b17)
04.09 02:53:29 [Server] ERROR #!#!   OS: Linux amd64 3.14.32-xxxx-grs-ipv6-64
04.09 02:53:29 [Server] ERROR #!#! 
04.09 02:53:29 [Server] ERROR #!#! Running CraftBukkit: false
04.09 02:53:29 [Server] ERROR #!#! 
04.09 02:53:29 [Server] ERROR #!#! Current node: null
04.09 02:53:29 [Server] ERROR #!#! Current item: send "Entering %the regions at at (the player >> ch.njol.skript.classes.data.DefaultConverters$10@62ef5df4: org.bukkit.entity.Player->org.bukkit.Location)%, owned by: %the owners of the regions at at (the player >> ch.njol.skript.classes.data.DefaultConverters$10@62ef5df4: org.bukkit.entity.Player->org.bukkit.Location)%." to event-player/console
04.09 02:53:29 [Server] ERROR #!#! 
04.09 02:53:29 [Server] ERROR #!#! Thread: Server thread
04.09 02:53:29 [Server] ERROR #!#! 
04.09 02:53:29 [Server] ERROR #!#! End of Error.
04.09 02:53:29 [Server] ERROR #!#! 
```

**Comment by bensku** [comment]
This is due to admin claims not having any owners technically. Anyway, should be fixed in next release.
