### ISSUE TITLE
Error on reload

### ISSUE THREAD

**Issue by DontKillCZ** [bensku/Skript#199]
[11:04:14 ERROR]: #!#!
[11:04:14 ERROR]: #!#! [Skript] Severe Error:
[11:04:14 ERROR]: #!#! Exception in thread Skript offline player resolver thread (fetches UUIDs from the minecraft servers)
[11:04:14 ERROR]: #!#!
[11:04:14 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[11:04:14 ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[11:04:14 ERROR]: #!#! and check whether this error has already been reported.
[11:04:14 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[11:04:14 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[11:04:14 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[11:04:14 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[11:04:14 ERROR]: #!#!
[11:04:14 ERROR]: #!#! Stack trace:
[11:04:14 ERROR]: #!#! java.lang.NullPointerException
[11:04:14 ERROR]: #!#!     at ch.njol.skript.bukkitutil.UnresolvedOfflinePlayer$1.run(UnresolvedOfflinePlayer.java:59)
[11:04:14 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[11:04:14 ERROR]: #!#!
[11:04:14 ERROR]: #!#! Version Information:
[11:04:14 ERROR]: #!#!   Skript: 2.2-dev20
[11:04:14 ERROR]: #!#!   Bukkit: 1.10.2-R0.1-SNAPSHOT
[11:04:14 ERROR]: #!#!   Minecraft: 1.10.2
[11:04:14 ERROR]: #!#!   Java: 1.8.0_102 (Java HotSpot(TM) 64-Bit Server VM 25.102-b14)
[11:04:14 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[11:04:14 ERROR]: #!#!
[11:04:14 ERROR]: #!#! Running CraftBukkit: false
[11:04:14 ERROR]: #!#!
[11:04:14 ERROR]: #!#! Current node: null
[11:04:14 ERROR]: #!#! Current item: null
[11:04:14 ERROR]: #!#!
[11:04:14 ERROR]: #!#! Thread: Skript offline player resolver thread (fetches UUIDs from the minecraft servers)
[11:04:14 ERROR]: #!#!
[11:04:14 ERROR]: #!#! End of Error.
[11:04:14 ERROR]: #!#!

[11:05:51 INFO]: Plugins (11): PlugMan, SkinsRestorer, WorldEdit, Skript, Vault, VoxelSniper, Multiverse-Core, WorldGuard, Citizens, Multiverse-Portals, Multiverse-NetherPortals

[11:06:04 INFO]: This server is running CraftBukkit version git-Spigot-570526c-c1b529e (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)
[11:06:04 INFO]: Checking version, please wait...
[11:06:04 INFO]: You are running the latest version

**Comment by bensku** [comment]
Are you using /reload of Spigot ot Skripts own reload?

**Comment by Weefle** [comment]
I've the same error when I reload skript alone in 1.10.2 with skript's own reload :/

**Comment by bensku** [comment]
Woow... There is something really really wrong with UUID fetching.

**Comment by bensku** [comment]
Allright, this error makes no sense. Skript uses static initialization of class to set queue of unresolved offline players... And then this queue appears to be null. Wait what...

I'll probably need help with this.

**Comment by Weefle** [comment]
I'm sorry for that but if you resolve this and the particle support, skript will be awesome!
(and I want to know if this is possible to compile skript with skquery and wildskript without bug? LOL)
Sorry if there are mistakes, I'm french :P 
pd: I love your work!!! <3

**Comment by Weefle** [comment]
edit: The error is on reload of spigot only!

**Comment by bensku** [comment]
That explains a lot. Spigot reload is utterly broken, and causes problems with most plugins.

If you need to reload Skript, use /sk reload all/scripts/config/scriptname. If you need to reload plugins, then restart is probably* required. Sorry, it is limitation of Java - writing safely reloadable code is not that easy, and most plugin authors (including Njol, Mirreski and me) have not tried to aim for that.

(*=you can try to set up Java debugging tools on your server to reload stuff (not easy, still kinda not reliable). I don't recommend that, though.)
