### ISSUE TITLE
Illegal group Reference

### ISSUE THREAD

**Issue by Grimmy347** [bensku/Skript#201]
> [15:07:14]

 [Server thread/INFO]: [0;37;22m[[0;33;22mSkript[0;37;22m][m Reloading [0;33;22mMore Mobs.sk[m...[m
[15:07:15] [Server thread/ERROR]: Can't understand this condition/effect: dye the last spawned zombie's boots aOgre (More Mobs.sk, line 252: dye the last spawned zombie's boots aOgre')
[15:07:15] [Server thread/ERROR]: Can't understand this condition/effect: dye the last spawned zombie's boots aOgre (More Mobs.sk, line 411: dye the last spawned zombie's boots aOgre')
[15:07:15] [Server thread/ERROR]: Can't understand this condition/effect: format slot 0 of player with creeper spawn egg named "&a&lMega Creeper" with lore "&7Summon Mega Creeper" to run [make player execute command "/mob mcreeper"](More Mobs.sk, line 465: format slot 0 of player with creeper spawn egg named)
[15:07:15] [Server thread/ERROR]: Can't understand this condition/effect: format slot 2 of player with zombie spawn egg named "&2&lMega Zombie" with lore "&7Summon Mega Zombie" to run [make player execute command "/mob giant"](More Mobs.sk, line 466: format slot 2 of player with zombie spawn egg named)
[15:07:15] [Server thread/ERROR]: Can't understand this condition/effect: format slot 4 of player with enderman spawn egg named "&8&lWraith" with lore "&7Summon Wraith" to run [make player execute command "/mob wraith"](More Mobs.sk, line 467: format slot 4 of player with enderman spawn egg named)
[15:07:15] [Server thread/ERROR]: Can't understand this condition/effect: format slot 6 of player with mooshroom spawn egg named "&c&lFire Rat" with lore "&7Summon Fire Rat" to run [make player execute command "/mob frat"](More Mobs.sk, line 468: format slot 6 of player with mooshroom spawn egg named)
[15:07:15] [Server thread/ERROR]: Can't understand this condition/effect: format slot 8 of player with spider spawn egg named "&7&lSpider of Death" with lore "&7Summon Spider of Death" to run [make player execute command "/mob dspider"](More Mobs.sk, line 469: format slot 8 of player with spider spawn egg named)
[15:07:15] [Server thread/ERROR]: Can't understand this condition/effect: format slot 9 of player with slime spawn egg named "&2&lZombie Horse" with lore "&7Summon Zombie Horse" to run [make player execute command "/mob zhorse"](More Mobs.sk, line 470: format slot 9 of player with slime spawn egg named)
[15:07:15] [Server thread/ERROR]: Can't understand this condition/effect: format slot 11 of player with ghast spawn egg named "&7&lSkeleton Horse" with lore "&7Summon Skeleton Horse" to run [make player execute command "/mob shorse"](More Mobs.sk, line 471: format slot 11 of player with ghast spawn egg named)
[15:07:15] [Server thread/ERROR]: Can't understand this condition/effect: format slot 13 of player with chicken spawn egg named "&4&lHell Hound" with lore "&7Summon Hell Hound" to run [make player execute command "/mob hell"](More Mobs.sk, line 472: format slot 13 of player with chicken spawn egg named)
[15:07:15] [Server thread/ERROR]: Can't understand this condition/effect: format slot 15 of player with sheep spawn egg named "&a&lFlying Creeper" with lore "&7Summon Flying Creeper" to run [make player execute command "/mob fcreeper"](More Mobs.sk, line 473: format slot 15 of player with sheep spawn egg named)
[15:07:15] [Server thread/ERROR]: Can't understand this condition/effect: format slot 17 of player with blaze spawn egg named "&c&lFire Demon" with lore "&7Summon Fire Demon" to run [make player execute command "/mob demon"](More Mobs.sk, line 474: format slot 17 of player with blaze spawn egg named)
[15:07:15] [Server thread/ERROR]: Can't understand this condition/effect: format slot 18 of player with ghast spawn egg named "&7&lGreat Golem" with lore "&7Summon Great Golem" to run [make player execute command "/mob ggolem"](More Mobs.sk, line 475: format slot 18 of player with ghast spawn egg named)
[15:07:15] [Server thread/ERROR]: Can't understand this condition/effect: format slot 20 of player with witch spawn egg named "&5&lFlying Witch" with lore "&7Summon Flying Witch" to run [make player execute command "/mob fwitch"](More Mobs.sk, line 476: format slot 20 of player with witch spawn egg named)
[15:07:15] [Server thread/ERROR]: Can't understand this condition/effect: format slot 22 of player with blaze spawn egg named "&c&lFire Spider" with lore "&7Summon Fire Spider" to run [make player execute command "/mob fspider"](More Mobs.sk, line 477: format slot 22 of player with blaze spawn egg named)
[15:07:15] [Server thread/ERROR]: Can't understand this condition/effect: format slot 24 of player with ghast spawn egg named "&4Endangered Ghast" with lore "&7Summon Endangered Ghast" to run [make player execute command "/mob eghast"](More Mobs.sk, line 478: format slot 24 of player with ghast spawn egg named)
[15:07:15] [Server thread/ERROR]: Can't understand this condition/effect: format slot 26 of player with zombie spawn egg named "&2Ogre" with lore "&7Summon Ogre" to run [make player execute command "/mob ogre"](More Mobs.sk, line 479: format slot 26 of player with zombie spawn egg named)
[15:07:15] [Server thread/ERROR]: #!#! 
[15:07:15] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[15:07:15] [Server thread/ERROR]: #!#! Could not load More Mobs.sk
[15:07:15] [Server thread/ERROR]: #!#! 
[15:07:15] [Server thread/ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[15:07:15] [Server thread/ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[15:07:15] [Server thread/ERROR]: #!#! and check whether this error has already been reported.
[15:07:15] [Server thread/ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[15:07:15] [Server thread/ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[15:07:15] [Server thread/ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[15:07:15] [Server thread/ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[15:07:15] [Server thread/ERROR]: #!#! 
[15:07:15] [Server thread/ERROR]: #!#! Stack trace:
[15:07:15] [Server thread/ERROR]: #!#! java.lang.IllegalArgumentException: Illegal group reference
[15:07:15] [Server thread/ERROR]: #!#!     at java.util.regex.Matcher.appendReplacement(Unknown Source)
[15:07:15] [Server thread/ERROR]: #!#!     at ch.njol.util.StringUtils.replaceAll(StringUtils.java:88)
[15:07:15] [Server thread/ERROR]: #!#!     at ch.njol.util.StringUtils.replaceAll(StringUtils.java:68)
[15:07:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.replaceOptions(ScriptLoader.java:721)
[15:07:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:751)
[15:07:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:56)
[15:07:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Conditional.<init>(Conditional.java:46)
[15:07:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:840)
[15:07:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:56)
[15:07:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Conditional.<init>(Conditional.java:46)
[15:07:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:840)
[15:07:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:56)
[15:07:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Conditional.<init>(Conditional.java:46)
[15:07:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:840)
[15:07:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:513)
[15:07:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:271)
[15:07:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:167)
[15:07:15] [Server thread/ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[15:07:15] [Server thread/ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140)
[15:07:15] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646)
[15:07:15] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchServerCommand(CraftServer.java:632)
[15:07:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_10_R1.DedicatedServer.aL(DedicatedServer.java:438)
[15:07:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:401)
[15:07:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668)
[15:07:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567)
[15:07:15] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[15:07:15] [Server thread/ERROR]: #!#! 
[15:07:15] [Server thread/ERROR]: #!#! Version Information:
[15:07:15] [Server thread/ERROR]: #!#!   Skript: 2.2-dev20
[15:07:15] [Server thread/ERROR]: #!#!   Bukkit: 1.10.2-R0.1-SNAPSHOT
[15:07:15] [Server thread/ERROR]: #!#!   Minecraft: 1.10.2
[15:07:15] [Server thread/ERROR]: #!#!   Java: 1.8.0_101 (Java HotSpot(TM) 64-Bit Server VM 25.101-b13)
[15:07:15] [Server thread/ERROR]: #!#!   OS: Windows 10 amd64 10.0
[15:07:15] [Server thread/ERROR]: #!#! 
[15:07:15] [Server thread/ERROR]: #!#! Running CraftBukkit: false
[15:07:15] [Server thread/ERROR]: #!#! 
[15:07:15] [Server thread/ERROR]: #!#! Current node: send "{@logo} {@moneymsg}" to the attacker (More Mobs.sk, line 490)
[15:07:15] [Server thread/ERROR]: #!#! Current item: null
[15:07:15] [Server thread/ERROR]: #!#! 
[15:07:15] [Server thread/ERROR]: #!#! Thread: Server thread
[15:07:15] [Server thread/ERROR]: #!#! 
[15:07:15] [Server thread/ERROR]: #!#! End of Error.
[15:07:15] [Server thread/ERROR]: #!#! 

Not sure what is causing this.  It happens when I load the the More Mobs skript.  Any help would be appreciated!

**Comment by bensku** [comment]
With what script... ? Code, please.

**Comment by JKGamerxD** [comment]
@bensku I think it's this script:
https://www.spigotmc.org/resources/more-mobs-new-mobs-and-now-with-gui-1-8-1-9-1-10-2000-downloads.17930/

**Comment by bensku** [comment]
Ok, checked it. Requires SkQuery -> not going to start debugging that. If someone is interested in debugging this, go ahead.

**Comment by TheBentoBox** [comment]
No interest in 2 months -> closed.
