### ISSUE TITLE
error

### ISSUE THREAD

**Issue by yyeerai** [bensku/Skript#221]
[17:56:33 ERROR]: #!#! 
    [17:56:33 ERROR]: #!#! [Skript] Severe Error:
    [17:56:33 ERROR]: #!#! 
    [17:56:33 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
    [17:56:33 ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
    [17:56:33 ERROR]: #!#! and check whether this error has already been reported.
    [17:56:33 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
    [17:56:33 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
    [17:56:33 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
    [17:56:33 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
    [17:56:33 ERROR]: #!#! 
    [17:56:33 ERROR]: #!#! Stack trace:
    [17:56:33 ERROR]: #!#! java.util.UnknownFormatConversionException: Conversion = '%'
    [17:56:33 ERROR]: #!#!     at org.bukkit.event.player.AsyncPlayerChatEvent.setFormat(AsyncPlayerChatEvent.java:100)
    [17:56:33 ERROR]: #!#!     at com.w00tmast3r.skquery.elements.expressions.ExprMessageFormat.change(ExprMessageFormat.java:52)
    [17:56:33 ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:273)
    [17:56:33 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:54)
    [17:56:33 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:65)
    [17:56:33 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93)
    [17:56:33 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
    [17:56:33 ERROR]: #!#!     at ch.njol.skript.events.EvtChat$1.execute(EvtChat.java:68)
    [17:56:33 ERROR]: #!#!     at ch.njol.skript.events.EvtChat$1$1.call(EvtChat.java:87)
    [17:56:33 ERROR]: #!#!     at ch.njol.skript.events.EvtChat$1$1.call(EvtChat.java:1)
    [17:56:33 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftFuture.run(CraftFuture.java:89)
    [17:56:33 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:355)
    [17:56:33 ERROR]: #!#!     at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:792)
    [17:56:33 ERROR]: #!#!     at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404)
    [17:56:33 ERROR]: #!#!     at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:734)
    [17:56:33 ERROR]: #!#!     at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:633)
    [17:56:33 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)
    [17:56:33 ERROR]: #!#! 
    [17:56:33 ERROR]: #!#! Version Information:
    [17:56:33 ERROR]: #!#!   Skript: 2.2-dev20
    [17:56:33 ERROR]: #!#!   Bukkit: 1.10.2-R0.1-SNAPSHOT
    [17:56:33 ERROR]: #!#!   Minecraft: 1.10.2
    [17:56:33 ERROR]: #!#!   Java: 1.8.0_101 (Java HotSpot(TM) 64-Bit Server VM 25.101-b13)
    [17:56:33 ERROR]: #!#!   OS: Linux amd64 3.10.0-327.36.2.el7.x86_64
    [17:56:33 ERROR]: #!#! 
    [17:56:33 ERROR]: #!#! Running CraftBukkit: false
    [17:56:33 ERROR]: #!#! 
    [17:56:33 ERROR]: #!#! Current node: null
    [17:56:33 ERROR]: #!#! Current item: set chat message format to "§f『§8%the prefix of the player%§f』§7『§f%the display name of the player%§7』       §8§l» §f%the chat message%"
    [17:56:33 ERROR]: #!#! 
    [17:56:33 ERROR]: #!#! Thread: Server thread
    [17:56:33 ERROR]: #!#! 
    [17:56:33 ERROR]: #!#! End of Error.
    [17:56:33 ERROR]: #!#!

###code

    options:
        prefix: &c[MineZ]
	    perm: chatcolor.color
	    messageformat1:&f『&a%player's prefix%&f』&9『&6%{db_.team::in::%player%}%&9』&7『&f%player's display name%&7』&8&l» %{color.%player%}%%message%
	    messageformat2:&f『&b%player's prefix%&f』&9『&6%{db_.team::in::%player%}%&9』&7『&f%player's display name%&7』&8&l» %{color.%player%}%%message%
	    messageformat3:&f『&d%player's prefix%&f』&9『&6%{db_.team::in::%player%}%&9』&7『&f%player's display name%&7』&8&l» %{color.%player%}%%message%
	    messageformat4:&f『&a%player's prefix%&f』&9『&6%{db_.team::in::%player%}%&9』&7『&f%player's display name%&7』&8&l» &f%message%
	    messageformat5:&f『&b%player's prefix%&f』&9『&6%{db_.team::in::%player%}%&9』&7『&f%player's display name%&7』&8&l» &f%message%
	    messageformat6:&f『&d%player's prefix%&f』&9『&6%{db_.team::in::%player%}%&9』&7『&f%player's display name%&7』&8&l» &f%message%
	    messageformat7:&f『&8%player's prefix%&f』&9『&6%{db_.team::in::%player%}%&9』&7『&f%player's display name%&7』&8&l» &f%message%
	    messageformat8:&f『&8%player's prefix%&f』&9『&6%{db_.team::in::%player%}%&9』&7『&f%player's display name%&7』&8&l» %{color.%player%}%%message%
	    messageformat9:&f『&a%player's prefix%&f』&7『&f%player's display name%&7』&8&l» %{color.%player%}%%message%
	    messageformat10:&f『&b%player's prefix%&f』&7『&f%player's display name%&7』&8&l» %{color.%player%}%%message%
	    messageformat11:&f『&d%player's prefix%&f』&7『&f%player's display name%&7』&8&l» %{color.%player%}%%message%
	    messageformat12:&f『&a%player's prefix%&f』&7『&f%player's display name%&7』&8&l» &f%message%
    	messageformat13:&f『&b%player's prefix%&f』&7『&f%player's display name%&7』&8&l» &f%message%
	    messageformat14:&f『&d%player's prefix%&f』&7『&f%player's display name%&7』&8&l» &f%message%
	    messageformat15:&f『&8%player's prefix%&f』&7『&f%player's display name%&7』&8&l» &f%message%
	    messageformat16:&f『&8%player's prefix%&f』&7『&f%player's display name%&7』&8&l» %{color.%player%}%%message%

**Comment by JKGamerxD** [comment]
It's a SkQuery error, not of Skript.

Also, afaik SkQuery isn't updated anymore, so nobody would solve it. At least if you have some dev that would do it for you.
