### ISSUE TITLE
Server version help

### ISSUE THREAD

**Issue by xbxymax** [bensku/Skript#224]
I have been using skript2.1.2 on my server.
My server version is 1.72
Because skript2.1.2 in the creation of GUI bug have chest can lead to brush items
So I want to upgrade skript, and then I use skript-dev20b on my server
The result has been reported to the wrong..
I don't know how to upgrade 1.72 to 1.8.8
Do not know which one to use in the 1.72 version of skript
I hope God can help.

server version:
This server is running CraftBukkit version git-Spigot-1.7.2-R0.3-122-gb58e277 (MC: 1.7.2) (Implementing API version 1.7.2-R0.4-SNAPSHOT)

Error information:
[01:38:26 INFO]: [Skript] Enabling Skript v2.2-dev20
[01:38:26 INFO]: [Skript] Successfully generated the config, the example scripts and the aliases files.
[01:38:26 ERROR]: Error occurred while enabling Skript v2.2-dev20 (Is it up to date?)
java.lang.NoSuchFieldError: LARGE_SMOKE
        at ch.njol.skript.util.VisualEffect$Type.<clinit>(VisualEffect.java:141) ~[?:?]
        at ch.njol.skript.util.VisualEffect.<clinit>(VisualEffect.java:242) ~[?:?]
        at ch.njol.skript.classes.data.SkriptClasses.<clinit>(SkriptClasses.java:859) ~[?:?]
        at ch.njol.skript.Skript.onEnable(Skript.java:278) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:250) ~[spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:350) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:390) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
        at org.bukkit.craftbukkit.v1_7_R1.CraftServer.loadPlugin(CraftServer.java:460) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
        at org.bukkit.craftbukkit.v1_7_R1.CraftServer.enablePlugins(CraftServer.java:380) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
        at net.minecraft.server.v1_7_R1.MinecraftServer.m(MinecraftServer.java:348) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
        at net.minecraft.server.v1_7_R1.MinecraftServer.g(MinecraftServer.java:325) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
        at net.minecraft.server.v1_7_R1.MinecraftServer.a(MinecraftServer.java:281) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
        at net.minecraft.server.v1_7_R1.DedicatedServer.init(DedicatedServer.java:186) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
        at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:437) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]
        at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [spigot.jar:git-Spigot-1.7.2-R0.3-122-gb58e277]

**Comment by xbxymax** [comment]
I just want to have a skript that can be used in 1.72
And he doesn't have GUI bug in terms of chest

**Comment by Nicofisi** [comment]
Sorry, but this version of Skript is only for Minecraft 1.9+

**Comment by xbxymax** [comment]
Is there any other version of skript that supports 1.72 servers?

**Comment by F8te** [comment]
You should use the 2.1.2 from Bukkit

**Comment by xbxymax** [comment]
Skript2.1.2 this version creates a problem with the interface, can come up with things ah...
I am now trying to use Skript 2.2 V7b Fixes...

**Comment by bensku** [comment]
Your error is caused due to 1.7 having differences when compared to 1.8+. I only support 1.9+ but 1.8 usually works... 1.7 though? Definitely not, as you can see.

I realize that 1.7 is still used, but I have no idea why. If someone could give ne some reason for using that ancient version with multiple security flaws, I might take look at it.

**Comment by ZeTioZ** [comment]
A lot of people say "The 1.7 is the most valuable version for PvP" (because of the possibility to item block etc ...) so they use the 1.7 and also for the modded servers, a lot of mod are still in 1.7 so they use the 1.7

**Comment by bensku** [comment]
I do not support modded (i.e. other than Spigot,ä servers anyway, regardless of version.

About 1.7 PvP... Well, I haven't been very interested in Minecraft pvp lately and IMO 1.8+ does it better. So if someone would like to pull request and later get push access to repo, please go ahead.  But 1.7 support for reasons provided is not something I'm going to do very soon.

Quick tip:  this error is related to particle effect support; some of particles do not exist with 1.7. Fixing it is harder than it sounds, but still possible.

**Comment by xbxymax** [comment]
Did I try to remove particles, particles aliases-german.sk and aliases-english.sk in the text, such as delete all LARGE_SMOKE, but there is still the problem, I don't know if this error will not affect the use of the plug-in, so now I can only use Skript 2.2 Fixes V7b, but he is a test version, Hope @bensku can solve the problem of the use of the 1.72

**Comment by bensku** [comment]
I do not think editing language files would help anything, sadly. Of course, feel free to test if it works.

**Comment by TheBentoBox** [comment]
Closing as this is long since explained and mostly invalid.
