### ISSUE TITLE
BIG, HUGE PROBELM 

### ISSUE THREAD

**Issue by MotoSolar** [bensku/Skript#236]
Well hi Bensku Im glade that you keep that project
dont know but some how all the Fixed Version of skript that you made it
it not work for me even though the default skript example(some example scripts when someone run skript first time) -> only commands work (skript [load] / [help] ,etc)
But fact skript 2.2FixedV(x) Version were work(also the other stable version too)
So I hope you fixed this bug if you can. and when it fixed, than for sure ill using yours
Sorry for bad english and also thank you for reading
The Error codes were down below

-Error Codes

[17:41:08] [Server thread/INFO]: [0;37;22m[[0;33;22mSkript[0;37;22m][m Reloading the config and all scripts...[m
[17:41:08] [Server thread/INFO]: [Skript] Loaded a total of 19791 english aliases
[17:41:08] [Server thread/WARN]: [Skript] There are no aliases defined for the following ids: 438, 441
[17:41:08] [Server thread/INFO]: [Skript] All scripts loaded without errors.
[17:41:08] [Server thread/INFO]: [0;37;22m[[0;33;22mSkript[0;37;22m][m Successfully reloaded the main configuration.[m
[17:41:08] [pool-7-thread-9/WARN]: Exception in thread "pool-7-thread-9" 
[17:41:08] [pool-7-thread-9/WARN]: java.lang.IllegalStateException: Cannot use classinfos until registration is over
[17:41:08] [pool-7-thread-9/WARN]: 	at ch.njol.skript.registrations.Classes.checkAllowClassInfoInteraction(Classes.java:243)
[17:41:08] [pool-7-thread-9/WARN]: 	at ch.njol.skript.registrations.Classes.getClassInfoFromUserInput(Classes.java:338)
[17:41:08] [pool-7-thread-9/WARN]: 	at ch.njol.skript.lang.function.Functions.loadSignature(Functions.java:169)
[17:41:08] [pool-7-thread-9/WARN]: 	at ch.njol.skript.lang.parser.LoaderInstance.run(LoaderInstance.java:77)
[17:41:08] [pool-7-thread-9/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[17:41:08] [pool-7-thread-9/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[17:41:08] [pool-7-thread-9/WARN]: 	at java.lang.Thread.run(Unknown Source)
[17:41:08] [pool-7-thread-3/WARN]: Exception in thread "pool-7-thread-3" 
[17:41:08] [pool-7-thread-3/WARN]: java.lang.IllegalStateException: Cannot use classinfos until registration is over
[17:41:08] [pool-7-thread-3/WARN]: 	at ch.njol.skript.registrations.Classes.checkAllowClassInfoInteraction(Classes.java:243)
[17:41:08] [pool-7-thread-3/WARN]: 	at ch.njol.skript.registrations.Classes.getClassInfoFromUserInput(Classes.java:338)
[17:41:08] [pool-7-thread-3/WARN]: 	at ch.njol.skript.lang.function.Functions.loadSignature(Functions.java:169)
[17:41:08] [pool-7-thread-3/WARN]: 	at ch.njol.skript.lang.parser.LoaderInstance.run(LoaderInstance.java:77)
[17:41:08] [pool-7-thread-3/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[17:41:08] [pool-7-thread-3/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[17:41:08] [pool-7-thread-3/WARN]: 	at java.lang.Thread.run(Unknown Source)
[17:41:08] [pool-7-thread-8/WARN]: Exception in thread "pool-7-thread-8" 
[17:41:08] [pool-7-thread-8/WARN]: java.lang.IllegalStateException: Cannot use classinfos until registration is over
[17:41:08] [pool-7-thread-8/WARN]: 	at ch.njol.skript.registrations.Classes.checkAllowClassInfoInteraction(Classes.java:243)
[17:41:08] [pool-7-thread-8/WARN]: 	at ch.njol.skript.registrations.Classes.getClassInfoFromUserInput(Classes.java:338)
[17:41:08] [pool-7-thread-8/WARN]: 	at ch.njol.skript.lang.function.Functions.loadSignature(Functions.java:169)
[17:41:08] [pool-7-thread-8/WARN]: 	at ch.njol.skript.lang.parser.LoaderInstance.run(LoaderInstance.java:77)
[17:41:08] [pool-7-thread-8/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[17:41:08] [pool-7-thread-8/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[17:41:08] [pool-7-thread-8/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by Pilvinen** [comment]
1) Download and install the latest Spigot BuildTools here:
https://hub.spigotmc.org/jenkins/job/BuildTools/

2) Run BuildTools to get the latest Spigot.

3) Download and install Skript here:
https://github.com/bensku/Skript/releases

4) Remove 3rd party Skript addons and start the server.

Do you still get this error after all this?

**Comment by MotoSolar** [comment]
Do i need to remove all Add-ons that i used it?

**Comment by Pilvinen** [comment]
Yes. By removing the add-ons we can see if the problem is caused by Skript or by the add-ons.

**Comment by MotoSolar** [comment]
Than;;;; you mean i cannot used any of addons when i using this?

**Comment by Pilvinen** [comment]
I don't mean that. I just want you to test what is causing this error so that it can be fixed.

**Comment by MotoSolar** [comment]
Oh so simply you think I got issue on my bukkit or addons

**Comment by Pilvinen** [comment]
No. **Skript addons**. Bukkit addons don't matter.

**Comment by MotoSolar** [comment]
Im using 1.10 Spigot 
And here is the screenshoot
![all-eyes-on-me-sergi-delgado_595-a](https://cloud.githubusercontent.com/assets/23397550/20214610/9b8ec2da-a852-11e6-8e65-cdaef7ec59d2.png)

**Comment by F8te** [comment]
What Pilvinen said is you need create other test server only with Skript for check if the error is of Skript or its addons.

Also, if you're using the latest 21b, I don't recommend it for a production server, it's too buggy yet and only recommended for test servers.

**Comment by MotoSolar** [comment]
It made by one guy in korea

**Comment by bensku** [comment]
This is caused by *something* trying to parse a function before Skript has been initialized. Interesting, indeed...

**Comment by MotoSolar** [comment]
[00:36:20] [Server thread/INFO]: [Skript] Enabling Skript v2.2-dev21
[00:36:20] [Server thread/INFO]: [Skript] Successfully generated the config, the example scripts and the aliases files.
[00:36:20] [Server thread/ERROR]: Error occurred while enabling Skript v2.2-dev21 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.entity.Villager$Profession.isZombie()Z
	at ch.njol.skript.entity.VillagerData.<clinit>(VillagerData.java:61) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_111]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_111]
	at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:110) ~[?:?]
	at ch.njol.skript.Skript.onEnable(Skript.java:286) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[MotoSolar-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [MotoSolar-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [MotoSolar-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:362) [MotoSolar-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:322) [MotoSolar-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:416) [MotoSolar-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:381) [MotoSolar-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:336) [MotoSolar-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:270) [MotoSolar-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:539) [MotoSolar-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
[00:36:20] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[00:36:20] [Server thread/INFO]: Done (3.897s)! For help, type "help" or "?"
[00:37:17] [Server thread/INFO]: Usage: [0;37;22m/[0;33;22mskript [0;36;1m...[m
[00:37:17] [Server thread/INFO]:   [0;36;1mreload [0;37;22m-[m Reloads the config, all scripts, everything, or a specific script[m
[00:37:17] [Server thread/INFO]:   [0;36;1menable [0;37;22m-[m Enables all scripts or a specific one[m
[00:37:17] [Server thread/INFO]:   [0;36;1mdisable [0;37;22m-[m Disables all scripts or a specific one[m
[00:37:17] [Server thread/INFO]:   [0;36;1mupdate [0;37;22m-[m Check for updates, read the changelog, or download the latest version of Skript[m
[00:37:17] [Server thread/INFO]:   [0;36;1mtimings [0;37;22m-[m Starts or stops Skript's timings[m
[00:37:17] [Server thread/INFO]:   [0;36;1mhelp [0;37;22m-[m Prints this help message. Use '/skript reload/enable/disable/update' to get more info[m
[00:37:21] [Server thread/INFO]: Usage: [0;37;22m/[0;33;22mskript [0;36;1m...[m
[00:37:21] [Server thread/INFO]:   [0;36;1mreload [0;37;22m-[m Reloads the config, all scripts, everything, or a specific script[m
[00:37:21] [Server thread/INFO]:   [0;36;1menable [0;37;22m-[m Enables all scripts or a specific one[m
[00:37:21] [Server thread/INFO]:   [0;36;1mdisable [0;37;22m-[m Disables all scripts or a specific one[m
[00:37:21] [Server thread/INFO]:   [0;36;1mupdate [0;37;22m-[m Check for updates, read the changelog, or download the latest version of Skript[m
[00:37:21] [Server thread/INFO]:   [0;36;1mtimings [0;37;22m-[m Starts or stops Skript's timings[m
[00:37:21] [Server thread/INFO]:   [0;36;1mhelp [0;37;22m-[m Prints this help message. Use '/skript reload/enable/disable/update' to get more info[m

**Comment by MotoSolar** [comment]
Even though i yours without any other plugins or skript add-ons
still not work

**Comment by F8te** [comment]
Which version are you using exactly?

**Comment by bensku** [comment]
Hmm... This might actually be some problem not related to parser updates. I'll need to check if I have logic error in code that should prevent this.

**Comment by F8te** [comment]
@bensku this isn't related, but you should edit the version string when it's a "b" or "c" or the updater will say "there is a new update" when there isn't.

**Comment by MotoSolar** [comment]
[13:01:20] [Server thread/INFO]: [Skript] Enabling Skript v2.2-dev21
[13:01:21] [Server thread/INFO]: [Skript] Successfully generated the config, the example scripts and the aliases files.
[13:01:21] [Server thread/ERROR]: Error occurred while enabling Skript v2.2-dev21 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.entity.Villager$Profession.isZombie()Z
	at ch.njol.skript.entity.VillagerData.<clinit>(VillagerData.java:61) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_111]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_111]
	at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:110) ~[?:?]
	at ch.njol.skript.Skript.onEnable(Skript.java:286) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[MotoSolar-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [MotoSolar-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [MotoSolar-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:362) [MotoSolar-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:322) [MotoSolar-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:416) [MotoSolar-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:381) [MotoSolar-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:336) [MotoSolar-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:270) [MotoSolar-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:539) [MotoSolar-1.10.jar:git-Spigot-6016ac7-10c10b3]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
[13:01:21] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[13:01:21] [Server thread/INFO]: Done (4.302s)! For help, type "help" or "?"
[13:02:14] [Server thread/INFO]: Usage: [0;37;22m/[0;33;22mskript [0;36;1m...[m
[13:02:14] [Server thread/INFO]:   [0;36;1mreload [0;37;22m-[m Reloads the config, all scripts, everything, or a specific script[m
[13:02:14] [Server thread/INFO]:   [0;36;1menable [0;37;22m-[m Enables all scripts or a specific one[m
[13:02:14] [Server thread/INFO]:   [0;36;1mdisable [0;37;22m-[m Disables all scripts or a specific one[m
[13:02:14] [Server thread/INFO]:   [0;36;1mupdate [0;37;22m-[m Check for updates, read the changelog, or download the latest version of Skript[m
[13:02:14] [Server thread/INFO]:   [0;36;1mtimings [0;37;22m-[m Starts or stops Skript's timings[m
[13:02:14] [Server thread/INFO]:   [0;36;1mhelp [0;37;22m-[m Prints this help message. Use '/skript reload/enable/disable/update' to get more info[m
[13:02:17] [Server thread/INFO]: Usage: [0;37;22m/[0;33;22mskript [0;36;1menable [0;31;22m...[m
[13:02:17] [Server thread/INFO]:   [0;31;22mall [0;37;22m-[m Enables all scripts[m
[13:02:17] [Server thread/INFO]:   [0;31;22m[0;37;22m<[0;31;22mscript[0;37;22m> [0;37;22m-[m Enables a specific script or a folder of scripts[m
[13:02:19] [Server thread/INFO]: [0;37;22m[[0;33;22mSkript[0;37;22m][m Enabling all disabled scripts...[m
[13:02:20] [Server thread/INFO]: [0;37;22m[[0;33;22mSkript[0;37;22m][m Successfully enabled & parsed all previously disabled scripts.[m
[13:02:20] [pool-6-thread-6/WARN]: [Skript] Empty configuration section! You might want to indent one or more of the subsequent lines to make them belong to this section or remove the colon at the end of the line if you don't want this line to start a section. (drop fixes.sk, line 11: on break of bookshelf:')
[13:02:20] [pool-6-thread-8/ERROR]: [Skript] 'TNT' is not an item type (item command.sk, line 11: blacklisted: TNT, bedrock, obsidian, monster spawner, lava, lava bucket')
[13:02:20] [pool-6-thread-13/WARN]: Exception in thread "pool-6-thread-13" 
[13:02:20] [pool-6-thread-13/WARN]: java.lang.IllegalStateException: Cannot use classinfos until registration is over
[13:02:20] [pool-6-thread-13/WARN]: 	at ch.njol.skript.registrations.Classes.checkAllowClassInfoInteraction(Classes.java:243)
[13:02:20] [pool-6-thread-13/WARN]: 	at ch.njol.skript.registrations.Classes.getClassInfoFromUserInput(Classes.java:338)
[13:02:20] [pool-6-thread-13/WARN]: 	at ch.njol.skript.lang.parser.ParserInstance$3.run(ParserInstance.java:412)
[13:02:20] [pool-6-thread-13/WARN]: 	at ch.njol.skript.lang.parser.ParserInstance$3.run(ParserInstance.java:1)
[13:02:20] [pool-6-thread-13/WARN]: 	at ch.njol.util.StringUtils.replaceAll(StringUtils.java:85)
[13:02:20] [pool-6-thread-13/WARN]: 	at ch.njol.util.StringUtils.replaceAll(StringUtils.java:68)
[13:02:20] [pool-6-thread-13/WARN]: 	at ch.njol.skript.lang.parser.ParserInstance.run(ParserInstance.java:404)
[13:02:20] [pool-6-thread-13/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[13:02:20] [pool-6-thread-13/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[13:02:20] [pool-6-thread-13/WARN]: 	at java.lang.Thread.run(Unknown Source)
[13:02:20] [pool-6-thread-5/ERROR]: [Skript] can't understand this event: 'on fuel burn' (plant with hoe.sk, line 12: on rightclick on grass, dirt or soil with any hoe:')
[13:02:20] [pool-6-thread-5/ERROR]: [Skript] can't understand this event: 'on smelt' (furnace automatisation.sk, line 27: on smelt:')
[13:02:20] [pool-6-thread-5/ERROR]: [Skript] can't understand this event: 'on smelt' (furnace automatisation.sk, line 37: on smelt:')
[13:02:20] [pool-6-thread-15/ERROR]: [Skript] can't understand this event: 'on rightclick on grass, dirt or soil with any hoe'
[13:02:20] [pool-6-thread-15/ERROR]: [Skript] can't understand this event: 'on rightclick on sand with any hoe' (plant with hoe.sk, line 25: on rightclick on sand with any hoe:')
[13:02:20] [pool-6-thread-10/ERROR]: [Skript] can't understand this event: 'on inventory click'
[13:02:20] [pool-6-thread-10/ERROR]: [Skript] can't understand this event: 'on right click' (equip anything.sk, line 17: on right click:')
[13:02:20] [pool-6-thread-11/ERROR]: [Skript] can't understand this event: 'on break of glass' (equip anything.sk, line 17: on right click:')
[13:02:20] [pool-6-thread-11/ERROR]: [Skript] can't understand this event: 'on break of thin glass' (drop fixes.sk, line 8: on break of thin glass:')
[13:02:20] [pool-6-thread-11/ERROR]: [Skript] can't understand this event: 'on break of bookshelf' (drop fixes.sk, line 11: on break of bookshelf:')
[13:02:20] [pool-6-thread-14/ERROR]: [Skript] can't understand this event: 'on weather change to rain or thunder'
[13:02:20] [pool-6-thread-7/ERROR]: [Skript] can't understand this event: 'on rightclick with compass'
[13:02:20] [pool-6-thread-9/ERROR]: [Skript] can't understand this event: 'on damage'
[13:02:20] [pool-6-thread-16/ERROR]: [Skript] can't understand this event: 'on enderman pickup'
[13:02:20] [pool-6-thread-16/ERROR]: [Skript] can't understand this event: 'on enderman place' (nerf endermen.sk, line 8: on enderman place:')
[13:02:20] [pool-6-thread-4/ERROR]: [Skript] can't understand this event: 'at 18:00'
[13:02:20] [pool-6-thread-8/WARN]: Exception in thread "pool-6-thread-8" 
[13:02:20] [pool-6-thread-8/WARN]: java.lang.IllegalStateException: Cannot use classinfos until registration is over
[13:02:20] [pool-6-thread-8/WARN]: 	at ch.njol.skript.registrations.Classes.checkAllowClassInfoInteraction(Classes.java:243)
[13:02:20] [pool-6-thread-8/WARN]: 	at ch.njol.skript.registrations.Classes.getClassInfoFromUserInput(Classes.java:338)
[13:02:20] [pool-6-thread-8/WARN]: 	at ch.njol.skript.command.Commands.loadCommand(Commands.java:370)
[13:02:20] [pool-6-thread-8/WARN]: 	at ch.njol.skript.lang.parser.ParserInstance.run(ParserInstance.java:468)
[13:02:20] [pool-6-thread-8/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[13:02:20] [pool-6-thread-8/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[13:02:20] [pool-6-thread-8/WARN]: 	at java.lang.Thread.run(Unknown Source)
[13:02:20] [pool-6-thread-2/WARN]: Exception in thread "pool-6-thread-2" 
[13:02:20] [pool-6-thread-2/WARN]: java.lang.IllegalStateException: Cannot use classinfos until registration is over
[13:02:20] [pool-6-thread-2/WARN]: 	at ch.njol.skript.registrations.Classes.checkAllowClassInfoInteraction(Classes.java:243)
[13:02:20] [pool-6-thread-2/WARN]: 	at ch.njol.skript.registrations.Classes.getClassInfoFromUserInput(Classes.java:338)
[13:02:20] [pool-6-thread-2/WARN]: 	at ch.njol.skript.command.Commands.loadCommand(Commands.java:370)
[13:02:20] [pool-6-thread-2/WARN]: 	at ch.njol.skript.lang.parser.ParserInstance.run(ParserInstance.java:468)
[13:02:20] [pool-6-thread-2/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[13:02:20] [pool-6-thread-2/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[13:02:20] [pool-6-thread-2/WARN]: 	at java.lang.Thread.run(Unknown Source)
[13:02:20] [pool-6-thread-12/WARN]: Exception in thread "pool-6-thread-12" 
[13:02:20] [pool-6-thread-12/WARN]: java.lang.IllegalStateException: Cannot use classinfos until registration is over
[13:02:20] [pool-6-thread-12/WARN]: 	at ch.njol.skript.registrations.Classes.checkAllowClassInfoInteraction(Classes.java:243)
[13:02:20] [pool-6-thread-12/WARN]: 	at ch.njol.skript.registrations.Classes.getClassInfoFromUserInput(Classes.java:338)
[13:02:20] [pool-6-thread-12/WARN]: 	at ch.njol.skript.command.Commands.loadCommand(Commands.java:370)
[13:02:20] [pool-6-thread-12/WARN]: 	at ch.njol.skript.lang.parser.ParserInstance.run(ParserInstance.java:468)
[13:02:20] [pool-6-thread-12/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[13:02:20] [pool-6-thread-12/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[13:02:20] [pool-6-thread-12/WARN]: 	at java.lang.Thread.run(Unknown Source)
[13:02:20] [pool-6-thread-6/ERROR]: [Skript] Can't understand this expression: player (command with cooldown.sk, line 16: set {_waited} to difference between {cake.%player%.lastused} and now')
[13:02:20] [pool-6-thread-3/WARN]: Exception in thread "pool-6-thread-3" 
[13:02:20] [pool-6-thread-3/WARN]: java.lang.IllegalStateException: Cannot use classinfos until registration is over
[13:02:20] [pool-6-thread-3/WARN]: 	at ch.njol.skript.registrations.Classes.checkAllowClassInfoInteraction(Classes.java:243)
[13:02:20] [pool-6-thread-3/WARN]: 	at ch.njol.skript.registrations.Classes.getSuperClassInfo(Classes.java:303)
[13:02:20] [pool-6-thread-3/WARN]: 	at ch.njol.skript.effects.EffChange.init(EffChange.java:158)
[13:02:20] [pool-6-thread-3/WARN]: 	at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:259)
[13:02:20] [pool-6-thread-3/WARN]: 	at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:182)
[13:02:20] [pool-6-thread-3/WARN]: 	at ch.njol.skript.lang.Statement.parse(Statement.java:61)
[13:02:20] [pool-6-thread-3/WARN]: 	at ch.njol.skript.lang.parser.ParserInstance.loadItems(ParserInstance.java:242)
[13:02:20] [pool-6-thread-3/WARN]: 	at ch.njol.skript.command.Commands.loadCommand(Commands.java:465)
[13:02:20] [pool-6-thread-3/WARN]: 	at ch.njol.skript.lang.parser.ParserInstance.run(ParserInstance.java:468)
[13:02:20] [pool-6-thread-3/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[13:02:20] [pool-6-thread-3/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[13:02:20] [pool-6-thread-3/WARN]: 	at java.lang.Thread.run(Unknown Source)
[13:02:20] [pool-6-thread-6/ERROR]: [Skript] Can't understand this expression: location of player (homes.sk, line 12: message "Set your home to <grey>%location of player%<reset>"')
[13:02:20] [pool-6-thread-6/WARN]: Exception in thread "pool-6-thread-6" 
[13:02:20] [pool-6-thread-6/WARN]: java.lang.IllegalStateException: Cannot use classinfos until registration is over
[13:02:20] [pool-6-thread-6/WARN]: 	at ch.njol.skript.registrations.Classes.checkAllowClassInfoInteraction(Classes.java:243)
[13:02:20] [pool-6-thread-6/WARN]: 	at ch.njol.skript.registrations.Classes.getClassInfos(Classes.java:248)
[13:02:20] [pool-6-thread-6/WARN]: 	at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:417)
[13:02:20] [pool-6-thread-6/WARN]: 	at ch.njol.skript.registrations.Classes.parse(Classes.java:452)
[13:02:20] [pool-6-thread-6/WARN]: 	at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:369)
[13:02:20] [pool-6-thread-6/WARN]: 	at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:429)
[13:02:20] [pool-6-thread-6/WARN]: 	at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1111)
[13:02:20] [pool-6-thread-6/WARN]: 	at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1064)
[13:02:20] [pool-6-thread-6/WARN]: 	at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:227)
[13:02:20] [pool-6-thread-6/WARN]: 	at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:182)
[13:02:20] [pool-6-thread-6/WARN]: 	at ch.njol.skript.lang.Statement.parse(Statement.java:61)
[13:02:20] [pool-6-thread-6/WARN]: 	at ch.njol.skript.lang.parser.ParserInstance.loadItems(ParserInstance.java:242)
[13:02:20] [pool-6-thread-6/WARN]: 	at ch.njol.skript.command.Commands.loadCommand(Commands.java:465)
[13:02:20] [pool-6-thread-6/WARN]: 	at ch.njol.skript.lang.parser.ParserInstance.run(ParserInstance.java:468)
[13:02:20] [pool-6-thread-6/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[13:02:20] [pool-6-thread-6/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[13:02:20] [pool-6-thread-6/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by F8te** [comment]
Well, I'll tell you the same thing other time.

> Don't use the dev21 for now, just use the dev20

Also, as I can see on that error, there is a problem with the villager types other time @bensku ...

**Comment by MotoSolar** [comment]
I downloaded 20
and it dont know why but i just got 21
and also when i do /skript enable all
i got error message
