### ISSUE TITLE
No class info found for player

### ISSUE THREAD

**Issue by Nicofisi** [bensku/Skript#24]
Im getting this with the lastest dev9b version

Notice the ' character at the end of *No class info found for player'*, I don't know if it should be there

```
[17:26:51] [Server thread/ERROR]: #!#! 
[17:26:51] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[17:26:51] [Server thread/ERROR]: #!#! Could not load aura.sk
[17:26:51] [Server thread/ERROR]: #!#! 
[17:26:51] [Server thread/ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[17:26:51] [Server thread/ERROR]: #!#! If you're a server admin however please go to http://dev.bukkit.org/server-mods/skript/tickets/
[17:26:51] [Server thread/ERROR]: #!#! and check whether this error has already been reported.
[17:26:51] [Server thread/ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it,
[17:26:51] [Server thread/ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[17:26:51] [Server thread/ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[17:26:51] [Server thread/ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[17:26:51] [Server thread/ERROR]: #!#! 
[17:26:51] [Server thread/ERROR]: #!#! Stack trace:
[17:26:51] [Server thread/ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for player'
[17:26:51] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:242)
[17:26:51] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1394)
[17:26:51] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1115)
[17:26:51] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:220)
[17:26:51] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:175)
[17:26:51] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:60)
[17:26:51] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:650)
[17:26:51] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:467)
[17:26:51] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:469)
[17:26:51] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:245)
[17:26:51] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:199)
[17:26:51] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript$2.run(Skript.java:406)
[17:26:51] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
[17:26:51] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[17:26:51] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729)
[17:26:51] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
[17:26:51] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660)
[17:26:51] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559)
[17:26:51] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)
[17:26:51] [Server thread/ERROR]: #!#! 
[17:26:51] [Server thread/ERROR]: #!#! Version Information:
[17:26:51] [Server thread/ERROR]: #!#!   Skript: 2.2-Fixes-V10
[17:26:51] [Server thread/ERROR]: #!#!   Bukkit: 1.9-R0.1-SNAPSHOT
[17:26:51] [Server thread/ERROR]: #!#!   Minecraft: 1.9
[17:26:51] [Server thread/ERROR]: #!#!   Java: 1.8.0_66 (Java HotSpot(TM) 64-Bit Server VM 25.66-b17)
[17:26:51] [Server thread/ERROR]: #!#!   OS: Linux amd64 3.16.0-4-amd64
[17:26:51] [Server thread/ERROR]: #!#! 
[17:26:51] [Server thread/ERROR]: #!#! Running CraftBukkit: false
[17:26:51] [Server thread/ERROR]: #!#! 
[17:26:51] [Server thread/ERROR]: #!#! Current node: set {_c} to a block behind location of player (aura.sk, line 34)
[17:26:51] [Server thread/ERROR]: #!#! Current item: null
[17:26:51] [Server thread/ERROR]: #!#! 
[17:26:51] [Server thread/ERROR]: #!#! Thread: Server thread
[17:26:51] [Server thread/ERROR]: #!#! 
[17:26:51] [Server thread/ERROR]: #!#! End of Error.
[17:26:51] [Server thread/ERROR]: #!#! 
```

**Comment by bensku** [comment]
Probably typo somewhere, if so it be fixed in next build tomorrow.

**Comment by bensku** [comment]
Oh well... This is actually complicated issue, could you provide more information? What were you trying to do?

**Comment by Nicofisi** [comment]
The script is
```
command /test123:
	trigger:
		set {_c} to a block behind location of player
```
don't know if can tell anything more

**Comment by bensku** [comment]
Oops, forgot to comment here. I think I fixed this, anyway.
