### ISSUE TITLE
Problem on Spigot 1.8.8 & PaperSpigot 1.8.8.

### ISSUE THREAD

**Issue by Karyte** [bensku/Skript#246]
So I recieve this message and my server automatically shuts down.
`[14:09:57] [Server thread/INFO]: [Skript] Enabling Skript v2.2-dev21c
[14:09:57] [Server thread/ERROR]: Error occurred while enabling Skript v2.2-dev21c (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/event/entity/AreaEffectCloudApplyEvent
	at ch.njol.skript.classes.data.BukkitEventValues.<clinit>(BukkitEventValues.java:434) ~[?:?]
	at ch.njol.skript.Skript.onEnable(Skript.java:277) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.ClassNotFoundException: org.bukkit.event.entity.AreaEffectCloudApplyEvent
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_72]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_72]
	... 13 more`

And after that my skQuery and Umbaska shut down too because of skript...

**Comment by bensku** [comment]
Oops... I guess this at least is easy enough to fix.

**Comment by Karyte** [comment]
Ok, I hope it will be fixed soon.
Do you know what version of Umbaska should I be using for Spigot 1.8.8 ?
Here's an error which occurs:
`[17:24:29 INFO]: [Umbaska] It appears you might be using a 1.8 Build! I'm going to attempt to register some things related to it :)
[17:24:29 INFO]: [Umbaska] [Umbaska > SkQuery] Attempting to register new Spawn Particle Effect.
[17:24:30 ERROR]: Error occurred while enabling Umbaska v2.0 Beta 5.0541 (Is it up to date?)
java.lang.ExceptionInInitializerError
        at ch.njol.skript.registrations.Classes.registerClass(Classes.java:101) ~[?:?]
        at uk.co.umbaska.Utils.EnumClassInfo.register(EnumClassInfo.java:70) ~[?:?]
        at uk.co.umbaska.Managers.Enums.registerEnum(Enums.java:73) ~[?:?]
        at uk.co.umbaska.Managers.Enums.runRegister(Enums.java:100) ~[?:?]
        at uk.co.umbaska.Managers.Register.registerAll(Register.java:60) ~[?:?]
        at uk.co.umbaska.Main.onEnable(Main.java:201) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.IllegalArgumentException: ch.njol.skript.util.Timespan
        at ch.njol.skript.config.Option.<init>(Option.java:71) ~[?:?]
        at ch.njol.skript.SkriptConfig.<clinit>(SkriptConfig.java:78) ~[?:?]
        ... 17 more`

**Comment by bensku** [comment]
I wouldn't myself use Umbaska 2 at all. But anyway, I have fixed the issue with Skript that it had with 1.8.
