### ISSUE TITLE
Inventory Item Stack Error

### ISSUE THREAD

**Issue by NicholasID** [bensku/Skript#268]
[07:57:28 ERROR]: #!#!
[07:57:28 ERROR]: #!#! Stack trace:
[07:57:28 ERROR]: #!#! java.lang.ArrayIndexOutOfBoundsException: 4
[07:57:28 ERROR]: #!#!     at java.util.Arrays$ArrayList.set(Unknown Source)
[07:57:28 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.NonNullList.set(Sour
ceFile:47)
[07:57:28 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.InventoryCrafting.se
tItem(InventoryCrafting.java:129)
[07:57:28 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_11_R1.inventory.CraftInv
entoryCrafting.setItem(CraftInventoryCrafting.java:85)
[07:57:28 ERROR]: #!#!     at com.w00tmast3r.skquery.elements.expressions.ExprIt
emInInventory$1.setItem(ExprItemInInventory.java:38)
[07:57:28 ERROR]: #!#!     at ch.njol.skript.classes.data.SkriptClasses$17.chang
e(SkriptClasses.java:640)
[07:57:28 ERROR]: #!#!     at ch.njol.skript.classes.data.SkriptClasses$17.chang
e(SkriptClasses.java:1)
[07:57:28 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.change(S
impleExpression.java:237)
[07:57:28 ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange
.java:273)
[07:57:28 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:54)
[07:57:28 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.j
ava:65)
[07:57:28 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.j
ava:93)
[07:57:28 ERROR]: #!#!     at ch.njol.skript.effects.Delay$1.run(Delay.java:84)
[07:57:28 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTas
k.run(CraftTask.java:71)
[07:57:28 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftSch
eduler.mainThreadHeartbeat(CraftScheduler.java:353)
[07:57:28 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.D(Mi
necraftServer.java:730)
[07:57:28 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.DedicatedServer.D(De
dicatedServer.java:399)
[07:57:28 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.C(Mi
necraftServer.java:675)
[07:57:28 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.run(
MinecraftServer.java:574)
[07:57:28 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[07:57:28 ERROR]: #!#!
[07:57:28 ERROR]: #!#! Version Information:
[07:57:28 ERROR]: #!#!   Skript: 2.2-dev22c
[07:57:28 ERROR]: #!#!   Bukkit: 1.11-R0.1-SNAPSHOT
[07:57:28 ERROR]: #!#!   Minecraft: 1.11
[07:57:28 ERROR]: #!#!   Java: 1.8.0_111 (Java HotSpot(TM) Client VM 25.111-b14)

[07:57:28 ERROR]: #!#!   OS: Windows 7 x86 6.1
[07:57:28 ERROR]: #!#!
[07:57:28 ERROR]: #!#! Running CraftBukkit: false
[07:57:28 ERROR]: #!#!
[07:57:28 ERROR]: #!#! Current node: null
[07:57:28 ERROR]: #!#! Current item: set slot to a random element out of {_glass
::*}(as org.bukkit.inventory.ItemStack)
[07:57:28 ERROR]: #!#!
[07:57:28 ERROR]: #!#! Thread: Server thread
[07:57:28 ERROR]: #!#!
[07:57:28 ERROR]: #!#! End of Error.
[07:57:28 ERROR]: #!#!

When i was making my crates system then this happend in my console

This is the sk file that i use

on rightclick on jukebox:
    cancel event
    open chest with 3 rows named "Tier 1 Crate" to player
    wait a tick
    set {isrolling::%player%} to true
    add stone to {_roll::*}
    add diamond to {_roll::*}
    add diamond sword named "&6&lDiamond Sword" to {_roll::*}
    add dirt to {_roll::*}
    add gold block to {_roll::*}
    add redstone block to {_roll::*}
    add beacon to {_roll::*}
    add name tag named "lol" to {_roll::*}
    add light green stained glass pane to {_glass::*}
    add black stained glass pane to {_glass::*}
    add white stained glass pane to {_glass::*}
    add orange stained glass pane to {_glass::*}
    add magenta stained glass pane to {_glass::*}
    add light blue stained glass pane to {_glass::*}
    add yellow stained glass pane to {_glass::*}
    add pink stained glass pane to {_glass::*}
    add gray stained glass pane to {_glass::*}
    add cyan stained glass pane to {_glass::*}
    add purple stained glass pane to {_glass::*}
    add blue stained glass pane to {_glass::*}
    add brown stained glass pane to {_glass::*}
    add green stained glass pane to {_glass::*}
    add red stained glass pane to {_glass::*}
    set {_speedFinal} to 1
    loop (random integer between 10 and 40) times:
        loop integers between 0 and 26:
            if loop-number-2 is 13:
                set slot loop-number-2 of player's current inventory to random item out of {_roll::*}
            else:
                set slot loop-number-2 of player's current inventory to random item out of {_glass::*}
        add 1 to {_sound}
        if {_sound} > 3:
            set {_sound} to 1
        if {_sound} = 1:
            play note pling at player with pitch 2
        if {_sound} = 2:
            play note pling at player with pitch 1
        if {_sound} = 3:
            play note pling at player with pitch 0.5
        add 1 to {_speed}
        if {_speed} is 5:
            set {_speed} to 0
            add 1 to {_speedFinal}
        loop {_speedFinal} times:
            wait a tick
    message "&e&l➤ &eYou won &c%slot 13 of player's current inventory%"
    give player slot 13 of player's current inventory
    set {isrolling::%player%} to false
on inventory click:
    if inventory name of player's current inventory is "Tier 1 Crate":
        cancel event
		
on inventory close:
	if {isrolling::%player%} is true:
		wait 1 tick
		open chest with 3 rows named "Tier 1 Crate" to player

		wait 1 tick
		
		format slot 13 of player with redstone block named "&4&lYOU DONT GET YOUR REWARD" with lore " " to be unstealable

**Comment by bensku** [comment]
SkQuery version that you use seems to be incompatible with 1.11. Not Skript issue.
