### ISSUE TITLE
Skript Functions

### ISSUE THREAD

**Issue by DontKillCZ** [bensku/Skript#272]
```
[17:27:34] [Server thread/INFO]: All scripts loaded without errors.
[17:27:34] [Server thread/WARN]: Unexpected exception while parsing console command "sk reload scripts"
org.bukkit.command.CommandException: Unhandled exception executing command 'sk' in plugin Skript v2.2-dev22d
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:647) ~[server.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchServerCommand(CraftServer.java:633) [server.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.DedicatedServer.aL(DedicatedServer.java:438) [server.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:401) [server.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [server.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [server.jar:git-Spigot-de459a2-51263e9]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldguard.protection.flags.DefaultFlag.fuzzyMatchFlag(Ljava/lang/String;)Lcom/sk89q/worldguard/protection/flags/Flag;
	at com.gmail.headshot.Register$29.parse(Register.java:774) ~[?:?]
	at com.gmail.headshot.Register$29.parse(Register.java:1) ~[?:?]
	at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:422) ~[?:?]
	at ch.njol.skript.registrations.Classes.parse(Classes.java:451) ~[?:?]
	at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:97) ~[?:?]
	at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:86) ~[?:?]
	at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:1) ~[?:?]
	at ch.njol.skript.conditions.CondCompare.init(CondCompare.java:181) ~[?:?]
	at ch.njol.skript.conditions.CondCompare.init(CondCompare.java:132) ~[?:?]
	at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:249) ~[?:?]
	at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176) ~[?:?]
	at ch.njol.skript.lang.Condition.parse(Condition.java:83) ~[?:?]
	at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:833) ~[?:?]
	at ch.njol.skript.lang.Loop.<init>(Loop.java:68) ~[?:?]
	at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:790) ~[?:?]
	at ch.njol.skript.lang.function.ScriptFunction.<init>(ScriptFunction.java:53) ~[?:?]
	at ch.njol.skript.lang.function.Functions.loadFunction(Functions.java:129) ~[?:?]
	at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:485) ~[?:?]
	at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:247) ~[?:?]
	at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:201) ~[?:?]
	at ch.njol.skript.Skript.reloadScripts(Skript.java:694) ~[?:?]
	at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:145) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-de459a2-51263e9]
	... 8 more
```
This same error i have when i start server and skript loads. (json.sk)
Plugins: 
![vystrizek](https://cloud.githubusercontent.com/assets/13977254/20867543/b38fc562-ba47-11e6-872d-ddc980a5692e.PNG)
Version: CraftBukkit version git-Spigot-de459a2-51263e9 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)

**Comment by Pyon-Pyon** [comment]
It's a problem of SkRambled and WG, due to in the latest versions of WG the flags were removed, the support of WG in some plugins is broken like SkRambled right now.

**Comment by DontKillCZ** [comment]
Any idea how to reapair this?

**Comment by bensku** [comment]
Update SkRambled (if possible) or downgrade WorldGuard. This it not Skript problem.
