### ISSUE TITLE
End portal error

### ISSUE THREAD

**Issue by jarek123442** [bensku/Skript#280]
[Server thread/ERROR]: Could not pass event PlayerPortalEvent to Skript v2.2-dev22e
java.lang.NullPointerException
at ch.njol.skript.hooks.regions.WorldGuardHook.getRegionsAt_i(WorldGuardHook.java:247) ~[?:?]
at ch.njol.skript.hooks.regions.RegionsPlugin.getRegionsAt(RegionsPlugin.java:94) ~[?:?]
at ch.njol.skript.hooks.regions.events.EvtRegionBorder$3.execute(EvtRegionBorder.java:161) ~[?:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[serwer36884.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[serwer36884.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [serwer36884.jar:git-PaperSpigot-"8b18730"]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [serwer36884.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.PlayerList.changeDimension(PlayerList.java:689) [serwer36884.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.EntityPlayer.c(EntityPlayer.java:552) [serwer36884.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.BlockEnderPortal.a(BlockEnderPortal.java:45) [serwer36884.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.Entity.checkBlockCollisions(Entity.java:795) [serwer36884.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.Entity.move(Entity.java:442) [serwer36884.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:411) [serwer36884.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [serwer36884.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [serwer36884.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [serwer36884.jar:git-PaperSpigot-"8b18730"]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [serwer36884.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [serwer36884.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [serwer36884.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [serwer36884.jar:git-PaperSpigot-"8b18730"]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [serwer36884.jar:git-PaperSpigot-"8b18730"]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

**Comment by bensku** [comment]
WorldGuard hook has a bug.

**Comment by jarek123442** [comment]
I'm sorry my bad. Thanks :)

**Comment by jarek123442** [comment]
How to fix this?

**Comment by bensku** [comment]
I mean, it is a fix for me to do. You cannot fix it yourself without modifying Skript's source code.

**Comment by jarek123442** [comment]
When you fix this?
Thanks for help.

**Comment by Pyon-Pyon** [comment]
when he can, just wait for the next release.

**Comment by bensku** [comment]
Let's see if it got fixed... Note: do not, ever, attempt to dynamically reload Skript.

**Comment by TheBentoBox** [comment]
I am personally [still getting this error](https://www.hastebin.com/folopujiwu.go). My WorldGuard is a few builds outdated, could that be the issue?

**Comment by bensku** [comment]
Yes. Please update your WorldGuard, it might help.

**Comment by TheBentoBox** [comment]
I [still get this error](http://pastebin.com/qFhE7J3w) in the very latest WorldGuard build. It sometimes fires a ton of times for the same portal event, e.g. this is me entering a portal once to go to the end:

```
12.01 13:40:08 [Server] ERROR Could not pass event PlayerPortalEvent to Skript v2.2-dev23
12.01 13:40:08 [Server] INFO java.lang.NullPointerException
12.01 13:40:08 [Server] ERROR Could not pass event PlayerPortalEvent to Skript v2.2-dev23
12.01 13:40:08 [Server] INFO java.lang.NullPointerException
12.01 13:40:08 [Server] ERROR Could not pass event PlayerPortalEvent to Skript v2.2-dev23
12.01 13:40:08 [Server] INFO java.lang.NullPointerException
12.01 13:40:08 [Server] ERROR Could not pass event PlayerPortalEvent to Skript v2.2-dev23
12.01 13:40:08 [Server] INFO java.lang.NullPointerException
12.01 13:40:08 [Server] ERROR Could not pass event PlayerPortalEvent to Skript v2.2-dev23
12.01 13:40:08 [Server] INFO java.lang.NullPointerException
12.01 13:40:08 [Server] ERROR Could not pass event PlayerPortalEvent to Skript v2.2-dev23
12.01 13:40:08 [Server] INFO java.lang.NullPointerException
12.01 13:40:08 [Server] ERROR Could not pass event PlayerPortalEvent to Skript v2.2-dev23
12.01 13:40:08 [Server] INFO java.lang.NullPointerException
12.01 13:40:08 [Server] ERROR Could not pass event PlayerPortalEvent to Skript v2.2-dev23
12.01 13:40:08 [Server] INFO java.lang.NullPointerException
12.01 13:40:08 [Server] ERROR Could not pass event PlayerPortalEvent to Skript v2.2-dev23
12.01 13:40:08 [Server] INFO java.lang.NullPointerException
12.01 13:40:08 [Server] ERROR Could not pass event PlayerPortalEvent to Skript v2.2-dev23
12.01 13:40:08 [Server] INFO java.lang.NullPointerException
12.01 13:40:08 [Server] ERROR Could not pass event PlayerPortalEvent to Skript v2.2-dev23
12.01 13:40:08 [Server] INFO java.lang.NullPointerException
12.01 13:40:08 [Server] ERROR Could not pass event PlayerPortalEvent to Skript v2.2-dev23
12.01 13:40:08 [Server] INFO java.lang.NullPointerException
12.01 13:40:08 [Server] ERROR Could not pass event PlayerPortalEvent to Skript v2.2-dev23
12.01 13:40:08 [Server] INFO java.lang.NullPointerException
12.01 13:40:08 [Server] ERROR Could not pass event PlayerPortalEvent to Skript v2.2-dev23
12.01 13:40:08 [Server] INFO java.lang.NullPointerException
12.01 13:40:08 [Server] ERROR Could not pass event PlayerPortalEvent to Skript v2.2-dev23
12.01 13:40:08 [Server] INFO java.lang.NullPointerException
12.01 13:40:08 [Server] ERROR Could not pass event PlayerPortalEvent to Skript v2.2-dev23
12.01 13:40:08 [Server] INFO java.lang.NullPointerException
12.01 13:40:08 [Server] ERROR Could not pass event PlayerPortalEvent to Skript v2.2-dev23
12.01 13:40:08 [Server] INFO java.lang.NullPointerException
12.01 13:40:08 [Server] ERROR Could not pass event PlayerPortalEvent to Skript v2.2-dev23
12.01 13:40:08 [Server] INFO java.lang.NullPointerException
12.01 13:40:08 [Server] ERROR Could not pass event PlayerPortalEvent to Skript v2.2-dev23
12.01 13:40:08 [Server] INFO java.lang.NullPointerException
```
