### ISSUE TITLE
"add "&2TEXT" to {LIST}" not working

### ISSUE THREAD

**Issue by mads03dk** [bensku/Skript#283]
I (may) found a bug
`[15:58:16]: Mads03DK issued server command: /sk reload main
[15:58:16]: #!#! 
[15:58:16]: #!#! [Skript] Severe Error:
[15:58:16]: #!#! Could not load main.sk
[15:58:16]: #!#! 
[15:58:16]: #!#! Stack trace:
[15:58:16]: #!#! java.lang.IllegalStateException: Cannot use classinfos until registration is over
[15:58:16]: #!#!     at ch.njol.skript.registrations.Classes.checkAllowClassInfoInteraction(Classes.java:242)
[15:58:16]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfos(Classes.java:247)
[15:58:16]: #!#!     at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:416)
[15:58:16]: #!#!     at ch.njol.skript.registrations.Classes.parse(Classes.java:451)
[15:58:16]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:359)
[15:58:16]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:418)
[15:58:16]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:408)
[15:58:16]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1132)
[15:58:16]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1084)
[15:58:16]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:221)
[15:58:16]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[15:58:16]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:61)
[15:58:16]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:754)
[15:58:16]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:467)
[15:58:16]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:472)
[15:58:16]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:271)
[15:58:16]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:167)
[15:58:16]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[15:58:16]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[15:58:16]: #!#!     at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646)
[15:58:16]: #!#!     at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1348)
[15:58:16]: #!#!     at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1183)
[15:58:16]: #!#!     at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[15:58:16]: #!#!     at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[15:58:16]: #!#!     at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[15:58:16]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[15:58:16]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
[15:58:16]: #!#!     at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45)
[15:58:16]: #!#!     at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:733)
[15:58:16]: #!#!     at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399)
[15:58:16]: #!#!     at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672)
[15:58:16]: #!#!     at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571)
[15:58:16]: #!#!     at java.lang.Thread.run(Unknown Source)
[15:58:16]: #!#! 
[15:58:16]: #!#! Version Information:
[15:58:16]: #!#!   Skript: 2.2-dev22d
[15:58:16]: #!#!   Bukkit: 1.10-R0.1-SNAPSHOT
[15:58:16]: #!#!   Minecraft: 1.10
[15:58:16]: #!#!   Java: 1.8.0_101 (Java HotSpot(TM) 64-Bit Server VM 25.101-b13)
[15:58:16]: #!#!   OS: Windows Server 2012 R2 amd64 6.3
[15:58:16]: #!#! 
[15:58:16]: #!#! Running CraftBukkit: false
[15:58:16]: #!#! 
[15:58:16]: #!#! Current node: add "&2Skoven" to {br1-baner::*} (main.sk, line 5)
[15:58:16]: #!#! Current item: null
[15:58:16]: #!#! 
[15:58:16]: #!#! Thread: Server thread
[15:58:16]: #!#! 
[15:58:16]: #!#! End of Error.
[15:58:16]: #!#! `

**Comment by Pyon-Pyon** [comment]
did you used the `/reload` command?

**Comment by Pyon-Pyon** [comment]
you can't add texts to a single value variable. Also, just for be sure, did you use the `/reload` command?

**Comment by mads03dk** [comment]
Back in time i used the official skript(2.2). Before i update my server to 1.11 i just want to be sure all the plugins work, so when i installed bensku's fork of skript this does not work any more. No i didnt used the `/reload`

**Comment by bensku** [comment]
I'd need to see your command declarations in main.sk to say anything more.

**Comment by mads03dk** [comment]
here: http://hastebin.com/kopoguqise.cpp

**Comment by Pyon-Pyon** [comment]
kinda weird, it's working just fine to me. Try using the latest version and if with that version it still won't work try using the dev20b which is the most stable version.

**Comment by bensku** [comment]
No response if it worked or not, so I assume it did. Closing.
