### ISSUE TITLE
nullpointer on parsing function without parameters

### ISSUE THREAD

**Issue by BananaPirate** [bensku/Skript#289]
```
[18:41:02] [Server thread/INFO]: [0;37;22m[[0;33;22mSkript[0;37;22m][m Reloading all scripts...[m
[18:41:02] [Server thread/ERROR]: The 1st argument's definition is invalid. It should look like 'name: type' or 'name: type = default value'. (function test.sk, line 1: function test():')
[18:41:02] [Server thread/ERROR]: #!#! 
[18:41:02] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[18:41:02] [Server thread/ERROR]: #!#! Could not load function test.sk
[18:41:02] [Server thread/ERROR]: #!#! 
[18:41:02] [Server thread/ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[18:41:02] [Server thread/ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[18:41:02] [Server thread/ERROR]: #!#! and check whether this error has already been reported.
[18:41:02] [Server thread/ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[18:41:02] [Server thread/ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[18:41:02] [Server thread/ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[18:41:02] [Server thread/ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[18:41:02] [Server thread/ERROR]: #!#! 
[18:41:02] [Server thread/ERROR]: #!#! Stack trace:
[18:41:02] [Server thread/ERROR]: #!#! java.lang.NullPointerException
[18:41:02] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.Functions.loadFunction(Functions.java:121)
[18:41:02] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:485)
[18:41:02] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:247)
[18:41:02] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:201)
[18:41:02] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript.reloadScripts(Skript.java:694)
[18:41:02] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:145)
[18:41:02] [Server thread/ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[18:41:02] [Server thread/ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[18:41:02] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:649)
[18:41:02] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchServerCommand(CraftServer.java:635)
[18:41:02] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.DedicatedServer.aM(DedicatedServer.java:437)
[18:41:02] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:400)
[18:41:02] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675)
[18:41:02] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574)
[18:41:02] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[18:41:02] [Server thread/ERROR]: #!#! 
[18:41:02] [Server thread/ERROR]: #!#! Version Information:
[18:41:02] [Server thread/ERROR]: #!#!   Skript: 2.2-dev22f
[18:41:02] [Server thread/ERROR]: #!#!   Bukkit: 1.11-R0.1-SNAPSHOT
[18:41:02] [Server thread/ERROR]: #!#!   Minecraft: 1.11
[18:41:02] [Server thread/ERROR]: #!#!   Java: 1.8.0_65 (Java HotSpot(TM) 64-Bit Server VM 25.65-b01)
[18:41:02] [Server thread/ERROR]: #!#!   OS: Windows Server 2012 R2 amd64 6.3
[18:41:02] [Server thread/ERROR]: #!#! 
[18:41:02] [Server thread/ERROR]: #!#! Running CraftBukkit: false
[18:41:02] [Server thread/ERROR]: #!#! 
[18:41:02] [Server thread/ERROR]: #!#! Current node: function test(): (function test.sk, line 1)
[18:41:02] [Server thread/ERROR]: #!#! Current item: null
[18:41:02] [Server thread/ERROR]: #!#! 
[18:41:02] [Server thread/ERROR]: #!#! Thread: Server thread
[18:41:02] [Server thread/ERROR]: #!#! 
[18:41:02] [Server thread/ERROR]: #!#! End of Error.
[18:41:02] [Server thread/ERROR]: #!#! 
```

script in question is:

```
function test():
	broadcast "test"
```

works fine if I simply add a parameter

```
function test(p: player):
	broadcast "test"
```

also worth noting that the error message lists the bukkit version incorrectly
Server is running CraftBukkit version git-Spigot-f950f8e-58bff62 (MC: 1.11) (Implementing API version 1.11-R0.1-SNAPSHOT)

Which when writing this is 1 version behind current.

**Comment by Tuke-Nuke** [comment]
To create a function w/o parameter, you just need to add a default value to them:
```
function(test: Number = 1):
```
Them call it
```
test()
```

**Comment by bensku** [comment]
... but it is stupid that it doesn't work out of the box.

**Comment by bensku** [comment]
Fixed in next release!
