### ISSUE TITLE
Problem with functions.

### ISSUE THREAD

**Issue by Snow-Pyon** [bensku/Skript#299]
Hey bensku, I noticed that when I use [this](http://hastebin.com/guxitogake.vbs) function in this way: `warpSystem("get", "Warpname")` it throws the following stack trace:

<details><summary>stack trace</summary>

```
[19:11:53] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[19:11:53] [Server thread/ERROR]: #!#! Unexpected error while executing effect command 'send "%warpSystem(""get"", ""Test"")%"' by 'Pyon_Pyon'
[19:11:53] [Server thread/ERROR]: #!#! Stack trace:
[19:11:53] [Server thread/ERROR]: #!#! ch.njol.skript.SkriptAPIException: UnparsedLiterals must be converted before use
[19:11:53] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.UnparsedLiteral.invalidAccessException(UnparsedLiteral.java:275)
[19:11:53] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.UnparsedLiteral.getArray(UnparsedLiteral.java:295)
[19:11:53] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.Function.execute(Function.java:104)
[19:11:53] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:191)
[19:11:53] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.ExprFunctionCall.get(ExprFunctionCall.java:46)
[19:11:53] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:103)
[19:11:53] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.VariableString.toString(VariableString.java:383)
[19:11:53] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.VariableString.getArray(VariableString.java:488)
[19:11:53] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.VariableString.getArray(VariableString.java:1)
[19:11:53] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.EffMessage.execute(EffMessage.java:69)
[19:11:53] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:54)
[19:11:53] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.handleEffectCommand(Commands.java:296)
[19:11:53] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands$4$1.call(Commands.java:229)
[19:11:53] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands$4$1.call(Commands.java:1)
[19:11:53] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftFuture.run(CraftFuture.java:89)
[19:11:53] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[19:11:53] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729)
[19:11:53] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
[19:11:53] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660)
[19:11:53] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559)
[19:11:53] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[19:11:53] [Server thread/ERROR]: #!#! 
[19:11:53] [Server thread/ERROR]: #!#! Version Information:
[19:11:53] [Server thread/ERROR]: #!#!   Skript: 2.2-dev20
[19:11:53] [Server thread/ERROR]: #!#!   Bukkit: 1.9.2-R0.1-SNAPSHOT
[19:11:53] [Server thread/ERROR]: #!#!   Minecraft: 1.9.2
[19:11:53] [Server thread/ERROR]: #!#!   Java: 1.8.0_111 (Java HotSpot(TM) Client VM 25.111-b14)
[19:11:53] [Server thread/ERROR]: #!#!   OS: Windows 7 x86 6.1
[19:11:53] [Server thread/ERROR]: #!#! 
[19:11:53] [Server thread/ERROR]: #!#! Running CraftBukkit: false
[19:11:53] [Server thread/ERROR]: #!#! 
[19:11:53] [Server thread/ERROR]: #!#! Current node: null
[19:11:53] [Server thread/ERROR]: #!#! Current item: null
[19:11:53] [Server thread/ERROR]: #!#! 
[19:11:53] [Server thread/ERROR]: #!#! Thread: Server thread
[19:11:53] [Server thread/ERROR]: #!#! 
[19:11:53] [Server thread/ERROR]: #!#! End of Error.
[19:11:53] [Server thread/ERROR]: #!#! 
```
</details>
it throws that stack trace no matter what, tried with the latest version and the dev20b as it says. I also tried to remove all what that part does and instead of get the warp location in the yml I just put a broadcast there and I got the same stack trace other time.

But, if I move that part of code to other function like [this](http://hastebin.com/zuqemunafi.rb), it works perfectly.

The addons that I'm using are:

EventSK, skUtilities, skDragon, skStuff, EnumSK, MundoSK, RandomSK, Reqn, SharpSK, skMorkaz, skQuery and TuSKe if that helps.

**Comment by TheBentoBox** [comment]
I've seen this issue for a long time in a lot of situations, though given that there's an error message associated with it I'm not sure if it's correct to call it a bug. It does seem to happen with code that looks like it should work fine (such as what you've provided Pyon) and it often requires counter-intuitive solutions to work around this error. Would like feedback on how you'd want to handle this @bensku .

**Comment by TheLimeGlass** [comment]
The issue is when Skript parses the function
```
function testing(test: text) :: text:
	broadcast "%{_test}%"
on script load:
    broadcast "%testing(""test"")%"
    broadcast testing("test")
```
The first broadcasts `<none>` and the other works fine.

I can only replicate the issue if the function contains a string parameter.

**Comment by bensku** [comment]
Postponing this, since working with function code is very hard.

**Comment by Snow-Pyon** [comment]
This was fixed a long time ago. Closed.
