### ISSUE TITLE
1.11 [BUG]

### ISSUE THREAD

**Issue by linghun91** [bensku/Skript#300]
[23:02:01] [Server thread/INFO]: [Skript] Enabling Skript v2.2-dev20
[23:02:01] [Server thread/INFO]: [Skript] Successfully generated the config, the example scripts and the aliases files.
[23:02:01] [Server thread/ERROR]: Error occurred while enabling Skript v2.2-dev20 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.DyeColor.getData()B
	at ch.njol.skript.util.Color.<clinit>(Color.java:82) ~[?:?]
	at ch.njol.skript.SkriptCommand.<clinit>(SkriptCommand.java:62) ~[?:?]
	at ch.njol.skript.Skript.onEnable(Skript.java:273) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot-1.11.jar:git-Spigot-f950f8e-7f31326]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.jar:git-Spigot-f950f8e-7f31326]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.jar:git-Spigot-f950f8e-7f31326]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:375) [spigot-1.11.jar:git-Spigot-f950f8e-7f31326]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:325) [spigot-1.11.jar:git-Spigot-f950f8e-7f31326]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:419) [spigot-1.11.jar:git-Spigot-f950f8e-7f31326]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:380) [spigot-1.11.jar:git-Spigot-f950f8e-7f31326]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:335) [spigot-1.11.jar:git-Spigot-f950f8e-7f31326]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.11.jar:git-Spigot-f950f8e-7f31326]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [spigot-1.11.jar:git-Spigot-f950f8e-7f31326]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
[23:02:01] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it

**Comment by TrademarkTM** [comment]
Seems like you are using an outdated version.
Go to releases page and download it.

**Comment by bensku** [comment]
Outdated version on 1.11.
