### ISSUE TITLE
Spigot 1.10.2 latest bug

### ISSUE THREAD

**Issue by GreatRaceofGithub** [bensku/Skript#305]
[20:25:19] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[20:25:19] [Server thread/ERROR]: #!#! 
[20:25:19] [Server thread/ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[20:25:19] [Server thread/ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[20:25:19] [Server thread/ERROR]: #!#! and check whether this error has already been reported.
[20:25:19] [Server thread/ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[20:25:19] [Server thread/ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[20:25:19] [Server thread/ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[20:25:19] [Server thread/ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[20:25:19] [Server thread/ERROR]: #!#! 
[20:25:19] [Server thread/ERROR]: #!#! Stack trace:
[20:25:19] [Server thread/ERROR]: #!#! java.lang.NullPointerException
[20:25:19] [Server thread/ERROR]: #!#!     at com.gmail.thelimeglass.BossBars.ExprBarTitle.get(ExprBarTitle.java:42)
[20:25:19] [Server thread/ERROR]: #!#!     at com.gmail.thelimeglass.BossBars.ExprBarTitle.get(ExprBarTitle.java:1)
[20:25:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:105)
[20:25:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.VariableString.toString(VariableString.java:383)
[20:25:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.VariableString.getAll(VariableString.java:493)
[20:25:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.VariableString.check(VariableString.java:508)
[20:25:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.conditions.CondCompare.check(CondCompare.java:260)
[20:25:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Condition.run(Condition.java:58)
[20:25:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Conditional.walk(Conditional.java:53)
[20:25:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93)
[20:25:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
[20:25:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:91)
[20:25:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.Function.execute(Function.java:109)
[20:25:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:191)
[20:25:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:55)
[20:25:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:54)
[20:25:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:65)
[20:25:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93)
[20:25:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
[20:25:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:152)
[20:25:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:112)
[20:25:19] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[20:25:19] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[20:25:19] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[20:25:19] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231)
[20:25:19] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:198)
[20:25:19] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:194)
[20:25:19] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:953)
[20:25:19] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_10_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26)
[20:25:19] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_10_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1)
[20:25:19] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[20:25:19] [Server thread/ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[20:25:19] [Server thread/ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
[20:25:19] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45)
[20:25:19] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732)
[20:25:19] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400)
[20:25:19] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668)
[20:25:19] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567)
[20:25:19] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[20:25:19] [Server thread/ERROR]: #!#!

**Comment by Pyon-Pyon** [comment]
It's a problem of Skellett, not of Skript.

**Comment by bensku** [comment]
Skellett might have dropped 1.10 compatibility... Or this is 1.11 only feature.
