### ISSUE TITLE
Region Hooks broke with update

### ISSUE THREAD

**Issue by melinstagibson** [bensku/Skript#307]
[01:35:56 ERROR]: Could not pass event PlayerMoveEvent to Skript v2.2-dev22f
java.lang.IncompatibleClassChangeError: Expected static method com.bekvon.bukkit.residence.Residence.getResidenceManager()Lcom/bekvon/bukkit/residence/protection/ResidenceManager;
        at ch.njol.skript.hooks.regions.ResidenceHook.getRegionsAt_i(ResidenceHook.java:94) ~[?:?]
        at ch.njol.skript.hooks.regions.RegionsPlugin.getRegionsAt(RegionsPlugin.java:94) ~[?:?]
        at ch.njol.skript.hooks.regions.events.EvtRegionBorder$3.execute(EvtRegionBorder.java:161) ~[?:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.11.2.jar:git-Paper-989]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.11.2.jar:git-Paper-989]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.11.2.jar:git-Paper-989]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.11.2.jar:git-Paper-989]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:617) [patched_1.11.2.jar:git-Paper-989]
        at net.minecraft.server.v1_11_R1.PacketPlayInFlying.a(SourceFile:126) [patched_1.11.2.jar:git-Paper-989]
        at net.minecraft.server.v1_11_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) [patched_1.11.2.jar:git-Paper-989]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.11.2.jar:git-Paper-989]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [patched_1.11.2.jar:git-Paper-989]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:817) [patched_1.11.2.jar:git-Paper-989]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-989]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [patched_1.11.2.jar:git-Paper-989]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [patched_1.11.2.jar:git-Paper-989]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]

:/

**Comment by melinstagibson** [comment]
Ugh this is actually a major blow to me since all my servers depend on those 2 plugins, anything i can do to motivate you fixing this immediately? Ill gladly toss you a few bucks...

**Comment by bensku** [comment]
Residence has updated, I guess. Shouldn't be too hard to fix on Skript side, but that will naturally break all previous Residence versions.

**Comment by melinstagibson** [comment]
Its just odd because this error spams the console even if i have no scripts running at all.

Could you fix this soon? Since old versions will always work with old skript versions it shouldnt be an issue. Please.

**Comment by bensku** [comment]
I guess this is fixed now. Can you confirm?

**Comment by melinstagibson** [comment]
I wont be able to get on today, will close this issue if its fixed tomorrow

Am 22.12.2016 10:06 nachm. schrieb "bensku" <notifications@github.com>:

**Comment by TheBentoBox** [comment]
@melinstagibson Can you confirm for us if this is now fixed?

**Comment by melinstagibson** [comment]
works for me on the latest spigot and residences aswell as worldguard, closed
