### ISSUE TITLE
Restart to load the script?

### ISSUE THREAD

**Issue by Slendarz** [bensku/Skript#310]
Sometimes the server need to be restarted then my script can be loaded. I tried using /sk reload <myscript>, it said "Successfully reloaded ..." but my script's feature doesn't work at all. I am using the latest version of bensku Skript. Please fix this thing. Very sorry about my english.

**Comment by bensku** [comment]
What is printed to console?

**Comment by MisterBrown8** [comment]
[14:27:25 ERROR]: #!#! >
[14:27:25 ERROR]: #!#! [Skript] Severe Error:>
[14:27:25 ERROR]: #!#! Could not load CW.sk>
[14:27:25 ERROR]: #!#! >
[14:27:25 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.>
[14:27:25 ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/>
[14:27:25 ERROR]: #!#! and check whether this error has already been reported.>
[14:27:25 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),>
[14:27:25 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.>
[14:27:25 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.>
[14:27:25 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.>
[14:27:25 ERROR]: #!#! >
[14:27:25 ERROR]: #!#! Stack trace:>
[14:27:25 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for skill>
[14:27:25 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:264)>
[14:27:25 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1390)>
[14:27:25 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1111)>
[14:27:25 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1057)>
[14:27:25 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:221)>

[14:27:25 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)>

[14:27:25 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:321)>

[14:27:25 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:418)>

[14:27:25 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1132)>

[14:27:25 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:221)>

[14:27:25 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)>

[14:27:25 ERROR]: #!#!     at ch.njol.skript.lang.Condition.parse(Condition.java:83)>

[14:27:25 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:833)>

[14:27:25 ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:467)>

[14:27:25 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:472)>

[14:27:25 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:271)>

[14:27:25 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:167)>

[14:27:25 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)>

[14:27:25 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)>

[14:27:25 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:649)>

[14:27:25 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1337)>

[14:27:25 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1172)>
[14:27:25 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)>
[14:27:25 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)>
[14:27:25 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)>
[14:27:25 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)>
[14:27:25 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(FutureTask.java:266)>
[14:27:25 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)>
[14:27:25 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739)>
[14:27:25 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)>
[14:27:25 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675)>
[14:27:25 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574)>
[14:27:25 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)>
[14:27:25 ERROR]: #!#! >
[14:27:25 ERROR]: #!#! Version Information:>
[14:27:25 ERROR]: #!#!   Skript: 2.2-dev22g>
[14:27:25 ERROR]: #!#!   Bukkit: 1.11-R0.1-SNAPSHOT>
[14:27:25 ERROR]: #!#!   Minecraft: 1.11>
[14:27:25 ERROR]: #!#!   Java: 1.8.0_111 (Java HotSpot(TM) 64-Bit Server VM 25.111-b14)>
[14:27:25 ERROR]: #!#!   OS: Linux amd64 4.8.6-x86_64-linode78>
[14:27:25 ERROR]: #!#! >
[14:27:25 ERROR]: #!#! Running CraftBukkit: false>
[14:27:25 ERROR]: #!#! >
[14:27:25 ERROR]: #!#! Current node: arg 1 is not set: (CW.sk, line 20)>
[14:27:25 ERROR]: #!#! Current item: null>
[14:27:25 ERROR]: #!#! >
[14:27:25 ERROR]: #!#! Thread: Server thread>
[14:27:25 ERROR]: #!#! >
[14:27:25 ERROR]: #!#! End of Error.>
[14:27:25 ERROR]: #!#! >
[14:27:25 ERROR]: #!#! List of plugins: >
[14:27:25 ERROR]: #!#! GroupManager - 2.0.1-b332, ClearLag - 2.9.3, CrackShot - 0.98.5, PlugMan - 2.1.1, Multiverse-Core - 2.5-b719, ProtocolLib - 4.2.0, SkinsRestorer - 12.9.5, FastAsyncWorldEdit - 16.12.23-59c45f0-448-9.23.1, VoidGenerator - 1.0, PointBlank - 1.0, VoxelSniper - 5.171.0-SNAPSHOT, WildSkript - 1.1, mcMMO - 1.5.00-b3547, MotdManager-Reloaded - 1.44, Vault - 1.5.6-b49, WorldEdit - 6.1.5;4651611, MyPet - 2.0.0, Skript - 2.2-dev22g, Essentials - 2.0.1-b434, skDragon - 0.13.1, SkQuery - 3.22.1, HolographicDisplays - 2.2.3, HideAndCustomPlugins - 1.7, WorldGuard - 6.1.3-SNAPSHOT;c904242, SkStuff - 1.6.3.6, Citizens - 2.0.21-SNAPSHOT (build 1437), skRayFall - 1.9.5, EssentialsXMPP - 2.0.1-b434, EssentialsProtect - 2.0.1-b434, React - 3.1p, EssentialsGeoIP - 2.0.1-b434, EssentialsChat - 2.0.1-b434, SkRambled - 2.1, EssentialsAntiBuild - 2.0.1-b434, skUtilities - 0.8.6, Umbaska - 2.0 Beta 5.5.1 for Minecraft 1.10, RandomSK - 2.7.1, EssentialsSpawn - 2.0.1-b434, TitleManager - 1.5.13, AuthMe - 5.2-SNAPSHOT-b1384, LiteBans - 2.1.9, SharpSK - 1.5.8>
[14:27:25 ERROR]: #!#! >
[14:27:25 ERROR]: #!#! List of addons: >
[14:27:25 ERROR]: #!#! skDragon v0.13.1skUtilities v0.8.6skRayFall v1.9.5Umbaska v2.0 Beta 5.5.1 for Minecraft 1.10SkQuery v3.22.1SharpSK v1.5.8RandomSK v2.7.1WildSkript v1.1SkStuff v1.6.3.6SkRambled v2.1>
[14:27:25 ERROR]: #!#! >
[14:27:25 ERROR]: #!#! >

**Comment by Slendarz** [comment]
I disabled the Umbaska plugin and my scripts works perfectly. I think its because of the Umbaska add-on, your Skript isn't compatible with Umbaska. Last time your Skript works perfectly with Umbaska is on dev20b. Can you please fix this? And again, very sory about my english.

**Comment by bensku** [comment]
No, I will not waste my time to mess with Umbaska 2. Version 3 is coming soon.

You might want to set "addon safety checks: true" in Skript config for temporary solution. If that doesn't work, "api soft exceptions: true". If it still won't work, you'll need to wait for Umbaska 3.
