### ISSUE TITLE
Any working version for 1.11.2?

### ISSUE THREAD

**Issue by YellowZaki** [bensku/Skript#313]
I have updated my server to 1.11.2 and any skript version loads. Please help.

**Comment by TheBentoBox** [comment]
What do you mean by "any version loads"? Are you saying it doesn't work?

**Comment by YellowZaki** [comment]
It says:
[15:24:15] [Server thread/INFO]: [Skript] Enabling Skript v2.2-dev22g
[15:24:15] [Server thread/ERROR]: Error occurred while enabling Skript v2.2-dev22g (Is it up to date?)
java.lang.IllegalAccessError: tried to access class ch.njol.skript.util.Color$1 from class ch.njol.skript.util.Color
	at ch.njol.skript.util.Color.<clinit>(Color.java:89) ~[?:?]
	at ch.njol.skript.SkriptCommand.<clinit>(SkriptCommand.java:62) ~[?:?]
	at ch.njol.skript.Skript.onEnable(Skript.java:273) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[patched_1.11.2.jar:git-Paper-992]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.11.2.jar:git-Paper-992]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.11.2.jar:git-Paper-992]
	at net.diamondmine.reloader.PluginReloader.loadPlugin(PluginReloader.java:216) [PluginReloader.jar:1.3.1]
	at net.diamondmine.reloader.PluginReloader.onCommand(PluginReloader.java:87) [PluginReloader.jar:1.3.1]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [patched_1.11.2.jar:git-Paper-992]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) [patched_1.11.2.jar:git-Paper-992]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:674) [patched_1.11.2.jar:git-Paper-992]
	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1383) [patched_1.11.2.jar:git-Paper-992]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1188) [patched_1.11.2.jar:git-Paper-992]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched_1.11.2.jar:git-Paper-992]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) [patched_1.11.2.jar:git-Paper-992]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.11.2.jar:git-Paper-992]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [patched_1.11.2.jar:git-Paper-992]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:817) [patched_1.11.2.jar:git-Paper-992]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-992]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [patched_1.11.2.jar:git-Paper-992]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [patched_1.11.2.jar:git-Paper-992]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]

**Comment by TheBentoBox** [comment]
Gotcha, I'll test and see if I have this issue too on 1.11.2.

What Skript addons are you using too, by chance? Can you do `/version` and `/plugins` and send us a screenshot of the results?

**Comment by YellowZaki** [comment]
I'm using PaperSpigot 1.11.2 (build 992)
The plugins are not affecting because I tried launching the server with skript only.
And I'm not using any skript addon.

**Comment by TheBentoBox** [comment]
Ok, thanks for the quick responses! I'll respond in a few with my test on a new non-Paper build with dev22g.

**Comment by TheBentoBox** [comment]
I am NOT getting this issue on a freshly built Spigot jar with dev22g. It must be an issue with Paper, they must've changed something in the Color class.

**Comment by melinstagibson** [comment]
No, im using the latest paper with the latest script too. Tried to retry
with 2 totally new files?

Am 25.12.2016 10:59 nachm. schrieb "Jake Ben-Tovim" <
notifications@github.com>:

**Comment by YellowZaki** [comment]
@melinstagibson I don't understand when you say 2 totally new files.
I'm using Skript-oldparser.jar 
I have tried dev22g dev22f dev22d...

**Comment by TheBentoBox** [comment]
Are you sure you're using a fully up to date PaperSpigot?

**Comment by YellowZaki** [comment]
Yes, I'm totally sure.

**Comment by melinstagibson** [comment]
Try with build 991

Am 25.12.2016 11:07 nachm. schrieb "YellowZaki" <notifications@github.com>:

**Comment by RoyCurtis** [comment]
Skript 2.2 dev22g is working fine for me, on both a [PaperSpigot 1.11.2 build 992 local testing server](http://i.imgur.com/MIjvKBX.png) and PaperSpigot 1.11.2 build 991 live Survival server.

@YellowZaki: According to your crash log, [someone is attempting to reload Skript using a plugin called PluginReloader](http://i.imgur.com/5CjBN8a.png). Reloading a plugin is [typically a bad idea](https://www.reddit.com/r/admincraft/comments/5jwi1m/my_spigot_110_server_crashes_when_i_try_and_do_a/dbjijw2/) as it can cause obscure issues such as this.

You said you tried launching the server with Skript only; can you please share the crash log from when you try that?

**Comment by TheBentoBox** [comment]
Thank you @RoyCurtis, I must've glazed over that PluginReloader thing without realizing it was an actual plugin which was triggering the reload. 

As Roy said, do NOT use /reload or any plugins which provide similar plugin reloading services and expect it to work well. It's not a good idea and you should always restart your server -- we certainly won't be trying to fix errors that're the result of a reload. Restart your server properly and see if the error persists.

**Comment by TheLimeGlass** [comment]
Especially Skript. Skript was not designed to be reloaded.

**Comment by YellowZaki** [comment]
I had reloaded skript in previous versions (1.10).
Anyway, I think that I started the server with skript... So strange

**Comment by TheBentoBox** [comment]
So you're saying it's working fine now @YellowZaki ?

**Comment by YellowZaki** [comment]
Yes it is working fine
