### ISSUE TITLE
not pass event PlayerCommandPreprocessEvent

### ISSUE THREAD

**Issue by aviations** [bensku/Skript#325]
Environment : Spigot 1.11.2 latest, Skript 2.2-dev22g.

error console :

`
[14:44:26] [Server thread/ERROR]: Could not pass event PlayerCommandPreprocessEvent to Skript v2.2-dev22g
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-ce89845]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-ce89845]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar:git-Spigot-7d78b81-ce89845]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2.jar:git-Spigot-7d78b81-ce89845]
	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1336) [spigot-1.11.2.jar:git-Spigot-7d78b81-ce89845]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1179) [spigot-1.11.2.jar:git-Spigot-7d78b81-ce89845]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.11.2.jar:git-Spigot-7d78b81-ce89845]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.11.2.jar:git-Spigot-7d78b81-ce89845]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-7d78b81-ce89845]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_112]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_112]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2.jar:git-Spigot-7d78b81-ce89845]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.11.2.jar:git-Spigot-7d78b81-ce89845]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-7d78b81-ce89845]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.2.jar:git-Spigot-7d78b81-ce89845]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.2.jar:git-Spigot-7d78b81-ce89845]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_112]
Caused by: java.lang.NoSuchMethodError: org.bukkit.Bukkit.getOnlinePlayers()[Lorg/bukkit/entity/Player;
	at com.w00tmast3r.skquery.elements.effects.EffParticle.execute(EffParticle.java:33) ~[?:?]
	at ch.njol.skript.lang.Effect.run(Effect.java:54) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:65) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93) ~[?:?]
	at ch.njol.skript.lang.Trigger.execute(Trigger.java:53) ~[?:?]
	at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:222) ~[?:?]
	at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:184) ~[?:?]
	at ch.njol.skript.command.Commands.handleCommand(Commands.java:270) ~[?:?]
	at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:165) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_112]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_112]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_112]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-ce89845]
	... 16 more
`

**Comment by TheBentoBox** [comment]
This is an SkQuery error, not a Skript error. Update to LimeGlass's 1.11 SkQuery from the forums.
