### ISSUE TITLE
Console getting spammed with warns

### ISSUE THREAD

**Issue by sandor111** [bensku/Skript#330]
My console is getting spammed with this message:
[09:45:08 WARN]: java.io.IOException: Het systeem kan het opgegeven pad niet vinden
[09:45:08 WARN]:        at java.io.WinNTFileSystem.createFileExclusively(Native Method)
[09:45:08 WARN]:        at java.io.File.createNewFile(Unknown Source)
[09:45:08 WARN]:        at com.w00tmast3r.skquery.elements.expressions.ExprYAMLValue.get(ExprYAMLValue.java:39)
[09:45:08 WARN]:        at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:105)
[09:45:08 WARN]:        at ch.njol.skript.effects.EffChange.execute(EffChange.java:270)
[09:45:08 WARN]:        at ch.njol.skript.lang.Effect.run(Effect.java:54)
[09:45:08 WARN]:        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:65)
[09:45:08 WARN]:        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93)
[09:45:08 WARN]:        at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
[09:45:08 WARN]:        at ch.njol.skript.events.EvtPeriodical.execute(EvtPeriodical.java:92)
[09:45:08 WARN]:        at ch.njol.skript.events.EvtPeriodical$1.run(EvtPeriodical.java:106)
[09:45:08 WARN]:        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71)
[09:45:08 WARN]:        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[09:45:08 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:734)
[09:45:08 WARN]:        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399)
[09:45:08 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665)
[09:45:08 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564)
[09:45:08 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by Pyon-Pyon** [comment]
Not a Skript problem, it's something related to skQuery.

**Comment by sandor111** [comment]
@Pyon-Pyon  Ok :(

**Comment by sandor111** [comment]
@Pyon-Pyon But its the only addon with the on any movement event :(
But it isn't getting updated any more :(
Or do you know another addon which does the same or is a good replacer for skquery

**Comment by Pyon-Pyon** [comment]
Gatt and LimeGlass did a fix of skQuery that are working in 1.9+

Gatt's fix:
https://umbaska.gatt.space/

Lime's fix:
https://forums.skunity.com/topic/4678/inventory-restore-umbaeska-skquery-a-limebae-project

**Comment by TheBentoBox** [comment]
Closing, as this isn't the replace to report addon issues.
