### ISSUE TITLE
resolving offline players

### ISSUE THREAD

**Issue by loadka95** [bensku/Skript#357]
# Console:
[15:01:57 ERROR]: #!#!
[15:01:57 ERROR]: #!#! [Skript] Severe Error:
[15:01:57 ERROR]: #!#! An error happened when trying to enably resolving offline players, so the feature has been turned off. Please report this at https://github.com/bensku/Skript/issues/237
[15:01:57 ERROR]: #!#!
[15:01:57 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[15:01:57 ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[15:01:57 ERROR]: #!#! and check whether this error has already been reported.
[15:01:57 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[15:01:57 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[15:01:57 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[15:01:57 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[15:01:57 ERROR]: #!#!
[15:01:57 ERROR]: #!#! Stack trace:
[15:01:57 ERROR]: #!#! java.lang.NullPointerException: null offline player resolve queue
[15:01:57 ERROR]: #!#!     at ch.njol.skript.bukkitutil.UnresolvedOfflinePlayer$1.run(UnresolvedOfflinePlayer.java:58)
[15:01:57 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[15:01:57 ERROR]: #!#!
[15:01:57 ERROR]: #!#! Version Information:
[15:01:57 ERROR]: #!#!   Skript: 2.2-dev23
[15:01:57 ERROR]: #!#!   Bukkit: 1.11.2-R0.1-SNAPSHOT
[15:01:57 ERROR]: #!#!   Minecraft: 1.11.2
[15:01:57 ERROR]: #!#!   Java: 1.8.0_112 (Java HotSpot(TM) 64-Bit Server VM 25.112-b15)
[15:01:57 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[15:01:57 ERROR]: #!#!
[15:01:57 ERROR]: #!#! Running CraftBukkit: false
[15:01:57 ERROR]: #!#!
[15:01:57 ERROR]: #!#! Current node: null
[15:01:57 ERROR]: #!#! Current item: null
[15:01:57 ERROR]: #!#!
[15:01:57 ERROR]: #!#! Thread: Skript offline player resolver thread (fetches UUIDs from the minecraft servers)
[15:01:57 ERROR]: #!#!
[15:01:57 ERROR]: #!#! End of Error.
[15:01:57 ERROR]: #!#!

**Comment by Pyon-Pyon** [comment]
What you did for make that happen?

**Comment by loadka95** [comment]
I installed the new version of skript. I got the error every time, when start my server.

**Comment by Pyon-Pyon** [comment]
can you tell me the plugins that you have please?

**Comment by loadka95** [comment]
Citizens,  Skellett,  SkinsRestorer-v12.9.5,  SkQuery,  skRayFall_v1.9.7,  Skript

**Comment by TheBentoBox** [comment]
Is your server in offline mode by chance?

**Comment by TheBentoBox** [comment]
No response, closing.
