### ISSUE TITLE
getOnlinePlayers() error ?

### ISSUE THREAD

**Issue by ZeTioZ** [bensku/Skript#372]
Hello, I'm using the dev 23 and the 1.10, I got this error message when I launch the server

`[Server thread/ERROR]: Error occurred while enabling Skript v2.2-dev23 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.entity.Villager$Profession.isZombie()Z
	at ch.njol.skript.entity.VillagerData.<clinit>(VillagerData.java:66) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_60]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_60]
	at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:110) ~[?:?]
	at ch.njol.skript.Skript.onEnable(Skript.java:286) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[Spigot-v1_10.jar:git-Spigot-da278d1-a8a4bed]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [Spigot-v1_10.jar:git-Spigot-da278d1-a8a4bed]
	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:145) [PerWorldPlugins%20v1.1.0.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [Spigot-v1_10.jar:git-Spigot-da278d1-a8a4bed]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:362) [Spigot-v1_10.jar:git-Spigot-da278d1-a8a4bed]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:322) [Spigot-v1_10.jar:git-Spigot-da278d1-a8a4bed]
	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:416) [Spigot-v1_10.jar:git-Spigot-da278d1-a8a4bed]
	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:381) [Spigot-v1_10.jar:git-Spigot-da278d1-a8a4bed]
	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:336) [Spigot-v1_10.jar:git-Spigot-da278d1-a8a4bed]
	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:270) [Spigot-v1_10.jar:git-Spigot-da278d1-a8a4bed]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:539) [Spigot-v1_10.jar:git-Spigot-da278d1-a8a4bed]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]`

**Comment by TheBentoBox** [comment]
That's really strange, given that this method DOES exist in Spigot 1.10 (even though it's a NoSuchMethodError). But the error log confirms your server is on 1.10 and you're using dev23.

**Comment by ZeTioZ** [comment]
I've updated the spigot 1.10.2 and the bug has been solved, but there is a other bug, the scripts into a folder doesn't load and this error message when trying to get an online player.

`[Server thread/ERROR]: Could not pass event PlayerCommandPreprocessEvent to Skript v2.2-dev23
java.lang.NoSuchMethodError: org.bukkit.Bukkit.getOnlinePlayers()[Lorg/bukkit/entity/Player;
	at ch.njol.skript.entity.EntityData.getAll(EntityData.java:455) ~[?:?]
	at ch.njol.skript.expressions.ExprEntities.get(ExprEntities.java:147) ~[?:?]
	at ch.njol.skript.expressions.ExprEntities.get(ExprEntities.java:1) ~[?:?]
	at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:105) ~[?:?]
	at ch.njol.skript.lang.util.SimpleExpression.iterator(SimpleExpression.java:308) ~[?:?]
	at ch.njol.skript.expressions.ExprEntities.iterator(ExprEntities.java:212) ~[?:?]
	at ch.njol.skript.lang.Loop.walk(Loop.java:81) ~[?:?]
	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93) ~[?:?]
	at ch.njol.skript.lang.Trigger.execute(Trigger.java:53) ~[?:?]
	at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:152) ~[?:?]
	at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:112) ~[?:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot-v1_10.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot-v1_10.jar:git-Spigot-de459a2-51263e9]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot-v1_10.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1350) [Spigot-v1_10.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1193) [Spigot-v1_10.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [Spigot-v1_10.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [Spigot-v1_10.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot-v1_10.jar:git-Spigot-de459a2-51263e9]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_60]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_60]
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [Spigot-v1_10.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [Spigot-v1_10.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [Spigot-v1_10.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [Spigot-v1_10.jar:git-Spigot-de459a2-51263e9]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [Spigot-v1_10.jar:git-Spigot-de459a2-51263e9]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]`

**Comment by Syst3ms** [comment]
The issue shows you're still on spigot 1.10 or on 1.10.1, which is unstable

**Comment by ZeTioZ** [comment]
You can close this thread, I don't know how but I solved the problem, I just updated all of the addons and all work as well ;). Thanks for your help ^^
