### ISSUE TITLE
Any of new versions not working

### ISSUE THREAD

**Issue by DatArnoGuy** [bensku/Skript#376]
Skript dev21 or newer versions does not work in 1.10 or 1.11. I reinstalled the whole server and still not working. I did put newest version (dev23) to the plugins-folder of empty server. Nothing did happen when i started the server and client says there is any plugins in server, while there was skript-oldparser.jar for dev23 in plugins folder. This is the error message from the client in 1.11

[18:10:43 ERROR]: Could not load 'plugins/Skript-oldparser.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: ch/njol/skript/Skript : Unsupported major.minor version 52.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[spigot.jar:git-Spigot-b4417b8-3c48711]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot.jar:git-Spigot-b4417b8-3c48711]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot.jar:git-Spigot-b4417b8-3c48711]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:301) [spigot.jar:git-Spigot-b4417b8-3c48711]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:204) [spigot.jar:git-Spigot-b4417b8-3c48711]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-Spigot-b4417b8-3c48711]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_121]
Caused by: java.lang.UnsupportedClassVersionError: ch/njol/skript/Skript : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_121]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803) ~[?:1.7.0_121]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_121]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442) ~[?:1.7.0_121]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64) ~[?:1.7.0_121]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354) ~[?:1.7.0_121]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348) ~[?:1.7.0_121]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_121]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347) ~[?:1.7.0_121]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-b4417b8-3c48711]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-b4417b8-3c48711]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_121]
	at java.lang.Class.forName0(Native Method) ~[?:1.7.0_121]
	at java.lang.Class.forName(Class.java:278) ~[?:1.7.0_121]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot.jar:git-Spigot-b4417b8-3c48711]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot.jar:git-Spigot-b4417b8-3c48711]
	... 6 more

**Comment by TheBentoBox** [comment]
dev21 and above work fine for everyone else, this is an issue on your end. You should learn to read error logs, this is an issue with your version of Java as can be seen after a simple Google search of the reason it gave you for being unable to load:

```
Unsupported major.minor version 52.0
```

Try updating your Java or running it on different versions, or trying a couple of different versions of Skript. I'm running dev23 on 1.11.2 with Java 8 though, and have no issues (and have not heard of anyone else having this issue).
