### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by SlimeDog** [bensku/Skript#379]
Spigot 1.11.2 latest, Skript 2.2 dev24

Skript ran without errors on dev23

> [21:46:42] [Server thread/ERROR]: #!#! 
[21:46:42] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[21:46:42] [Server thread/ERROR]: #!#! Could not load clear-inventory.sk
[21:46:42] [Server thread/ERROR]: #!#! 
[21:46:42] [Server thread/ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[21:46:42] [Server thread/ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[21:46:42] [Server thread/ERROR]: #!#! and check whether this error has already been reported.
[21:46:42] [Server thread/ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[21:46:42] [Server thread/ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[21:46:42] [Server thread/ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[21:46:42] [Server thread/ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[21:46:42] [Server thread/ERROR]: #!#! 
[21:46:42] [Server thread/ERROR]: #!#! Stack trace:
[21:46:42] [Server thread/ERROR]: #!#! java.lang.UnsupportedOperationException: Parsing not implemented (remember to override parse method)
[21:46:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.classes.Parser.parse(Parser.java:72)
[21:46:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:422)
[21:46:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Classes.parse(Classes.java:451)
[21:46:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:97)
[21:46:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:86)
[21:46:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:1)
[21:46:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.conditions.CondContains.init(CondContains.java:72)
[21:46:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:249)
[21:46:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[21:46:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:61)
[21:46:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:754)
[21:46:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Loop.<init>(Loop.java:68)
[21:46:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:790)
[21:46:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:467)
[21:46:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:472)
[21:46:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:247)
[21:46:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:201)
[21:46:42] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript$2.run(Skript.java:406)
[21:46:42] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
[21:46:42] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[21:46:42] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738)
[21:46:42] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[21:46:42] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
[21:46:42] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
[21:46:42] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)
[21:46:42] [Server thread/ERROR]: #!#! 
[21:46:42] [Server thread/ERROR]: #!#! Version Information:
[21:46:42] [Server thread/ERROR]: #!#!   Skript: 2.2-dev24
[21:46:42] [Server thread/ERROR]: #!#!   Bukkit: 1.11.2-R0.1-SNAPSHOT
[21:46:42] [Server thread/ERROR]: #!#!   Minecraft: 1.11.2
[21:46:42] [Server thread/ERROR]: #!#!   Java: 1.8.0_121 (OpenJDK 64-Bit Server VM 25.121-b13)
[21:46:42] [Server thread/ERROR]: #!#!   OS: Linux amd64 3.10.0-514.6.1.el7.x86_64
[21:46:42] [Server thread/ERROR]: #!#! 
[21:46:42] [Server thread/ERROR]: #!#! Running CraftBukkit: false
[21:46:42] [Server thread/ERROR]: #!#! 
[21:46:42] [Server thread/ERROR]: #!#! Current node: {_name} does not contain "Change world" (clear-inventory.sk, line 23)
[21:46:42] [Server thread/ERROR]: #!#! Current item: null
[21:46:42] [Server thread/ERROR]: #!#! 
[21:46:42] [Server thread/ERROR]: #!#! Thread: Server thread
[21:46:42] [Server thread/ERROR]: #!#! 
[21:46:42] [Server thread/ERROR]: #!#! End of Error.
[21:46:42] [Server thread/ERROR]: #!#!

**Comment by bensku** [comment]
I would like to see relevant parts of clear-inventory.sk. Need to test...

**Comment by JadedDragoon** [comment]
Almost identical error. Also worked flawlessly under dev23 (which I have reverted to in order to resolve the error for now.)

```
[06:18:23 ERROR]: #!#!
[06:18:23 ERROR]: #!#! [Skript] Severe Error:
[06:18:23 ERROR]: #!#! Could not load homes.sk
[06:18:23 ERROR]: #!#!
[06:18:23 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[06:18:23 ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[06:18:23 ERROR]: #!#! and check whether this error has already been reported.
[06:18:23 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[06:18:23 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[06:18:23 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[06:18:23 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[06:18:23 ERROR]: #!#!
[06:18:23 ERROR]: #!#! Stack trace:
[06:18:23 ERROR]: #!#! java.lang.UnsupportedOperationException: Parsing not implemented (remember to override parse method)
[06:18:23 ERROR]: #!#!     at ch.njol.skript.classes.Parser.parse(Parser.java:72)
[06:18:23 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:422)
[06:18:23 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.parse(Classes.java:451)
[06:18:23 ERROR]: #!#!     at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:97)
[06:18:23 ERROR]: #!#!     at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:86)
[06:18:23 ERROR]: #!#!     at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:1)
[06:18:23 ERROR]: #!#!     at ch.njol.skript.expressions.ExprDifference.init(ExprDifference.java:89)
[06:18:23 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:249)
[06:18:23 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[06:18:23 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:321)
[06:18:23 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:418)
[06:18:23 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.newInstance(VariableString.java:197)
[06:18:23 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.newInstance(VariableString.java:109)
[06:18:23 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:319)
[06:18:23 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:418)
[06:18:23 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1132)
[06:18:23 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1084)
[06:18:23 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:221)
[06:18:23 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[06:18:23 ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:61)
[06:18:23 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:754)
[06:18:23 ERROR]: #!#!     at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:56)
[06:18:23 ERROR]: #!#!     at ch.njol.skript.lang.Conditional.<init>(Conditional.java:46)
[06:18:23 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:840)
[06:18:23 ERROR]: #!#!     at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:56)
[06:18:23 ERROR]: #!#!     at ch.njol.skript.lang.Conditional.<init>(Conditional.java:46)
[06:18:23 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:840)
[06:18:23 ERROR]: #!#!     at ch.njol.skript.lang.function.ScriptFunction.<init>(ScriptFunction.java:53)
[06:18:23 ERROR]: #!#!     at ch.njol.skript.lang.function.Functions.loadFunction(Functions.java:129)
[06:18:23 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:485)
[06:18:23 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:247)
[06:18:23 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:201)
[06:18:23 ERROR]: #!#!     at ch.njol.skript.Skript$2.run(Skript.java:406)
[06:18:23 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
[06:18:23 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[06:18:23 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738)
[06:18:23 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[06:18:23 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
[06:18:23 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
[06:18:23 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)
[06:18:23 ERROR]: #!#!
[06:18:23 ERROR]: #!#! Version Information:
[06:18:23 ERROR]: #!#!   Skript: 2.2-dev24
[06:18:23 ERROR]: #!#!   Bukkit: 1.11.2-R0.1-SNAPSHOT
[06:18:23 ERROR]: #!#!   Minecraft: 1.11.2
[06:18:23 ERROR]: #!#!   Java: 1.8.0_121 (Java HotSpot(TM) 64-Bit Server VM 25.121-b13)
[06:18:23 ERROR]: #!#!   OS: Linux amd64 3.13.0-107-generic
[06:18:23 ERROR]: #!#!
[06:18:23 ERROR]: #!#! Running CraftBukkit: false
[06:18:23 ERROR]: #!#!
[06:18:23 ERROR]: #!#! Current node: message "You must wait %difference between {@homeCooldown} and {_waited}% before using this command again." to {_p} (homes.sk, line 13)
[06:18:23 ERROR]: #!#! Current item: null
[06:18:23 ERROR]: #!#!
[06:18:23 ERROR]: #!#! Thread: Server thread
[06:18:23 ERROR]: #!#!
[06:18:23 ERROR]: #!#! End of Error.
[06:18:23 ERROR]: #!#!
```

Relevant script:

```
options:
	bedClickSpeed:	1 second
	homeCooldown:	15 minutes
	dmgCooldown:	15 seconds

function checkHomeCD(p: player) :: boolean:
	if {_p} does not have permission "skript.homes.nocooldown":
		if {shared.%{_p}%.lastdamaged} was less than {@dmgCooldown} ago:
			message "You cannot flee while taking damage!" to {_p}
			return false
		if {homes.%{_p}%.lasthometp} was less than {@homeCooldown} ago:
			set {_waited} to difference between {homes.%{_p}%.lasthometp} and now
			message "You must wait %difference between {@homeCooldown} and {_waited}% before using this command again." to {_p}
			return false
	return true

#command /sethome:
#	description: Set your home
#	permission: skript.homes.sethome
#	executable by: players
#	trigger:
#		set {homes.%player%.location} to location of player
#		message "Your home has been set to <grey>%location of player%<reset>"

command /home:
	description: Teleport yourself to your home
	permission: skript.homes.home
	executable by: players
	trigger:
		if {homes.%player%.location} is not set:
			message "You have not set your home yet!"
			stop trigger
		if checkHomeCD(player) is false:
			stop
		message "Going home..."
		teleport player to {homes.%player%.location}
		set {homes.%player%.lasthometp} to now

on rightclick on bed_block:
	if player does not have permission "skript.homes.bedhome":
		stop
	#if player can use bedhome, disable standard bed behavior to keep usage consistent
	cancel event
	if {homes.%player%.firstclick} was more than {@bedClickSpeed}:
		set {homes.%player%.firstclick} to now
		stop
	if player cannot build at the clicked block:
		message "You cannot use this bed for your home."
		stop
	set {homes.%player%.location} to location of player
	message "Your home has been set to this spot."

on respawn:
	if player does not have permission "skript.homes.respawnhome":
		stop
	if {homes.%player%.location} does not exist:
		message "You have not set a home! Using default respawn."
		stop
	teleport player to {homes.%player%.location}

#intercept multiverse spawn command and apply cooldown
on command "/mv":
	if arguments is "spawn":
		if checkHomeCD(player) is false:
			cancel event
			stop
		set {homes.%player%.lasthometp} to now
```

**Comment by SlimeDog** [comment]
> ...Also worked flawlessly under dev23 (which I have reverted to in order to resolve the error for now.)

I didn't think to mention it. As you might expect, my skripts also work flawlessly under dev23, and likewise I reverted until the fix is in.

**Comment by RezzedUp** [comment]
Same error. Both worked perfectly fine in dev23 as well.

* **Spigot Version:** CraftBukkit version git-Spigot-b4417b8-3c48711 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)
* **Skript Version:** 2.2-dev24

# Error 1

```yaml
#!#!
#!#! [Skript] Severe Error:
#!#! Could not load json.sk
#!#!
#!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
#!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
#!#! and check whether this error has already been reported.
#!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
#!#! and describe what you did before it happened and/or what you think caused the error.
#!#! If you think that it's a trigger that's causing the error please post the trigger as well.
#!#! By following this guide fixing the error should be easy and done fast.
#!#!
#!#! Stack trace:
#!#! java.lang.UnsupportedOperationException: Parsing not implemented (remember to override parse method)                                                                                                         [48/1989]
#!#!     at ch.njol.skript.classes.Parser.parse(Parser.java:72)
#!#!     at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:422)
#!#!     at ch.njol.skript.registrations.Classes.parse(Classes.java:451)
#!#!     at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:97)
#!#!     at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:86)
#!#!     at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:1)
#!#!     at ch.njol.skript.conditions.CondCompare.init(CondCompare.java:181)
#!#!     at ch.njol.skript.conditions.CondCompare.init(CondCompare.java:132)
#!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:249)
#!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
#!#!     at ch.njol.skript.lang.Condition.parse(Condition.java:83)
#!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:833)
#!#!     at ch.njol.skript.lang.Loop.<init>(Loop.java:68)
#!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:790)
#!#!     at ch.njol.skript.lang.function.ScriptFunction.<init>(ScriptFunction.java:53)
#!#!     at ch.njol.skript.lang.function.Functions.loadFunction(Functions.java:129)
#!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:485)
#!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:247)
#!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:201)
#!#!     at ch.njol.skript.Skript$2.run(Skript.java:406)
#!#!     at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
#!#!     at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
#!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738)
#!#!     at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
#!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
#!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
#!#!     at java.lang.Thread.run(Thread.java:745)
#!#!
#!#! Version Information:
#!#!   Skript: 2.2-dev24
#!#!   Bukkit: 1.11.2-R0.1-SNAPSHOT
#!#!   Minecraft: 1.11.2
#!#!   Java: 1.8.0_121 (OpenJDK 64-Bit Server VM 25.121-b13)
#!#!   OS: Linux amd64 3.14.32-xxxx-grs-ipv6-64
#!#!
#!#! Running CraftBukkit: false
#!#!
#!#! Current node: if {_skip} is more than or equal to 1: (json.sk, line 138)
#!#! Current item: null
#!#!
#!#! Thread: Server thread
#!#!
#!#! End of Error.
#!#!
```

Relevant script portion:

```vbs
options:
    debug: false
    codes: 0|1|2|3|4|5|6|7|8|9|a|b|c|d|e|f|k|l|m|n|o|r

function jsonColorize(msg: text, default-color: text = "&r") :: text:
    set {_m::*} to {_msg} split at ""
    
    set {_color-codes} to "{@codes}"
    set {_colors::*} to {_color-codes} split at "|"
    
    set {_color} to colored {_default-color}
    set {_code} to the first character of {_color}
    
    set {_new} to ""
    set {_skip} to 0
    
    loop amount of {_m::*} times:
    
        if {_skip} is more than or equal to 1:
            subtract 1 from {_skip}
            
        else:
            set {_char} to {_m::%loop-number%}
            set {_next} to {_m::%loop-number + 1%}
            
            if {@debug} is true:
                broadcast "&a[Character Check] &r%loop-number%: &7%{_char}% &r&onext: &8%{_next}% &r[%{_color}%color&r]"
            
            if {_char} is "&" or {_code}:
            
                if {@debug} is true:
                    broadcast "&a[Color Check] &rFOUND: &o%{_char}%%{_next}% &7&m<--&7&o is it valid?"
            
                loop {_colors::*}:
                
                    if loop-value-2 is {_next}:
                        set {_color} to "%{_color}%%{_code}%%{_next}%"
                        
                        if {_next} is "r":
                            set {_color} to {_default-color}
                            
                        set {_new} to "%{_new}%%{_color}%"
                        set {_skip} to 1
                        
                if {_skip} is less than or equal to 0:
                    set {_new} to "%{_new}%%{_char}%"
                
            else if {_char} is " ":
                set {_new} to "%{_new}% %{_color}%"
            
            else:
                set {_new} to "%{_new}%%{_char}%"
                
    return {_new}
```

# Error 2

```yaml
#!#!                                                                                                                                                                                                               [3/1989]
#!#! [Skript] Severe Error:
#!#! Could not load number.sk
#!#!
#!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
#!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
#!#! and check whether this error has already been reported.
#!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
#!#! and describe what you did before it happened and/or what you think caused the error.
#!#! If you think that it's a trigger that's causing the error please post the trigger as well.
#!#! By following this guide fixing the error should be easy and done fast.
#!#!
#!#! Stack trace:
#!#! java.lang.UnsupportedOperationException: Parsing not implemented (remember to override parse method)
#!#!     at ch.njol.skript.classes.Parser.parse(Parser.java:72)
#!#!     at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:422)
#!#!     at ch.njol.skript.registrations.Classes.parse(Classes.java:451)
#!#!     at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:97)
#!#!     at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:86)
#!#!     at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:1)
#!#!     at ch.njol.skript.conditions.CondContains.init(CondContains.java:72)
#!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:249)
#!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
#!#!     at ch.njol.skript.lang.Condition.parse(Condition.java:83)
#!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:833)
#!#!     at ch.njol.skript.lang.Loop.<init>(Loop.java:68)
#!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:790)
#!#!     at ch.njol.skript.lang.function.ScriptFunction.<init>(ScriptFunction.java:53)
#!#!     at ch.njol.skript.lang.function.Functions.loadFunction(Functions.java:129)
#!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:485)
#!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:247)
#!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:201)
#!#!     at ch.njol.skript.Skript$2.run(Skript.java:406)
#!#!     at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
#!#!     at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
#!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738)
#!#!     at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
#!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
#!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
#!#!     at java.lang.Thread.run(Thread.java:745)
#!#!
#!#! Version Information:
#!#!   Skript: 2.2-dev24
#!#!   Bukkit: 1.11.2-R0.1-SNAPSHOT
#!#!   Minecraft: 1.11.2
#!#!   Java: 1.8.0_121 (OpenJDK 64-Bit Server VM 25.121-b13)
#!#!   OS: Linux amd64 3.14.32-xxxx-grs-ipv6-64
#!#!
#!#! Running CraftBukkit: false
#!#!
#!#! Current node: if "0123456789" doesn't contain "%loop-value%": (number.sk, line 163)
#!#! Current item: null
#!#!
#!#! Thread: Server thread
#!#!
#!#! End of Error.
#!#!
```
Relevant script portion:
```vbs
function validateDigitsOf(text: text) :: boolean:
    set {_chars::*} to {_text} split at ""
    
    loop {_chars::*}:
        if "0123456789" doesn't contain "%loop-value%":
            return false
            
    return true
```

**Comment by bensku** [comment]
I think this is fixed.
