### ISSUE TITLE
move citizen 0 to location of player

### ISSUE THREAD

**Issue by UnknwonPerson** [bensku/Skript#380]
21:18:38 ERROR]: #!#! [21:18:38 ERROR]: #!#! [Skript] Severe Error:[21:18:38 ERROR]: #!#! [21:18:38 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.[21:18:38 ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[21:18:38 ERROR]: #!#! and check whether this error has already been reported.[21:18:38 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),[21:18:38 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[21:18:38 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.[21:18:38 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.[21:18:38 ERROR]: #!#! [21:18:38 ERROR]: #!#! Stack trace:[21:18:38 ERROR]: #!#! java.lang.NullPointerException[21:18:38 ERROR]: #!#!     at net.rayfall.eyesniper2.skRayFall.CitizenEffects.EffCitizenMove.execute(EffCitizenMove.java:41)
[21:18:38 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:54)[21:18:38 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:65)[21:18:38 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93)[21:18:38 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
[21:18:38 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:222)[21:18:38 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:184)[21:18:38 ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:270)[21:18:38 ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:165)[21:18:38 ERROR]: #!#!     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[21:18:38 ERROR]: #!#!     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:18:38 ERROR]: #!#!     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[21:18:38 ERROR]: #!#!     at java.lang.reflect.Method.invoke(Method.java:498)[21:18:38 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)[21:18:38 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)[21:18:38 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[21:18:38 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)[21:18:38 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1107)[21:18:38 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950)[21:18:38 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26)[21:18:38 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53)[21:18:38 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13)
[21:18:38 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[21:18:38 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(FutureTask.java:266)[21:18:38 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696)[21:18:38 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)[21:18:38 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634)
[21:18:38 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537)[21:18:38 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)[21:18:38 ERROR]: #!#! [21:18:38 ERROR]: #!#! Version Information:
[21:18:38 ERROR]: #!#!   Skript: 2.2-dev23[21:18:38 ERROR]: #!#!   Bukkit: 1.8-R0.1-SNAPSHOT[21:18:38 ERROR]: #!#!   Minecraft: 1.8
[21:18:38 ERROR]: #!#!   Java: 1.8.0_91 (Java HotSpot(TM) 64-Bit Server VM 25.91-b14)[21:18:38 ERROR]: #!#!   OS: Linux amd64 4.2.0-27-generic[21:18:38 ERROR]: #!#! [21:18:38 ERROR]: #!#! Running CraftBukkit: false[21:18:38 ERROR]: #!#! 
[21:18:38 ERROR]: #!#! Current node: null[21:18:38 ERROR]: #!#! Current item: Citizens move, Id Number: 0 To loaction: the location of the player
[21:18:38 ERROR]: #!#! [21:18:38 ERROR]: #!#! Thread: Server thread[21:18:38 ERROR]: #!#! [21:18:38 ERROR]: #!#! End of Error.[21:18:38 ERROR]: #!#! 
[21:18:39 INFO]: GhoXDragonSHTC issued server command: /here[21:18:39 INFO]: [CommandLogger] Player: GhoXDragonSHTC Command: /here[21:18:39 INFO]: GhoXDragonSHTC [e7012405-933c-3623-94a5-66758ba5041d]: /here[21:18:39 ERROR]: #!#! 
[21:18:39 ERROR]: #!#! [Skript] Severe Error:[21:18:39 ERROR]: #!#! [21:18:39 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.[21:18:39 ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/[21:18:39 ERROR]: #!#! and check whether this error has already been reported.[21:18:39 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),[21:18:39 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.[21:18:39 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[21:18:39 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.[21:18:39 ERROR]: #!#! [21:18:39 ERROR]: #!#! Stack trace:
[21:18:39 ERROR]: #!#! java.lang.NullPointerException[21:18:39 ERROR]: #!#!     at net.rayfall.eyesniper2.skRayFall.CitizenEffects.EffCitizenMove.execute(EffCitizenMove.java:41)[21:18:39 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:54)[21:18:39 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:65)[21:18:39 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93)[21:18:39 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
[21:18:39 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:222)[21:18:39 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:184)[21:18:39 ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:270)[21:18:39 ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:165)
[21:18:39 ERROR]: #!#!     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[21:18:39 ERROR]: #!#!     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)[21:18:39 ERROR]: #!#!     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[21:18:39 ERROR]: #!#!     at java.lang.reflect.Method.invoke(Method.java:498)[21:18:39 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)[21:18:39 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)[21:18:39 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)[21:18:39 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[21:18:39 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1107)[21:18:39 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950)[21:18:39 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26)[21:18:39 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53)[21:18:39 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13)[21:18:39 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[21:18:39 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(FutureTask.java:266)[21:18:39 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696)[21:18:39 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[21:18:39 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634)[21:18:39 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537)[21:18:39 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)[21:18:39 ERROR]: #!#! [21:18:39 ERROR]: #!#! Version Information:[21:18:39 ERROR]: #!#!   Skript: 2.2-dev23[21:18:39 ERROR]: #!#!   Bukkit: 1.8-R0.1-SNAPSHOT[21:18:39 ERROR]: #!#!   Minecraft: 1.8
[21:18:39 ERROR]: #!#!   Java: 1.8.0_91 (Java HotSpot(TM) 64-Bit Server VM 25.91-b14)[21:18:39 ERROR]: #!#!   OS: Linux amd64 4.2.0-27-generic[21:18:39 ERROR]: #!#! 
[21:18:39 ERROR]: #!#! Running CraftBukkit: false[21:18:39 ERROR]: #!#! [21:18:39 ERROR]: #!#! Current node: null[21:18:39 ERROR]: #!#! Current item: Citizens move, Id Number: 0 To loaction: the location of the player[21:18:39 ERROR]: #!#! [21:18:39 ERROR]: #!#! Thread: Server thread[21:18:39 ERROR]: #!#! [21:18:39 ERROR]: #!#! End of Error.
[21:18:39 ERROR]: #!#! 
[21:18:45 WARN]: java.net.UnknownHostException: umbaska.funnygatt.space
[21:18:45 WARN]: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)[21:18:45 WARN]: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)[21:18:45 WARN]: 	at java.net.Socket.connect(Socket.java:589)[21:18:45 WARN]: 	at java.net.Socket.connect(Socket.java:538)[21:18:45 WARN]: 	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)[21:18:45 WARN]: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)[21:18:45 WARN]: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)[21:18:45 WARN]: 	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)[21:18:45 WARN]: 	at sun.net.www.http.HttpClient.New(HttpClient.java:308)[21:18:45 WARN]: 	at sun.net.www.http.HttpClient.New(HttpClient.java:326)[21:18:45 WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)[21:18:45 WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)[21:18:45 WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
[21:18:45 WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)[21:18:45 WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)[21:18:45 WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)[21:18:45 WARN]: 	at java.net.URL.openStream(URL.java:1045)[21:18:45 WARN]: 	at uk.co.umbaska.UpdateChecker.runNow(UpdateChecker.java:48)[21:18:45 WARN]: 	at uk.co.umbaska.UpdateChecker$1.run(UpdateChecker.java:74)[21:18:45 WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)[21:18:45 WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)[21:18:45 WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[21:18:45 WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[21:18:45 WARN]: 	at java.lang.Thread.run(Thread.java:745)
[21:18:51 INFO]: GhoXDragonSHTC issued server command: /here
[21:18:51 INFO]: [CommandLogger] Player: GhoXDragonSHTC Command: /here[21:18:51 INFO]: GhoXDragonSHTC [e7012405-933c-3623-94a5-66758ba5041d]: /here
[21:18:51 ERROR]: #!#! [21:18:51 ERROR]: #!#! [Skript] Severe Error:[21:18:51 ERROR]: #!#! [21:18:51 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.[21:18:51 ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/[21:18:51 ERROR]: #!#! and check whether this error has already been reported.[21:18:51 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),[21:18:51 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[21:18:51 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.[21:18:51 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.[21:18:51 ERROR]: #!#! [21:18:51 ERROR]: #!#! Stack trace:[21:18:51 ERROR]: #!#! java.lang.NullPointerException
[21:18:51 ERROR]: #!#!     at net.rayfall.eyesniper2.skRayFall.CitizenEffects.EffCitizenMove.execute(EffCitizenMove.java:41)[21:18:51 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:54)[21:18:51 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:65)[21:18:51 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93)[21:18:51 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
[21:18:51 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:222)[21:18:51 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:184)[21:18:51 ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:270)[21:18:51 ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:165)[21:18:51 ERROR]: #!#!     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[21:18:51 ERROR]: #!#!     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:18:51 ERROR]: #!#!     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[21:18:51 ERROR]: #!#!     at java.lang.reflect.Method.invoke(Method.java:498)[21:18:51 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)[21:18:51 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)[21:18:51 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[21:18:51 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)[21:18:51 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1107)[21:18:51 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950)[21:18:51 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26)[21:18:51 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53)[21:18:51 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13)[21:18:51 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[21:18:51 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[21:18:51 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696)[21:18:51 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)[21:18:51 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634)[21:18:51 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537)[21:18:51 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)[21:18:51 ERROR]: #!#! [21:18:51 ERROR]: #!#! Version Information:
[21:18:51 ERROR]: #!#!   Skript: 2.2-dev23[21:18:51 ERROR]: #!#!   Bukkit: 1.8-R0.1-SNAPSHOT[21:18:51 ERROR]: #!#!   Minecraft: 1.8[21:18:51 ERROR]: #!#!   Java: 1.8.0_91 (Java HotSpot(TM) 64-Bit Server VM 25.91-b14)[21:18:51 ERROR]: #!#!   OS: Linux amd64 4.2.0-27-generic[21:18:51 ERROR]: #!#! [21:18:51 ERROR]: #!#! Running CraftBukkit: false[21:18:51 ERROR]: #!#! 
[21:18:51 ERROR]: #!#! Current node: null[21:18:51 ERROR]: #!#! Current item: Citizens move, Id Number: 0 To loaction: the location of the player[21:18:51 ERROR]: #!#! [21:18:51 ERROR]: #!#! Thread: Server thread[21:18:51 ERROR]: #!#! [21:18:51 ERROR]: #!#! End of Error.
[21:18:51 ERROR]: #!#! 
[21:23:00 INFO]: [ClearLag] Warning Ground items will be removed in 60 seconds!
[21:23:04 INFO]: AutoSaving
[21:23:05 INFO]: AutoSave Complete
[21:23:40 INFO]: [ClearLag] Warning Ground items will be removed in 20 seconds!
[21:23:53 INFO]: GhoXDragonSHTC issued server command: /here
[21:23:53 INFO]: [CommandLogger] Player: GhoXDragonSHTC Command: /here
[21:23:53 INFO]: GhoXDragonSHTC [e7012405-933c-3623-94a5-66758ba5041d]: /here
[21:23:53 ERROR]: #!#! [21:23:53 ERROR]: #!#! [Skript] Severe Error:[21:23:53 ERROR]: #!#! [21:23:53 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[21:23:53 ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/[21:23:53 ERROR]: #!#! and check whether this error has already been reported.[21:23:53 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[21:23:53 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.[21:23:53 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.[21:23:53 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.[21:23:53 ERROR]: #!#! [21:23:53 ERROR]: #!#! Stack trace:
[21:23:53 ERROR]: #!#! java.lang.NullPointerException[21:23:53 ERROR]: #!#!     at net.rayfall.eyesniper2.skRayFall.CitizenEffects.EffCitizenMove.execute(EffCitizenMove.java:41)[21:23:53 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:54)[21:23:53 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:65)[21:23:53 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93)[21:23:53 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)[21:23:53 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:222)
[21:23:53 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:184)[21:23:53 ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:270)[21:23:53 ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:165)[21:23:53 ERROR]: #!#!     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[21:23:53 ERROR]: #!#!     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:23:53 ERROR]: #!#!     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[21:23:53 ERROR]: #!#!     at java.lang.reflect.Method.invoke(Method.java:498)[21:23:53 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
[21:23:53 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)[21:23:53 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)[21:23:53 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[21:23:53 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1107)[21:23:53 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950)[21:23:53 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26)[21:23:53 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53)[21:23:53 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13)
[21:23:53 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[21:23:53 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(FutureTask.java:266)[21:23:53 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696)[21:23:53 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)[21:23:53 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634)[21:23:53 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537)[21:23:53 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)
[21:23:53 ERROR]: #!#! [21:23:53 ERROR]: #!#! Version Information:[21:23:53 ERROR]: #!#!   Skript: 2.2-dev23[21:23:53 ERROR]: #!#!   Bukkit: 1.8-R0.1-SNAPSHOT
[21:23:53 ERROR]: #!#!   Minecraft: 1.8[21:23:53 ERROR]: #!#!   Java: 1.8.0_91 (Java HotSpot(TM) 64-Bit Server VM 25.91-b14)[21:23:53 ERROR]: #!#!   OS: Linux amd64 4.2.0-27-generic
[21:23:53 ERROR]: #!#! [21:23:53 ERROR]: #!#! Running CraftBukkit: false[21:23:53 ERROR]: #!#! [21:23:53 ERROR]: #!#! Current node: null
[21:23:53 ERROR]: #!#! Current item: Citizens move, Id Number: 0 To loaction: the location of the player[21:23:53 ERROR]: #!#! [21:23:53 ERROR]: #!#! Thread: Server thread
[21:23:53 ERROR]: #!#! [21:23:53 ERROR]: #!#! End of Error.[21:23:53 ERROR]: #!#!

**Comment by Pyon-Pyon** [comment]
This isn't related to Skript, it's related to skRayFall, I don't know why you're putting this here.

**Comment by UnknwonPerson** [comment]
Ohh okk thx
