### ISSUE TITLE
If world is "world" and play mob flames

### ISSUE THREAD

**Issue by UnknwonPerson** [bensku/Skript#382]
[17:02:27 ERROR]: #!#! [17:02:27 ERROR]: #!#! [Skript] Severe Error:[17:02:27 ERROR]: #!#! Could not load blackenchant.sk
[17:02:27 ERROR]: #!#! [17:02:27 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.[17:02:27 ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/[17:02:27 ERROR]: #!#! and check whether this error has already been reported.[17:02:27 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),[17:02:27 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.[17:02:27 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.[17:02:27 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.[17:02:27 ERROR]: #!#! [17:02:27 ERROR]: #!#! Stack trace:[17:02:27 ERROR]: #!#! java.lang.UnsupportedOperationException: Parsing not implemented (remember to override parse method)[17:02:27 ERROR]: #!#!     at ch.njol.skript.classes.Parser.parse(Parser.java:72)
[17:02:27 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:422)[17:02:27 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.parse(Classes.java:451)[17:02:27 ERROR]: #!#!     at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:97)[17:02:27 ERROR]: #!#!     at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:86)
[17:02:27 ERROR]: #!#!     at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:1)[17:02:27 ERROR]: #!#!     at ch.njol.skript.conditions.CondCompare.init(CondCompare.java:173)
[17:02:27 ERROR]: #!#!     at ch.njol.skript.conditions.CondCompare.init(CondCompare.java:132)[17:02:27 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:249)[17:02:27 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)[17:02:27 ERROR]: #!#!     at ch.njol.skript.lang.Condition.parse(Condition.java:83)[17:02:27 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:833)[17:02:27 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:513)[17:02:27 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:271)[17:02:27 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:167)
[17:02:27 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)[17:02:27 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)[17:02:27 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)[17:02:27 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)[17:02:27 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[17:02:27 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)[17:02:27 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)[17:02:27 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[17:02:27 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[17:02:27 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(FutureTask.java:266)[17:02:27 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[17:02:27 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)[17:02:27 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)[17:02:27 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)[17:02:27 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)[17:02:27 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)[17:02:27 ERROR]: #!#! 
[17:02:27 ERROR]: #!#! Version Information:[17:02:27 ERROR]: #!#!   Skript: 2.2-dev24[17:02:27 ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[17:02:27 ERROR]: #!#!   Minecraft: 1.8.8[17:02:27 ERROR]: #!#!   Java: 1.8.0_91 (Java HotSpot(TM) 64-Bit Server VM 25.91-b14)
[17:02:27 ERROR]: #!#!   OS: Linux amd64 4.2.0-27-generic[17:02:27 ERROR]: #!#! [17:02:27 ERROR]: #!#! Running CraftBukkit: false[17:02:27 ERROR]: #!#! [17:02:27 ERROR]: #!#! Current node: if citizen is named "BlackSmith": (blackenchant.sk, line 115)[17:02:27 ERROR]: #!#! Current item: null
[17:02:27 ERROR]: #!#! [17:02:27 ERROR]: #!#! Thread: Server thread[17:02:27 ERROR]: #!#! [17:02:27 ERROR]: #!#! End of Error.[17:02:27 ERROR]: #!#! 
[17:02:35 INFO]: GhoXDragonSHTC issued server command: /sk reload blackenchant
[17:02:35 INFO]: [CommandLogger] Player: GhoXDragonSHTC Command: /sk reload blackenchant
[17:02:36 ERROR]: #!#! [17:02:36 ERROR]: #!#! [Skript] Severe Error:[17:02:36 ERROR]: #!#! Could not load blackenchant.sk
[17:02:36 ERROR]: #!#! [17:02:36 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.[17:02:36 ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/[17:02:36 ERROR]: #!#! and check whether this error has already been reported.[17:02:36 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),[17:02:36 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.[17:02:36 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.[17:02:36 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.[17:02:36 ERROR]: #!#! [17:02:36 ERROR]: #!#! Stack trace:
[17:02:36 ERROR]: #!#! java.lang.UnsupportedOperationException: Parsing not implemented (remember to override parse method)[17:02:36 ERROR]: #!#!     at ch.njol.skript.classes.Parser.parse(Parser.java:72)[17:02:36 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:422)
[17:02:36 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.parse(Classes.java:451)[17:02:36 ERROR]: #!#!     at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:97)[17:02:36 ERROR]: #!#!     at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:86)
[17:02:36 ERROR]: #!#!     at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:1)[17:02:36 ERROR]: #!#!     at ch.njol.skript.conditions.CondCompare.init(CondCompare.java:173)[17:02:36 ERROR]: #!#!     at ch.njol.skript.conditions.CondCompare.init(CondCompare.java:132)[17:02:36 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:249)[17:02:36 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)[17:02:36 ERROR]: #!#!     at ch.njol.skript.lang.Condition.parse(Condition.java:83)[17:02:36 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:833)[17:02:36 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:513)
[17:02:36 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:271)[17:02:36 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:167)[17:02:36 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)[17:02:36 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[17:02:36 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)[17:02:36 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[17:02:36 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)[17:02:36 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)[17:02:36 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)[17:02:36 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)[17:02:36 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[17:02:36 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(FutureTask.java:266)[17:02:36 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)[17:02:36 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)[17:02:36 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[17:02:36 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)[17:02:36 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)[17:02:36 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)
[17:02:36 ERROR]: #!#! [17:02:36 ERROR]: #!#! Version Information:
[17:02:36 ERROR]: #!#!   Skript: 2.2-dev24[17:02:36 ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT[17:02:36 ERROR]: #!#!   Minecraft: 1.8.8[17:02:36 ERROR]: #!#!   Java: 1.8.0_91 (Java HotSpot(TM) 64-Bit Server VM 25.91-b14)[17:02:36 ERROR]: #!#!   OS: Linux amd64 4.2.0-27-generic[17:02:36 ERROR]: #!#! 
[17:02:36 ERROR]: #!#! Running CraftBukkit: false[17:02:36 ERROR]: #!#! [17:02:36 ERROR]: #!#! Current node: if citizen is named "BlackSmith": (blackenchant.sk, line 115)[17:02:36 ERROR]: #!#! Current item: null
[17:02:36 ERROR]: #!#! 
[17:02:36 ERROR]: #!#! Thread: Server thread[17:02:36 ERROR]: #!#! [17:02:36 ERROR]: #!#! End of Error.[17:02:36 ERROR]: #!#! 
[17:02:43 INFO]: GhoXDragonSHTC issued server command: /sk reload blackenchant
[17:02:43 INFO]: [CommandLogger] Player: GhoXDragonSHTC Command: /sk reload blackenchant
[17:02:44 ERROR]: #!#! 
[17:02:44 ERROR]: #!#! [Skript] Severe Error:
[17:02:44 ERROR]: #!#! Could not load blackenchant.sk[17:02:44 ERROR]: #!#! [17:02:44 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.[17:02:44 ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/[17:02:44 ERROR]: #!#! and check whether this error has already been reported.[17:02:44 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),[17:02:44 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.[17:02:44 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.[17:02:44 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.[17:02:44 ERROR]: #!#! [17:02:44 ERROR]: #!#! Stack trace:[17:02:44 ERROR]: #!#! java.lang.UnsupportedOperationException: Parsing not implemented (remember to override parse method)[17:02:44 ERROR]: #!#!     at ch.njol.skript.classes.Parser.parse(Parser.java:72)[17:02:44 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:422)[17:02:44 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.parse(Classes.java:451)[17:02:44 ERROR]: #!#!     at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:97)[17:02:44 ERROR]: #!#!     at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:86)[17:02:44 ERROR]: #!#!     at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:1)[17:02:44 ERROR]: #!#!     at ch.njol.skript.conditions.CondCompare.init(CondCompare.java:173)[17:02:44 ERROR]: #!#!     at ch.njol.skript.conditions.CondCompare.init(CondCompare.java:132)
[17:02:44 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:249)[17:02:44 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)[17:02:44 ERROR]: #!#!     at ch.njol.skript.lang.Condition.parse(Condition.java:83)[17:02:44 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:833)[17:02:44 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:513)
[17:02:44 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:271)
[17:02:44 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:167)[17:02:44 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)[17:02:44 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)[17:02:44 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[17:02:44 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)[17:02:44 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[17:02:44 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)[17:02:44 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[17:02:44 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[17:02:44 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[17:02:44 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(FutureTask.java:266)[17:02:44 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)[17:02:44 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[17:02:44 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)[17:02:44 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[17:02:44 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)[17:02:44 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)
[17:02:44 ERROR]: #!#! [17:02:44 ERROR]: #!#! Version Information:[17:02:44 ERROR]: #!#!   Skript: 2.2-dev24[17:02:44 ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[17:02:44 ERROR]: #!#!   Minecraft: 1.8.8[17:02:44 ERROR]: #!#!   Java: 1.8.0_91 (Java HotSpot(TM) 64-Bit Server VM 25.91-b14)[17:02:44 ERROR]: #!#!   OS: Linux amd64 4.2.0-27-generic[17:02:44 ERROR]: #!#! 
[17:02:44 ERROR]: #!#! Running CraftBukkit: false[17:02:44 ERROR]: #!#! 
[17:02:44 ERROR]: #!#! Current node: if citizen is named "BlackSmith": (blackenchant.sk, line 115)[17:02:44 ERROR]: #!#! Current item: null[17:02:44 ERROR]: #!#! 
[17:02:44 ERROR]: #!#! Thread: Server thread[17:02:44 ERROR]: #!#! [17:02:44 ERROR]: #!#! End of Error.[17:02:44 ERROR]: #!#!

**Comment by bensku** [comment]
Should be fixed since last build.
