### ISSUE TITLE
NoSuchMethodError at ch.njol.skript.entity.EntityData.getAll(EntityData.java:455)

### ISSUE THREAD

**Issue by Nicofisi** [bensku/Skript#39]
Hello, I'm having an issue. When I use *message "%all players%"* I get an error that you probably know well.
```
[19:09:31 WARN]: [Skript] Task #381 for Skript v2.2-Fixes-V10 generated an exception
java.lang.NoSuchMethodError: org.bukkit.Bukkit.getOnlinePlayers()[Lorg/bukkit/entity/Player;
	at ch.njol.skript.entity.EntityData.getAll(EntityData.java:455) ~[?:?]
	at ch.njol.skript.expressions.ExprEntities.get(ExprEntities.java:146) ~[?:?]
	at ch.njol.skript.expressions.ExprEntities.get(ExprEntities.java:1) ~[?:?]
	at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:103) ~[?:?]
	at ch.njol.skript.lang.VariableString.toString(VariableString.java:383) ~[?:?]
	at ch.njol.skript.lang.VariableString.getArray(VariableString.java:488) ~[?:?]
	at ch.njol.skript.lang.VariableString.getArray(VariableString.java:1) ~[?:?]
	at ch.njol.skript.effects.EffMessage.execute(EffMessage.java:69) ~[?:?]
	at ch.njol.skript.lang.Effect.run(Effect.java:54) ~[?:?]
	at ch.njol.skript.command.Commands.handleEffectCommand(Commands.java:289) ~[?:?]
	at ch.njol.skript.command.Commands$4$1.call(Commands.java:222) ~[?:?]
	at ch.njol.skript.command.Commands$4$1.call(Commands.java:219) ~[?:?]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftFuture.run(CraftFuture.java:89) ~[patched_1.9.jar:git-Paper-606]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched_1.9.jar:git-Paper-606]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:819) [patched_1.9.jar:git-Paper-606]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.jar:git-Paper-606]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:720) [patched_1.9.jar:git-Paper-606]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:619) [patched_1.9.jar:git-Paper-606]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

```
Using latest 2.2-Fixes-V10 (dev B if I understand your versioning system well :) from 4 days ago)
& PaperSpigot 1.9 generated a moment ago.

**Comment by bensku** [comment]
Hmm... Interesting, because Skript has checks against calling this method on new MC versions. I will try to reproduce this anyway.

**Comment by Nicofisi** [comment]
I have seen, on SkUnity's discord, that other people are also experiencing this with Spigot 1.9. They can't loop all players, etc.

**Comment by bensku** [comment]
<code>send "test" to all player</code> works perfectly. Soo... What is wrong?

**Comment by bensku** [comment]
I have never got this issue with Spigot 1.9. 1.8 I don't have time to support.
