### ISSUE TITLE
Skript 2.2v Error

### ISSUE THREAD

**Issue by BlueKillerHD** [bensku/Skript#391]
Can you Please fix this error i can't use the Plugin Guardian Anti Cheat here the Error : 

[21:05:40 ERROR]: #!#! [Skript] Severe Error:
[21:05:40 ERROR]: #!#! An error happened when trying to enably resolving offline players, so the feature has been turned off. Please report this at https://github.com/bensku/Skript/issues/237
[21:05:40 ERROR]: #!#!
[21:05:40 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[21:05:40 ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[21:05:40 ERROR]: #!#! and check whether this error has already been reported.
[21:05:40 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[21:05:40 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[21:05:40 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[21:05:40 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[21:05:40 ERROR]: #!#!
[21:05:40 ERROR]: #!#! Stack trace:
[21:05:40 ERROR]: #!#! java.lang.NullPointerException: null offline player resolve queue
[21:05:40 ERROR]: #!#!     at ch.njol.skript.bukkitutil.UnresolvedOfflinePlayer$1.run(UnresolvedOfflinePlayer.java:58)
[21:05:40 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[21:05:40 ERROR]: #!#!
[21:05:40 ERROR]: #!#! Version Information:
[21:05:40 ERROR]: #!#!   Skript: 2.2-dev24b
[21:05:40 ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[21:05:40 ERROR]: #!#!   Minecraft: 1.8.8
[21:05:40 ERROR]: #!#!   Java: 1.8.0_121 (Java HotSpot(TM) 64-Bit Server VM 25.121-b13)
[21:05:40 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[21:05:40 ERROR]: #!#!
[21:05:40 ERROR]: #!#! Running CraftBukkit: false
[21:05:40 ERROR]: #!#!
[21:05:40 ERROR]: #!#! Current node: null
[21:05:40 ERROR]: #!#! Current item: null
[21:05:40 ERROR]: #!#!
[21:05:40 ERROR]: #!#! Thread: Skript offline player resolver thread (fetches UUIDs from the minecraft servers)
[21:05:40 ERROR]: #!#!
[21:05:40 ERROR]: #!#! End of Error.
[21:05:40 ERROR]: #!#!

Please Fix it 

LG

BlueKillerHD

**Comment by TheBentoBox** [comment]
This fork doesn't officially support versions below 1.9. I'll tag as dev needed to see if Bensku wants to support this, but if not it's on you for not updating.

**Comment by bensku** [comment]
This issue. Again.

With 1.8. No, not going to spend hours and hours trying to debug this.
