### ISSUE TITLE
Skript Loading issue

### ISSUE THREAD

**Issue by mmagoo13** [bensku/Skript#393]
Im getting the following trying to load one of my skripts it worked in dev23 but it wont work in dev24
18.02 23:36:01 [Server] ERROR #!#! 
18.02 23:36:01 [Server] ERROR #!#! End of Error. 
18.02 23:36:01 [Server] ERROR #!#! 
18.02 23:36:01 [Server] ERROR #!#! Thread: Server thread 
18.02 23:36:01 [Server] ERROR #!#! 
18.02 23:36:01 [Server] ERROR #!#! Current item: null 
18.02 23:36:01 [Server] ERROR #!#! Current node: if player's balance is greater than or equal to 50000: (ItemBuy.sk, line 3) 
18.02 23:36:01 [Server] ERROR #!#! 18.02 23:36:01 [Server] ERROR #!#! Running CraftBukkit: false 
18.02 23:36:01 [Server] ERROR #!#! 18.02 23:36:01 [Server] ERROR #!#!   OS: Linux amd64 2.6.32-642.11.1.el6.x86_64 
18.02 23:36:01 [Server] ERROR #!#!   Java: 1.8.0_111 (Java HotSpot(TM) 64-Bit Server VM 25.111-b14) 
18.02 23:36:01 [Server] ERROR #!#!   Minecraft: 1.11.2 
18.02 23:36:01 [Server] ERROR #!#!   Bukkit: 1.11.2-R0.1-SNAPSHOT 
18.02 23:36:01 [Server] ERROR #!#!   Skript: 2.2-dev24 
18.02 23:36:01 [Server] ERROR #!#! Version Information: 
18.02 23:36:01 [Server] ERROR #!#! 
18.02 23:36:01 [Server] ERROR #!#!     at java.lang.Thread.run(Unknown Source) 
18.02 23:36:01 [Server] ERROR #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) 
18.02 23:36:01 [Server] ERROR #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) 
18.02 23:36:01 [Server] ERROR #!#!     at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) 
18.02 23:36:01 [Server] ERROR #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) 
18.02 23:36:01 [Server] ERROR #!#!     at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) 
18.02 23:36:01 [Server] ERROR #!#!     at java.util.concurrent.FutureTask.run(Unknown Source) 
18.02 23:36:01 [Server] ERROR #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) 
18.02 23:36:01 [Server] ERROR #!#!     at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) 
18.02 23:36:01 [Server] ERROR #!#!     at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) 
18.02 23:36:01 [Server] ERROR #!#!     at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) 
18.02 23:36:01 [Server] ERROR #!#!     at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1179) 
18.02 23:36:01 [Server] ERROR #!#!     at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1344) 
18.02 23:36:01 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) 
18.02 23:36:01 [Server] ERROR #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) 
18.02 23:36:01 [Server] ERROR #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) 
18.02 23:36:01 [Server] ERROR #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:167) 
18.02 23:36:01 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:271) 
18.02 23:36:01 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:472) 
18.02 23:36:01 [Server] ERROR #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:467) 
18.02 23:36:01 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:833) 
18.02 23:36:01 [Server] ERROR #!#!     at ch.njol.skript.lang.Condition.parse(Condition.java:83) 
18.02 23:36:01 [Server] ERROR #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176) 
18.02 23:36:01 [Server] ERROR #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:249) 
18.02 23:36:01 [Server] ERROR #!#!     at ch.njol.skript.conditions.CondCompare.init(CondCompare.java:132) 
18.02 23:36:01 [Server] ERROR #!#!     at ch.njol.skript.conditions.CondCompare.init(CondCompare.java:181) 
18.02 23:36:01 [Server] ERROR #!#!     at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:1) 
18.02 23:36:01 [Server] ERROR #!#!     at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:86) 
18.02 23:36:01 [Server] ERROR #!#!     at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:97) 
18.02 23:36:01 [Server] ERROR #!#!     at ch.njol.skript.registrations.Classes.parse(Classes.java:451) 
18.02 23:36:01 [Server] ERROR #!#!     at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:422) 
18.02 23:36:01 [Server] ERROR #!#!     at ch.njol.skript.classes.Parser.parse(Parser.java:72) 
18.02 23:36:01 [Server] ERROR #!#! java.lang.UnsupportedOperationException: Parsing not implemented (remember to override parse method) 
18.02 23:36:01 [Server] ERROR #!#! Stack trace: 18.02 23:36:01 [Server] ERROR #!#! 
18.02 23:36:01 [Server] ERROR #!#! By following this guide fixing the error should be easy and done fast. 
18.02 23:36:01 [Server] ERROR #!#! If you think that it's a trigger that's causing the error please post the trigger as well. 
18.02 23:36:01 [Server] ERROR #!#! and describe what you did before it happened and/or what you think caused the error. 
18.02 23:36:01 [Server] ERROR #!#! If not please create a new ticket with a meaningful title, copy &amp; paste this whole error into it (or use paste service), 
18.02 23:36:01 [Server] ERROR #!#! and check whether this error has already been reported. 
18.02 23:36:01 [Server] ERROR #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/ 
18.02 23:36:01 [Server] ERROR #!#! If you're developing an add-on for Skript this likely means that you have done something wrong. 
18.02 23:36:01 [Server] ERROR #!#! 18.02 23:36:01 [Server] ERROR #!#! Could not load ItemBuy.sk 
18.02 23:36:01 [Server] ERROR #!#! [Skript] Severe Error: 
18.02 23:36:01 [Server] ERROR #!#!

**Comment by mmagoo13** [comment]
Okay Im an idiot and didn't check to see if there was a new version dev24b fixed this
