### ISSUE TITLE
NullPointerException - ExprLoopValue

### ISSUE THREAD

**Issue by TTLInferno** [bensku/Skript#394]
Error:
```
[08:02:54 ERROR]: #!#!
[08:02:54 ERROR]: #!#! [Skript] Severe Error:
[08:02:54 ERROR]: #!#! Could not load !Datenbank.sk
[08:02:54 ERROR]: #!#!
[08:02:54 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[08:02:54 ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[08:02:54 ERROR]: #!#! and check whether this error has already been reported.
[08:02:54 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[08:02:54 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[08:02:54 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[08:02:54 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[08:02:54 ERROR]: #!#!
[08:02:54 ERROR]: #!#! Stack trace:
[08:02:54 ERROR]: #!#! java.lang.NullPointerException
[08:02:54 ERROR]: #!#!     at ch.njol.skript.expressions.ExprLoopValue.init(ExprLoopValue.java:103)
[08:02:54 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:249)
[08:02:54 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[08:02:54 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:321)
[08:02:54 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:418)
[08:02:54 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.newInstance(VariableString.java:197)
[08:02:54 ERROR]: #!#!     at ch.njol.skript.lang.Variable.newInstance(Variable.java:153)
[08:02:54 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseVariable(SkriptParser.java:277)
[08:02:54 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:293)
[08:02:54 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:418)
[08:02:54 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:408)
[08:02:54 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1132)
[08:02:54 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1123)
[08:02:54 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:221)
[08:02:54 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[08:02:54 ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:61)
[08:02:54 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:754)
[08:02:54 ERROR]: #!#!     at ch.njol.skript.lang.Loop.<init>(Loop.java:68)
[08:02:54 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:790)
[08:02:54 ERROR]: #!#!     at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:56)
[08:02:54 ERROR]: #!#!     at ch.njol.skript.lang.Conditional.<init>(Conditional.java:46)
[08:02:54 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:840)
[08:02:54 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:513)
[08:02:54 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:271)
[08:02:54 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:167)
[08:02:54 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[08:02:54 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[08:02:54 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:647)
[08:02:54 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchServerCommand(CraftServer.java:633)
[08:02:54 ERROR]: #!#!     at net.minecraft.server.v1_10_R1.DedicatedServer.aL(DedicatedServer.java:438)
[08:02:54 ERROR]: #!#!     at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:401)
[08:02:54 ERROR]: #!#!     at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668)
[08:02:54 ERROR]: #!#!     at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567)
[08:02:54 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[08:02:54 ERROR]: #!#!
[08:02:54 ERROR]: #!#! Version Information:
[08:02:54 ERROR]: #!#!   Skript: 2.2-dev24b
[08:02:54 ERROR]: #!#!   Bukkit: 1.10.2-R0.1-SNAPSHOT
[08:02:54 ERROR]: #!#!   Minecraft: 1.10.2
[08:02:54 ERROR]: #!#!   Java: 1.8.0_121 (Java HotSpot(TM) Client VM 25.121-b13)
[08:02:54 ERROR]: #!#!   OS: Windows 10 x86 10.0
[08:02:54 ERROR]: #!#!
[08:02:54 ERROR]: #!#! Running CraftBukkit: false
[08:02:54 ERROR]: #!#!
[08:02:54 ERROR]: #!#! Current node: set {_loopValue} to {allModules::%loop-index%} (!Datenbank.sk, line 206)
[08:02:54 ERROR]: #!#! Current item: null
[08:02:54 ERROR]: #!#!
[08:02:54 ERROR]: #!#! Thread: Server thread
[08:02:54 ERROR]: #!#!
[08:02:54 ERROR]: #!#! End of Error.
[08:02:54 WARN]: #!#!
[08:02:54 WARN]: #!#! [Umbaska] List of plugins:
[08:02:54 WARN]: #!#! WildSkript - 1.9, Skript - 2.2-dev24b, Bungeekaska - 1.0 Beta 0.0.1, Skellett - 1.8.0a, skUtilities - 0.8.9, skRayFall - 1.9.7, Umbaska - 2.0 Beta 5.5.1, SkQuery - 3.5.5-Lime
[08:02:54 WARN]: #!#!
[08:02:54 WARN]: #!#! [Umbaska] List of addons:
[08:02:54 WARN]: #!#! Skellett v1.8.0askUtilities v0.8.9skRayFall v1.9.7Umbaska v2.0 Beta 5.5.1SkQuery v3.5.5-LimeWildSkript v1.9Bungeekaska v1.0 Beta 0.0.1
[08:02:54 WARN]: #!#!
[08:02:54 ERROR]: #!#!
```

**Comment by TheBentoBox** [comment]
Does this happen every time you start up your server, or does restarting fix it? I had this happen once when I accidentally tried to reference a function before it was loaded, but fixing the load order then restarting my server resolved it.

**Comment by TheBentoBox** [comment]
No response, closing.
