### ISSUE TITLE
Skript not running

### ISSUE THREAD

**Issue by crston** [bensku/Skript#400]
[22:04:53 ERROR]: #!#!
[22:04:53 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[22:04:53 ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[22:04:53 ERROR]: #!#! and check whether this error has already been reported.
[22:04:53 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[22:04:53 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[22:04:53 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[22:04:53 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[22:04:53 ERROR]: #!#!
[22:04:53 ERROR]: #!#! Stack trace:
[22:04:53 ERROR]: #!#! java.lang.NullPointerException
[22:04:53 ERROR]: #!#!     at net.rayfall.eyesniper2.skrayfall.citizenexpressions.ExprNameOfCitizen.get(ExprNameOfCitizen.java:45)
[22:04:53 ERROR]: #!#!     at net.rayfall.eyesniper2.skrayfall.citizenexpressions.ExprNameOfCitizen.get(ExprNameOfCitizen.java:1)
[22:04:53 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:105)
[22:04:53 ERROR]: #!#!     at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:76)
[22:04:53 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:105)
[22:04:53 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.toString(VariableString.java:383)
[22:04:53 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.getSingle(VariableString.java:483)
[22:04:53 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.getSingle(VariableString.java:1)
[22:04:53 ERROR]: #!#!     at net.dzikoysk.wildskript.conditions.CondFileExists.check(CondFileExists.java:18)
[22:04:53 ERROR]: #!#!     at ch.njol.skript.lang.Condition.run(Condition.java:58)
[22:04:53 ERROR]: #!#!     at ch.njol.skript.lang.Conditional.walk(Conditional.java:53)
[22:04:53 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93)
[22:04:53 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
[22:04:53 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:152)
[22:04:53 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:112)
[22:04:53 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[22:04:53 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[22:04:53 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[22:04:53 ERROR]: #!#!     at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:414)
[22:04:53 ERROR]: #!#!     at sun.reflect.GeneratedMethodAccessor997.invoke(Unknown Source)
[22:04:53 ERROR]: #!#!     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[22:04:53 ERROR]: #!#!     at java.lang.reflect.Method.invoke(Unknown Source)
[22:04:53 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[22:04:53 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[22:04:53 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[22:04:53 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[22:04:53 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1527)
[22:04:53 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(SourceFile:69)
[22:04:53 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(SourceFile:13)
[22:04:53 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[22:04:53 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[22:04:53 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
[22:04:53 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
[22:04:53 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747)
[22:04:53 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[22:04:53 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
[22:04:53 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
[22:04:53 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[22:04:53 ERROR]: #!#!
[22:04:53 ERROR]: #!#! Version Information:
[22:04:53 ERROR]: #!#!   Skript: 2.2-dev23
[22:04:53 ERROR]: #!#!   Bukkit: 1.11.2-R0.1-SNAPSHOT
[22:04:53 ERROR]: #!#!   Minecraft: 1.11.2
[22:04:53 ERROR]: #!#!   Java: 1.8.0_111 (Java HotSpot(TM) 64-Bit Server VM 25.111-b14)
[22:04:53 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[22:04:53 ERROR]: #!#!
[22:04:53 ERROR]: #!#! Running CraftBukkit: false
[22:04:53 ERROR]: #!#!
[22:04:53 ERROR]: #!#! Current node: null
[22:04:53 ERROR]: #!#! Current item: net.dzikoysk.wildskript.conditions.CondFileExists
[22:04:53 ERROR]: #!#!
[22:04:53 ERROR]: #!#! Thread: Server thread
[22:04:53 ERROR]: #!#!
[22:04:53 ERROR]: #!#! End of Error.
[22:04:53 ERROR]: #!#!

**Comment by TheBentoBox** [comment]
This says it's a null pointer exception with SkRayFall trying to get the name of a citizen, and also lists the "Current item" as a WildSkript condition. Given you're on 1.11.2, I would recommend that you make sure you're using a version of WildSkript that someone has updated relatively recently, as the original author hasn't updated it in years. 

Either way, this is an addon issue, not a Skript issue, so it doesn't belong here.
