### ISSUE TITLE
Error: Loop all players in radius x around player's location

### ISSUE THREAD

**Issue by SpaceTurtle420** [bensku/Skript#413]
Hi, I always get an error when I try to loop players around another player.
This is what the console says:
[14:03:52 ERROR]: Could not pass event PlayerInteractEvent to Skript v2.2-dev24b
java.lang.NoSuchMethodError: org.bukkit.World.getNearbyEntities(Lorg/bukkit/Location;DDD)Ljava/util/Collection;
        at ch.njol.skript.expressions.ExprEntities.iterator(ExprEntities.java:196) ~[?:?]
        at ch.njol.skript.lang.Loop.walk(Loop.java:81) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93) ~[?:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:53) ~[?:?]
        at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:152) ~[?:?]
        at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:112) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-4b89e7b-7d0f836]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-4b89e7b-7d0f836]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-4b89e7b-7d0f836]
        at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:226) [spigot.jar:git-Spigot-4b89e7b-7d0f836]
        at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:193) [spigot.jar:git-Spigot-4b89e7b-7d0f836]
        at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:189) [spigot.jar:git-Spigot-4b89e7b-7d0f836]
        at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:692) [spigot.jar:git-Spigot-4b89e7b-7d0f836]
        at net.minecraft.server.v1_8_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [spigot.jar:git-Spigot-4b89e7b-7d0f836]
        at net.minecraft.server.v1_8_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot.jar:git-Spigot-4b89e7b-7d0f836]
        at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-4b89e7b-7d0f836]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
        at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot.jar:git-Spigot-4b89e7b-7d0f836]
        at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [spigot.jar:git-Spigot-4b89e7b-7d0f836]
        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot.jar:git-Spigot-4b89e7b-7d0f836]
        at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot.jar:git-Spigot-4b89e7b-7d0f836]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-4b89e7b-7d0f836]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
>
[14:03:54 ERROR]: Could not pass event PlayerInteractEvent to Skript v2.2-dev24b
java.lang.NoSuchMethodError: org.bukkit.World.getNearbyEntities(Lorg/bukkit/Location;DDD)Ljava/util/Collection;
        at ch.njol.skript.expressions.ExprEntities.iterator(ExprEntities.java:196) ~[?:?]
        at ch.njol.skript.lang.Loop.walk(Loop.java:81) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93) ~[?:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:53) ~[?:?]
        at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:152) ~[?:?]
        at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:112) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-4b89e7b-7d0f836]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-4b89e7b-7d0f836]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-4b89e7b-7d0f836]
        at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:226) [spigot.jar:git-Spigot-4b89e7b-7d0f836]
        at net.minecraft.server.v1_8_R2.PlayerInteractManager.interact(PlayerInteractManager.java:463) [spigot.jar:git-Spigot-4b89e7b-7d0f836]
        at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:734) [spigot.jar:git-Spigot-4b89e7b-7d0f836]
        at net.minecraft.server.v1_8_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [spigot.jar:git-Spigot-4b89e7b-7d0f836]
        at net.minecraft.server.v1_8_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot.jar:git-Spigot-4b89e7b-7d0f836]
        at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-4b89e7b-7d0f836]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
        at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot.jar:git-Spigot-4b89e7b-7d0f836]
        at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [spigot.jar:git-Spigot-4b89e7b-7d0f836]
        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot.jar:git-Spigot-4b89e7b-7d0f836]
        at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot.jar:git-Spigot-4b89e7b-7d0f836]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-4b89e7b-7d0f836]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
>
[14:04:10 INFO]: SpaceTurtle420 issued server command: /skr
>
[14:04:10 INFO]: SpaceTurtle420 [b4f89c3e-a029-457f-bd56-6c8e02d98672]: /skr
>
[14:09:39 INFO]: SpaceTurtle420 issued server command: /skr
>
[14:09:39 INFO]: SpaceTurtle420 [b4f89c3e-a029-457f-bd56-6c8e02d98672]: /skr
>
[14:09:41 ERROR]: Could not pass event PlayerInteractEvent to Skript v2.2-dev24b
java.lang.NoSuchMethodError: org.bukkit.World.getNearbyEntities(Lorg/bukkit/Location;DDD)Ljava/util/Collection;
        at ch.njol.skript.expressions.ExprEntities.iterator(ExprEntities.java:196) ~[?:?]
        at ch.njol.skript.lang.Loop.walk(Loop.java:81) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93) ~[?:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:53) ~[?:?]
        at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:152) ~[?:?]
        at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:112) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-4b89e7b-7d0f836]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-4b89e7b-7d0f836]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-4b89e7b-7d0f836]
        at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:226) [spigot.jar:git-Spigot-4b89e7b-7d0f836]
        at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:193) [spigot.jar:git-Spigot-4b89e7b-7d0f836]
        at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:189) [spigot.jar:git-Spigot-4b89e7b-7d0f836]
        at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:692) [spigot.jar:git-Spigot-4b89e7b-7d0f836]
        at net.minecraft.server.v1_8_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [spigot.jar:git-Spigot-4b89e7b-7d0f836]
        at net.minecraft.server.v1_8_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot.jar:git-Spigot-4b89e7b-7d0f836]
        at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-4b89e7b-7d0f836]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
        at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot.jar:git-Spigot-4b89e7b-7d0f836]
        at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [spigot.jar:git-Spigot-4b89e7b-7d0f836]
        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot.jar:git-Spigot-4b89e7b-7d0f836]
        at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot.jar:git-Spigot-4b89e7b-7d0f836]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-4b89e7b-7d0f836]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
>

Did anybody have the same error or is it just me?
(I'm using the newest build)

**Comment by Ayase-san** [comment]
This fork doesn't support any version lower the 1.9, you might also think on use the 1.8.8 instead of the 1.8.3 in your server. Your issue might be because the method that the entities in radius expression uses isn't on that version of Spigot.

**Comment by SpaceTurtle420** [comment]
I just tried it with the 2.1.2 Skript Version (downloaded from the dev.Bukkit Skript site) and it worked perfectly fine with the same Spigot version (1.8.3) ...So I don't think it is because of the Spigot version I'm using. But I'll try it with a newer version of Spigot.

**Comment by SpaceTurtle420** [comment]
Ok, I just updated my server to Spigot 1.8.8 and it works. 👍  Thanks @Ayase-san!!!
