### ISSUE TITLE
Error on console tells me to report here...

### ISSUE THREAD

**Issue by MrKiller01** [bensku/Skript#433]
[11:35:22] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! 
[11:35:22] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! [Skript] Severe Error:
[11:35:22] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! An error happened when trying to enably resolving offline players, so the feature has been turned off. Please report this at https://github.com/bensku/Skript/issues/237
[11:35:22] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! 
[11:35:22] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[11:35:22] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[11:35:22] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! and check whether this error has already been reported.
[11:35:22] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[11:35:22] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[11:35:22] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[11:35:22] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[11:35:22] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! 
[11:35:22] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! Stack trace:
[11:35:22] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! java.lang.NullPointerException: null offline player resolve queue
[11:35:22] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#!     at ch.njol.skript.bukkitutil.UnresolvedOfflinePlayer$1.run(UnresolvedOfflinePlayer.java:58)
[11:35:22] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[11:35:22] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! 
[11:35:22] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! Version Information:
[11:35:22] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#!   Skript: 2.2-dev23
[11:35:22] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#!   Bukkit: 1.11.2-R0.1-SNAPSHOT
[11:35:22] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#!   Minecraft: 1.11.2
[11:35:22] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#!   Java: 1.8.0_121 (Java HotSpot(TM) 64-Bit Server VM 25.121-b13)
[11:35:22] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#!   OS: Windows Server 2012 amd64 6.2
[11:35:22] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! 
[11:35:22] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! Running CraftBukkit: false
[11:35:22] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! 
[11:35:22] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! Current node: databases: (config.sk, line 168)
[11:35:22] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! Current item: null
[11:35:22] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! 
[11:35:22] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! Thread: Skript offline player resolver thread (fetches UUIDs from the minecraft servers)
[11:35:22] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! 
[11:35:22] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! End of Error.
[11:35:22] [Skript offline player resolver thread (fetches UUIDs from the minecraft servers)/ERROR]: #!#! 
All this happened when i stopped the server for updating some plugins....

**Comment by bensku** [comment]
Hmm. Very interesting, again... But I might have a clue wht this happens if it is specially on shutdown.

**Comment by MrKiller01** [comment]
Yes, upon stopping the server.... can i ignore it? I temporarily moved it out of spigot server plugin folder. Hope to see next update with lesser errors...
Thanks

**Comment by TheBentoBox** [comment]
You're using dev23, do you still have this issue when using the newer releases?

**Comment by MrKiller01** [comment]
I had a similar (i think) error in the mean time, but if you can point me towards the newest version, i shall put it in pluginlist...
thanks

**Comment by TheBentoBox** [comment]
The newest release can always be found [here](https://github.com/bensku/Skript/releases).

**Comment by TheBentoBox** [comment]
Are you having this issue anymore on the latest version @MrKiller01 ?

**Comment by MrKiller01** [comment]
I have been trying to get the latest version Working without problems, but
unfortunately there were still errors on the console, so I removed it
again. I do not think I am gonna use it again, sorry. Messaging from my
phone, so I can't produce a log... In the future I might give it another
try. Thanks for everything so far.

Op 18 mrt. 2017 15:55 schreef "Jake Ben-Tovim" <notifications@github.com>:

**Comment by TheBentoBox** [comment]
If you do not think you're going to use it again, and nobody else seems to be having this problem, then I will close.

**Comment by Moderocky** [comment]
I have the same error on a more recent version. (Didn't know if i'm supposed to open a new ticket if it's the same problem?)

**Comment by TheBentoBox** [comment]
@Moderocky Only report something if you encounter it while using the MOST recent version (not just newer, newest) and if it isn't already reported.

**Comment by SylverKN** [comment]
I have the same issue on dev29. Not sure if I should make a new ticket or respond to this one.
