### ISSUE TITLE
Better error message for calling non-existent (or not yet registered) functions

### ISSUE THREAD

**Issue by Aerosmite** [bensku/Skript#434]
When I declare a function that use an other juste after it, I know it's normal to have an error but can you just say 'function doesn't exist' instead of an annoying internal error which can mean anything ?

**Comment by Syst3ms** [comment]
Could you detail your issue with proper grammar, especially for the first sentence ? No way we can help if we can't understand.

**Comment by Snow-Pyon** [comment]
Can you show us the error that it throws?

**Comment by TheBentoBox** [comment]
@Aerosmite give us the error, please. If not I will close this in the coming days.

**Comment by Aerosmite** [comment]
`[09:27:00] [Server thread/ERROR]: #!#! 
[09:27:00] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[09:27:00] [Server thread/ERROR]: #!#! Could not load +function.sk
[09:27:00] [Server thread/ERROR]: #!#! 
[09:27:00] [Server thread/ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[09:27:00] [Server thread/ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[09:27:00] [Server thread/ERROR]: #!#! and check whether this error has already been reported.
[09:27:00] [Server thread/ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[09:27:00] [Server thread/ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[09:27:00] [Server thread/ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[09:27:00] [Server thread/ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[09:27:00] [Server thread/ERROR]: #!#! 
[09:27:00] [Server thread/ERROR]: #!#! Stack trace:
[09:27:00] [Server thread/ERROR]: #!#! ch.njol.skript.SkriptAPIException: Signature of function is null when return type is asked!
[09:27:00] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.FunctionReference.getReturnType(FunctionReference.java:201)
[09:27:00] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.ExprFunctionCall.getReturnType(ExprFunctionCall.java:56)
[09:27:00] [Server thread/ERROR]: #!#!     at ch.njol.skript.conditions.CondCompare.init(CondCompare.java:172)
[09:27:00] [Server thread/ERROR]: #!#!     at ch.njol.skript.conditions.CondCompare.init(CondCompare.java:132)
[09:27:00] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:249)
[09:27:00] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[09:27:00] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Condition.parse(Condition.java:83)
[09:27:00] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:833)
[09:27:00] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:56)
[09:27:00] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Conditional.<init>(Conditional.java:46)
[09:27:00] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:840)
[09:27:00] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Loop.<init>(Loop.java:68)
[09:27:00] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:790)
[09:27:00] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.ScriptFunction.<init>(ScriptFunction.java:53)
[09:27:00] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.Functions.loadFunction(Functions.java:129)
[09:27:00] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:485)
[09:27:00] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:247)
[09:27:00] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:245)
[09:27:00] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:201)
[09:27:00] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript$2.run(Skript.java:406)
[09:27:00] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
[09:27:00] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[09:27:00] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:741)
[09:27:00] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399)
[09:27:00] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672)
[09:27:00] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571)
[09:27:00] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)
[09:27:00] [Server thread/ERROR]: #!#! 
[09:27:00] [Server thread/ERROR]: #!#! Version Information:
[09:27:00] [Server thread/ERROR]: #!#!   Skript: 2.2-dev24b
[09:27:00] [Server thread/ERROR]: #!#!   Bukkit: 1.10.2-R0.1-SNAPSHOT
[09:27:00] [Server thread/ERROR]: #!#!   Minecraft: 1.10.2
[09:27:00] [Server thread/ERROR]: #!#!   Java: 1.8.0_121 (Java HotSpot(TM) 64-Bit Server VM 25.121-b13)
[09:27:00] [Server thread/ERROR]: #!#!   OS: Linux amd64 2.6.32-openvz-042stab116.2-amd64
[09:27:00] [Server thread/ERROR]: #!#! 
[09:27:00] [Server thread/ERROR]: #!#! Running CraftBukkit: false
[09:27:00] [Server thread/ERROR]: #!#! 
[09:27:00] [Server thread/ERROR]: #!#! Current node: if PlayerIsInList(loop-player,{game::current.team::orange::*}) is true: (+function.sk, line 14)
[09:27:00] [Server thread/ERROR]: #!#! Current item: null
[09:27:00] [Server thread/ERROR]: #!#! 
[09:27:00] [Server thread/ERROR]: #!#! Thread: Server thread
[09:27:00] [Server thread/ERROR]: #!#! 
[09:27:00] [Server thread/ERROR]: #!#! End of Error.`

**Comment by Snow-Pyon** [comment]
You're calling a non-existent function, that's why it's throwing that error, you should put the functions at the top of your script, and if you're using it in other scripts, make sure that the script with that function is being loaded before the scripts that are using it.

**Comment by Aerosmite** [comment]
I finally known it was this that causes the error Snow Pion, but for me the bug is not that it throw an error (it's normal) but the fact that this error is internal and should be like "fonction doesn't exist" instead. It's very mindblowing when you don't think to check logs.. (and log aren't very clear for people like me)

**Comment by TheBentoBox** [comment]
Alright, so you're requesting that calling a non-existent function should give a better error message, which would be an enhancement I guess.

**Comment by bensku** [comment]
You are supposed to be able to call any existing function from anywhere. Might be bugged though...
