### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by baptiste0928** [bensku/Skript#439]
[15:23:11] [Server thread/ERROR]: #!#!
[15:23:11] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[15:23:11] [Server thread/ERROR]: #!#!
[15:23:11] [Server thread/ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[15:23:11] [Server thread/ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[15:23:11] [Server thread/ERROR]: #!#! and check whether this error has already been reported.
[15:23:11] [Server thread/ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[15:23:11] [Server thread/ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[15:23:11] [Server thread/ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[15:23:11] [Server thread/ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[15:23:11] [Server thread/ERROR]: #!#!
[15:23:11] [Server thread/ERROR]: #!#! Stack trace:
[15:23:11] [Server thread/ERROR]: #!#! java.lang.NullPointerException
[15:23:11] [Server thread/ERROR]: #!#! at me.iblitzkriegi.vixio.effects.effGenerals.EffSendToChannel.execute(EffSendToChannel.java:18)
[15:23:11] [Server thread/ERROR]: #!#! at ch.njol.skript.lang.Effect.run(Effect.java:54)
[15:23:11] [Server thread/ERROR]: #!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:65)
[15:23:11] [Server thread/ERROR]: #!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93)
[15:23:11] [Server thread/ERROR]: #!#! at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
[15:23:11] [Server thread/ERROR]: #!#! at ch.njol.skript.events.EvtChat$1.execute(EvtChat.java:68)
[15:23:11] [Server thread/ERROR]: #!#! at ch.njol.skript.events.EvtChat$1$1.call(EvtChat.java:87)
[15:23:11] [Server thread/ERROR]: #!#! at ch.njol.skript.events.EvtChat$1$1.call(EvtChat.java:1)
[15:23:11] [Server thread/ERROR]: #!#! at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftFuture.run(CraftFuture.java:89)
[15:23:11] [Server thread/ERROR]: #!#! at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[15:23:11] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730)
[15:23:11] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[15:23:11] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675)
[15:23:11] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574)
[15:23:11] [Server thread/ERROR]: #!#! at java.lang.Thread.run(Thread.java:745)
[15:23:11] [Server thread/ERROR]: #!#!
[15:23:11] [Server thread/ERROR]: #!#! Version Information:
[15:23:11] [Server thread/ERROR]: #!#! Skript: 2.2-dev25
[15:23:11] [Server thread/ERROR]: #!#! Bukkit: 1.11.2-R0.1-SNAPSHOT
[15:23:11] [Server thread/ERROR]: #!#! Minecraft: 1.11.2
[15:23:11] [Server thread/ERROR]: #!#! Java: 1.8.0_112 (Java HotSpot(TM) 64-Bit Server VM 25.112-b15)
[15:23:11] [Server thread/ERROR]: #!#! OS: Linux amd64 3.14.32-xxxx-std-ipv6-64-hz1000
[15:23:11] [Server thread/ERROR]: #!#!
[15:23:11] [Server thread/ERROR]: #!#! Running CraftBukkit: false
[15:23:11] [Server thread/ERROR]: #!#!
[15:23:11] [Server thread/ERROR]: #!#! Current node: null
[15:23:11] [Server thread/ERROR]: #!#! Current item: me.iblitzkriegi.vixio.effects.effGenerals.EffSendToChannel
[15:23:11] [Server thread/ERROR]: #!#!
[15:23:11] [Server thread/ERROR]: #!#! Thread: Server thread
[15:23:11] [Server thread/ERROR]: #!#!
[15:23:11] [Server thread/ERROR]: #!#! End of Error.
[15:23:11] [Server thread/ERROR]: #!#!

**Comment by TheBentoBox** [comment]
This is an issue with Vixio, not Skript. Contact the Vixio dev.
