### ISSUE TITLE
Not working with any CraftBukkit or Spigot version. I also tried plenty other skript version.

### ISSUE THREAD

**Issue by Lukhausen** [bensku/Skript#441]
The Error:

[19:17:06 ERROR]: Could not load 'plugins\Skript (15).jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError
: ch/njol/skript/Skript : Unsupported major.minor version 52.0
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.j
ava:133) ~[spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-6de2fbc-c1aa859]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.
java:329) ~[spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-6de2fbc-c1aa859]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager
.java:251) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-6de2fbc-c1aa859]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.j
ava:301) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-6de2fbc-c1aa859]
        at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.ja
va:204) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-6de2fbc-c1aa859]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.jav
a:542) [spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-6de2fbc-c1aa859]
        at java.lang.Thread.run(Unknown Source) [?:1.6.0_16]
Caused by: java.lang.UnsupportedClassVersionError: ch/njol/skript/Skript : Unsup
ported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.6.0_16]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.6.0_16]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.6.0
_16]
        at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.6.0_16]
        at java.net.URLClassLoader.access$000(Unknown Source) ~[?:1.6.0_16]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.6.0_16]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.6.0_
16]
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.6.0_16]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:101) ~[spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-6de2fbc-c1aa859]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:86) ~[spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-6de2fbc-c1aa859]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.6.0_16]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.6.0_16]
        at java.lang.ClassLoader.loadClassInternal(Unknown Source) ~[?:1.6.0_16]

        at java.lang.Class.forName0(Native Method) ~[?:1.6.0_16]
        at java.lang.Class.forName(Unknown Source) ~[?:1.6.0_16]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.jav
a:64) ~[spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-6de2fbc-c1aa859]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.j
ava:129) ~[spigot-1.11.2-R0.1-SNAPSHOT.jar:git-Spigot-6de2fbc-c1aa859]
        ... 6 more

**Comment by Tuke-Nuke** [comment]
You need java 8 to run Skript.
Contact your host to update it.
