### ISSUE TITLE
loop players in radius 200 of player:

### ISSUE THREAD

**Issue by UnknwonPerson** [bensku/Skript#442]
An internal error occured while attempting to perform this command

**Comment by Snow-Pyon** [comment]
Could you show us the error that's being sent to the console when you execute that command?

**Comment by TheBentoBox** [comment]
I am not having this issue. We can't help you without know the error you're getting.

**Comment by UnknwonPerson** [comment]
[11:14:46 ERROR]: Could not pass event PlayerCommandPreprocessEvent to Skript v2.2-dev25org.bukkit.event.EventException	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[server.jar:git-Spigot-c3c767f-33d5de3]	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-c3c767f-33d5de3]	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-c3c767f-33d5de3]	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar:git-Spigot-c3c767f-33d5de3]	at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1107) [server.jar:git-Spigot-c3c767f-33d5de3]	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [server.jar:git-Spigot-c3c767f-33d5de3]	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [server.jar:git-Spigot-c3c767f-33d5de3]	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [server.jar:git-Spigot-c3c767f-33d5de3]	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [server.jar:git-Spigot-c3c767f-33d5de3]	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696) [server.jar:git-Spigot-c3c767f-33d5de3]	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [server.jar:git-Spigot-c3c767f-33d5de3]	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [server.jar:git-Spigot-c3c767f-33d5de3]	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [server.jar:git-Spigot-c3c767f-33d5de3]	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]Caused by: java.lang.NoSuchMethodError: org.bukkit.World.getNearbyEntities(Lorg/bukkit/Location;DDD)Ljava/util/Collection;	at ch.njol.skript.expressions.ExprEntities.iterator(ExprEntities.java:196) ~[?:?]	at ch.njol.skript.lang.Loop.walk(Loop.java:81) ~[?:?]	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93) ~[?:?]	at ch.njol.skript.lang.Trigger.execute(Trigger.java:53) ~[?:?]	at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:222) ~[?:?]	at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:184) ~[?:?]	at ch.njol.skript.command.Commands.handleCommand(Commands.java:270) ~[?:?]	at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:165) ~[?:?]	at sun.reflect.GeneratedMethodAccessor245.invoke(Unknown Source) ~[?:?]	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[server.jar:git-Spigot-c3c767f-33d5de3]	... 15 more
[11:14:46 ERROR]: nullorg.bukkit.command.CommandException: Unhandled exception executing command 'near' in plugin Skript v2.2-dev25	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-c3c767f-33d5de3]	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-c3c767f-33d5de3]	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[server.jar:git-Spigot-c3c767f-33d5de3]	at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [server.jar:git-Spigot-c3c767f-33d5de3]	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [server.jar:git-Spigot-c3c767f-33d5de3]	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [server.jar:git-Spigot-c3c767f-33d5de3]	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [server.jar:git-Spigot-c3c767f-33d5de3]	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [server.jar:git-Spigot-c3c767f-33d5de3]	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696) [server.jar:git-Spigot-c3c767f-33d5de3]	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [server.jar:git-Spigot-c3c767f-33d5de3]	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [server.jar:git-Spigot-c3c767f-33d5de3]	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [server.jar:git-Spigot-c3c767f-33d5de3]	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]Caused by: java.lang.NoSuchMethodError: org.bukkit.World.getNearbyEntities(Lorg/bukkit/Location;DDD)Ljava/util/Collection;	at ch.njol.skript.expressions.ExprEntities.iterator(ExprEntities.java:196) ~[?:?]	at ch.njol.skript.lang.Loop.walk(Loop.java:81) ~[?:?]	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93) ~[?:?]	at ch.njol.skript.lang.Trigger.execute(Trigger.java:53) ~[?:?]	at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:222) ~[?:?]	at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:184) ~[?:?]	at ch.njol.skript.command.ScriptCommand.onCommand(ScriptCommand.java:161) ~[?:?]	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-c3c767f-33d5de3]	... 14 more

**Comment by bensku** [comment]
What Minecraft version are you running? Spigot, Bukkit, Paper?

**Comment by UnknwonPerson** [comment]
Spigot 1.8.8

**Comment by Tuke-Nuke** [comment]
You sure it is 1.8.8? Because iirc `net.minecraft.server.v1_8_R1` is for `1.8-1.8.3` which is a old supported version.

**Comment by Syst3ms** [comment]
In any way, this fork doesn't support 1.8 and is not meant to. To close.

**Comment by TheBentoBox** [comment]
(Sorry, was away for the weekend)

This fork doesn't officially support versions below 1.9. If Bensku wants to come around and decide to pick up this issue for you, then by all means, but otherwise you either need to use the older 1.8 versions of Skript (I'd recommending Mirre's Skrip 2.2 fixes v8b or v9), or update your server.
