### ISSUE TITLE
dev19, idk what caused keep spam tons of this error

### ISSUE THREAD

**Issue by cwken10** [bensku/Skript#445]
[00:08:53] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[00:08:53] [Server thread/ERROR]: #!#! 
[00:08:53] [Server thread/ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[00:08:53] [Server thread/ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[00:08:53] [Server thread/ERROR]: #!#! and check whether this error has already been reported.
[00:08:53] [Server thread/ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[00:08:53] [Server thread/ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[00:08:53] [Server thread/ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[00:08:53] [Server thread/ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[00:08:53] [Server thread/ERROR]: #!#! 
[00:08:53] [Server thread/ERROR]: #!#! Stack trace:
[00:08:53] [Server thread/ERROR]: #!#! java.lang.NullPointerException
[00:08:53] [Server thread/ERROR]: #!#!     at com.gmail.thelimeglass.Expressions.ExprWorldOfLocation.get(ExprWorldOfLocation.java:47)
[00:08:53] [Server thread/ERROR]: #!#!     at com.gmail.thelimeglass.Expressions.ExprWorldOfLocation.get(ExprWorldOfLocation.java:1)
[00:08:53] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:162)
[00:08:53] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:157)
[00:08:53] [Server thread/ERROR]: #!#!     at ch.njol.skript.conditions.CondCompare.check(CondCompare.java:259)
[00:08:53] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Condition.run(Condition.java:58)
[00:08:53] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Conditional.walk(Conditional.java:53)
[00:08:53] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93)
[00:08:53] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
[00:08:53] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:152)
[00:08:53] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:112)
[00:08:53] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[00:08:53] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[00:08:53] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[00:08:53] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R2.BlockPortal.a(BlockPortal.java:119)
[00:08:53] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R2.Entity.checkBlockCollisions(Entity.java:841)
[00:08:53] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R2.Entity.move(Entity.java:475)
[00:08:53] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R2.EntityLiving.g(EntityLiving.java:1653)
[00:08:53] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R2.EntityLiving.n(EntityLiving.java:1955)
[00:08:53] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R2.EntityInsentient.n(EntityInsentient.java:489)
[00:08:53] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R2.EntityMonster.n(EntityMonster.java:24)
[00:08:53] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R2.EntityZombie.n(EntityZombie.java:176)
[00:08:53] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R2.EntityLiving.m(EntityLiving.java:1784)
[00:08:53] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R2.EntityInsentient.m(EntityInsentient.java:249)
[00:08:53] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R2.EntityMonster.m(EntityMonster.java:28)
[00:08:53] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R2.EntityZombie.m(EntityZombie.java:233)
[00:08:53] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R2.EntityPigZombie.m(SourceFile:68)
[00:08:53] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R2.World.entityJoinedWorld(World.java:1617)
[00:08:53] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R2.World.g(World.java:1592)
[00:08:53] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R2.World.tickEntities(World.java:1426)
[00:08:53] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R2.WorldServer.tickEntities(WorldServer.java:632)
[00:08:53] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:797)
[00:08:53] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399)
[00:08:53] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665)
[00:08:53] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564)
[00:08:53] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)
[00:08:53] [Server thread/ERROR]: #!#! 
[00:08:53] [Server thread/ERROR]: #!#! Version Information:
[00:08:53] [Server thread/ERROR]: #!#!   Skript: 2.2-dev19
[00:08:53] [Server thread/ERROR]: #!#!   Bukkit: 1.9.4-R0.1-SNAPSHOT
[00:08:53] [Server thread/ERROR]: #!#!   Minecraft: 1.9.4
[00:08:53] [Server thread/ERROR]: #!#!   Java: 1.8.0_111 (Java HotSpot(TM) 64-Bit Server VM 25.111-b14)
[00:08:53] [Server thread/ERROR]: #!#!   OS: Linux amd64 4.2.0-27-generic
[00:08:53] [Server thread/ERROR]: #!#! 
[00:08:53] [Server thread/ERROR]: #!#! Running CraftBukkit: false
[00:08:53] [Server thread/ERROR]: #!#! 
[00:08:53] [Server thread/ERROR]: #!#! Current node: null
[00:08:53] [Server thread/ERROR]: #!#! Current item: [skellett] world (of|from) [location] %location% is equal to "spawn" (comparator: ch.njol.skript.classes.data.DefaultComparators$13@272f24ef)
[00:08:53] [Server thread/ERROR]: #!#! 
[00:08:53] [Server thread/ERROR]: #!#! Thread: Server thread
[00:08:53] [Server thread/ERROR]: #!#! 
[00:08:53] [Server thread/ERROR]: #!#! End of Error.

**Comment by bensku** [comment]
Old Skript version + addon issue. Closing.
