### ISSUE TITLE
java.lang.NullPointerException: null offline player resolve queue

### ISSUE THREAD

**Issue by Remixful** [bensku/Skript#454]
> [22:50:58 ERROR]: #!#!
[22:50:58 ERROR]: #!#! [Skript] Severe Error:
[22:50:58 ERROR]: #!#! An error happened when trying to enably resolving offline players, so the feature has been turned off. Please report this at https://github.com/bensku/Skript/issues/237
[22:50:58 ERROR]: #!#!
[22:50:58 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[22:50:58 ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[22:50:58 ERROR]: #!#! and check whether this error has already been reported.
[22:50:58 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[22:50:58 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[22:50:58 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[22:50:58 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[22:50:58 ERROR]: #!#!
[22:50:58 ERROR]: #!#! Stack trace:
[22:50:58 ERROR]: #!#! java.lang.NullPointerException: null offline player resolve queue
[22:50:58 ERROR]: #!#!     at ch.njol.skript.bukkitutil.UnresolvedOfflinePlayer$1.run(UnresolvedOfflinePlayer.java:61)
[22:50:58 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[22:50:58 ERROR]: #!#!
[22:50:58 ERROR]: #!#! Version Information:
[22:50:58 ERROR]: #!#!   Skript: 2.2-dev25
[22:50:58 ERROR]: #!#!   Bukkit: 1.11.2-R0.1-SNAPSHOT
[22:50:58 ERROR]: #!#!   Minecraft: 1.11.2
[22:50:58 ERROR]: #!#!   Java: 1.8.0_121 (Java HotSpot(TM) 64-Bit Server VM 25.121-b13)
[22:50:58 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[22:50:58 ERROR]: #!#!
[22:50:58 ERROR]: #!#! Running CraftBukkit: false
[22:50:58 ERROR]: #!#!
[22:50:58 ERROR]: #!#! Current node: null
[22:50:58 ERROR]: #!#! Current item: null
[22:50:58 ERROR]: #!#!
[22:50:58 ERROR]: #!#! Thread: Skript offline player resolver thread (fetches UUIDs from the minecraft servers)
[22:50:58 ERROR]: #!#!
[22:50:58 ERROR]: #!#! End of Error.
[22:50:58 ERROR]: #!#!

Current version is included in the error log. This seems to occur after server reloads.

**Comment by bensku** [comment]
This is old bug, but I do have some idea how it could be fixed.
