### ISSUE TITLE
Exception on startup

### ISSUE THREAD

**Issue by itismejoey** [bensku/Skript#47]
```
[21:47:36] [Server thread/WARN]: [Skript] Task #23 for Skript v2.2-Fixes-V10 generated an exception
java.lang.NullPointerException
	at java.lang.Class.isAssignableFrom(Native Method) ~[?:1.8.0_72-internal]
	at ch.njol.skript.registrations.Classes.sortClassInfos(Classes.java:147) ~[?:?]
	at ch.njol.skript.registrations.Classes.onRegistrationsStop(Classes.java:100) ~[?:?]
	at ch.njol.skript.Skript.stopAcceptingRegistrations(Skript.java:877) ~[?:?]
	at ch.njol.skript.Skript.access$2(Skript.java:872) ~[?:?]
	at ch.njol.skript.Skript$2.run(Skript.java:347) ~[?:?]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-944aa20-8d16fc0]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-944aa20-8d16fc0]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729) [spigot.jar:git-Spigot-944aa20-8d16fc0]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-944aa20-8d16fc0]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-944aa20-8d16fc0]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-944aa20-8d16fc0]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]

```

**Comment by itismejoey** [comment]
Actually, this is with 1.9 in general, I guess I missed it before.

**Comment by bensku** [comment]
Please provide more details about your server. Do you have addons for Skript?

**Comment by itismejoey** [comment]
MC: 1.9-.2
Skript: Your version 10b and 11b
Addons: RandomSK, SkQuery 3 and 4, SkRayFall, SkStuff, skUtilites, Umbaska, WildSkript

**Comment by bensku** [comment]
You have so many closed source addons that I have no idea which is causing this. Can't check, that it is. Please try to identify which addon is causing this. If it happens to be open source, I might be able to do something; otherwise, sorry.

**Comment by itismejoey** [comment]
Newest release (dev12c). ZERO addons enabled.

```
[23:23:51] [Server thread/WARN]: [Skript] Task #8 for Skript v2.2-Fixes-V10 generated an exception
java.lang.NullPointerException
	at java.lang.Class.isAssignableFrom(Native Method) ~[?:1.8.0_72-internal]
	at ch.njol.skript.registrations.Classes.sortClassInfos(Classes.java:147) ~[?:?]
	at ch.njol.skript.registrations.Classes.onRegistrationsStop(Classes.java:100) ~[?:?]
	at ch.njol.skript.Skript.stopAcceptingRegistrations(Skript.java:877) ~[?:?]
	at ch.njol.skript.Skript.access$2(Skript.java:872) ~[?:?]
	at ch.njol.skript.Skript$2.run(Skript.java:347) ~[?:?]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-d20369f-7fc5cd8]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-d20369f-7fc5cd8]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729) [spigot.jar:git-Spigot-d20369f-7fc5cd8]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-d20369f-7fc5cd8]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-d20369f-7fc5cd8]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-d20369f-7fc5cd8]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
```

**Comment by itismejoey** [comment]
Are you on any of the Discords for either skU or Skript? If you are message me on there. If not, wait until the forums are back up and message me there. I might have an idea on how we can get this fixed. I use all the major addons, I can't be the only one having this issue.

**Comment by bensku** [comment]
Well, on our project server we have RandomSK, skRayFall and SkStuff with no errors like this..

Umbaska doesn't (at least didn't) register itself as Skript addon, and if it wasn't so popular I'd make Skript require addon registration. Maybe some day... Anyway, if you have idea how to fix this, I can at least try it.

**Comment by itismejoey** [comment]
Do you not use Umbaska at all?

Skript loads fine with no addons at all. Throw Umbaska on and get the error. I actually didn't even try with any others, I just assumed it was Umbaska causing it.

**Comment by bensku** [comment]
Sorry for delay - have been busy.

I don't use Umbaska at all. We certainly tried before I started updating my own fork of Skript, but in the end it caused serious problems with RandomSK (?) and some old Skript version. I'm not also that motivated to fix anything related to any closed source addons :)

If you can provide me good explanation (or better, code) how to fix this error - I will do that. If not, well... low priority.

**Comment by itismejoey** [comment]
Check your messages on skUnity.

**Comment by bensku** [comment]
This was "fixed"; check dev13c release notes for more information.
