### ISSUE TITLE
I'm using dev-26b 

### ISSUE THREAD

**Issue by UnknwonPerson** [bensku/Skript#471]
[03:33:03 ERROR]: #!#! [03:33:03 ERROR]: #!#! [Skript] Severe Error:
[03:33:03 ERROR]: #!#! Could not load herocraft.sk[03:33:03 ERROR]: #!#! 
[03:33:03 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.[03:33:03 ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/[03:33:03 ERROR]: #!#! and check whether this error has already been reported.[03:33:03 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),[03:33:03 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.[03:33:03 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.[03:33:03 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.[03:33:03 ERROR]: #!#! [03:33:03 ERROR]: #!#! Stack trace:[03:33:03 ERROR]: #!#! java.lang.NullPointerException[03:33:03 ERROR]: #!#!     at ch.njol.skript.util.chat.ChatMessages.parse(ChatMessages.java:197)[03:33:03 ERROR]: #!#!     at ch.njol.skript.util.chat.ChatMessages.parseToArray(ChatMessages.java:228)[03:33:03 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.<init>(VariableString.java:107)[03:33:03 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.newInstance(VariableString.java:299)[03:33:03 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.newInstance(VariableString.java:129)[03:33:03 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:317)[03:33:03 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:416)[03:33:03 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1130)[03:33:03 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1082)[03:33:03 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:219)[03:33:03 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:174)[03:33:03 ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:59)[03:33:03 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:753)[03:33:03 ERROR]: #!#!     at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:54)[03:33:03 ERROR]: #!#!     at ch.njol.skript.lang.Conditional.<init>(Conditional.java:44)[03:33:03 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:839)[03:33:03 ERROR]: #!#!     at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:54)[03:33:03 ERROR]: #!#!     at ch.njol.skript.lang.Conditional.<init>(Conditional.java:44)[03:33:03 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:839)[03:33:03 ERROR]: #!#!     at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:54)[03:33:03 ERROR]: #!#!     at ch.njol.skript.lang.Conditional.<init>(Conditional.java:44)[03:33:03 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:839)
[03:33:03 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:510)[03:33:03 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:269)[03:33:03 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:185)[03:33:03 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)[03:33:03 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)[03:33:03 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_9_R2.CraftServer.dispatchCommand(CraftServer.java:645)[03:33:03 ERROR]: #!#!     at net.minecraft.server.v1_9_R2.PlayerConnection.handleCommand(PlayerConnection.java:1349)[03:33:03 ERROR]: #!#!     at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1184)[03:33:03 ERROR]: #!#!     at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)[03:33:03 ERROR]: #!#!     at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)[03:33:03 ERROR]: #!#!     at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13)[03:33:03 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[03:33:03 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(FutureTask.java:266)[03:33:03 ERROR]: #!#!     at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45)[03:33:03 ERROR]: #!#!     at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726)[03:33:03 ERROR]: #!#!     at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399)[03:33:03 ERROR]: #!#!     at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665)[03:33:03 ERROR]: #!#!     at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564)[03:33:03 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)[03:33:03 ERROR]: #!#! [03:33:03 ERROR]: #!#! Version Information:[03:33:03 ERROR]: #!#!   Skript: 2.2-dev26[03:33:03 ERROR]: #!#!   Bukkit: 1.9.4-R0.1-SNAPSHOT[03:33:03 ERROR]: #!#!   Minecraft: 1.9.4[03:33:03 ERROR]: #!#!   Java: 1.8.0_91 (Java HotSpot(TM) 64-Bit Server VM 25.91-b14)[03:33:03 ERROR]: #!#!   OS: Linux amd64 4.2.0-27-generic[03:33:03 ERROR]: #!#! [03:33:03 ERROR]: #!#! Running CraftBukkit: false[03:33:03 ERROR]: #!#! [03:33:03 ERROR]: #!#! Current node: message "&9&L冷静>&6&l%difference between 2 second and {_chat_waited}%" (herocraft.sk, line 80)[03:33:03 ERROR]: #!#! Current item: null[03:33:03 ERROR]: #!#! 
[03:33:03 ERROR]: #!#! Thread: Server thread[03:33:03 ERROR]: #!#! [03:33:03 ERROR]: #!#! End of Error.[03:33:03 ERROR]: #!#!

**Comment by TheBentoBox** [comment]
Duplicates #465.
