### ISSUE TITLE
Can't use broadcast/send effect

### ISSUE THREAD

**Issue by ItalianRedstone** [bensku/Skript#475]
When I use the broadcast or the send effect, the console gives me this error:

[10:46:28 ERROR]: #!#! java.lang.NullPointerException
[10:46:28 ERROR]: #!#!     at ch.njol.skript.util.chat.ChatMessages.parse(ChatMessages.java:197)
[10:46:28 ERROR]: #!#!     at ch.njol.skript.util.chat.ChatMessages.parseToArray(ChatMessages.java:228)
[10:46:28 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.<init>(VariableString.java:94)
[10:46:28 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.newInstance(VariableString.java:295)
[10:46:28 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.newInstance(VariableString.java:129)
[10:46:28 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:317)
[10:46:28 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:416)
[10:46:28 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1130)
[10:46:28 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1082)
[10:46:28 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:219)
[10:46:28 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:174)
[10:46:28 ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:59)
[10:46:28 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:753)
[10:46:28 ERROR]: #!#!     at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:54)
[10:46:28 ERROR]: #!#!     at ch.njol.skript.lang.Conditional.<init>(Conditional.java:44)
[10:46:28 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:839)
[10:46:28 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:510)
[10:46:28 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:245)
[10:46:28 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:199)
[10:46:28 ERROR]: #!#!     at ch.njol.skript.Skript$2.run(Skript.java:407)
[10:46:28 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
[10:46:28 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[10:46:28 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738)
[10:46:28 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[10:46:28 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
[10:46:28 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
[10:46:28 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)
[10:46:28 ERROR]: #!#! 
[10:46:28 ERROR]: #!#! Version Information:
[10:46:28 ERROR]: #!#!   Skript: 2.2-dev26
[10:46:28 ERROR]: #!#!   Bukkit: 1.11.2-R0.1-SNAPSHOT
[10:46:28 ERROR]: #!#!   Minecraft: 1.11.2
[10:46:28 ERROR]: #!#!   Java: 1.8.0_112 (Java HotSpot(TM) 64-Bit Server VM 25.112-b15)
[10:46:28 ERROR]: #!#!   OS: Linux amd64 3.14.32-xxxx-grs-ipv6-64
[10:46:28 ERROR]: #!#! 
[10:46:28 ERROR]: #!#! Running CraftBukkit: false
[10:46:28 ERROR]: #!#! 
[10:46:28 ERROR]: #!#! Current node: send "text here" to player (equilibrio team.sk, line 24)
[10:46:28 ERROR]: #!#! Current item: null
[10:46:28 ERROR]: #!#! 
[10:46:28 ERROR]: #!#! Thread: Server thread
[10:46:28 ERROR]: #!#! 
[10:46:28 ERROR]: #!#! End of Error.
[10:46:28 ERROR]: #!#! 

I tried removing all the addons but this error is still occurring.

This script works with the previous version of the plugin.

**Comment by TheBentoBox** [comment]
This was mostly fixed in dev26b, and you seem to be still running dev26a. However, 26b still has some issues as well, and I recommend downgrading to dev25 for now. 

Duplicates #465. Please search before submitting an issue to ensure it isn't already reported. Keep an eye on #465 to see when this will be fixed.
