### ISSUE TITLE
1.11.2 Spigot issue: "java.lang.NoSuchMethodError: org.bukkit.DyeColor.getData()B"

### ISSUE THREAD

**Issue by Starwort** [bensku/Skript#504]
Here is a crash log:

`[20:41:18 ERROR]: Error occurred while enabling Skript v2.1.2 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.DyeColor.getData()B
        at ch.njol.skript.util.Color.<clinit>(Color.java:82) ~[?:?]
        at ch.njol.skript.SkriptCommand.<clinit>(SkriptCommand.java:60) ~[?:?]
        at ch.njol.skript.Skript.onEnable(Skript.java:254) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot-1.11.2.jar:git-Spigot-625bc00-41a7d14]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.2.jar:git-Spigot-625bc00-41a7d14]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.2.jar:git-Spigot-625bc00-41a7d14]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376) [spigot-1.11.2.jar:git-Spigot-625bc00-41a7d14]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326) [spigot-1.11.2.jar:git-Spigot-625bc00-41a7d14]
        at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.11.2.jar:git-Spigot-625bc00-41a7d14]
        at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.11.2.jar:git-Spigot-625bc00-41a7d14]
        at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.11.2.jar:git-Spigot-625bc00-41a7d14]
        at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.11.2.jar:git-Spigot-625bc00-41a7d14]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.11.2.jar:git-Spigot-625bc00-41a7d14]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
`

Did I overlook something obvious, or have I actually found a bug?

If I were to guess I'd say that it's a typo (.getData()**B**)

**Comment by bensku** [comment]
Yes. You have ancient Skript version.

**Comment by Starwort** [comment]
A) Very quick; B) Just downloaded it -- Where is the latest release then?

**Comment by bensku** [comment]
I just happened to be reading other issues :)

https://github.com/bensku/Skript/releases
