### ISSUE TITLE
Use of < and >

### ISSUE THREAD

**Issue by GabrielAugustoTI** [bensku/Skript#506]
When i try use < or > symbols (not for JSON) console send me a error:

> [19:59:06] [Server thread/INFO]: AugustoResende issued server command: /sk reload sp
[19:59:06] [Server thread/ERROR]: #!#! 
[19:59:06] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[19:59:06] [Server thread/ERROR]: #!#! Could not load sp.sk
[19:59:06] [Server thread/ERROR]: #!#! 
[19:59:06] [Server thread/ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[19:59:06] [Server thread/ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[19:59:06] [Server thread/ERROR]: #!#! and check whether this error has already been reported.
[19:59:06] [Server thread/ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[19:59:06] [Server thread/ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[19:59:06] [Server thread/ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[19:59:06] [Server thread/ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[19:59:06] [Server thread/ERROR]: #!#! 
[19:59:06] [Server thread/ERROR]: #!#! Stack trace:
[19:59:06] [Server thread/ERROR]: #!#! java.lang.NullPointerException
[19:59:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.util.chat.ChatMessages.parse(ChatMessages.java:197)
[19:59:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.util.chat.ChatMessages.parseToArray(ChatMessages.java:228)
[19:59:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.VariableString.<init>(VariableString.java:94)
[19:59:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.VariableString.newInstance(VariableString.java:295)
[19:59:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.VariableString.newInstance(VariableString.java:129)
[19:59:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:317)
[19:59:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:416)
[19:59:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1130)
[19:59:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1048)
[19:59:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1082)
[19:59:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:219)
[19:59:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:174)
[19:59:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:319)
[19:59:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:416)
[19:59:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1130)
[19:59:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1055)
[19:59:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1082)
[19:59:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:219)
[19:59:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:174)
[19:59:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:59)
[19:59:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:753)
[19:59:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:54)
[19:59:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Conditional$1.<init>(Conditional.java:72)
[19:59:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Conditional.loadElseClause(Conditional.java:72)
[19:59:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:812)
[19:59:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:54)
[19:59:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Conditional.<init>(Conditional.java:44)
[19:59:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:839)
[19:59:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:465)
[19:59:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:469)
[19:59:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:269)
[19:59:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:185)
[19:59:06] [Server thread/ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[19:59:06] [Server thread/ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[19:59:06] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:675)
[19:59:06] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1392)
[19:59:06] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1197)
[19:59:06] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[19:59:06] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[19:59:06] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[19:59:06] [Server thread/ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[19:59:06] [Server thread/ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
[19:59:06] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
[19:59:06] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:830)
[19:59:06] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403)
[19:59:06] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754)
[19:59:06] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652)
[19:59:06] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[19:59:06] [Server thread/ERROR]: #!#! 
[19:59:06] [Server thread/ERROR]: #!#! Version Information:
[19:59:06] [Server thread/ERROR]: #!#!   Skript: 2.2-dev26
[19:59:06] [Server thread/ERROR]: #!#!   Bukkit: 1.11.2-R0.1-SNAPSHOT
[19:59:06] [Server thread/ERROR]: #!#!   Minecraft: 1.11.2
[19:59:06] [Server thread/ERROR]: #!#!   Java: 1.8.0_121 (Java HotSpot(TM) 64-Bit Server VM 25.121-b13)
[19:59:06] [Server thread/ERROR]: #!#!   OS: Linux amd64 2.6.32-042stab120.11
[19:59:06] [Server thread/ERROR]: #!#! 
[19:59:06] [Server thread/ERROR]: #!#! Running CraftBukkit: false
[19:59:06] [Server thread/ERROR]: #!#! 
[19:59:06] [Server thread/ERROR]: #!#! Current node: send coloured "&6&l[S]&f Para usar o comando digite: &6/sp vender <valor>" (sp.sk, line 49)
[19:59:06] [Server thread/ERROR]: #!#! Current item: null
[19:59:06] [Server thread/ERROR]: #!#! 
[19:59:06] [Server thread/ERROR]: #!#! Thread: Server thread
[19:59:06] [Server thread/ERROR]: #!#! 
[19:59:06] [Server thread/ERROR]: #!#! End of Error.
[19:59:06] [Server thread/ERROR]: #!#!

**Comment by TheBentoBox** [comment]
It looks like you're on dev26 instead of dev26d. Make sure you have the latest release from [here](https://github.com/bensku/Skript/releases), and please note that there are still bugs with the new JSON chat system that are being discussed in other tickets.

Let me know if upgrading doesn't fix your issue and I'll reopen.

**Comment by GabrielAugustoTI** [comment]
Thanks, but i have another bug!

send "&6&l[S]&f Test"

&f is not resetting bold!

**Comment by GabrielAugustoTI** [comment]
Use of send coloured fix this issue!

**Comment by GabrielAugustoTI** [comment]
@TheBentoBox

**Comment by TheBentoBox** [comment]
Already being discussed in #488.
