### ISSUE TITLE
PaperSpigot Errors

### ISSUE THREAD

**Issue by bertek41** [bensku/Skript#512]
PaperSpigot 1.8.x Errors:
`[22:07:08] [Craft Scheduler Thread - 135/WARN]: Exception in thread "Craft Scheduler Thread - 135"
[22:07:08] [Craft Scheduler Thread - 135/WARN]: org.apache.commons.lang.UnhandledException: Plugin Skript v2.2-dev25 generated an exception while executing task 7
    at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: com/google/gson/Gson
    at ch.njol.skript.Updater.deserialize(Updater.java:166)
    at ch.njol.skript.Updater$CheckerTask.run(Updater.java:281)
    at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
    at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more
Caused by: java.lang.ClassNotFoundException: com.google.gson.Gson
    at java.net.URLClassLoader.findClass(Unknown Source)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 7 more`

**Comment by Snow-Pyon** [comment]
This fork doesn't support any version lower the 1.9 and you're actually using the 1.8.0 (for fuck sake, at least use the 1.8.8)

**Comment by bensku** [comment]
Your server is missing GSON which is mandatory. It is provided with newer Spigot versions.
