### ISSUE TITLE
NullPointerException on a certain message

### ISSUE THREAD

**Issue by xXAndrew28Xx** [bensku/Skript#519]
Stacktrace (and log right before it)
```
[17:48:24 INFO]: [Factions v1.6.9.5-U0.1.20] xXAndrew28Xx created a new faction: Andrew
[17:49:36 INFO]: xXAndrew28Xx issued server command: /skript reload test
[17:49:40 INFO]: xXAndrew28Xx issued server command: /f disband andrew
[17:49:40 INFO]: [Factions v1.6.9.5-U0.1.20] The faction Andrew (1) was disbanded by xXAndrew28Xx.
[17:49:42 INFO]: xXAndrew28Xx issued server command: /f create Andrew
[17:49:42 ERROR]: #!#! 
[17:49:42 ERROR]: #!#! [Skript] Severe Error:
[17:49:42 ERROR]: #!#! 
[17:49:42 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[17:49:42 ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[17:49:42 ERROR]: #!#! and check whether this error has already been reported.
[17:49:42 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[17:49:42 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[17:49:42 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[17:49:42 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[17:49:42 ERROR]: #!#! 
[17:49:42 ERROR]: #!#! Stack trace:
[17:49:42 ERROR]: #!#! java.lang.NullPointerException
[17:49:42 ERROR]: #!#!     at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:25)
[17:49:42 ERROR]: #!#!     at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:16)
[17:49:42 ERROR]: #!#!     at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
[17:49:42 ERROR]: #!#!     at com.google.gson.Gson.fromJson(Gson.java:803)
[17:49:42 ERROR]: #!#!     at com.google.gson.Gson.fromJson(Gson.java:868)
[17:49:42 ERROR]: #!#!     at com.google.gson.Gson$1.deserialize(Gson.java:126)
[17:49:42 ERROR]: #!#!     at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:62)
[17:49:42 ERROR]: #!#!     at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:17)
[17:49:42 ERROR]: #!#!     at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
[17:49:42 ERROR]: #!#!     at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
[17:49:42 ERROR]: #!#!     at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
[17:49:42 ERROR]: #!#!     at com.google.gson.Gson.fromJson(Gson.java:803)
[17:49:42 ERROR]: #!#!     at com.google.gson.Gson.fromJson(Gson.java:868)
[17:49:42 ERROR]: #!#!     at com.google.gson.Gson$1.deserialize(Gson.java:126)
[17:49:42 ERROR]: #!#!     at net.md_5.bungee.chat.BaseComponentSerializer.deserialize(BaseComponentSerializer.java:50)
[17:49:42 ERROR]: #!#!     at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:24)
[17:49:42 ERROR]: #!#!     at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:16)
[17:49:42 ERROR]: #!#!     at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
[17:49:42 ERROR]: #!#!     at com.google.gson.Gson.fromJson(Gson.java:803)
[17:49:42 ERROR]: #!#!     at com.google.gson.Gson.fromJson(Gson.java:868)
[17:49:42 ERROR]: #!#!     at com.google.gson.Gson$1.deserialize(Gson.java:126)
[17:49:42 ERROR]: #!#!     at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:62)
[17:49:42 ERROR]: #!#!     at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:17)
[17:49:42 ERROR]: #!#!     at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
[17:49:42 ERROR]: #!#!     at com.google.gson.Gson.fromJson(Gson.java:803)
[17:49:42 ERROR]: #!#!     at com.google.gson.Gson.fromJson(Gson.java:768)
[17:49:42 ERROR]: #!#!     at com.google.gson.Gson.fromJson(Gson.java:717)
[17:49:42 ERROR]: #!#!     at com.google.gson.Gson.fromJson(Gson.java:689)
[17:49:42 ERROR]: #!#!     at net.md_5.bungee.chat.ComponentSerializer.parse(ComponentSerializer.java:34)
[17:49:42 ERROR]: #!#!     at ch.njol.skript.effects.EffMessage.execute(EffMessage.java:85)
[17:49:42 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[17:49:42 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[17:49:42 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[17:49:42 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
[17:49:42 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:151)
[17:49:42 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:109)
[17:49:42 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[17:49:42 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[17:49:42 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[17:49:42 ERROR]: #!#!     at me.andrew28.addons.conquer.factions.EventWrapperListener.throwEvent(EventWrapperListener.java:12)
[17:49:42 ERROR]: #!#!     at me.andrew28.addons.conquer.factions.impl.factionsuuid.FactionsUUIDImplEventWrapperListener.onFPlayerJoin(FactionsUUIDImplEventWrapperListener.java:90)
[17:49:42 ERROR]: #!#!     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:49:42 ERROR]: #!#!     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[17:49:42 ERROR]: #!#!     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:49:42 ERROR]: #!#!     at java.lang.reflect.Method.invoke(Method.java:498)
[17:49:42 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[17:49:42 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[17:49:42 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[17:49:42 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[17:49:42 ERROR]: #!#!     at com.massivecraft.factions.cmd.CmdCreate.perform(CmdCreate.java:83)
[17:49:42 ERROR]: #!#!     at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:130)
[17:49:42 ERROR]: #!#!     at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53)
[17:49:42 ERROR]: #!#!     at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:116)
[17:49:42 ERROR]: #!#!     at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53)
[17:49:42 ERROR]: #!#!     at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:134)
[17:49:42 ERROR]: #!#!     at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:299)
[17:49:42 ERROR]: #!#!     at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:262)
[17:49:42 ERROR]: #!#!     at com.massivecraft.factions.P.handleCommand(P.java:189)
[17:49:42 ERROR]: #!#!     at com.massivecraft.factions.P.onCommand(P.java:200)
[17:49:42 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[17:49:42 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[17:49:42 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650)
[17:49:42 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1353)
[17:49:42 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1188)
[17:49:42 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[17:49:42 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[17:49:42 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[17:49:42 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[17:49:42 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[17:49:42 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
[17:49:42 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747)
[17:49:42 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[17:49:42 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
[17:49:42 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
[17:49:42 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)
[17:49:42 ERROR]: #!#! 
[17:49:42 ERROR]: #!#! Version Information:
[17:49:42 ERROR]: #!#!   Skript: 2.2-dev26e
[17:49:42 ERROR]: #!#!   Bukkit: 1.11.2-R0.1-SNAPSHOT
[17:49:42 ERROR]: #!#!   Minecraft: 1.11.2
[17:49:42 ERROR]: #!#!   Java: 1.8.0_112 (Java HotSpot(TM) 64-Bit Server VM 25.112-b15)
[17:49:42 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[17:49:42 ERROR]: #!#! 
[17:49:42 ERROR]: #!#! Running CraftBukkit: false
[17:49:42 ERROR]: #!#! 
[17:49:42 ERROR]: #!#! Current node: null
[17:49:42 ERROR]: #!#! Current item: send "event-joinreason %event-types.conquerjoinreason%" to event-player/console
[17:49:42 ERROR]: #!#! 
[17:49:42 ERROR]: #!#! Thread: Server thread
[17:49:42 ERROR]: #!#! 
[17:49:42 ERROR]: #!#! End of Error.
[17:49:42 ERROR]: #!#! 
```
Skript Code Used:
```
on faction player join:
    message "Faction Player Join Event"
    message "event-faction %event-faction%"
    message "event-player %event-player%"
    message "event-joinreason %event-joinreason%" #THIS LINE
```
Weird thing is that the text isn't a JSON text .

**Comment by xXAndrew28Xx** [comment]
Nevermind, randomly disappeared.
