### ISSUE TITLE
Particles Errors

### ISSUE THREAD

**Issue by bertek41** [bensku/Skript#538]
Spigot Version: This server is running CraftBukkit version git-Spigot-5f38d38-12698ea (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
Java: 8
Errors:
Pastebin: https://pastebin.com/S9SsJNP5
Hastebin: https://hastebin.com/uqiciconel.sql
Pasted.Co: http://pasted.co/5096c6fd
Skript:
```
options:
	p: &8[&6Market&8] &7» &6

command /ver [<player>] [<items>] [<integer>]:
	executable by: console and players
	usage: /Ver Oyuncu Miktar Esya Fiyat
	trigger:
		if command sender isn't the console:
			if player is "YasinSubasi" or "IrfanMW":
				if arg-3 is set:
					if arg-1's balance is bigger than or equal to arg-3:
						loop arg-2:
							remove arg-3 from arg-1's balance
							give loop-item to arg-1
							send "{@p} Marketten %arg-3%TL ye %loop-item% Satın Aldın!" to arg-1
							spawn 3 of particle heart at location of player
							stop
					else:
						send arg-1 title "&6Market" with subtitle "&cBu Eşyayı Almak Için Paranız Yetersiz!" for 3 second
						stop
		else:
			if arg-3 is set:
				if arg-1's balance is bigger than or equal to arg-3:
					loop arg-2:
						remove arg-3 from arg-1's balance
						give loop-item to arg-1
						send "{@p} Marketten %arg-3%TL ye %loop-item% Satın Aldın!" to arg-1
						stop
				else:
					send arg-1 title "&6Market" with subtitle "&cBu Eşyayı Almak Için Paranız Yetersiz!" for 3 second
					stop
```

```
[20:49:21] [Server thread/INFO]: YasinSubasi issued server command: /sk reload ver
[20:49:27] [Server thread/INFO]: YasinSubasi issued server command: /ver YasinSubasi 5 diamond 0
[20:49:27] [Server thread/INFO]: YasinSubasi [e55b2750-1d94-31e9-9778-354c7d0522e0]: /ver YasinSubasi 5 diamond 0
[20:49:27] [Server thread/WARN]: java.lang.IllegalArgumentException: Can not set net.minecraft.server.v1_8_R3.EnumParticle field net.minecraft.server.v1_8_R3.PacketPlayOutWorldParticles.a to java.lang.String
[20:49:27] [Server thread/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
[20:49:27] [Server thread/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
[20:49:27] [Server thread/WARN]: 	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
[20:49:27] [Server thread/WARN]: 	at java.lang.reflect.Field.set(Field.java:764)
[20:49:27] [Server thread/WARN]: 	at com.w00tmast3r.skquery.util.packet.particle.Particle.play(Particle.java:62)
[20:49:27] [Server thread/WARN]: 	at com.w00tmast3r.skquery.elements.effects.EffParticle.execute(EffParticle.java:38)
[20:49:27] [Server thread/WARN]: 	at ch.njol.skript.lang.Effect.run(Effect.java:54)
[20:49:27] [Server thread/WARN]: 	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:65)
[20:49:27] [Server thread/WARN]: 	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93)
[20:49:27] [Server thread/WARN]: 	at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
[20:49:27] [Server thread/WARN]: 	at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:222)
[20:49:27] [Server thread/WARN]: 	at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:184)
[20:49:27] [Server thread/WARN]: 	at ch.njol.skript.command.Commands.handleCommand(Commands.java:270)
[20:49:27] [Server thread/WARN]: 	at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:165)
[20:49:27] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor78.invoke(Unknown Source)
[20:49:27] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:49:27] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[20:49:27] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[20:49:27] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[20:49:27] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[20:49:27] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[20:49:27] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1154)
[20:49:27] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[20:49:27] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[20:49:27] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[20:49:27] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[20:49:27] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[20:49:27] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[20:49:27] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[20:49:27] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[20:49:27] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[20:49:27] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[20:49:27] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[20:49:27] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[20:49:28] [Server thread/INFO]: YasinSubasi issued server command: /ver YasinSubasi 5 diamond 0
[20:49:28] [Server thread/INFO]: YasinSubasi [e55b2750-1d94-31e9-9778-354c7d0522e0]: /ver YasinSubasi 5 diamond 0
[20:49:28] [Server thread/WARN]: java.lang.IllegalArgumentException: Can not set net.minecraft.server.v1_8_R3.EnumParticle field net.minecraft.server.v1_8_R3.PacketPlayOutWorldParticles.a to java.lang.String
[20:49:28] [Server thread/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
[20:49:28] [Server thread/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
[20:49:28] [Server thread/WARN]: 	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
[20:49:28] [Server thread/WARN]: 	at java.lang.reflect.Field.set(Field.java:764)
[20:49:28] [Server thread/WARN]: 	at com.w00tmast3r.skquery.util.packet.particle.Particle.play(Particle.java:62)
[20:49:28] [Server thread/WARN]: 	at com.w00tmast3r.skquery.elements.effects.EffParticle.execute(EffParticle.java:38)
[20:49:28] [Server thread/WARN]: 	at ch.njol.skript.lang.Effect.run(Effect.java:54)
[20:49:28] [Server thread/WARN]: 	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:65)
[20:49:28] [Server thread/WARN]: 	at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93)
[20:49:28] [Server thread/WARN]: 	at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
[20:49:28] [Server thread/WARN]: 	at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:222)
[20:49:28] [Server thread/WARN]: 	at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:184)
[20:49:28] [Server thread/WARN]: 	at ch.njol.skript.command.Commands.handleCommand(Commands.java:270)
[20:49:28] [Server thread/WARN]: 	at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:165)
[20:49:28] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor78.invoke(Unknown Source)
[20:49:28] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:49:28] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[20:49:28] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[20:49:28] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[20:49:28] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[20:49:28] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[20:49:28] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1154)
[20:49:28] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[20:49:28] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[20:49:28] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[20:49:28] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[20:49:28] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[20:49:28] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[20:49:28] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[20:49:28] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[20:49:28] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[20:49:28] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[20:49:28] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[20:49:28] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by TheBentoBox** [comment]
This issue appears to be caused by SkQuery (read the error messages in the log), and this fork doesn't support 1.8 anyways.
