### ISSUE TITLE
Metadata Value Errors

### ISSUE THREAD

**Issue by bertek41** [bensku/Skript#541]
Spigot 1.8.8 Java 8
```
command /hey:
	trigger:
		set metadata value "Type" of target-entity to "NPC"
		broadcast "hay"
```
Errors:
```
[22:04:11] [Server thread/INFO]: YasinSubasi [e55b2750-1d94-31e9-9778-354c7d0522e0]: /hey
[22:04:11] [Server thread/ERROR]: #!#! 
[22:04:11] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[22:04:11] [Server thread/ERROR]: #!#! 
[22:04:11] [Server thread/ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[22:04:11] [Server thread/ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[22:04:11] [Server thread/ERROR]: #!#! and check whether this error has already been reported.
[22:04:11] [Server thread/ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[22:04:11] [Server thread/ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[22:04:11] [Server thread/ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[22:04:11] [Server thread/ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[22:04:11] [Server thread/ERROR]: #!#! 
[22:04:11] [Server thread/ERROR]: #!#! Stack trace:
[22:04:11] [Server thread/ERROR]: #!#! ch.njol.skript.SkriptAPIException: UnparsedLiterals must be converted before use
[22:04:11] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.UnparsedLiteral.invalidAccessException(UnparsedLiteral.java:275)
[22:04:11] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.UnparsedLiteral.getSingle(UnparsedLiteral.java:305)
[22:04:11] [Server thread/ERROR]: #!#!     at com.mirre.random.lang.data.lists.ExpressionList.catchAnyNull(ExpressionList.java:56)
[22:04:11] [Server thread/ERROR]: #!#!     at com.mirre.random.lang.RandomExpression.change(RandomExpression.java:65)
[22:04:11] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:273)
[22:04:11] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:54)
[22:04:11] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:65)
[22:04:11] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93)
[22:04:11] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
[22:04:11] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:222)
[22:04:11] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:184)
[22:04:11] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:270)
[22:04:11] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:165)
[22:04:11] [Server thread/ERROR]: #!#!     at sun.reflect.GeneratedMethodAccessor132.invoke(Unknown Source)
[22:04:11] [Server thread/ERROR]: #!#!     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:04:11] [Server thread/ERROR]: #!#!     at java.lang.reflect.Method.invoke(Method.java:498)
[22:04:11] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[22:04:11] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[22:04:11] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[22:04:11] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[22:04:11] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1154)
[22:04:11] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[22:04:11] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[22:04:11] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[22:04:11] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[22:04:11] [Server thread/ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[22:04:11] [Server thread/ERROR]: #!#!     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[22:04:11] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[22:04:11] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[22:04:11] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[22:04:11] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[22:04:11] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[22:04:11] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)
[22:04:11] [Server thread/ERROR]: #!#! 
[22:04:11] [Server thread/ERROR]: #!#! Version Information:
[22:04:11] [Server thread/ERROR]: #!#!   Skript: 2.2-dev20
[22:04:11] [Server thread/ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[22:04:11] [Server thread/ERROR]: #!#!   Minecraft: 1.8.8
[22:04:11] [Server thread/ERROR]: #!#!   Java: 1.8.0_101 (Java HotSpot(TM) 64-Bit Server VM 25.101-b13)
[22:04:11] [Server thread/ERROR]: #!#!   OS: Linux amd64 4.4.26-nitradoV3-MC-1000-nH-dP-d-i
[22:04:11] [Server thread/ERROR]: #!#! 
[22:04:11] [Server thread/ERROR]: #!#! Running CraftBukkit: false
[22:04:11] [Server thread/ERROR]: #!#! 
[22:04:11] [Server thread/ERROR]: #!#! Current node: null
[22:04:11] [Server thread/ERROR]: #!#! Current item: set ExprMetadata to "NPC"
[22:04:11] [Server thread/ERROR]: #!#! 
[22:04:11] [Server thread/ERROR]: #!#! Thread: Server thread
[22:04:11] [Server thread/ERROR]: #!#! 
[22:04:11] [Server thread/ERROR]: #!#! End of Error.
[22:04:11] [Server thread/ERROR]: #!#! 
```

**Comment by TheBentoBox** [comment]
1. The metadata expression is not part of vanilla Skript, so this isn't really the place to report issues with it. Ask on the SkUnity forums or personally ask the developer of the addon which adds that syntax (speaking of, if you're using RandomSK for metadata, you should change over to Skellett)
2. This fork doesn't support any versions below 1.9, so any issues you have while using this fork on pre-1.9 versions are very unlikely to be helped.

**Comment by bertek41** [comment]
How can i use metadata with Skellett ?
