### ISSUE TITLE
skript erreur when I do /sk reload all

### ISSUE THREAD

**Issue by Wanders111** [bensku/Skript#585]
skript erreur when I do /sk reload all

`12:35:24 ERROR]: #!#! [Skript] Severe Error:
[12:35:24 ERROR]: #!#! Could not load elyring.sk
[12:35:24 ERROR]: #!#! 
[12:35:24 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[12:35:24 ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[12:35:24 ERROR]: #!#! and check whether this error has already been reported.
[12:35:24 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[12:35:24 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[12:35:24 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[12:35:24 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[12:35:24 ERROR]: #!#! 
[12:35:24 ERROR]: #!#! Stack trace:
[12:35:24 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for rgbcolor
[12:35:24 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:264)
[12:35:24 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1390)
[12:35:24 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1111)
[12:35:24 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1057)
[12:35:24 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1123)
[12:35:24 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1084)
[12:35:24 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:221)
[12:35:24 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[12:35:24 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:321)
[12:35:24 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:418)
[12:35:24 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1132)
[12:35:24 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1084)
[12:35:24 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:221)
[12:35:24 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:176)
[12:35:24 ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:60)
[12:35:24 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:754)
[12:35:24 ERROR]: #!#!     at ch.njol.skript.lang.Loop.<init>(Loop.java:68)
[12:35:24 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:790)
[12:35:24 ERROR]: #!#!     at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:56)
[12:35:24 ERROR]: #!#!     at ch.njol.skript.lang.Conditional.<init>(Conditional.java:46)
[12:35:24 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:840)
[12:35:24 ERROR]: #!#!     at ch.njol.skript.lang.Loop.<init>(Loop.java:68)
[12:35:24 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:790)
[12:35:24 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:513)
[12:35:24 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:247)
[12:35:24 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:201)
[12:35:24 ERROR]: #!#!     at ch.njol.skript.Skript.reload(Skript.java:686)
[12:35:24 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:141)
[12:35:24 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[12:35:24 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[12:35:24 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645)
[12:35:24 ERROR]: #!#!     at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1302)
[12:35:24 ERROR]: #!#!     at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1137)
[12:35:24 ERROR]: #!#!     at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[12:35:24 ERROR]: #!#!     at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[12:35:24 ERROR]: #!#!     at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[12:35:24 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[12:35:24 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[12:35:24 ERROR]: #!#!     at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45)
[12:35:24 ERROR]: #!#!     at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:716)
[12:35:24 ERROR]: #!#!     at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
[12:35:24 ERROR]: #!#!     at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655)
[12:35:24 ERROR]: #!#!     at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554)
[12:35:24 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)
[12:35:24 ERROR]: #!#! 
[12:35:24 ERROR]: #!#! Version Information:
[12:35:24 ERROR]: #!#!   Skript: 2.2-dev20
[12:35:24 ERROR]: #!#!   Bukkit: 1.9-SNAPSHOT
[12:35:24 ERROR]: #!#!   Minecraft: 1.9
[12:35:24 ERROR]: #!#!   Java: 1.8.0_91 (Java HotSpot(TM) 64-Bit Server VM 25.91-b14)
[12:35:24 ERROR]: #!#!   OS: Mac OS X x86_64 10.11.6
[12:35:24 ERROR]: #!#! 
[12:35:24 ERROR]: #!#! Running CraftBukkit: false
[12:35:24 ERROR]: #!#! 
[12:35:24 ERROR]: #!#! Current node: launch creeper firework colored red at {gagnant} timed 1 (elyring.sk, line 254)
[12:35:24 ERROR]: #!#! Current item: null
[12:35:24 ERROR]: #!#! 
[12:35:24 ERROR]: #!#! Thread: Server thread
[12:35:24 ERROR]: #!#! 
[12:35:24 ERROR]: #!#! End of Error.
`

**Comment by bensku** [comment]
Please try without any addons.

**Comment by TheBentoBox** [comment]
No response, closing for now
