### ISSUE TITLE
server error 

### ISSUE THREAD

**Issue by setrymagent** [bensku/Skript#591]
[13:52:06] [Server thread/ERROR]: #!#! Stack trace:
[13:52:06] [Server thread/ERROR]: #!#! java.lang.NullPointerException
[13:52:06] [Server thread/ERROR]: #!#!     at io.loyloy.fe.VaultHandler.currencyNameSingular(VaultHandler.java:55)
[13:52:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.hooks.economy.classes.Money.parse(Money.java:159)
[13:52:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.hooks.economy.classes.Money$1.parse(Money.java:57)
[13:52:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.hooks.economy.classes.Money$1.parse(Money.java:1)
[13:52:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:420)
[13:52:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Classes.parse(Classes.java:459)
[13:52:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:385)
[13:52:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:445)
[13:52:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:435)
[13:52:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1159)
[13:52:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1111)
[13:52:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:219)
[13:52:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:174)
[13:52:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Condition.parse(Condition.java:81)
[13:52:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:832)
[13:52:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:510)
[13:52:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:245)
[13:52:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:199)
[13:52:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript.reload(Skript.java:722)
[13:52:06] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:159)
[13:52:06] [Server thread/ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[13:52:06] [Server thread/ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[13:52:06] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650)
[13:52:06] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1354)
[13:52:06] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1189)
[13:52:06] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[13:52:06] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[13:52:06] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[13:52:06] [Server thread/ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[13:52:06] [Server thread/ERROR]: #!#!     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[13:52:06] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
[13:52:06] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747)
[13:52:06] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[13:52:06] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
[13:52:06] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
[13:52:06] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)

**Comment by bensku** [comment]
What exactly are you doing?

**Comment by TheBentoBox** [comment]
No response in 5 days, closing for now
