### ISSUE TITLE
It's not possible to loop players in radius of a location.

### ISSUE THREAD

**Issue by YoungLucasAA** [bensku/Skript#593]
[21:15:31 WARN]: [Skript] Task #54 for Skript v2.2-dev27 generated an exception
java.lang.NoSuchMethodError: org.bukkit.World.getNearbyEntities(Lorg/bukkit/Loca
tion;DDD)Ljava/util/Collection;
        at ch.njol.skript.expressions.ExprEntities.iterator(ExprEntities.java:19
4) ~[?:?]
        at ch.njol.skript.lang.Loop.walk(Loop.java:79) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[?:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:55) ~[?:?]
        at ch.njol.skript.events.EvtPeriodical.execute(EvtPeriodical.java:90) ~[
?:?]
        at ch.njol.skript.events.EvtPeriodical$1.run(EvtPeriodical.java:104) ~[?
:?]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java
:71) ~[spigot-att.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHea
rtbeat(CraftScheduler.java:350) [spigot-att.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:7
09) [spigot-att.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:3
16) [spigot-att.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:6
34) [spigot-att.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java
:537) [spigot-att.jar:git-Spigot-c3c767f-33d5de3]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
```
>The code is:
command setking:
	trigger:
		set {kingloc} to location of player
		loop all players in radius 4 of {kingloc}:
			add 1 to {king.disputando}
		broadcast "&a%{king.disputando}% jogadores estao disputando o King"
		wait 10 seconds 
		set {king.disputando} to 0
```
It returns as an internal error.

Spigot version: 1.8
Skript version:  v2.2-dev27

**Comment by Snow-Pyon** [comment]
This fork doesn't support any version lower the 1.9, it should work on Spigot 1.8.8 though. An update wouldn't be bad, I mean, why 1.8.

**Comment by YoungLucasAA** [comment]
If I updated to 1.9 or higher, a lot of the plugins I use wouldn't be compatible and it's literally a nightmare to find addons in other versions.
Anyways, with that told, I will try it out on 1.10 or something.

**Comment by bensku** [comment]
This comes from the fact that functionality required to get nearby entities came in 1.9. At least *this* method.
