### ISSUE TITLE
[Skript] Severe Error:

### ISSUE THREAD

**Issue by baku00** [bensku/Skript#601]
[19:28:04] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[19:28:04] [Server thread/ERROR]: #!#! Exception occurred in Skript's main command
[19:28:04] [Server thread/ERROR]: #!#! Used command: /sk reload staff
[19:28:04] [Server thread/ERROR]: #!#! 
[19:28:04] [Server thread/ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[19:28:04] [Server thread/ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[19:28:04] [Server thread/ERROR]: #!#! and check whether this error has already been reported.
[19:28:04] [Server thread/ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[19:28:04] [Server thread/ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[19:28:04] [Server thread/ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[19:28:04] [Server thread/ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[19:28:04] [Server thread/ERROR]: #!#! 
[19:28:04] [Server thread/ERROR]: #!#! Stack trace:
[19:28:04] [Server thread/ERROR]: #!#! java.lang.NullPointerException
[19:28:04] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.Functions.clearFunctions(Functions.java:269)
[19:28:04] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.removeTriggers(SkriptEventHandler.java:251)
[19:28:04] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.unloadScript_(ScriptLoader.java:712)
[19:28:04] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.unloadScript(ScriptLoader.java:705)
[19:28:04] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:183)
[19:28:04] [Server thread/ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[19:28:04] [Server thread/ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140)
[19:28:04] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646)
[19:28:04] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchServerCommand(CraftServer.java:632)
[19:28:04] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_10_R1.DedicatedServer.aL(DedicatedServer.java:438)
[19:28:04] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:401)
[19:28:04] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668)
[19:28:04] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567)
[19:28:04] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[19:28:04] [Server thread/ERROR]: #!#! 
[19:28:04] [Server thread/ERROR]: #!#! Version Information:
[19:28:04] [Server thread/ERROR]: #!#!   Skript: 2.2-dev26e
[19:28:04] [Server thread/ERROR]: #!#!   Bukkit: 1.10.2-R0.1-SNAPSHOT
[19:28:04] [Server thread/ERROR]: #!#!   Minecraft: 1.10.2
[19:28:04] [Server thread/ERROR]: #!#!   Java: 1.8.0_131 (Java HotSpot(TM) 64-Bit Server VM 25.131-b11)
[19:28:04] [Server thread/ERROR]: #!#!   OS: Windows 10 amd64 10.0
[19:28:04] [Server thread/ERROR]: #!#! 
[19:28:04] [Server thread/ERROR]: #!#! Running CraftBukkit: false
[19:28:04] [Server thread/ERROR]: #!#! 
[19:28:04] [Server thread/ERROR]: #!#! Current node: null
[19:28:04] [Server thread/ERROR]: #!#! Current item: null
[19:28:04] [Server thread/ERROR]: #!#! 
[19:28:04] [Server thread/ERROR]: #!#! Thread: Server thread
[19:28:04] [Server thread/ERROR]: #!#! 
[19:28:04] [Server thread/ERROR]: #!#! End of Error.
[19:28:04] [Server thread/ERROR]: #!#!

**Comment by bensku** [comment]
Not latest Skript version.
