### ISSUE TITLE
Player is Not online Server Error

### ISSUE THREAD

**Issue by TheMineWall** [bensku/Skript#605]
[10:47:36 ERROR]: #!#! [Skript] Severe Error:
[10:47:36 ERROR]: #!#!
[10:47:36 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[10:47:36 ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[10:47:36 ERROR]: #!#! and check whether this error has already been reported.
[10:47:36 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[10:47:36 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[10:47:36 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[10:47:36 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[10:47:36 ERROR]: #!#!
[10:47:36 ERROR]: #!#! Stack trace:
[10:47:36 ERROR]: #!#! java.lang.NullPointerException
[10:47:36 ERROR]: #!#!     at net.rayfall.eyesniper2.skRayFall.Scoreboard.EffSetScore.execute(EffSetScore.java:47)
[10:47:36 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[10:47:36 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[10:47:36 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[10:47:36 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
[10:47:36 ERROR]: #!#!     at ch.njol.skript.events.EvtPeriodical.execute(EvtPeriodical.java:90)
[10:47:36 ERROR]: #!#!     at ch.njol.skript.events.EvtPeriodical$1.run(EvtPeriodical.java:104)
[10:47:36 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[10:47:36 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[10:47:36 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
[10:47:36 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[10:47:36 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[10:47:36 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[10:47:36 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[10:47:36 ERROR]: #!#!
[10:47:36 ERROR]: #!#! Version Information:
[10:47:36 ERROR]: #!#!   Skript: 2.2-dev27
[10:47:36 ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[10:47:36 ERROR]: #!#!   Minecraft: 1.8.8
[10:47:36 ERROR]: #!#!   Java: 1.8.0_111 (Java HotSpot(TM) 64-Bit Server VM 25.111-b14)
[10:47:36 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[10:47:36 ERROR]: #!#!
[10:47:36 ERROR]: #!#! Running CraftBukkit: false
[10:47:36 ERROR]: #!#!
[10:47:36 ERROR]: #!#! Current node: null
[10:47:36 ERROR]: #!#! Current item: null
[10:47:36 ERROR]: #!#!
[10:47:36 ERROR]: #!#! Thread: Server thread
[10:47:36 ERROR]: #!#!
[10:47:36 ERROR]: #!#! End of Error.
[10:47:36 ERROR]: #!#!

see How to fix this!?

**Comment by TheBentoBox** [comment]
This is an skRayFall error, not vanilla Skript. Report it to the skRayFall dev (eyesniper2).

**Comment by TheMineWall** [comment]
thx
