### ISSUE TITLE
Error with java.lang.NoClassDefFoundError: org/bukkit/Particle in 1.8

### ISSUE THREAD

**Issue by Spartan9802** [bensku/Skript#613]
` Error occurred while enabling Skript v2.2-dev28 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/Particle
	at ch.njol.skript.util.VisualEffect$Type.<clinit>(VisualEffect.java:93) ~[?:?]
	at ch.njol.skript.util.VisualEffect.<clinit>(VisualEffect.java:262) ~[?:?]
	at ch.njol.skript.classes.data.SkriptClasses.<clinit>(SkriptClasses.java:889) ~[?:?]
	at ch.njol.skript.Skript.onEnable(Skript.java:277) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[Spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [Spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at com.massivecraft.massivelag.inject.event.MassiveLagPluginLoader.enablePlugin(MassiveLagPluginLoader.java:216) [MassiveLag.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [Spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [Spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [Spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [Spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [Spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [Spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [Spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [Spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.ClassNotFoundException: org.bukkit.Particle
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[Spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[Spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
	... 16 more`

**Comment by Pikachu920** [comment]
1.8 isn't supported, but I'm pretty sure the issue is that the particle enum didn't exist in 1.8 (at least I can't find it in my 1.8 javadocs) ![](https://i.imgur.com/628LBES.png)

**Comment by Spartan9802** [comment]
My all skript is disable :/

**Comment by TheBentoBox** [comment]
Then don't upgrade. This fork doesn't support 1.8 and never has, bensku only officially supports versions 1.9 and above. Understandably as well, since 1.8 is ancient and you really should update.

I'll mark as dev needed just this once, since I think bensku at least vaguely tries to keep compatibility with old versions and this sounds like a completely breaking change for pre-1.9 versions, but don't be surprised or complain if bensku just closes this.

**Comment by bensku** [comment]
Sorry, new Particle enum is needed for 1.11 particles. Can't support it and 1.8 easily, so... Here goes 1.8 support.

**Comment by Pikachu920** [comment]
Would it not be possible to just not load them on 1.8 and completely break particles for them. It's a stretch since 1.8 was never supported and it would potentially increase clutter of people reporting it as a bug, but would that even work?

**Comment by bensku** [comment]
Skript constructs its own enum which uses Spigot's particle enum. One can't just *not load* enum if the class is loaded.
