### ISSUE TITLE
 (Dev28c) Signature of function is null

### ISSUE THREAD

**Issue by Goetheus** [bensku/Skript#621]
Hi! I tried the last build of Skript, and I have errors with my functions.

Here is the complete error (this is always exactly the same).
```
[20:28:04 ERROR]: #!#! Stack trace:
[20:28:04 ERROR]: #!#! ch.njol.skript.SkriptAPIException: Signature of function is null when return type is asked!
[20:28:04 ERROR]: #!#!     at ch.njol.skript.lang.function.FunctionReference.getReturnType(FunctionReference.java:199)
[20:28:04 ERROR]: #!#!     at ch.njol.skript.lang.function.ExprFunctionCall.getReturnType(ExprFunctionCall.java:54)
[20:28:04 ERROR]: #!#!     at ch.njol.skript.effects.EffChange.init(EffChange.java:206)
[20:28:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:247)
[20:28:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:174)
[20:28:04 ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:59)
[20:28:04 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:659)
[20:28:04 ERROR]: #!#!     at ch.njol.skript.lang.function.ScriptFunction.<init>(ScriptFunction.java:51)
[20:28:04 ERROR]: #!#!     at ch.njol.skript.lang.function.Functions.loadFunction(Functions.java:129)
[20:28:04 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:422)
[20:28:04 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:243)
[20:28:04 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:200)
[20:28:04 ERROR]: #!#!     at ch.njol.skript.Skript$2.run(Skript.java:405)
[20:28:04 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
[20:28:04 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[20:28:04 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738)
[20:28:04 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[20:28:04 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
[20:28:04 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
[20:28:04 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[20:28:04 ERROR]: #!#!
[20:28:04 ERROR]: #!#! Version Information:
[20:28:04 ERROR]: #!#!   Skript: 2.2-dev28c
[20:28:04 ERROR]: #!#!   Bukkit: 1.11.2-R0.1-SNAPSHOT
[20:28:04 ERROR]: #!#!   Minecraft: 1.11.2
[20:28:04 ERROR]: #!#!   Java: 1.8.0_77 (Java HotSpot(TM) 64-Bit Server VM 25.77-b03)
[20:28:04 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[20:28:04 ERROR]: #!#!
[20:28:04 ERROR]: #!#! Running CraftBukkit: false
[20:28:04 ERROR]: #!#!
[20:28:04 ERROR]: #!#! Current node: set {_lvl} to GetNumber("stats", "level", "uuid", "%uuid of {_player}%") (AzAptitudes.sk, line 6)
[20:28:04 ERROR]: #!#! Current item: null
```

Thank you for your work.
And good luck!

**Comment by bensku** [comment]
Luck I'm going to need when trying to solve this :)

**Comment by Goetheus** [comment]
The error disappeared in the next dev! :)

**Comment by bensku** [comment]
Woohooo!
