### ISSUE TITLE
Skript enabling error

### ISSUE THREAD

**Issue by ZeTioZ** [bensku/Skript#622]
I got this in my console with the dev28c (I'm in 1.8.8)

`Error occurred while enabling Skript v2.2-dev28c (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/Particle
        at ch.njol.skript.util.VisualEffect$Type.<clinit>(VisualEffect.java:93) ~[?:?]
        at ch.njol.skript.util.VisualEffect.<clinit>(VisualEffect.java:262) ~[?:?]
        at ch.njol.skript.classes.data.SkriptClasses.<clinit>(SkriptClasses.java:889) ~[?:?]
        at ch.njol.skript.Skript.onEnable(Skript.java:277) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[paperspigot.jar:git-PaperSpigot-8b18730]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [paperspigot.jar:git-PaperSpigot-8b18730]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [paperspigot.jar:git-PaperSpigot-8b18730]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [paperspigot.jar:git-PaperSpigot-8b18730]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [paperspigot.jar:git-PaperSpigot-8b18730]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [paperspigot.jar:git-PaperSpigot-8b18730]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [paperspigot.jar:git-PaperSpigot-8b18730]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [paperspigot.jar:git-PaperSpigot-8b18730]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [paperspigot.jar:git-PaperSpigot-8b18730]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [paperspigot.jar:git-PaperSpigot-8b18730]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.ClassNotFoundException: org.bukkit.Particle
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[paperspigot.jar:git-PaperSpigot-8b18730]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[paperspigot.jar:git-PaperSpigot-8b18730]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
        ... 15 more`

**Comment by TheBentoBox** [comment]
1.8 is no longer supported by this fork as of dev28. Either downgrade to an earlier version (I'd recommend dev25) or use a different fork.

Closed #622.

**Comment by Pikachu920** [comment]
Should probably note that 1.8 was never supported, it just happened to work on it which it no longer happens to do

**Comment by TheBentoBox** [comment]
Yeah good point, I definitely didn't word that 100% correctly :')
