### ISSUE TITLE
Does not load properly

### ISSUE THREAD

**Issue by marcellmit2l** [bensku/Skript#632]
Skript does not load properly, all my skripts have errors after the update

`[03:22:17] [Server thread/INFO]: [Skript] Enabling Skript v2.2-dev28c
[03:22:17] [Server thread/INFO]: [Skript] Successfully generated the config, the example scripts and the aliases files.
[03:22:17] [Server thread/ERROR]: Error occurred while enabling Skript v2.2-dev28c (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/Particle
	at ch.njol.skript.util.VisualEffect$Type.<clinit>(VisualEffect.java:93) ~[?:?]
	at ch.njol.skript.util.VisualEffect.<clinit>(VisualEffect.java:262) ~[?:?]
	at ch.njol.skript.classes.data.SkriptClasses.<clinit>(SkriptClasses.java:889) ~[?:?]
	at ch.njol.skript.Skript.onEnable(Skript.java:277) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.ClassNotFoundException: org.bukkit.Particle
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_91]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_91]
	... 15 more`

**Comment by Snow-Pyon** [comment]
the versions from the dev28 and up will not work unless someone does a pull request to make this fork compatible with 1.8.8 again, otherwise it'll not work due to an Enum which isn't available on that version of Spigot.

**Comment by TheBentoBox** [comment]
This fork is no longer compatible with versions of Minecraft older than 1.8 as of dev28. Either downgrade to an earlier version (I'd recommend dev25) or upgrade your server.

Closed #632.
