### ISSUE TITLE
error when load Skript dev28c on spigot 1.8.8

### ISSUE THREAD

**Issue by tuanjr** [bensku/Skript#637]
```
[10:40:00 INFO]: [Skript] Enabling Skript v2.2-dev28c
[10:40:00 ERROR]: Error occurred while enabling Skript v2.2-dev28c (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/Particle
        at ch.njol.skript.util.VisualEffect$Type.<clinit>(VisualEffect.java:93) ~[?:?]
        at ch.njol.skript.util.VisualEffect.<clinit>(VisualEffect.java:262) ~[?:?]
        at ch.njol.skript.classes.data.SkriptClasses.<clinit>(SkriptClasses.java:889) ~[?:?]
        at ch.njol.skript.Skript.onEnable(Skript.java:277) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.ClassNotFoundException: org.bukkit.Particle
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
        ... 15 more
```

**Comment by TheBentoBox** [comment]
Goodness, how many of these are we going to get. 

Check other issue reports. This fork is no longer compatible with versions older than 1.9 as of dev28. Either downgrade to an earlier version (probably dev25), use a different fork, or upgrade your server (what I recommend, you'll only get disappointed like this more and more the longer you stay on an ancient Skript version). 

Closed #637.
