### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by Chriskraft9** [bensku/Skript#640]
[11:59:10] [Server thread/ERROR]: #!#! 
[11:59:10] [Server thread/ERROR]: #!#! Skript: 2.2-dev28c
[11:59:10] [Server thread/ERROR]: #!#! Minecraft: 1.11.2
[11:59:10] [Server thread/ERROR]: #!#! OS: Linux amd64 3.16.0-4-amd64
[11:59:10] [Server thread/ERROR]: #!#! Running CraftBukkit: false
[11:59:10] [Server thread/ERROR]: #!#! Current node: null
[11:59:10] [Server thread/ERROR]: #!#! 
[11:59:10] [Server thread/ERROR]: #!#! 
[11:59:10] [Server thread/ERROR]: #!#! 
[11:59:10] [Server thread/ERROR]: #!#! 
[11:59:10] [Server thread/ERROR]: #!#! 
[11:59:10] [Server thread/ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[11:59:10] [Server thread/ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[11:59:10] [Server thread/ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[11:59:10] [Server thread/ERROR]: #!#! 
[11:59:10] [Server thread/ERROR]: #!#! java.lang.NullPointerException
[11:59:10] [Server thread/ERROR]: #!#! at ch.njol.skript.lang.Effect.run(Effect.java:52)
[11:59:10] [Server thread/ERROR]: #!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[11:59:10] [Server thread/ERROR]: #!#! at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
[11:59:10] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738)
[11:59:10] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
[11:59:10] [Server thread/ERROR]: #!#! at java.lang.Thread.run(Thread.java:748)
[11:59:10] [Server thread/ERROR]: #!#! Version Information:
[11:59:10] [Server thread/ERROR]: #!#! Bukkit: 1.11.2-R0.1-SNAPSHOT
[11:59:10] [Server thread/ERROR]: #!#! Java: 1.8.0_131 (Java HotSpot(TM) 64-Bit Server VM 25.131-b11)
[11:59:10] [Server thread/ERROR]: #!#! 
[11:59:10] [Server thread/ERROR]: #!#! 
[11:59:10] [Server thread/ERROR]: #!#! Current item: null
[11:59:10] [Server thread/ERROR]: #!#! Thread: Server thread
[11:59:10] [Server thread/ERROR]: #!#! End of Error.
[11:59:10] [Server thread/ERROR]: #!#!

**Comment by TheBentoBox** [comment]
Can you give any more information about what code causes this or anything? Does this happen without addons too?

**Comment by TheBentoBox** [comment]
No response, closing.
