### ISSUE TITLE
error :C

### ISSUE THREAD

**Issue by hypersmc** [bensku/Skript#642]
[19:11:18 ERROR]: #!#!
[19:11:18 ERROR]: #!#! [Skript] Severe Error:
[19:11:18 ERROR]: #!#! An error happened when trying to enably resolving offline players, so the feature has been turned off. Please report this at https://github.com/bensku/Skript/issues/237
[19:11:18 ERROR]: #!#!
[19:11:18 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[19:11:18 ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[19:11:18 ERROR]: #!#! and check whether this error has already been reported.
[19:11:18 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[19:11:18 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[19:11:18 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[19:11:18 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[19:11:18 ERROR]: #!#!
[19:11:18 ERROR]: #!#! Stack trace:
[19:11:18 ERROR]: #!#! java.lang.NullPointerException: null offline player resolve queue
[19:11:18 ERROR]: #!#!     at ch.njol.skript.bukkitutil.UnresolvedOfflinePlayer$1.run(UnresolvedOfflinePlayer.java:59)
[19:11:18 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[19:11:18 ERROR]: #!#!
[19:11:18 ERROR]: #!#! Version Information:
[19:11:18 ERROR]: #!#!   Skript: 2.2-dev26e
[19:11:18 ERROR]: #!#!   Bukkit: 1.11.2-R0.1-SNAPSHOT
[19:11:18 ERROR]: #!#!   Minecraft: 1.11.2
[19:11:18 ERROR]: #!#!   Java: 1.8.0_121 (Java HotSpot(TM) 64-Bit Server VM 25.121-b13)
[19:11:18 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[19:11:18 ERROR]: #!#!
[19:11:18 ERROR]: #!#! Running CraftBukkit: false
[19:11:18 ERROR]: #!#!
[19:11:18 ERROR]: #!#! Current node: null
[19:11:18 ERROR]: #!#! Current item: null
[19:11:18 ERROR]: #!#!
[19:11:18 ERROR]: #!#! Thread: Skript offline player resolver thread (fetches UUIDs from the minecraft servers)
[19:11:18 ERROR]: #!#!
[19:11:18 ERROR]: #!#! End of Error.
[19:11:18 ERROR]: #!#!
And yes it happens with no addons :|

**Comment by Classic36MC** [comment]
Try dev26f, dev27 or any of the dev28 builds and see if that resolves it.

**Comment by bensku** [comment]
Duplicate and old Skript version at time of report.
