### ISSUE TITLE
1.8.8 Startup Error

### ISSUE THREAD

**Issue by Mxra** [bensku/Skript#643]
`[23:59:42 INFO]: [Skript] Enabling Skript v2.2-dev28c
[23:59:43 ERROR]: Error occurred while enabling Skript v2.2-dev28c (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/Particle
        at ch.njol.skript.util.VisualEffect$Type.<clinit>(VisualEffect.java:93) ~[?:?]
        at ch.njol.skript.util.VisualEffect.<clinit>(VisualEffect.java:262) ~[?:?]
        at ch.njol.skript.classes.data.SkriptClasses.<clinit>(SkriptClasses.java:889) ~[?:?]
        at ch.njol.skript.Skript.onEnable(Skript.java:277) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[PaperSpigot.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [PaperSpigot.jar:git-PaperSpigot-"8b18730"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.ClassNotFoundException: org.bukkit.Particle
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[PaperSpigot.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[PaperSpigot.jar:git-PaperSpigot-"8b18730"]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
        ... 15 more
[23:59:43 INFO]: [Skript] Disabling Skript v2.2-dev28c`

**Comment by Snow-Pyon** [comment]
Do we have to see this all the time? Please look at other issues and see if one of them is similar to yours, it's annoying to see the same issue over and over.

Said that, I'll tell you what happened: Skript dev28 and up doesn't work at any version lower than the 1.8.8 because an Enum (the Particle one) which was added in later versions. It was never supported so it will not be fixed unless someone does a PR to make 1.8.8 compatible again **but 1.8.8 and lower versions aren't supported by Skript**.

**Comment by Syst3ms** [comment]
@Snow-Pyon We should make an announcement on skUnity

**Comment by Mxra** [comment]
I was not aware an addon was broken, thought it had something to do with the update itself.

**Comment by Syst3ms** [comment]
@Mxra Uhh... It's Skript that broke along with the update in 1.8

**Comment by TheBentoBox** [comment]
As has been said, this fork isn't compatible with 1.8.8 or below anymore. Save yourself more future headaches and update your server, 1.8 came out literally almost 3 years ago. It's too old to justify using anymore and way too old to expect support for, you're lucky so many people still do (honestly I'd intentionally not support it as a developer to get people to update finally). 

Closed #643.

**Comment by Mxra** [comment]
Alright, the only reason I haven't updated is due to the combat. I'll see what I can do as an alternative.
