### ISSUE TITLE
Unknown type 'number'

### ISSUE THREAD

**Issue by Gulot13** [bensku/Skript#658]
![image](https://user-images.githubusercontent.com/29377444/27037963-da67359e-4f89-11e7-8e74-34e75fb29e60.png)

Error on startup

[15:36:48 ERROR]: [Skript] Could not hook into Vault. This can happen if Skript doesn't support the installed version of Vault
[15:36:48 WARN]: [Skript] Task #6 for Skript v2.2-dev29 generated an exception
java.lang.NullPointerException
        at java.lang.Class.isAssignableFrom(Native Method) ~[?:1.8.0_121]
        at ch.njol.skript.registrations.Classes.sortClassInfos(Classes.java:157) ~[?:?]
        at ch.njol.skript.registrations.Classes.onRegistrationsStop(Classes.java:107) ~[?:?]
        at ch.njol.skript.Skript.stopAcceptingRegistrations(Skript.java:916) ~[?:?]
        at ch.njol.skript.Skript.access$2(Skript.java:911) ~[?:?]
        at ch.njol.skript.Skript$2.run(Skript.java:346) ~[?:?]
        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:734) [spigot1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]

**Comment by bensku** [comment]
Do you use addons and what ones do you use?

**Comment by Gulot13** [comment]
Umbaska, i delete it and my problems is resolve :D
