### ISSUE TITLE
Skript Function Error

### ISSUE THREAD

**Issue by nutella25** [bensku/Skript#662]
```
[23:18:13 ERROR]: #!#! Stack trace:
[23:18:13 ERROR]: #!#! ch.njol.skript.SkriptAPIException: Signature of function is null when return type is asked!
[23:18:13 ERROR]: #!#!     at ch.njol.skript.lang.function.FunctionReference.getReturnType(FunctionReference.java:199)
[23:18:13 ERROR]: #!#!     at ch.njol.skript.lang.function.ExprFunctionCall.getReturnType(ExprFunctionCall.java:54)
[23:18:13 ERROR]: #!#!     at ch.njol.skript.effects.EffChange.init(EffChange.java:206)
[23:18:13 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:247)
[23:18:13 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:174)
[23:18:13 ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:59)
[23:18:13 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:659)
[23:18:13 ERROR]: #!#!     at ch.njol.skript.lang.Loop.<init>(Loop.java:66)
[23:18:13 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:695)
[23:18:13 ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:465)
[23:18:13 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:409)
[23:18:13 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:243)
[23:18:13 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:267)
[23:18:13 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:187)
[23:18:13 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[23:18:13 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[23:18:13 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:644)
[23:18:13 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:630)
[23:18:13 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:443)
[23:18:13 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[23:18:13 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
[23:18:13 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
[23:18:13 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)
[23:18:13 ERROR]: #!#!
[23:18:13 ERROR]: #!#! Version Information:
[23:18:13 ERROR]: #!#!   Skript: 2.2-dev29
[23:18:13 ERROR]: #!#!   Bukkit: 1.12-R0.1-SNAPSHOT
[23:18:13 ERROR]: #!#!   Minecraft: 1.12
[23:18:13 ERROR]: #!#!   Java: 1.8.0_72 (Java HotSpot(TM) 64-Bit Server VM 25.72-b15)
[23:18:13 ERROR]: #!#!   OS: Linux amd64 3.16.0-4-amd64
[23:18:13 ERROR]: #!#!
[23:18:13 ERROR]: #!#! Running CraftBukkit: false
[23:18:13 ERROR]: #!#!
[23:18:13 ERROR]: #!#! Current node: set {_nf} to numformat("%{_xx::2}%") (motd.sk, line 87)
[23:18:13 ERROR]: #!#! Current item: null
[23:18:13 ERROR]: #!#!
[23:18:13 ERROR]: #!#! Thread: Server thread
[23:18:13 ERROR]: #!#!
[23:18:13 ERROR]: #!#! End of Error.
[23:18:13 ERROR]: #!#!
```

This one has a function error, I asked to skUnity they told me to get the function into the same file as I executed but still got an error on console.

**Comment by nutella25** [comment]
```
function numformat(txt: text) :: text:
	set {_n} to the length of {_txt}
	if {_n} < 3:
		return {_txt}
	set {_s} to {_n}-2
	set {_lim} to 0
	set {_hasil} to "x"
	while {_s} is greater than 0:
		set {_m} to the substring of {_txt} from {_s} to {_n}

		if {_s} > 0:
			if "%{_hasil}%" is not "x": 
				set {_hasil} to "%{_m}%,%{_hasil}%"
			else:
				set {_hasil} to "%{_m}%"

		set {_n} to {_s}-1
		subtract 3 from {_s}
		add 1 to {_lim}
		if {_lim} is greater than 52:
			message "&4infinite loop prevention![numberformat.sk]" to "aloata" parsed as player
			message "&4infinite loop prevention![numberformat.sk]" to "ivanst321" parsed as player
			stop
	if {_s} = -1:
		set {_m} to the substring of {_txt} from 1 to {_s}-(({_s})*2)
		set {_hasil} to "%{_m}%,%{_hasil}%"
	if {_s} = 0:
		set {_m} to the substring of {_txt} from 1 to 2
		set {_hasil} to "%{_m}%,%{_hasil}%"
	return {_hasil}
```
This is the function, it has a parse also in it.

**Comment by TheBentoBox** [comment]
You're calling the function before it's loaded. You need to load the script that the function is in above any script that uses it.

**Comment by bensku** [comment]
Actually, that should not be necessary. And usually, it is not. This has been reported before, though.

**Comment by TheBentoBox** [comment]
I definitely had this issue on my server the other day, accidentally called a function in a script before it in load order and the chain reaction caused something like 20-30 scripts to not load properly 😂
