### ISSUE TITLE
Error...?

### ISSUE THREAD

**Issue by Sam1370** [bensku/Skript#664]
Skript Version: Skript 2.2 (dev20c)
Minecraft Version: 1.11
Addons: SkQuery Lime 3.5.7, TuSKe 1.7.7.
Here's the code for my Skript script. When I right click a compass it outputs the error.
```
on right click:
	player's world is "world":
		if player is holding compass:
			wait 1 tick
			open virtual dispenser inventory named "&a&nSelector" to player
			format gui slot 4 of player with grass block named "&aSurvival" with lore "&9Play vanilla survival" to close then run function doSomething()
function doSomething():
    broadcast "And it did"
```
Here's the error.
```
13.06 22:02:39 [Server] ERROR #!#! 
13.06 22:02:39 [Server] ERROR #!#! [Skript] Severe Error:
13.06 22:02:39 [Server] ERROR #!#! 
13.06 22:02:39 [Server] ERROR #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
13.06 22:02:39 [Server] ERROR #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
13.06 22:02:39 [Server] ERROR #!#! and check whether this error has already been reported.
13.06 22:02:39 [Server] ERROR #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
13.06 22:02:39 [Server] ERROR #!#! and describe what you did before it happened and/or what you think caused the error.
13.06 22:02:39 [Server] ERROR #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
13.06 22:02:39 [Server] ERROR #!#! By following this guide fixing the error should be easy and done fast.
13.06 22:02:39 [Server] ERROR #!#! 
13.06 22:02:39 [Server] ERROR #!#! Stack trace:
13.06 22:02:39 [Server] ERROR #!#! java.lang.ArrayIndexOutOfBoundsException: 0
13.06 22:02:39 [Server] ERROR #!#!     at ch.njol.skript.lang.function.Function.getParameter(Function.java:55)
13.06 22:02:39 [Server] ERROR #!#!     at me.tuke.sktuke.util.EvalFunction.getParemetersValues(EvalFunction.java:85)
13.06 22:02:39 [Server] ERROR #!#!     at me.tuke.sktuke.sections.gui.EffFormatGUI.execute(EffFormatGUI.java:141)
13.06 22:02:39 [Server] ERROR #!#!     at me.tuke.sktuke.util.EffectSection.check(EffectSection.java:57)
13.06 22:02:39 [Server] ERROR #!#!     at ch.njol.skript.lang.Condition.run(Condition.java:56)
13.06 22:02:39 [Server] ERROR #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
13.06 22:02:39 [Server] ERROR #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
13.06 22:02:39 [Server] ERROR #!#!     at ch.njol.skript.effects.Delay$1.run(Delay.java:94)
13.06 22:02:39 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
13.06 22:02:39 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
13.06 22:02:39 [Server] ERROR #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730)
13.06 22:02:39 [Server] ERROR #!#!     at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
13.06 22:02:39 [Server] ERROR #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675)
13.06 22:02:39 [Server] ERROR #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574)
13.06 22:02:39 [Server] ERROR #!#!     at java.lang.Thread.run(Thread.java:745)
13.06 22:02:39 [Server] ERROR #!#! 
13.06 22:02:39 [Server] ERROR #!#! Version Information:
13.06 22:02:41 [Multicraft] Skipped 15 lines due to rate limit (30/s)
13.06 22:02:41 [Server] ERROR #!#! 
13.06 22:02:41 [Server] ERROR #!#! [Skript] Severe Error:
13.06 22:02:41 [Server] ERROR #!#! 
13.06 22:02:41 [Server] ERROR #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
13.06 22:02:41 [Server] ERROR #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
13.06 22:02:41 [Server] ERROR #!#! and check whether this error has already been reported.
13.06 22:02:41 [Server] ERROR #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
13.06 22:02:41 [Server] ERROR #!#! and describe what you did before it happened and/or what you think caused the error.
13.06 22:02:41 [Server] ERROR #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
13.06 22:02:41 [Server] ERROR #!#! By following this guide fixing the error should be easy and done fast.
13.06 22:02:41 [Server] ERROR #!#! 
13.06 22:02:41 [Server] ERROR #!#! Stack trace:
13.06 22:02:41 [Server] ERROR #!#! java.lang.ArrayIndexOutOfBoundsException: 0
13.06 22:02:41 [Server] ERROR #!#!     at ch.njol.skript.lang.function.Function.getParameter(Function.java:55)
13.06 22:02:41 [Server] ERROR #!#!     at me.tuke.sktuke.util.EvalFunction.getParemetersValues(EvalFunction.java:85)
13.06 22:02:41 [Server] ERROR #!#!     at me.tuke.sktuke.util.EvalFunction.getParemetersValues(EvalFunction.java:73)
13.06 22:02:41 [Server] ERROR #!#!     at me.tuke.sktuke.sections.gui.EffFormatGUI.execute(EffFormatGUI.java:141)
13.06 22:02:41 [Server] ERROR #!#!     at me.tuke.sktuke.util.EffectSection.check(EffectSection.java:57)
13.06 22:02:41 [Server] ERROR #!#!     at ch.njol.skript.lang.Condition.run(Condition.java:56)
13.06 22:02:41 [Server] ERROR #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
13.06 22:02:41 [Server] ERROR #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
13.06 22:02:41 [Server] ERROR #!#!     at ch.njol.skript.effects.Delay$1.run(Delay.java:94)
13.06 22:02:41 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
13.06 22:02:41 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
13.06 22:02:41 [Server] ERROR #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730)
13.06 22:02:41 [Server] ERROR #!#!     at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
13.06 22:02:41 [Server] ERROR #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675)
13.06 22:02:41 [Server] ERROR #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574)
13.06 22:02:41 [Server] ERROR #!#!     at java.lang.Thread.run(Thread.java:745)
13.06 22:02:41 [Server] ERROR #!#! 
13.06 22:02:45 [Multicraft] Skipped 16 lines due to rate limit (30/s)
13.06 22:02:45 [Server] INFO CONSOLE issued server command: /list 
13.06 22:02:45 [Server] INFO default: Sam1370
13.06 22:02:46 [Server] INFO Sam1370 issued server command: /clear
13.06 22:02:46 [Server] INFO Sam1370 was denied access to command.
13.06 22:03:16 [Server] INFO CONSOLE issued server command: /list 
13.06 22:03:16 [Server] INFO default: Sam1370
13.06 22:03:30 [Server] ERROR #!#! 
13.06 22:03:30 [Server] ERROR #!#! [Skript] Severe Error:
13.06 22:03:30 [Server] ERROR #!#! 
13.06 22:03:30 [Server] ERROR #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
13.06 22:03:30 [Server] ERROR #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
13.06 22:03:30 [Server] ERROR #!#! and check whether this error has already been reported.
13.06 22:03:30 [Server] ERROR #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
13.06 22:03:30 [Server] ERROR #!#! and describe what you did before it happened and/or what you think caused the error.
13.06 22:03:30 [Server] ERROR #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
13.06 22:03:30 [Server] ERROR #!#! By following this guide fixing the error should be easy and done fast.
13.06 22:03:30 [Server] ERROR #!#! 
13.06 22:03:30 [Server] ERROR #!#! Stack trace:
13.06 22:03:30 [Server] ERROR #!#! java.lang.ArrayIndexOutOfBoundsException: 0
13.06 22:03:30 [Server] ERROR #!#!     at ch.njol.skript.lang.function.Function.getParameter(Function.java:55)
13.06 22:03:30 [Server] ERROR #!#!     at me.tuke.sktuke.util.EvalFunction.getParemetersValues(EvalFunction.java:85)
13.06 22:03:30 [Server] ERROR #!#!     at me.tuke.sktuke.util.EvalFunction.getParemetersValues(EvalFunction.java:73)
13.06 22:03:30 [Server] ERROR #!#!     at me.tuke.sktuke.sections.gui.EffFormatGUI.execute(EffFormatGUI.java:141)
13.06 22:03:30 [Server] ERROR #!#!     at me.tuke.sktuke.util.EffectSection.check(EffectSection.java:57)
13.06 22:03:30 [Server] ERROR #!#!     at ch.njol.skript.lang.Condition.run(Condition.java:56)
13.06 22:03:30 [Server] ERROR #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
13.06 22:03:30 [Server] ERROR #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
13.06 22:03:30 [Server] ERROR #!#!     at ch.njol.skript.effects.Delay$1.run(Delay.java:94)
13.06 22:03:30 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
13.06 22:03:30 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
13.06 22:03:30 [Server] ERROR #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730)
13.06 22:03:30 [Server] ERROR #!#!     at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
13.06 22:03:30 [Server] ERROR #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675)
13.06 22:03:30 [Server] ERROR #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574)
13.06 22:03:30 [Server] ERROR #!#!     at java.lang.Thread.run(Thread.java:745)
13.06 22:03:30 [Server] ERROR #!#! 
```
I'm

**Comment by TheBentoBox** [comment]
Well for one this is a TuSKe issue, not a Skript issue; addon issues don't get reported here, you should ask for help on the skUnity forums. Additionally, you're using a fairly out of date Skript version. Don't get me wrong, dev20 was really nice and solid, but it's old and a lot of issues with it may have been fixed in newer versions. I'd recommend dev25, or dev29 if you don't mind your scripts taking longer to load (there's some parsing issues currently, but it's the newest build and it's pretty stable otherwise).

**Comment by Sam1370** [comment]
Just checked, my Skript version is dev29, sorry about the typo :P

**Comment by TheBentoBox** [comment]
Ah alright, that's good at least. And yeah, it's understandable why you'd report here. Perhaps the error message should be made more specific to let people know that addon issues don't get reported here.

**Comment by bensku** [comment]
TODO improve console message to be more helpful and try to sniff about potential addons :)

**Comment by Syst3ms** [comment]
@bensku Reflection#getCallerClass might help in this case

**Comment by bensku** [comment]
Sniffing would mean more like looking through installed plugins and seeing if they have Skript as dependency. Of course direct stack walking has its use cases, but in many cases it will not help.
