### ISSUE TITLE
first character of string variable list not working?

### ISSUE THREAD

**Issue by TheLimeGlass** [bensku/Skript#676]
```
[Server] ERROR #!#! 
[Server] ERROR #!#! Stack trace: 
[Server] ERROR #!#! ch.njol.skript.SkriptAPIException: Call to getSingle() on a non-single expression 
[Server] ERROR #!#! at ch.njol.skript.lang.util.SimpleExpression.getSingle(SimpleExpression.java:67) 
[Server] ERROR #!#! at ch.njol.skript.expressions.ExprSubstring.get(ExprSubstring.java:73) 
[Server] ERROR #!#! at ch.njol.skript.expressions.ExprSubstring.get(ExprSubstring.java:1) 
[Server] ERROR #!#! at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:164) 
[Server] ERROR #!#! at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:159) 
[Server] ERROR #!#! at ch.njol.skript.conditions.CondCompare.check(CondCompare.java:260) 
[Server] ERROR #!#! at ch.njol.skript.lang.Condition.run(Condition.java:58) 
[Server] ERROR #!#! at ch.njol.skript.lang.Conditional.walk(Conditional.java:53) 
[Server] ERROR #!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93) 
[Server] ERROR #!#! at ch.njol.skript.lang.Trigger.execute(Trigger.java:53) 
[Server] ERROR #!#! at ch.njol.skript.events.EvtChat$1.execute(EvtChat.java:68) 
[Server] ERROR #!#! at ch.njol.skript.events.EvtChat$1$1.call(EvtChat.java:87) 
[Server] ERROR #!#! at ch.njol.skript.events.EvtChat$1$1.call(EvtChat.java:1) 
[Server] ERROR #!#! at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftFuture.run(CraftFuture.java:89) 
[Server] ERROR #!#! at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) 
[Server] ERROR #!#! at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) 
[Server] ERROR #!#! at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
```
From
```
on chat:
	cancel event
	if first character of uncoloured message split by "" is "@":
		message "%message% TEST"
```
If I replace the first character with first element it doesn't return properly. I can fix it by spliting it up. I just found this error.

I think this is more of a suggestion to make it a test a list. Or is there another syntax to get the first element of a list?

**Comment by Syst3ms** [comment]
```
first element of %objects%
```

**Comment by TheLimeGlass** [comment]
"If I replace the first character with first element it doesn't return properly"

It can't detect the symbol regardless if I use that.

**Comment by Syst3ms** [comment]
It's (sorta) like trying to do : 
```
Math.pow(new int[]{1, 2})
```
in Java. It's logic, but the compiler can't guess that for you.

**Comment by TheLimeGlass** [comment]
**Edit:** I just remembered I can just use Substring.
```
if first character of uncoloured message is "@":
```
But the bug still persists.

I think Skript is still returning it as a list or it returns as `@ ` with a space.

**Comment by bensku** [comment]
Your original code is invalid, since split *does* return a list. First character, however, takes a string and will not work with a list. The exact code in your last message is working for me; please try without addons.

**Comment by TheBentoBox** [comment]
No response, closing.
