### ISSUE TITLE
Script error 1.10

### ISSUE THREAD

**Issue by SzlugPL** [bensku/Skript#682]
I have a problem with the plugin skript.jar. I do not know why this does not work for me why? Any advice?

sk reload all
[21:47:12 INFO]: [Skript] Reloading the config and all scripts...
[21:47:12 ERROR]: There doesn't exist a material with id 218! (aliases-english.sk, line 322: observer¦s = 218')
[21:47:12 ERROR]: There doesn't exist a material with id 219! (aliases-english.sk, line 324: white(_| )shulker(_| )(box|chest)¦s = 219')
[21:47:12 ERROR]: There doesn't exist a material with id 220! (aliases-english.sk, line 325: orange(_| )shulker(_| )(box|chest)¦s = 220')
[21:47:12 ERROR]: There doesn't exist a material with id 221! (aliases-english.sk, line 326: magenta(_| )shulker(_| )(box|chest)¦s = 221')
[21:47:12 ERROR]: There doesn't exist a material with id 222! (aliases-english.sk, line 327: light(_| )blue(_| )shulker(_| )(box|chest)¦s = 222')
[21:47:12 ERROR]: There doesn't exist a material with id 223! (aliases-english.sk, line 328: yellow(_| )shulker(_| )(box|chest)¦s = 223')
[21:47:12 ERROR]: There doesn't exist a material with id 224! (aliases-english.sk, line 329: (lime|light(_| )green)(_| )shulker(_| )(box|chest)¦s = 224')
[21:47:12 ERROR]: There doesn't exist a material with id 225! (aliases-english.sk, line 330: pink(_| )shulker(_| )(box|chest)¦s = 225')
[21:47:12 ERROR]: There doesn't exist a material with id 226! (aliases-english.sk, line 331: gray(_| )shulker(_| )(box|chest)¦s = 226')
[21:47:12 ERROR]: There doesn't exist a material with id 227! (aliases-english.sk, line 332: light(_| )gray(_| )shulker(_| )(box|chest)¦s = 227')
[21:47:12 ERROR]: There doesn't exist a material with id 228! (aliases-english.sk, line 333: cyan(_| )shulker(_| )(box|chest)¦s = 228')
[21:47:12 ERROR]: There doesn't exist a material with id 229! (aliases-english.sk, line 334: [purple(_| )]shulker(_| )(box|chest)¦s = 229')
[21:47:12 ERROR]: There doesn't exist a material with id 230! (aliases-english.sk, line 335: blue(_| )shulker(_| )(box|chest)¦s = 230')
[21:47:12 ERROR]: There doesn't exist a material with id 231! (aliases-english.sk, line 336: brown(_| )shulker(_| )(box|chest)¦s = 231')
[21:47:12 ERROR]: There doesn't exist a material with id 232! (aliases-english.sk, line 337: green(_| )shulker(_| )(box|chest)¦s = 232')
[21:47:12 ERROR]: There doesn't exist a material with id 233! (aliases-english.sk, line 338: red(_| )shulker(_| )(box|chest)¦s = 233')
[21:47:12 ERROR]: There doesn't exist a material with id 234! (aliases-english.sk, line 339: black(_| )shulker(_| )(box|chest)¦s = 234')
[21:47:12 ERROR]: There doesn't exist a material with id 219! (aliases-english.sk, line 340: [<any>](_| )shulker(_| )(box|chest)¦s = 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234')
[21:47:12 ERROR]: There doesn't exist a material with id 449! (aliases-english.sk, line 343: totem(_| )of(_| )Undying¦s = 449')
[21:47:12 ERROR]: There doesn't exist a material with id 450! (aliases-english.sk, line 344: shulker(_| )shell¦s = 450')
[21:47:12 ERROR]: There doesn't exist a material with id 452! (aliases-english.sk, line 345: iron(_| )nugget¦s = 452')
[21:47:13 INFO]: Loaded a total of 20298 english aliases
[21:47:13 WARN]: There are no aliases defined for the following ids: 438, 441
[21:47:13 ERROR]: #!#!
[21:47:13 ERROR]: #!#! [Skript] Severe Error:
[21:47:13 ERROR]: #!#! Could not load zadaniaxD.sk
[21:47:13 ERROR]: #!#!
[21:47:13 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[21:47:13 ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[21:47:13 ERROR]: #!#! and check whether this error has already been reported.
[21:47:13 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[21:47:13 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[21:47:13 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[21:47:13 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[21:47:13 ERROR]: #!#!
[21:47:13 ERROR]: #!#! Stack trace:
[21:47:13 ERROR]: #!#! java.lang.IllegalStateException: Cannot use classinfos until registration is over
[21:47:13 ERROR]: #!#!at ch.njol.skript.registrations.Classes.checkAllowClassInfoInteraction(Classes.java:240)
[21:47:13 ERROR]: #!#!at ch.njol.skript.registrations.Classes.getClassInfos(Classes.java:245)
[21:47:13 ERROR]: #!#!at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:414)
[21:47:13 ERROR]: #!#!at ch.njol.skript.registrations.Classes.parse(Classes.java:449)
[21:47:13 ERROR]: #!#!at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:385)
[21:47:13 ERROR]: #!#!at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:445)
[21:47:13 ERROR]: #!#!at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1159)
[21:47:13 ERROR]: #!#!at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:219)
[21:47:13 ERROR]: #!#!at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:174)
[21:47:13 ERROR]: #!#!at ch.njol.skript.lang.Condition.parse(Condition.java:81)
[21:47:13 ERROR]: #!#!at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:738)
[21:47:13 ERROR]: #!#!at ch.njol.skript.command.Commands.loadCommand(Commands.java:465)
[21:47:13 ERROR]: #!#!at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:409)
[21:47:13 ERROR]: #!#!at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:243)
[21:47:13 ERROR]: #!#!at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:200)
[21:47:13 ERROR]: #!#!at ch.njol.skript.Skript.reload(Skript.java:722)
[21:47:13 ERROR]: #!#!at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:161)
[21:47:13 ERROR]: #!#!at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[21:47:13 ERROR]: #!#!at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140)
[21:47:13 ERROR]: #!#!at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:626)
[21:47:13 ERROR]: #!#!at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchServerCommand(CraftServer.java:612)
[21:47:13 ERROR]: #!#!at net.minecraft.server.v1_10_R1.DedicatedServer.aL(DedicatedServer.java:398)
[21:47:13 ERROR]: #!#!at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:362)
[21:47:13 ERROR]: #!#!at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:643)
[21:47:13 ERROR]: #!#!at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:547)
[21:47:13 ERROR]: #!#!at java.lang.Thread.run(Thread.java:745)
[21:47:13 ERROR]: #!#!
[21:47:13 ERROR]: #!#! Version Information:
[21:47:13 ERROR]: #!#!Skript: 2.2-dev29
[21:47:13 ERROR]: #!#!Bukkit: 1.10.2-R0.1-SNAPSHOT
[21:47:13 ERROR]: #!#!Minecraft: 1.10.2
[21:47:13 ERROR]: #!#!Java: 1.8.0_74 (Java HotSpot(TM) 64-Bit Server VM 25.74-b02)
[21:47:13 ERROR]: #!#!OS: Linux amd64 3.16.0-4-amd64
[21:47:13 ERROR]: #!#!
[21:47:13 ERROR]: #!#! Running CraftBukkit: false
[21:47:13 ERROR]: #!#!
[21:47:13 ERROR]: #!#! Current node: world is "world_nether": (zadaniaxD.sk, line 3)
[21:47:13 ERROR]: #!#! Current item: null
[21:47:13 ERROR]: #!#!
[21:47:13 ERROR]: #!#! Thread: Server thread
[21:47:13 ERROR]: #!#!
[21:47:13 ERROR]: #!#! End of Error.
[21:47:13 ERROR]: #!#!
[21:47:13 INFO]: All scripts loaded without errors.
[21:47:13 WARN]: No scripts were found, maybe you should write some ;)
[21:47:13 INFO]: [Skript] Encountered 21 errors while reloading the config and all scripts!

pls help me :) xD

**Comment by bensku** [comment]
Do you have addons? If so, try without them.

**Comment by SzlugPL** [comment]
What kind of additives? You for the wildskript etc ... or some skript in which it is written

**Comment by SzlugPL** [comment]
sk reload all
[18:59:28 INFO]: [Skript] Reloading the config and all scripts...
[18:59:56 INFO]: Loaded a total of 777473 english aliases
[18:59:56 WARN]: There are no aliases defined for the following ids: 213, 214, 215, 216, 217, 441
[18:59:56 ERROR]: #!#!
[18:59:56 ERROR]: #!#! [Skript] Severe Error:
[18:59:56 ERROR]: #!#! Could not load zadaniaxD.sk
[18:59:56 ERROR]: #!#!
[18:59:56 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[18:59:56 ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[18:59:56 ERROR]: #!#! and check whether this error has already been reported.
[18:59:56 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[18:59:56 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[18:59:56 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[18:59:56 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[18:59:56 ERROR]: #!#!
[18:59:56 ERROR]: #!#! Stack trace:
[18:59:56 ERROR]: #!#! java.lang.IllegalStateException: Cannot use classinfos until registration is over
[18:59:56 ERROR]: #!#!at ch.njol.skript.registrations.Classes.checkAllowClassInfoInteraction(Classes.java:240)
[18:59:56 ERROR]: #!#!at ch.njol.skript.registrations.Classes.getClassInfos(Classes.java:245)
[18:59:56 ERROR]: #!#!at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:414)
[18:59:56 ERROR]: #!#!at ch.njol.skript.registrations.Classes.parse(Classes.java:449)
[18:59:56 ERROR]: #!#!at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:385)
[18:59:56 ERROR]: #!#!at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:445)
[18:59:56 ERROR]: #!#!at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1159)
[18:59:56 ERROR]: #!#!at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:219)
[18:59:56 ERROR]: #!#!at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:174)
[18:59:56 ERROR]: #!#!at ch.njol.skript.lang.Condition.parse(Condition.java:81)
[18:59:56 ERROR]: #!#!at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:738)
[18:59:56 ERROR]: #!#!at ch.njol.skript.command.Commands.loadCommand(Commands.java:465)
[18:59:56 ERROR]: #!#!at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:409)
[18:59:56 ERROR]: #!#!at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:243)
[18:59:56 ERROR]: #!#!at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:200)
[18:59:56 ERROR]: #!#!at ch.njol.skript.Skript.reload(Skript.java:722)
[18:59:56 ERROR]: #!#!at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:161)
[18:59:56 ERROR]: #!#!at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[18:59:56 ERROR]: #!#!at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140)
[18:59:56 ERROR]: #!#!at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:626)
[18:59:56 ERROR]: #!#!at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchServerCommand(CraftServer.java:612)
[18:59:56 ERROR]: #!#!at net.minecraft.server.v1_10_R1.DedicatedServer.aL(DedicatedServer.java:398)
[18:59:56 ERROR]: #!#!at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:362)
[18:59:56 ERROR]: #!#!at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:643)
[18:59:56 ERROR]: #!#!at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:547)
[18:59:56 ERROR]: #!#!at java.lang.Thread.run(Thread.java:745)
[18:59:56 ERROR]: #!#!
[18:59:56 ERROR]: #!#! Version Information:
[18:59:56 ERROR]: #!#!Skript: 2.2-dev29
[18:59:56 ERROR]: #!#!Bukkit: 1.10.2-R0.1-SNAPSHOT
[18:59:56 ERROR]: #!#!Minecraft: 1.10.2
[18:59:56 ERROR]: #!#!Java: 1.8.0_74 (Java HotSpot(TM) 64-Bit Server VM 25.74-b02)
[18:59:56 ERROR]: #!#!OS: Linux amd64 3.16.0-4-amd64
[18:59:56 ERROR]: #!#!
[18:59:56 ERROR]: #!#! Running CraftBukkit: false
[18:59:56 ERROR]: #!#!
[18:59:56 ERROR]: #!#! Current node: world is "world_nether": (zadaniaxD.sk, line 3)
[18:59:56 ERROR]: #!#! Current item: null
[18:59:56 ERROR]: #!#!
[18:59:56 ERROR]: #!#! Thread: Server thread
[18:59:56 ERROR]: #!#!
[18:59:56 ERROR]: #!#! End of Error.
[18:59:56 ERROR]: #!#!
[18:59:56 INFO]: All scripts loaded without errors.
[18:59:56 WARN]: No scripts were found, maybe you should write some ;)
[18:59:56 INFO]: [Skript] Successfully reloaded the config and all scripts.

code zadaniaxD.sk
command /ustteleport:
	trigger:
		world is "world_nether":
			set {teleport::spawn} to location of player
			sent "&aUStawiles punkt teleportacji" to player
		else:
		       send "&cMusisz byc w netherze" to player
			
on portal enter:
	world is "world":
		teleport player to spawn

**Comment by bensku** [comment]
Can anyone reproduce? Can't run 1.10 test server right now...

**Comment by SzlugPL** [comment]
nie rozumiem :D

**Comment by TheBentoBox** [comment]
No response and reporter can't really provide info we need anyways, closing.
