### ISSUE TITLE
Random error (maybe related to regions) 

### ISSUE THREAD

**Issue by melinstagibson** [bensku/Skript#689]
This gets written to my console randomly and i have no idea why or if its harmful but i didnt realize any issues so far.
```
[16:45:31 WARN]: [Skript] Plugin Skript v2.2-dev29 generated an exception while executing task 96
ch.njol.skript.SkriptAPIException: Serializer of region must override newInstance(), canBeInstantiated() or mustSyncDeserialization() if its class does not have a nullary constructor
        at ch.njol.skript.classes.Serializer.newInstance(Serializer.java:80) ~[?:?]
        at ch.njol.yggdrasil.Yggdrasil.newInstance(Yggdrasil.java:340) ~[?:?]
        at ch.njol.yggdrasil.Yggdrasil.isSerializable(Yggdrasil.java:155) ~[?:?]
        at ch.njol.yggdrasil.YggdrasilOutputStream.writeGenericObject(YggdrasilOutputStream.java:167) ~[?:?]
        at ch.njol.yggdrasil.YggdrasilOutputStream.writeObject(YggdrasilOutputStream.java:247) ~[?:?]
        at ch.njol.skript.registrations.Classes.serialize(Classes.java:707) ~[?:?]
        at ch.njol.skript.variables.FlatFileStorage.save(FlatFileStorage.java:441) ~[?:?]
        at ch.njol.skript.variables.FlatFileStorage.save(FlatFileStorage.java:434) ~[?:?]
        at ch.njol.skript.variables.FlatFileStorage.saveVariables(FlatFileStorage.java:396) ~[?:?]
        at ch.njol.skript.variables.FlatFileStorage$1.run(FlatFileStorage.java:202) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.jar:git-Paper-1133]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.jar:git-Paper-1133]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.jar:git-Paper-1133]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]```

**Comment by bensku** [comment]
Do you have addons, specially addons that add support for region plugins?

**Comment by melinstagibson** [comment]
Nothing special/uncommon
Skquery
Skellett
SkRayfall
TuSke
SharpSk
All updated

**Comment by melinstagibson** [comment]
Is it harmful tho? I use persistent variables alot so the line wirh variables and flatfilestorage kinda troubled me

**Comment by bensku** [comment]
Harmful? Might be. Iy is likely that this is an issue of some of your addons, though. Try if it happens without them.

**Comment by Syst3ms** [comment]
@Snow-Pyon Did you close it by accident
