### ISSUE TITLE
Tooltip json throws exception in console [Bungee]

### ISSUE THREAD

**Issue by 100photos** [bensku/Skript#690]
Probably isnt _directly_ related to bungee, but it mentions it in the error so maybe?
```[19:37:10 ERROR]: #!#!
[19:37:10 ERROR]: #!#! [Skript] Severe Error:
[19:37:10 ERROR]: #!#!
[19:37:10 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[19:37:10 ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[19:37:10 ERROR]: #!#! and check whether this error has already been reported.
[19:37:10 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[19:37:10 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[19:37:10 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[19:37:10 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[19:37:10 ERROR]: #!#!
[19:37:10 ERROR]: #!#! Stack trace:
[19:37:10 ERROR]: #!#! java.lang.NullPointerException
[19:37:10 ERROR]: #!#!     at ch.njol.skript.util.chat.BungeeConverter.convert(BungeeConverter.java:51)
[19:37:10 ERROR]: #!#!     at ch.njol.skript.util.chat.BungeeConverter.convert(BungeeConverter.java:59)
[19:37:10 ERROR]: #!#!     at ch.njol.skript.effects.EffMessage.execute(EffMessage.java:88)
[19:37:10 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[19:37:10 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[19:37:10 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[19:37:10 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
[19:37:10 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:151)
[19:37:10 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:109)
[19:37:10 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[19:37:10 ERROR]: #!#!     at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:36)
[19:37:10 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499)
[19:37:10 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
[19:37:10 ERROR]: #!#!     at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:414)
[19:37:10 ERROR]: #!#!     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:37:10 ERROR]: #!#!     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[19:37:10 ERROR]: #!#!     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[19:37:10 ERROR]: #!#!     at java.lang.reflect.Method.invoke(Unknown Source)
[19:37:10 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[19:37:10 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[19:37:10 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499)
[19:37:10 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
[19:37:10 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1568)
[19:37:10 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:69)
[19:37:10 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(SourceFile:13)
[19:37:10 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[19:37:10 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[19:37:10 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
[19:37:10 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[19:37:10 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747)
[19:37:10 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405)
[19:37:10 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
[19:37:10 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
[19:37:10 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[19:37:10 ERROR]: #!#!
[19:37:10 ERROR]: #!#! Version Information:
[19:37:10 ERROR]: #!#!   Skript: 2.2-dev29
[19:37:10 ERROR]: #!#!   Bukkit: 1.12-R0.1-SNAPSHOT
[19:37:10 ERROR]: #!#!   Minecraft: 1.12
[19:37:10 ERROR]: #!#!   Java: 1.8.0_131 (Java HotSpot(TM) 64-Bit Server VM 25.131-b11)
[19:37:10 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[19:37:10 ERROR]: #!#!
[19:37:10 ERROR]: #!#! Running CraftBukkit: false
[19:37:10 ERROR]: #!#!
[19:37:10 ERROR]: #!#! Current node: null
[19:37:10 ERROR]: #!#! Current item: send "<tooltip:Click on me!>┬ºe┬ºlClick here!" to event-player/console
[19:37:10 ERROR]: #!#!
[19:37:10 ERROR]: #!#! Thread: Server thread
[19:37:10 ERROR]: #!#!
[19:37:10 ERROR]: #!#! End of Error.
[19:37:10 ERROR]: #!#!
```

**Comment by bensku** [comment]
Uh, that was a stupid little bug. By stupid I mean very easy to fix!
