### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kuba2003tv** [bensku/Skript#694]
[09:49:05 ERROR]: #!#! [Skript] Severe Error:
[09:49:05 ERROR]: #!#! Could not load sc.sk
[09:49:05 ERROR]: #!#!
[09:49:05 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[09:49:05 ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[09:49:05 ERROR]: #!#! and check whether this error has already been reported.
[09:49:05 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[09:49:05 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[09:49:05 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[09:49:05 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[09:49:05 ERROR]: #!#!
[09:49:05 ERROR]: #!#! Stack trace:
[09:49:05 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for particle
[09:49:05 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:262)
[09:49:05 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1417)
[09:49:05 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1138)
[09:49:05 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1084)
[09:49:05 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:219)
[09:49:05 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:174)
[09:49:05 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:319)
[09:49:05 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:445)
[09:49:05 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1159)
[09:49:05 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1084)
[09:49:05 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1084)
[09:49:05 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1150)
[09:49:05 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:219)
[09:49:05 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:174)
[09:49:05 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:319)
[09:49:05 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:445)
[09:49:05 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:677)
[09:49:05 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:450)
[09:49:05 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:243)
[09:49:05 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:200)
[09:49:05 ERROR]: #!#!     at ch.njol.skript.Skript$2.run(Skript.java:405)
[09:49:05 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58)
[09:49:05 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356)
[09:49:05 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:832)
[09:49:05 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[09:49:05 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:766)
[09:49:05 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:664)
[09:49:05 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[09:49:05 ERROR]: #!#!
[09:49:05 ERROR]: #!#! Version Information:
[09:49:05 ERROR]: #!#!   Skript: 2.2-dev29
[09:49:05 ERROR]: #!#!   Bukkit: 1.12-R0.1-SNAPSHOT
[09:49:05 ERROR]: #!#!   Minecraft: 1.12
[09:49:05 ERROR]: #!#!   Java: 1.8.0_92 (Java HotSpot(TM) 64-Bit Server VM 25.92-b14)
[09:49:05 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[09:49:05 ERROR]: #!#!
[09:49:05 ERROR]: #!#! Running CraftBukkit: false
[09:49:05 ERROR]: #!#!
[09:49:05 ERROR]: #!#! Current node: loop all players: (sc.sk, line 2)
[09:49:05 ERROR]: #!#! Current item: null
[09:49:05 ERROR]: #!#!
[09:49:05 ERROR]: #!#! Thread: Server thread
[09:49:05 ERROR]: #!#!
[09:49:05 ERROR]: #!#! End of Error.
[09:49:05 ERROR]: #!#!
[09:49:05 ERROR]: #!#!
[09:49:05 ERROR]: #!#! [Skript] Severe Error:
[09:49:05 ERROR]: #!#! Could not load signedit.sk
[09:49:05 ERROR]: #!#!
[09:49:05 INFO]: [Skript] You're currently running the latest stable version of Skript.
> [09:49:05 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[09:49:05 ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[09:49:05 ERROR]: #!#! and check whether this error has already been reported.
[09:49:05 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[09:49:05 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[09:49:05 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[09:49:05 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[09:49:05 ERROR]: #!#!
[09:49:05 ERROR]: #!#! Stack trace:
[09:49:05 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for particle
[09:49:05 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:262)
[09:49:05 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1417)
[09:49:05 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1138)
[09:49:05 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1084)
[09:49:05 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:219)
[09:49:05 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:174)
[09:49:05 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:319)
[09:49:05 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:445)
[09:49:05 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1159)
[09:49:05 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1111)
[09:49:05 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1150)
[09:49:05 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:219)
[09:49:05 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:174)
[09:49:05 ERROR]: #!#!     at ch.njol.skript.lang.Condition.parse(Condition.java:81)
[09:49:05 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:738)
[09:49:05 ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:465)
[09:49:05 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:409)
[09:49:05 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:243)
[09:49:05 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:200)
[09:49:05 ERROR]: #!#!     at ch.njol.skript.Skript$2.run(Skript.java:405)
[09:49:05 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58)
[09:49:05 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356)
[09:49:05 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:832)
[09:49:05 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[09:49:05 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:766)
[09:49:05 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:664)
[09:49:05 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[09:49:05 ERROR]: #!#!
[09:49:05 ERROR]: #!#! Version Information:
[09:49:05 ERROR]: #!#!   Skript: 2.2-dev29
[09:49:05 ERROR]: #!#!   Bukkit: 1.12-R0.1-SNAPSHOT
[09:49:05 ERROR]: #!#!   Minecraft: 1.12
[09:49:05 ERROR]: #!#!   Java: 1.8.0_92 (Java HotSpot(TM) 64-Bit Server VM 25.92-b14)
[09:49:05 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[09:49:05 ERROR]: #!#!
[09:49:05 ERROR]: #!#! Running CraftBukkit: false
[09:49:05 ERROR]: #!#!
[09:49:05 ERROR]: #!#! Current node: player has permission "signedit.edit" or "signedit.*": (signedit.sk, line 6)
[09:49:05 ERROR]: #!#! Current item: null
[09:49:05 ERROR]: #!#!
[09:49:05 ERROR]: #!#! Thread: Server thread
[09:49:05 ERROR]: #!#!
[09:49:05 ERROR]: #!#! End of Error.
[09:49:05 ERROR]: #!#!

**Comment by Snow-Pyon** [comment]
Are you using addons? If so try without them.

**Comment by kuba2003tv** [comment]
Yes im usung, problem has ben repair. Thanks
