### ISSUE TITLE
Error Inventory

### ISSUE THREAD

**Issue by molresa** [bensku/Skript#697]
[23:32:18] [Server thread/ERROR]: #!#! 
[23:32:18] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[23:32:18] [Server thread/ERROR]: #!#! Could not load lol.sk
[23:32:18] [Server thread/ERROR]: #!#! 
[23:32:18] [Server thread/ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[23:32:18] [Server thread/ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[23:32:18] [Server thread/ERROR]: #!#! and check whether this error has already been reported.
[23:32:18] [Server thread/ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[23:32:18] [Server thread/ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[23:32:18] [Server thread/ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[23:32:18] [Server thread/ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[23:32:18] [Server thread/ERROR]: #!#! 
[23:32:18] [Server thread/ERROR]: #!#! Stack trace:
[23:32:18] [Server thread/ERROR]: #!#! java.lang.IllegalStateException: Cannot use classinfos until registration is over
[23:32:18] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Classes.checkAllowClassInfoInteraction(Classes.java:240)
[23:32:18] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfos(Classes.java:245)
[23:32:18] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:414)
[23:32:18] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Classes.parse(Classes.java:449)
[23:32:18] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:385)
[23:32:18] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:445)
[23:32:18] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1159)
[23:32:18] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1150)
[23:32:18] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1077)
[23:32:18] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1077)
[23:32:18] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1150)
[23:32:18] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1077)
[23:32:18] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1150)
[23:32:18] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1084)
[23:32:18] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1084)
[23:32:18] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:219)
[23:32:18] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:174)
[23:32:18] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:59)
[23:32:18] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:659)
[23:32:18] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:465)
[23:32:18] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:409)
[23:32:18] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:243)
[23:32:18] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:267)
[23:32:18] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:187)
[23:32:18] [Server thread/ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[23:32:18] [Server thread/ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[23:32:18] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[23:32:18] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[23:32:18] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[23:32:18] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[23:32:18] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[23:32:18] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[23:32:18] [Server thread/ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[23:32:18] [Server thread/ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
[23:32:18] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[23:32:18] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[23:32:18] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[23:32:18] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[23:32:18] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[23:32:18] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[23:32:18] [Server thread/ERROR]: #!#! 
[23:32:18] [Server thread/ERROR]: #!#! Version Information:
[23:32:18] [Server thread/ERROR]: #!#!   Skript: 2.2-dev29
[23:32:18] [Server thread/ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[23:32:18] [Server thread/ERROR]: #!#!   Minecraft: 1.8.8
[23:32:18] [Server thread/ERROR]: #!#!   Java: 1.8.0_71 (Java HotSpot(TM) 64-Bit Server VM 25.71-b15)
[23:32:18] [Server thread/ERROR]: #!#!   OS: Windows 10 amd64 10.0
[23:32:18] [Server thread/ERROR]: #!#! 
[23:32:18] [Server thread/ERROR]: #!#! Running CraftBukkit: false
[23:32:18] [Server thread/ERROR]: #!#! 
[23:32:18] [Server thread/ERROR]: #!#! Current node: open chest with 3 rows named "&7My Profile" to player (lol.sk, line 3)
[23:32:18] [Server thread/ERROR]: #!#! Current item: null
[23:32:18] [Server thread/ERROR]: #!#! 
[23:32:18] [Server thread/ERROR]: #!#! Thread: Server thread
[23:32:18] [Server thread/ERROR]: #!#! 
[23:32:18] [Server thread/ERROR]: #!#! End of Error.
[23:32:18] [Server thread/ERROR]: #!#!

**Comment by TheBentoBox** [comment]
That error isn't coming from a vanilla Skript effect, and regardless this fork of Skript is no longer compatible with 1.8.9 and below as of dev28. You'll need to upgrade your server to 1.9 or higher, or downgrade your Skript version to dev25, but no more support will be given past that.
