### ISSUE TITLE
Error when loading scripts

### ISSUE THREAD

**Issue by DaWiHs** [bensku/Skript#700]
After issuing reload of scripts in plugin, console pops out this error.
I haven't changed much in config file, also in-game after reload of scripts Skript tells, that it "Can't understand this event: (...)" of any example scripts.
Serever runs in offline mode (cracked).
```
> [22:37:58 ERROR]: #!#!
> [22:37:58 ERROR]: #!#! [Skript] Severe Error:
> [22:37:58 ERROR]: #!#! An error happened when trying to enably resolving offline
>  players, so the feature has been turned off. Please report this at https://gith
> ub.com/bensku/Skript/issues/237
> [22:37:58 ERROR]: #!#!
> [22:37:58 ERROR]: #!#! If you're developing an add-on for Skript this likely mea
> ns that you have done something wrong.
> [22:37:58 ERROR]: #!#! If you're a server admin however please go to https://git
> hub.com/bensku/Skript/issues/
> [22:37:58 ERROR]: #!#! and check whether this error has already been reported.
> [22:37:58 ERROR]: #!#! If not please create a new ticket with a meaningful title
> , copy & paste this whole error into it (or use paste service),
> [22:37:58 ERROR]: #!#! and describe what you did before it happened and/or what
> you think caused the error.
> [22:37:58 ERROR]: #!#! If you think that it's a trigger that's causing the error
>  please post the trigger as well.
> [22:37:58 ERROR]: #!#! By following this guide fixing the error should be easy a
> nd done fast.
> [22:37:58 ERROR]: #!#!
> [22:37:58 ERROR]: #!#! Stack trace:
> [22:37:58 ERROR]: #!#! java.lang.NullPointerException: null offline player resol
> ve queue
> [22:37:58 ERROR]: #!#!     at ch.njol.skript.bukkitutil.UnresolvedOfflinePlayer$
> 1.run(UnresolvedOfflinePlayer.java:59)
> [22:37:58 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
> [22:37:58 ERROR]: #!#!
> [22:37:58 ERROR]: #!#! Version Information:
> [22:37:58 ERROR]: #!#!   Skript: 2.2-dev29
> [22:37:58 ERROR]: #!#!   Bukkit: 1.12-R0.1-SNAPSHOT
> [22:37:58 ERROR]: #!#!   Minecraft: 1.12
> [22:37:58 ERROR]: #!#!   Java: 1.8.0_131 (Java HotSpot(TM) 64-Bit Server VM 25.1
> 31-b11)
> [22:37:58 ERROR]: #!#!   OS: Windows 7 amd64 6.1
> [22:37:58 ERROR]: #!#!
> [22:37:58 ERROR]: #!#! Running CraftBukkit: false
> [22:37:58 ERROR]: #!#!
> [22:37:58 ERROR]: #!#! Current node: null
> [22:37:58 ERROR]: #!#! Current item: null
> [22:37:58 ERROR]: #!#!
> [22:37:58 ERROR]: #!#! Thread: Skript offline player resolver thread (fetches UU
> IDs from the minecraft servers)
> [22:37:58 ERROR]: #!#!
> [22:37:58 ERROR]: #!#! End of Error.
> [22:37:58 ERROR]: #!#!
> 
```
Any ideas what to do?

**Comment by DaWiHs** [comment]
@bensku Any replies?

**Comment by Snow-Pyon** [comment]
This happens to me only, and only when I use the `/reload` command (which you shouldn't use as it breaks many plugins, including Skript). Did you use it?

**Comment by DaWiHs** [comment]
Weel, i tried to use Skript just by itself, without any others. Made up a another server folder, set up bukkit 1.12 server, added Skript, and while starting server this error appeared. Give me a sec, already setting up again fresh bukkit with Skript only.

**Comment by DaWiHs** [comment]
`
D:\Pliki\Bukkit 1.12 Skript>java -Xmx1536M -jar craftbukkit-1.12.jar -o false
Loading libraries, please wait...
[02:17:35 INFO]: Starting minecraft server version 1.12
[02:17:35 INFO]: Loading properties
[02:17:35 INFO]: Default game type: SURVIVAL
[02:17:35 INFO]: Generating keypair
[02:17:36 INFO]: Starting Minecraft server on *:25565
[02:17:36 INFO]: Using default channel type
[02:17:37 INFO]: This server is running CraftBukkit version git-Bukkit-d603539 (MC: 1.12) (Implement
ing API version 1.12-R0.1-SNAPSHOT)
[02:17:37 INFO]: [Skript] Loading Skript v2.2-dev29
[02:17:37 WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[02:17:37 WARN]: The server will make no attempt to authenticate usernames. Beware.
[02:17:37 WARN]: While this makes the game possible to play without internet access, it also opens u
p the ability for hackers to connect with any username they choose.
[02:17:37 WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[02:17:37 INFO]: Preparing level "world"
[02:17:39 INFO]: Preparing start region for level 0 (Seed: -1027173224962358233)
[02:17:40 INFO]: Preparing spawn area: 0%
[02:17:41 INFO]: Preparing spawn area: 28%
[02:17:42 INFO]: Preparing spawn area: 39%
[02:17:43 INFO]: Preparing spawn area: 75%
[02:17:44 INFO]: Preparing start region for level 1 (Seed: -1027173224962358233)
[02:17:45 INFO]: Preparing spawn area: 60%
[02:17:45 INFO]: Preparing start region for level 2 (Seed: -1027173224962358233)
[02:17:46 INFO]: [Skript] Enabling Skript v2.2-dev29
[02:17:46 INFO]: [Skript] Successfully generated the config, the example scripts and the aliases fil
es.
[02:17:46 ERROR]: Error occurred while enabling Skript v2.2-dev29 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.Effect.getName()Ljava/lang/String;
        at ch.njol.skript.util.VisualEffect$Type.<init>(VisualEffect.java:203) ~[?:?]
        at ch.njol.skript.util.VisualEffect$Type.<clinit>(VisualEffect.java:70) ~[?:?]
        at ch.njol.skript.util.VisualEffect.<clinit>(VisualEffect.java:262) ~[?:?]
        at ch.njol.skript.classes.data.SkriptClasses.<clinit>(SkriptClasses.java:889) ~[?:?]
        at ch.njol.skript.Skript.onEnable(Skript.java:277) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[craftbukkit-1.12.jar:
git-Bukkit-d603539]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) [craftbuk
kit-1.12.jar:git-Bukkit-d603539]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:401) [craftbu
kkit-1.12.jar:git-Bukkit-d603539]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:361) [craftbukk
it-1.12.jar:git-Bukkit-d603539]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:323) [craftbuk
kit-1.12.jar:git-Bukkit-d603539]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:411) [craftbukkit-1.
12.jar:git-Bukkit-d603539]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:372) [craftbukkit-1.
12.jar:git-Bukkit-d603539]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:327) [craftbukkit-1.
12.jar:git-Bukkit-d603539]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:244) [craftbukkit
-1.12.jar:git-Bukkit-d603539]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:521) [craftbukkit-
1.12.jar:git-Bukkit-d603539]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
[02:17:46 INFO]: Server permissions file permissions.yml is empty, ignoring it
[02:17:46 INFO]: Done (9,017s)! For help, type "help" or "?"
[02:17:50 WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 370
6ms behind, skipping 74 tick(s)
>`

**Comment by DaWiHs** [comment]
What i did:
Got fresh Bukkit 1.12 server file
Started it, Accepted EULA, Started again.
Shut down.
Inserted Skript.jar into plugins
Started.

**Comment by DaWiHs** [comment]
Also when running in secure (online) mode;

```
D:\Pliki\Bukkit 1.12 Skript>java -Xmx1536M -jar craftbukkit-1.12.jar -o true
Loading libraries, please wait...
[02:24:46 INFO]: Starting minecraft server version 1.12
[02:24:46 INFO]: Loading properties
[02:24:46 INFO]: Default game type: SURVIVAL
[02:24:46 INFO]: Generating keypair
[02:24:47 INFO]: Starting Minecraft server on *:25565
[02:24:47 INFO]: Using default channel type
[02:24:48 INFO]: This server is running CraftBukkit version git-Bukkit-d603539 (MC: 1.12) (Implement
ing API version 1.12-R0.1-SNAPSHOT)
[02:24:48 INFO]: [Skript] Loading Skript v2.2-dev29
[02:24:48 INFO]: Preparing level "world"
[02:24:50 INFO]: Preparing start region for level 0 (Seed: -1027173224962358233)
[02:24:51 INFO]: Preparing spawn area: 0%
[02:24:52 INFO]: Preparing spawn area: 20%
[02:24:54 INFO]: Preparing spawn area: 37%
[02:24:55 INFO]: Preparing spawn area: 69%
[02:24:55 INFO]: Preparing start region for level 1 (Seed: -1027173224962358233)
[02:24:56 INFO]: Preparing spawn area: 52%
[02:24:57 INFO]: Preparing start region for level 2 (Seed: -1027173224962358233)
[02:24:58 INFO]: [Skript] Enabling Skript v2.2-dev29
[02:24:58 ERROR]: Error occurred while enabling Skript v2.2-dev29 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.Effect.getName()Ljava/lang/String;
        at ch.njol.skript.util.VisualEffect$Type.<init>(VisualEffect.java:203) ~[?:?]
        at ch.njol.skript.util.VisualEffect$Type.<clinit>(VisualEffect.java:70) ~[?:?]
        at ch.njol.skript.util.VisualEffect.<clinit>(VisualEffect.java:262) ~[?:?]
        at ch.njol.skript.classes.data.SkriptClasses.<clinit>(SkriptClasses.java:889) ~[?:?]
        at ch.njol.skript.Skript.onEnable(Skript.java:277) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[craftbukkit-1.12.jar:
git-Bukkit-d603539]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) [craftbuk
kit-1.12.jar:git-Bukkit-d603539]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:401) [craftbu
kkit-1.12.jar:git-Bukkit-d603539]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:361) [craftbukk
it-1.12.jar:git-Bukkit-d603539]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:323) [craftbuk
kit-1.12.jar:git-Bukkit-d603539]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:411) [craftbukkit-1.
12.jar:git-Bukkit-d603539]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:372) [craftbukkit-1.
12.jar:git-Bukkit-d603539]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:327) [craftbukkit-1.
12.jar:git-Bukkit-d603539]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:244) [craftbukkit
-1.12.jar:git-Bukkit-d603539]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:521) [craftbukkit-
1.12.jar:git-Bukkit-d603539]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
[02:24:58 INFO]: Server permissions file permissions.yml is empty, ignoring it
[02:24:58 INFO]: Done (10,039s)! For help, type "help" or "?"
[02:25:01 WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 283
3ms behind, skipping 56 tick(s)
>
```

**Comment by Snow-Pyon** [comment]
You need either Spigot or PaperSpigot, Skript doesn't support CraftBukkit so it won't work. Also, you should use BuildTools to get your builds.

**Comment by TheBentoBox** [comment]
Yeah, just switch over to Spigot as @Snow-Pyon said. If you need more help feel free to ask on the skUnity forums.

**Comment by DaWiHs** [comment]
Everything works for now on Spigot. Thanks then.
But there is no way to make Skript work on Bukkit too?

**Comment by TheBentoBox** [comment]
The fact that it uses Spigot-specific pieces of the API at all indicates that making it work on Bukkit would require removing features. There's also very little reason to use Bukkit instead of Spigot since all the latter offers is improvements to performance and customization (since many of changes it makes can be modified in the spigot.yml config).

**Comment by DaWiHs** [comment]
Okay then, i will move on to spigot.
Thanks for the help ;)
