### ISSUE TITLE
Broadcasting a variable broke down? D:

### ISSUE THREAD

**Issue by Moderocky** [bensku/Skript#705]
I tried to broadcast a list variable in quotations, which usually works by printing "thing1, thing2 and thing3"

Today it gave me a nasty error (see bottom).

I think the problem is with the variable itself, because looping it didn't work either.

`[07:15:52] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[07:15:52] [Server thread/ERROR]: #!#! Unexpected error while executing effect command 'broadcast "%{guilds::*}%"' by 'MTAC'
[07:15:52] [Server thread/ERROR]: #!#!
[07:15:52] [Server thread/ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[07:15:52] [Server thread/ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[07:15:52] [Server thread/ERROR]: #!#! and check whether this error has already been reported.
[07:15:52] [Server thread/ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[07:15:52] [Server thread/ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[07:15:52] [Server thread/ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[07:15:52] [Server thread/ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[07:15:52] [Server thread/ERROR]: #!#!
[07:15:52] [Server thread/ERROR]: #!#! Stack trace:
[07:15:52] [Server thread/ERROR]: #!#! warning: no/empty exception given, dumping current stack trace instead
[07:15:52] [Server thread/ERROR]: #!#! java.lang.Exception: java.lang.NullPointerException
[07:15:52] [Server thread/ERROR]: #!#! at ch.njol.skript.Skript.exception(Skript.java:1212)
[07:15:52] [Server thread/ERROR]: #!#! at ch.njol.skript.Skript.exception(Skript.java:1176)
[07:15:52] [Server thread/ERROR]: #!#! at ch.njol.skript.command.Commands.handleEffectCommand(Commands.java:309)
[07:15:52] [Server thread/ERROR]: #!#! at ch.njol.skript.command.Commands$4$1.call(Commands.java:229)
[07:15:52] [Server thread/ERROR]: #!#! at ch.njol.skript.command.Commands$4$1.call(Commands.java:1)
[07:15:52] [Server thread/ERROR]: #!#! at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftFuture.run(CraftFuture.java:89)
[07:15:52] [Server thread/ERROR]: #!#! at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[07:15:52] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738)
[07:15:52] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[07:15:52] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
[07:15:52] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
[07:15:52] [Server thread/ERROR]: #!#! at java.lang.Thread.run(Thread.java:748)
[07:15:52] [Server thread/ERROR]: #!#! Caused by: java.lang.NullPointerException
[07:15:52] [Server thread/ERROR]: #!#!
[07:15:52] [Server thread/ERROR]: #!#! Version Information:
[07:15:52] [Server thread/ERROR]: #!#! Skript: 2.2-dev25
[07:15:52] [Server thread/ERROR]: #!#! Bukkit: 1.11.2-R0.1-SNAPSHOT
[07:15:52] [Server thread/ERROR]: #!#! Minecraft: 1.11.2
[07:15:52] [Server thread/ERROR]: #!#! Java: 1.8.0_131 (OpenJDK 64-Bit Server VM 25.131-b12)
[07:15:52] [Server thread/ERROR]: #!#! OS: Linux amd64 3.10.0-514.10.2.el7.x86_64
[07:15:52] [Server thread/ERROR]: #!#!
[07:15:52] [Server thread/ERROR]: #!#! Running CraftBukkit: false
[07:15:52] [Server thread/ERROR]: #!#!
[07:15:52] [Server thread/ERROR]: #!#! Current node: null
[07:15:52] [Server thread/ERROR]: #!#! Current item: null
[07:15:52] [Server thread/ERROR]: #!#!
[07:15:52] [Server thread/ERROR]: #!#! Thread: Server thread
[07:15:52] [Server thread/ERROR]: #!#!
[07:15:52] [Server thread/ERROR]: #!#! End of Error.
[07:15:52] [Server thread/ERROR]: #!#!`

**Comment by Moderocky** [comment]
I cannot clear, delete or otherwise touch that variable.

**Comment by TheBentoBox** [comment]
Could you send your variables file?

**Comment by Moderocky** [comment]
I fixed the variable now, so it wouldn't be any use. I set it to things, and it worked after.

**Comment by TheBentoBox** [comment]
Something must've just gotten corrupted with the variable. If you find a way to reproduce it feel free to report how.
