### ISSUE TITLE
Error occurred while enabling Skript v2.2-dev23

### ISSUE THREAD

**Issue by droopi29** [bensku/Skript#706]
my server is on 1.7.10 and i have this issu 

> [15:23:09] [Server thread/ERROR]: Error occurred while enabling Skript v2.2-dev23 (Is it up to date?)
java.lang.NoSuchFieldError: SPRUCE_DOOR
	at ch.njol.skript.effects.EffToggle.<clinit>(EffToggle.java:75) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_72]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_72]
	at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:110) ~[?:?]
	at ch.njol.skript.Skript.onEnable(Skript.java:286) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1614.58]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1614.58]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1614.58]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438) [CraftServer.class:1.7.10-1614.58]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372) [CraftServer.class:1.7.10-1614.58]
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:519) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:493) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:453) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

**Comment by TheBentoBox** [comment]
We don't provide support for much older versions of this fork (you're 6 dev releases behind), nor is it compatible with versions below 1.9. This issue is caused by the toggle effect being updated in dev18 to support 1.8 doors, so if you'd like you could downgrade to [dev17](https://github.com/bensku/Skript/releases/tag/dev17) since it may work on 1.7, but that's all the help we can give at this point. You should really update your server.
