### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by LeCraft2Ouf** [bensku/Skript#712]
```
[07:09:22] [Server thread/ERROR]: #!#! 

[07:09:22] [Server thread/ERROR]: #!#! [Skript] Severe Error:

[07:09:22] [Server thread/ERROR]: #!#! Could not load Récompense.sk

[07:09:22] [Server thread/ERROR]: #!#! 

[07:09:22] [Server thread/ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.

[07:09:22] [Server thread/ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/

[07:09:22] [Server thread/ERROR]: #!#! and check whether this error has already been reported.

[07:09:22] [Server thread/ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),

[07:09:22] [Server thread/ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.

[07:09:22] [Server thread/ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.

[07:09:22] [Server thread/ERROR]: #!#! By following this guide fixing the error should be easy and done fast.

[07:09:22] [Server thread/ERROR]: #!#! 

[07:09:22] [Server thread/ERROR]: #!#! Stack trace:

[07:09:22] [Server thread/ERROR]: #!#! java.lang.IllegalStateException: Cannot use classinfos until registration is over

[07:09:22] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Classes.checkAllowClassInfoInteraction(Classes.java:240)

[07:09:22] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfos(Classes.java:245)

[07:09:22] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:414)

[07:09:22] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Classes.parse(Classes.java:449)

[07:09:22] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:385)

[07:09:22] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:445)

[07:09:22] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1159)

[07:09:22] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:219)

[07:09:22] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:174)

[07:09:22] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:59)

[07:09:22] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:659)

[07:09:22] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:465)

[07:09:22] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:409)

[07:09:22] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:243)

[07:09:22] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:267)

[07:09:22] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:187)

[07:09:22] [Server thread/ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)

[07:09:22] [Server thread/ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)

[07:09:22] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)

[07:09:22] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)

[07:09:22] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)

[07:09:22] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)

[07:09:22] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)

[07:09:22] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)

[07:09:22] [Server thread/ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

[07:09:22] [Server thread/ERROR]: #!#!     at java.util.concurrent.FutureTask.run(FutureTask.java:266)

[07:09:22] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)

[07:09:22] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)

[07:09:22] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)

[07:09:22] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)

[07:09:22] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)

[07:09:22] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)

[07:09:22] [Server thread/ERROR]: #!#! 
[07:09:22] [Server thread/ERROR]: #!#! Version Information:
[07:09:22] [Server thread/ERROR]: #!#!   Skript: 2.2-dev28c
[07:09:22] [Server thread/ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[07:09:22] [Server thread/ERROR]: #!#!   Minecraft: 1.8.8
[07:09:22] [Server thread/ERROR]: #!#!   Java: 1.8.0_72 (Java HotSpot(TM) 64-Bit Server VM 25.72-b15)
[07:09:22] [Server thread/ERROR]: #!#!   OS: Linux amd64 3.16.0-0.bpo.4-amd64
[07:09:22] [Server thread/ERROR]: #!#! 
[07:09:22] [Server thread/ERROR]: #!#! Running CraftBukkit: false
[07:09:22] [Server thread/ERROR]: #!#! 
[07:09:22] [Server thread/ERROR]: #!#! Current node: open chest with 6 rows named "&9&l>> &6&lRÉCOMPENSE &9&l<<" to player (Récompense.sk, line 3)
[07:09:22] [Server thread/ERROR]: #!#! Current item: null
[07:09:22] [Server thread/ERROR]: #!#! 
[07:09:22] [Server thread/ERROR]: #!#! Thread: Server thread
[07:09:22] [Server thread/ERROR]: #!#! 
[07:09:22] [Server thread/ERROR]: #!#! End of Error.
[07:09:22] [Server thread/ERROR]: #!#! 
``` 
Please help me :c

**Comment by TheBentoBox** [comment]
This fork isn't compatible with 1.8 anymore. You could try downgrading to dev25 as that was the last version that worked on 1.8 but past that we can provide you no support.
