### ISSUE TITLE
Skript reload EZStaff v4.0-pre3.sk

### ISSUE THREAD

**Issue by master861** [bensku/Skript#722]
[16:50:22 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[16:50:22 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[16:50:22 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[16:50:22 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[16:50:22 ERROR]: #!#!
[16:50:22 ERROR]: #!#! Stack trace:
[16:50:22 ERROR]: #!#! java.lang.NullPointerException
[16:50:22 ERROR]: #!#!     at ch.njol.skript.effects.EffChange.init(EffChange.java:157)
[16:50:22 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:247)
[16:50:22 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:174)
[16:50:22 ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:59)
[16:50:22 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:659)
[16:50:22 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:450)
[16:50:22 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:243)
[16:50:22 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:267)
[16:50:22 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:187)
[16:50:22 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[16:50:22 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[16:50:22 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:645)
[16:50:22 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:631)
[16:50:22 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:443)
[16:50:22 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[16:50:22 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
[16:50:22 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
[16:50:22 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[16:50:22 ERROR]: #!#!
[16:50:22 ERROR]: #!#! Version Information:
[16:50:22 ERROR]: #!#!   Skript: 2.2-dev29
[16:50:22 ERROR]: #!#!   Bukkit: 1.12-R0.1-SNAPSHOT
[16:50:22 ERROR]: #!#!   Minecraft: 1.12
[16:50:22 ERROR]: #!#!   Java: 1.8.0_131 (OpenJDK 64-Bit Server VM 25.131-b11)
[16:50:22 ERROR]: #!#!   OS: Linux amd64 4.4.0-21-generic
[16:50:22 ERROR]: #!#!
[16:50:22 ERROR]: #!#! Running CraftBukkit: false
[16:50:22 ERROR]: #!#!
[16:50:22 ERROR]: #!#! Current node: set {ezstaff.prefix} to single value "Prefix" get of "plugins/EZStaff/messages.yml" (EZStaff v4.0-pre3.sk, line 52)
[16:50:22 ERROR]: #!#! Current item: null
[16:50:22 ERROR]: #!#!
[16:50:22 ERROR]: #!#! Thread: Server thread
[16:50:22 ERROR]: #!#!
[16:50:22 ERROR]: #!#! End of Error.
[16:50:22 ERROR]: #!#!

**Comment by EazyFTW** [comment]
Hi, i am the author.... xD Try using 2.2-dev25

That the version of skript i use.

**Comment by EazyFTW** [comment]
Also try to get all of the dependencies listed.

**Comment by TheBentoBox** [comment]
Looks like the node giving the error isn't even a vanilla Skript syntax, so this probably isn't an issue that should be reported here.
