### ISSUE TITLE
Help me some error

### ISSUE THREAD

**Issue by effiraid** [bensku/Skript#729]
[12:22:55 ERROR]: #!#!
[12:22:55 ERROR]: #!#! [Skript] Severe Error:
[12:22:55 ERROR]: #!#! An error occurred while shutting down.
[12:22:55 ERROR]: #!#! This might or might not cause any issues.
[12:22:55 ERROR]: #!#!
[12:22:55 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[12:22:55 ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[12:22:55 ERROR]: #!#! and check whether this error has already been reported.
[12:22:55 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[12:22:55 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[12:22:55 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[12:22:55 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[12:22:55 ERROR]: #!#!
[12:22:55 ERROR]: #!#! Stack trace:
[12:22:55 ERROR]: #!#! java.lang.NullPointerException
[12:22:55 ERROR]: #!#!     at ch.njol.skript.bukkitutil.UnresolvedOfflinePlayer$2.close(UnresolvedOfflinePlayer.java:79)
[12:22:55 ERROR]: #!#!     at ch.njol.skript.Skript.onDisable(Skript.java:776)
[12:22:55 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273)
[12:22:55 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344)
[12:22:55 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:427)
[12:22:55 ERROR]: #!#!     at com.rylinaux.plugman.util.PluginUtil.unload(PluginUtil.java:419)
[12:22:55 ERROR]: #!#!     at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:379)
[12:22:55 ERROR]: #!#!     at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122)
[12:22:55 ERROR]: #!#!     at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
[12:22:55 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[12:22:55 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[12:22:55 ERROR]: #!#!     at gyurix.commands.CustomCommandMap.dispatch(CustomCommandMap.java:89)
[12:22:55 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:675)
[12:22:55 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchServerCommand(CraftServer.java:638)
[12:22:55 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.DedicatedServer.aM(DedicatedServer.java:441)
[12:22:55 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:404)
[12:22:55 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:763)
[12:22:55 ERROR]: #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:661)
[12:22:55 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[12:22:55 ERROR]: #!#!
[12:22:55 ERROR]: #!#! Version Information:
[12:22:55 ERROR]: #!#!   Skript: 2.2-dev29
[12:22:55 ERROR]: #!#!   Bukkit: 1.11.2-R0.1-SNAPSHOT
[12:22:55 ERROR]: #!#!   Minecraft: 1.11.2
[12:22:55 ERROR]: #!#!   Java: 1.8.0_131 (Java HotSpot(TM) 64-Bit Server VM 25.131-b11)
[12:22:55 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[12:22:55 ERROR]: #!#!
[12:22:55 ERROR]: #!#! Running CraftBukkit: false
[12:22:55 ERROR]: #!#!
[12:22:55 ERROR]: #!#! Current node: null
[12:22:55 ERROR]: #!#! Current item: null
[12:22:55 ERROR]: #!#!
[12:22:55 ERROR]: #!#! Thread: Server thread
[12:22:55 ERROR]: #!#!
[12:22:55 ERROR]: #!#! End of Error.
[12:22:55 ERROR]: #!#!

Please~~~~~~~~

**Comment by bensku** [comment]
Reported already...

**Comment by Wqrld** [comment]
Extreme bump but what was the problem with this? i am having this error too
