### ISSUE TITLE
Error loading Skript

### ISSUE THREAD

**Issue by CarloDrift** [bensku/Skript#730]
An error appears in the console during the loading of my scripts, here it is.

> [13:33:37] [Server thread/ERROR]: #!#! 
[13:33:37] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[13:33:37] [Server thread/ERROR]: #!#! 
[13:33:37] [Server thread/ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[13:33:37] [Server thread/ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[13:33:37] [Server thread/ERROR]: #!#! and check whether this error has already been reported.
[13:33:37] [Server thread/ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[13:33:37] [Server thread/ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[13:33:37] [Server thread/ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[13:33:37] [Server thread/ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[13:33:37] [Server thread/ERROR]: #!#! 
[13:33:37] [Server thread/ERROR]: #!#! Stack trace:
[13:33:37] [Server thread/ERROR]: #!#! java.lang.NullPointerException
[13:33:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:191)
[13:33:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:55)
[13:33:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:54)
[13:33:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:65)
[13:33:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93)
[13:33:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
[13:33:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.events.EvtScript.register(EvtScript.java:63)
[13:33:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:519)
[13:33:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:247)
[13:33:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:201)
[13:33:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript$2.run(Skript.java:406)
[13:33:37] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[13:33:37] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[13:33:37] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
[13:33:37] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[13:33:37] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[13:33:37] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[13:33:37] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)
[13:33:37] [Server thread/ERROR]: #!#! 
[13:33:37] [Server thread/ERROR]: #!#! Version Information:
[13:33:37] [Server thread/ERROR]: #!#!   Skript: 2.2-dev25
[13:33:37] [Server thread/ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[13:33:37] [Server thread/ERROR]: #!#!   Minecraft: 1.8.8
[13:33:37] [Server thread/ERROR]: #!#!   Java: 1.8.0_60 (Java HotSpot(TM) 64-Bit Server VM 25.60-b23)
[13:33:37] [Server thread/ERROR]: #!#!   OS: Linux amd64 3.5.0-49-generic
[13:33:37] [Server thread/ERROR]: #!#! 
[13:33:37] [Server thread/ERROR]: #!#! Running CraftBukkit: false
[13:33:37] [Server thread/ERROR]: #!#! 
[13:33:37] [Server thread/ERROR]: #!#! Current node: on load: (uhcmeetup.sk, line 590)
[13:33:37] [Server thread/ERROR]: #!#! Current item: UHCMeetupGameStop("d")
[13:33:37] [Server thread/ERROR]: #!#! 
[13:33:37] [Server thread/ERROR]: #!#! Thread: Server thread
[13:33:37] [Server thread/ERROR]: #!#! 
[13:33:37] [Server thread/ERROR]: #!#! End of Error.
[13:33:37] [Server thread/ERROR]: #!#! 

>

**Comment by Syst3ms** [comment]
Outdated Skript version and 1.8 is not supported. To close. The issue has been fixed in some version above dev25, but you're paying the price for not updating there.

**Comment by TheBentoBox** [comment]
What Syst3ms said. All I can say is to make sure you're not calling a function in a script that loads before the one the function is declared in. Otherwise we can't provide error support for people not using the latest version (AKA 1.8 users).
