### ISSUE TITLE
`on portal` event not working in 1.9

### ISSUE THREAD

**Issue by LuckyBowers** [bensku/Skript#74]
I am using the on portal event on my 1.9.2 server, and when player enters portal, it gives this console error:
`[13:34:13 ERROR]: Could not pass event PlayerPortalEvent to Skript v2.2-dev13
java.lang.NullPointerException
        at ch.njol.skript.hooks.regions.WorldGuardHook.getRegionsAt_i(WorldGuardHook.java:243) ~[?:?]
        at ch.njol.skript.hooks.regions.RegionsPlugin.getRegionsAt(RegionsPlugin.java:94) ~[?:?]
        at ch.njol.skript.hooks.regions.events.EvtRegionBorder$3.execute(EvtRegionBorder.java:161) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-944aa20-8d16fc0]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-944aa20-8d16fc0]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-944aa20-8d16fc0]
        at net.minecraft.server.v1_9_R1.PlayerList.changeDimension(PlayerList.java:728) [spigot.jar:git-Spigot-944aa20-8d16fc0]
        at net.minecraft.server.v1_9_R1.EntityPlayer.c(EntityPlayer.java:537) [spigot.jar:git-Spigot-944aa20-8d16fc0]
        at net.minecraft.server.v1_9_R1.Entity.U(Entity.java:338) [spigot.jar:git-Spigot-944aa20-8d16fc0]
        at net.minecraft.server.v1_9_R1.EntityLiving.U(EntityLiving.java:181) [spigot.jar:git-Spigot-944aa20-8d16fc0]
        at net.minecraft.server.v1_9_R1.Entity.m(Entity.java:299) [spigot.jar:git-Spigot-944aa20-8d16fc0]
        at net.minecraft.server.v1_9_R1.EntityLiving.m(EntityLiving.java:1701) [spigot.jar:git-Spigot-944aa20-8d16fc0]
        at net.minecraft.server.v1_9_R1.EntityHuman.m(EntityHuman.java:142) [spigot.jar:git-Spigot-944aa20-8d16fc0]
        at net.minecraft.server.v1_9_R1.EntityPlayer.k_(EntityPlayer.java:239) [spigot.jar:git-Spigot-944aa20-8d16fc0]
        at net.minecraft.server.v1_9_R1.PlayerConnection.c(PlayerConnection.java:139) [spigot.jar:git-Spigot-944aa20-8d16fc0]
        at net.minecraft.server.v1_9_R1.NetworkManager.a(NetworkManager.java:232) [spigot.jar:git-Spigot-944aa20-8d16fc0]
        at net.minecraft.server.v1_9_R1.ServerConnection.c(ServerConnection.java:141) [spigot.jar:git-Spigot-944aa20-8d16fc0]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:820) [spigot.jar:git-Spigot-944aa20-8d16fc0]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-944aa20-8d16fc0]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-944aa20-8d16fc0]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-944aa20-8d16fc0]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]`

A fix would be greatly appreciated,
thanks 👍

**Comment by bensku** [comment]
Regions support is quite bad anyway, but I'll look if I can fix this. It is problem with WorldGuard + Skript compatibility.

**Comment by bensku** [comment]
Should be fixed in latest release. Please try again.

**Comment by LuckyBowers** [comment]
Just tried newest release, and gives same or similar error:

`[21:17:45] [Server thread/ERROR]: Could not pass event PlayerPortalEvent to Skript v2.2-dev14c
java.lang.NullPointerException
	at ch.njol.skript.hooks.regions.WorldGuardHook.getRegionsAt_i(WorldGuardHook.java:247) ~[?:?]
	at ch.njol.skript.hooks.regions.RegionsPlugin.getRegionsAt(RegionsPlugin.java:94) ~[?:?]
	at ch.njol.skript.hooks.regions.events.EvtRegionBorder$3.execute(EvtRegionBorder.java:161) ~[?:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-944aa20-8d16fc0]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-944aa20-8d16fc0]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-944aa20-8d16fc0]
	at net.minecraft.server.v1_9_R1.PlayerList.changeDimension(PlayerList.java:728) [spigot.jar:git-Spigot-944aa20-8d16fc0]
	at net.minecraft.server.v1_9_R1.EntityPlayer.c(EntityPlayer.java:537) [spigot.jar:git-Spigot-944aa20-8d16fc0]
	at net.minecraft.server.v1_9_R1.Entity.U(Entity.java:338) [spigot.jar:git-Spigot-944aa20-8d16fc0]
	at net.minecraft.server.v1_9_R1.EntityLiving.U(EntityLiving.java:181) [spigot.jar:git-Spigot-944aa20-8d16fc0]
	at net.minecraft.server.v1_9_R1.Entity.m(Entity.java:299) [spigot.jar:git-Spigot-944aa20-8d16fc0]
	at net.minecraft.server.v1_9_R1.EntityLiving.m(EntityLiving.java:1701) [spigot.jar:git-Spigot-944aa20-8d16fc0]
	at net.minecraft.server.v1_9_R1.EntityHuman.m(EntityHuman.java:142) [spigot.jar:git-Spigot-944aa20-8d16fc0]
	at net.minecraft.server.v1_9_R1.EntityPlayer.k_(EntityPlayer.java:239) [spigot.jar:git-Spigot-944aa20-8d16fc0]
	at net.minecraft.server.v1_9_R1.PlayerConnection.c(PlayerConnection.java:139) [spigot.jar:git-Spigot-944aa20-8d16fc0]
	at net.minecraft.server.v1_9_R1.NetworkManager.a(NetworkManager.java:232) [spigot.jar:git-Spigot-944aa20-8d16fc0]
	at net.minecraft.server.v1_9_R1.ServerConnection.c(ServerConnection.java:141) [spigot.jar:git-Spigot-944aa20-8d16fc0]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:820) [spigot.jar:git-Spigot-944aa20-8d16fc0]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-944aa20-8d16fc0]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-944aa20-8d16fc0]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-944aa20-8d16fc0]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]`

**Comment by LuckyBowers** [comment]
any updates on this getting fixed?

**Comment by bensku** [comment]
WorldGuard API is working incorrectly. No idea how to fix this.

**Comment by itismejoey** [comment]
`on portal enter:` works fine for me since dev13d

**Comment by bensku** [comment]
Assuming that this works; if it probable won't fix.
