### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by bertek41** [bensku/Skript#740]
Latest skript java 8 spigot 1.8.8
Hastebin: https://hastebin.com/biqijukaxu.vbs
`[14:01:27] [Server thread/INFO]: [Skript] Enabling Skript v2.2-dev29
[14:01:28] [Server thread/ERROR]: Error occurred while enabling Skript v2.2-dev29 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/Particle
	at ch.njol.skript.util.VisualEffect$Type.<clinit>(VisualEffect.java:93) ~[?:?]
	at ch.njol.skript.util.VisualEffect.<clinit>(VisualEffect.java:262) ~[?:?]
	at ch.njol.skript.classes.data.SkriptClasses.<clinit>(SkriptClasses.java:889) ~[?:?]
	at ch.njol.skript.Skript.onEnable(Skript.java:277) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-5f38d38-12698ea]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-5f38d38-12698ea]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-5f38d38-12698ea]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-5f38d38-12698ea]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-5f38d38-12698ea]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-5f38d38-12698ea]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.ClassNotFoundException: org.bukkit.Particle
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot.jar:git-Spigot-5f38d38-12698ea]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-5f38d38-12698ea]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
	... 15 more`

**Comment by bertek41** [comment]
Yeah latest version doesn't support 1.8.8 and in the dev25 can't use on chat event :/
