### ISSUE TITLE
Internal Error Occured while reloading skript

### ISSUE THREAD

**Issue by Elsmok** [bensku/Skript#741]
Hello my name is alex and when i try to reload my scripts it says an internal error occurred while attempting to perform this command.
I am on MC 1.12 and i am using Skript version 2.2-dev29
Here are the erros i receive from the console when i execute "/sk reload <script>"

```
22.07 17:56:12 [Server] INFO Elsmok issued server command: /sk reload Kits
22.07 17:56:12 [Server] ERROR null
22.07 17:56:12 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'sk' in plugin Skript v2.2-dev29
22.07 17:56:12 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.1.12.jar:git-Spigot-99c2a37-f078eed]
22.07 17:56:12 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.1.12.jar:git-Spigot-99c2a37-f078eed]
22.07 17:56:12 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot.1.12.jar:git-Spigot-99c2a37-f078eed]
22.07 17:56:12 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1385) [spigot.1.12.jar:git-Spigot-99c2a37-f078eed]
22.07 17:56:12 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1220) [spigot.1.12.jar:git-Spigot-99c2a37-f078eed]
22.07 17:56:12 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.1.12.jar:git-Spigot-99c2a37-f078eed]
22.07 17:56:12 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.1.12.jar:git-Spigot-99c2a37-f078eed]
22.07 17:56:12 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.1.12.jar:git-Spigot-99c2a37-f078eed]
22.07 17:56:12 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
22.07 17:56:12 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
22.07 17:56:12 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.1.12.jar:git-Spigot-99c2a37-f078eed]
22.07 17:56:12 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot.1.12.jar:git-Spigot-99c2a37-f078eed]
22.07 17:56:12 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot.1.12.jar:git-Spigot-99c2a37-f078eed]
22.07 17:56:12 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.1.12.jar:git-Spigot-99c2a37-f078eed]
22.07 17:56:12 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.1.12.jar:git-Spigot-99c2a37-f078eed]
22.07 17:56:12 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
22.07 17:56:12 [Server] INFO Caused by: java.lang.NoClassDefFoundError: com/comphenix/protocol/reflect/ObjectEnum
22.07 17:56:12 [Server] INFO at com.pie.tlatoani.Mundo$24.parse(Mundo.java:566) ~[?:?]
22.07 17:56:12 [Server] INFO at com.pie.tlatoani.Mundo$24.parse(Mundo.java:563) ~[?:?]
22.07 17:56:12 [Server] INFO at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:420) ~[?:?]
22.07 17:56:12 [Server] INFO at ch.njol.skript.registrations.Classes.parse(Classes.java:449) ~[?:?]
22.07 17:56:12 [Server] INFO at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:95) ~[?:?]
22.07 17:56:12 [Server] INFO at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:84) ~[?:?]
22.07 17:56:12 [Server] INFO at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:1) ~[?:?]
22.07 17:56:12 [Server] INFO at ch.njol.skript.conditions.CondCompare.init(CondCompare.java:179) ~[?:?]
22.07 17:56:12 [Server] INFO at ch.njol.skript.conditions.CondCompare.init(CondCompare.java:130) ~[?:?]
22.07 17:56:12 [Server] INFO at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:247) ~[?:?]
```

**Comment by TheBentoBox** [comment]
If you notice this line:

```
22.07 17:56:12 [Server] INFO Caused by: java.lang.NoClassDefFoundError: com/comphenix/protocol/reflect/ObjectEnum
```

You can see that this is a ProtocolLib issue, which likely means you're running incompatible versions of ProtocolLib and MundoSK (or some other Skript addon that requires ProtocolLib, if there are any). Regardless, this doesn't appear to be a vanilla Skript issue to me, which means it doesn't belong here. Check with the MundoSK dev to make sure you have the right versions of both of those plugins installed.
