### ISSUE TITLE
Skript Error

### ISSUE THREAD

**Issue by LandonPlayz2** [bensku/Skript#743]
Why do I have this console error that is lagging my server.

```
22.07 19:02:12 [Server] ERROR #!#! 
22.07 19:02:12 [Server] ERROR #!#! [Skript] Severe Error:
22.07 19:02:12 [Server] ERROR #!#! Unexpected error while checking for a new version of Skript
22.07 19:02:12 [Server] ERROR #!#! 
22.07 19:02:12 [Server] ERROR #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
22.07 19:02:12 [Server] ERROR #!#! If you're a server admin however please go to http://dev.bukkit.org/server-mods/skript/tickets/
22.07 19:02:12 [Server] ERROR #!#! and check whether this error has already been reported.
22.07 19:02:12 [Server] ERROR #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it,
22.07 19:02:12 [Server] ERROR #!#! and describe what you did before it happened and/or what you think caused the error.
22.07 19:02:12 [Server] ERROR #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
22.07 19:02:12 [Server] ERROR #!#! By following this guide fixing the error should be easy and done fast.
22.07 19:02:12 [Server] ERROR #!#! 
22.07 19:02:12 [Server] ERROR #!#! Stack trace:
22.07 19:02:12 [Server] ERROR #!#! javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1]
22.07 19:02:12 [Server] INFO Message: Premature end of file.
22.07 19:02:12 [Server] ERROR #!#!     at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:604)
22.07 19:02:12 [Server] ERROR #!#!     at com.sun.xml.internal.stream.XMLEventReaderImpl.nextEvent(XMLEventReaderImpl.java:83)
22.07 19:02:12 [Server] ERROR #!#!     at ch.njol.skript.Updater.getChangelogs(Updater.java:286)
22.07 19:02:12 [Server] ERROR #!#!     at ch.njol.skript.Updater$2.run(Updater.java:210)
22.07 19:02:12 [Server] ERROR #!#!     at java.lang.Thread.run(Thread.java:748)
22.07 19:02:12 [Server] ERROR #!#! 
22.07 19:02:12 [Server] ERROR #!#! Version Information:
22.07 19:02:12 [Server] ERROR #!#!   Skript: 2.2-Mineplex-Core-Patch
22.07 19:02:12 [Server] ERROR #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
22.07 19:02:12 [Server] ERROR #!#!   Minecraft: 1.8.8
22.07 19:02:12 [Server] ERROR #!#!   Java: 1.8.0_131 (OpenJDK 64-Bit Server VM 25.131-b11)
22.07 19:02:12 [Server] ERROR #!#!   OS: Linux amd64 2.6.32-642.4.2.el6.x86_64
22.07 19:02:12 [Server] ERROR #!#! 
22.07 19:02:12 [Server] ERROR #!#! Running CraftBukkit: false
```

**Comment by TheBentoBox** [comment]
You're not even running this fork's version of Skript, and even if you were this fork doesn't support 1.8. You'll have to go ask whoever made the "2.2-Mineplex-Core-Patch" version of Skript that you're using.
