### ISSUE TITLE
Errir with parse

### ISSUE THREAD

**Issue by Spartan9802** [bensku/Skript#755]
[20:00:50] [Server thread/WARN]: #!#! 
[20:00:50] [Server thread/ERROR]: #!#! 
[20:00:50] [Server thread/ERROR]: #!#! 
[20:00:50] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[20:00:50] [Server thread/ERROR]: #!#! 
[20:00:50] [Server thread/ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[20:00:50] [Server thread/ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[20:00:50] [Server thread/ERROR]: #!#! and check whether this error has already been reported.
[20:00:50] [Server thread/ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[20:00:50] [Server thread/ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[20:00:50] [Server thread/ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[20:00:50] [Server thread/ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[20:00:50] [Server thread/ERROR]: #!#! 
[20:00:50] [Server thread/ERROR]: #!#! Stack trace:
[20:00:50] [Server thread/ERROR]: #!#! java.lang.NullPointerException
[20:00:50] [Server thread/ERROR]: #!#!     at java.util.LinkedList$ListItr.next(LinkedList.java:893)
[20:00:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.log.SkriptLogger.log(SkriptLogger.java:174)
[20:00:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.log.SkriptLogger.log(SkriptLogger.java:166)
[20:00:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript.error(Skript.java:1149)
[20:00:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.classes.data.BukkitClasses$18.parse(BukkitClasses.java:923)
[20:00:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.classes.data.BukkitClasses$18.parse(BukkitClasses.java:1)
[20:00:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.ExprParse.get(ExprParse.java:149)
[20:00:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:105)
[20:00:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:270)
[20:00:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:54)
[20:00:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:65)
[20:00:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93)
[20:00:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
[20:00:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:91)
[20:00:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.Function.execute(Function.java:109)
[20:00:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:191)
[20:00:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:55)
[20:00:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:54)
[20:00:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:65)
[20:00:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93)
[20:00:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
[20:00:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:152)
[20:00:50] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:112)
[20:00:50] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[20:00:50] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:36)
[20:00:50] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[20:00:50] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[20:00:50] [Server thread/ERROR]: #!#!     at com.btk5h.skriptmirror.skript.EvtByReflection.lambda$static$0(EvtByReflection.java:49)
[20:00:50] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[20:00:50] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:36)
[20:00:50] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[20:00:50] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[20:00:50] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:270)
[20:00:50] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126)
[20:00:50] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18)
[20:00:50] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[20:00:50] [Server thread/ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[20:00:50] [Server thread/ERROR]: #!#!     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[20:00:50] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[20:00:50] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[20:00:50] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[20:00:50] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[20:00:50] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[20:00:50] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[20:00:50] [Server thread/ERROR]: #!#! 
[20:00:50] [Server thread/ERROR]: #!#! Version Information:
[20:00:50] [Server thread/ERROR]: #!#!   Skript: 2.2-dev25
[20:00:50] [Server thread/ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[20:00:50] [Server thread/ERROR]: #!#!   Minecraft: 1.8.8
[20:00:50] [Server thread/ERROR]: #!#!   Java: 1.8.0_131 (Java HotSpot(TM) 64-Bit Server VM 25.131-b11)
[20:00:50] [Server thread/ERROR]: #!#!   OS: Linux amd64 3.14.32-xxxx-grs-ipv6-64
[20:00:50] [Server thread/ERROR]: #!#! 
[20:00:50] [Server thread/ERROR]: #!#! Running CraftBukkit: false
[20:00:50] [Server thread/ERROR]: #!#! 
[20:00:50] [Server thread/ERROR]: #!#! Current node: null
[20:00:50] [Server thread/ERROR]: #!#! Current item: set {_block}(as java.lang.Object) to "%{_block}(as java.lang.Object)%" parsed as an item stack
[20:00:50] [Server thread/ERROR]: #!#! 
[20:00:50] [Server thread/ERROR]: #!#! Thread: Server thread
[20:00:50] [Server thread/ERROR]: #!#! 
[20:00:50] [Server thread/ERROR]: #!#! End of Error.
[20:00:50] [Server thread/WARN]: #!#! 
[20:00:50] [Server thread/WARN]: #!#! 
[20:00:50] [Server thread/WARN]: #!#! [Umbaska] List of addons: 
[20:00:50] [Server thread/WARN]: #!#! SkWorldCube v1.0Skellett v1.8.2aLargeSk v1.2-BetaVixio v1.1.3skRayFall v1.9.7SharpSK v1.5.7BWildSkript v1.8MundoSK v1.7.5-BETA.7.84PirateSK v1.0skDragon v0.13.1ExertSK v0.1.3bskUtilities v0.9.0Reqn v1.2.0Umbaska v2.0 Beta 5.5.1HookSk v0.2SkQuery v3.21.4SkExtras v3.9.1skript-mirror v0.6.0ExtrasSK v1.1TuSKe v1.8.1RandomSK v2.0WolvSK v1.5.6SkStuff v1.6.4SkMorkaz v0.35
[20:00:50] [Server thread/WARN]: #!#! 
[20:00:50] [Server thread/ERROR]: #!#!

**Comment by TheBentoBox** [comment]
You're using an old version and this version is no longer compatible with 1.8. Sorry, try experimenting with addons to see if removing some fixes it. We can't help past that.
