### ISSUE TITLE
An error (Paper 1.8.8)

### ISSUE THREAD

**Issue by rplcnn** [bensku/Skript#756]
[23:02:40] [Server thread/ERROR]: Error occurred while enabling Skript v2.2-dev29 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/Particle
 at ch.njol.skript.util.VisualEffect$Type.<clinit>(VisualEffect.java:93) ~[?:?]
 at ch.njol.skript.util.VisualEffect.<clinit>(VisualEffect.java:262) ~[?:?]
 at ch.njol.skript.classes.data.SkriptClasses.<clinit>(SkriptClasses.java:889) ~[?:?]
 at ch.njol.skript.Skript.onEnable(Skript.java:277) ~[?:?]
 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-PaperSpigot-"8b18730"]
 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [spigot.jar:git-PaperSpigot-"8b18730"]
 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [spigot.jar:git-PaperSpigot-"8b18730"]
 at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [spigot.jar:git-PaperSpigot-"8b18730"]
 at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [spigot.jar:git-PaperSpigot-"8b18730"]
 at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [spigot.jar:git-PaperSpigot-"8b18730"]
 at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [spigot.jar:git-PaperSpigot-"8b18730"]
 at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [spigot.jar:git-PaperSpigot-"8b18730"]
 at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [spigot.jar:git-PaperSpigot-"8b18730"]
 at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [spigot.jar:git-PaperSpigot-"8b18730"]
 at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.ClassNotFoundException: org.bukkit.Particle
 at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[spigot.jar:git-PaperSpigot-"8b18730"]
 at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[spigot.jar:git-PaperSpigot-"8b18730"]
 at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
 at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
 ... 15 more
[23:02:40] [Server thread/INFO]: [Skript] Disabling Skript v2.2-dev29

**Comment by Snow-Pyon** [comment]
This fork doesn't support any version lower than 1.9, you can use the dev25 (the last version that is *stable* and works on 1.8.8) if you want.
