### ISSUE TITLE
weird error

### ISSUE THREAD

**Issue by Feerko** [bensku/Skript#757]
[11:50:59] [Server thread/ERROR]: #!#! 
[11:50:59] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[11:50:59] [Server thread/ERROR]: #!#! Unexpected error while executing effect command 'send "%amount of worlds%"' by 'Feerko'
[11:50:59] [Server thread/ERROR]: #!#! 
[11:50:59] [Server thread/ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[11:50:59] [Server thread/ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[11:50:59] [Server thread/ERROR]: #!#! and check whether this error has already been reported.
[11:50:59] [Server thread/ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[11:50:59] [Server thread/ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[11:50:59] [Server thread/ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[11:50:59] [Server thread/ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[11:50:59] [Server thread/ERROR]: #!#! 
[11:50:59] [Server thread/ERROR]: #!#! Stack trace:
[11:50:59] [Server thread/ERROR]: #!#!   warning: no/empty exception given, dumping current stack trace instead
[11:50:59] [Server thread/ERROR]: #!#! java.lang.Exception: java.lang.NullPointerException
[11:50:59] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript.exception(Skript.java:1248)
[11:50:59] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript.exception(Skript.java:1212)
[11:50:59] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.handleEffectCommand(Commands.java:307)
[11:50:59] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands$4$1.call(Commands.java:227)
[11:50:59] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands$4$1.call(Commands.java:1)
[11:50:59] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftFuture.run(CraftFuture.java:89)
[11:50:59] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356)
[11:50:59] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:832)
[11:50:59] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[11:50:59] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:766)
[11:50:59] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:664)
[11:50:59] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[11:50:59] [Server thread/ERROR]: #!#! Caused by: java.lang.NullPointerException
[11:50:59] [Server thread/ERROR]: #!#! 
[11:50:59] [Server thread/ERROR]: #!#! Version Information:
[11:50:59] [Server thread/ERROR]: #!#!   Skript: 2.2-dev29
[11:50:59] [Server thread/ERROR]: #!#!   Bukkit: 1.12-R0.1-SNAPSHOT
[11:50:59] [Server thread/ERROR]: #!#!   Minecraft: 1.12
[11:50:59] [Server thread/ERROR]: #!#!   Java: 1.8.0_131 (OpenJDK 64-Bit Server VM 25.131-b11)
[11:50:59] [Server thread/ERROR]: #!#!   OS: Linux amd64 4.9.33-mod-std-ipv6-64
[11:50:59] [Server thread/ERROR]: #!#! 
[11:50:59] [Server thread/ERROR]: #!#! Running CraftBukkit: false
[11:50:59] [Server thread/ERROR]: #!#! 
[11:50:59] [Server thread/ERROR]: #!#! Current node: null
[11:50:59] [Server thread/ERROR]: #!#! Current item: null
[11:50:59] [Server thread/ERROR]: #!#! 
[11:50:59] [Server thread/ERROR]: #!#! Thread: Server thread
[11:50:59] [Server thread/ERROR]: #!#! 
[11:50:59] [Server thread/ERROR]: #!#! End of Error.
[11:50:59] [Server thread/ERROR]: #!#!

**Comment by bensku** [comment]
Any addons used?

**Comment by bensku** [comment]
Closed due to no response given.
