### ISSUE TITLE
Problem with MySQL and "UnparsedLiterals must be converted before use"

### ISSUE THREAD

**Issue by marcelltukora** [bensku/Skript#760]
LOG:

`[21:33:31 ERROR]: #!#!
[21:33:31 ERROR]: #!#! [Skript] Severe Error:
[21:33:31 ERROR]: #!#!
[21:33:31 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[21:33:31 ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[21:33:31 ERROR]: #!#! and check whether this error has already been reported.
[21:33:31 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[21:33:31 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[21:33:31 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[21:33:31 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[21:33:31 ERROR]: #!#!
[21:33:31 ERROR]: #!#! Stack trace:
[21:33:31 ERROR]: #!#! ch.njol.skript.SkriptAPIException: UnparsedLiterals must be converted before use
[21:33:31 ERROR]: #!#!     at ch.njol.skript.lang.UnparsedLiteral.invalidAccessException(UnparsedLiteral.java:273)
[21:33:31 ERROR]: #!#!     at ch.njol.skript.lang.UnparsedLiteral.iterator(UnparsedLiteral.java:308)
[21:33:31 ERROR]: #!#!     at ch.njol.skript.lang.UnparsedLiteral.iterator(UnparsedLiteral.java:1)
[21:33:31 ERROR]: #!#!     at ch.njol.skript.expressions.ExprElement.get(ExprElement.java:72)
[21:33:31 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:103)
[21:33:31 ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:268)
[21:33:31 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[21:33:31 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[21:33:31 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[21:33:31 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
[21:33:31 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:220)
[21:33:31 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:182)
[21:33:31 ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:268)
[21:33:31 ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:163)
[21:33:31 ERROR]: #!#!     at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35)
[21:33:31 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[21:33:31 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[21:33:31 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514)
[21:33:31 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499)
[21:33:31 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1416)
[21:33:31 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1229)
[21:33:31 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[21:33:31 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[21:33:31 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[21:33:31 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[21:33:31 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
[21:33:31 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[21:33:31 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:842)
[21:33:31 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[21:33:31 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:766)
[21:33:31 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:664)
[21:33:31 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[21:33:31 ERROR]: #!#!
[21:33:31 ERROR]: #!#! Version Information:
[21:33:31 ERROR]: #!#!   Skript: 2.2-dev29
[21:33:31 ERROR]: #!#!   Bukkit: 1.12-R0.1-SNAPSHOT
[21:33:31 ERROR]: #!#!   Minecraft: 1.12
[21:33:31 ERROR]: #!#!   Java: 1.8.0_131 (Java HotSpot(TM) 64-Bit Server VM 25.131-b11)
[21:33:31 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[21:33:31 ERROR]: #!#!
[21:33:31 ERROR]: #!#! Running CraftBukkit: false
[21:33:31 ERROR]: #!#!
[21:33:31 ERROR]: #!#! Current node: null
[21:33:31 ERROR]: #!#! Current item: set {_get}(as java.lang.Object) to the first element of 'objects in column "coin" from result of query "SELECT coin FROM users WHERE name = '%command sender%'"'
[21:33:31 ERROR]: #!#!
[21:33:31 ERROR]: #!#! Thread: Server thread
[21:33:31 ERROR]: #!#!
[21:33:31 ERROR]: #!#! End of Error.
[21:33:31 ERROR]: #!#!`

Skript:

`command test:
	trigger:
		set {_get} to first element out of objects in column "coin" from result of query "SELECT coin FROM users WHERE name = '%command sender%'"`

On command Run:
`An internal error occured while attempting to to perform this command.`

Anyone can help me?

**Comment by marcelltukora** [comment]
sry for unformatted Skript: command test

**Comment by bensku** [comment]
Addon syntax, so nope.
