### ISSUE TITLE
dev 30 weirdness

### ISSUE THREAD

**Issue by melinstagibson** [bensku/Skript#779]
So this stopped working after updating to dev30b

```
the skull of the player is neither an item stack nor an entity type (holo.sk, line 129: drop 1 of player's skull at player')
```
i tried with player's tool aswell, same error.
same with this:
```
drop {_f} of gold ingot
```
{_f} is a number (int)
throws:
{_f} of golden_ingot is neither an item type nor an experience point (voterstuff.sk, line 130: drop {_f} of gold ingot')

and last i have this weird error i get when trying to reload this function:
```
function checkdb() :: boolean:
        set {_conn} to mysql result of query "SELECT * FROM arena.test"
        if {_conn} is set:
                return true
        else:
                connect to mysql
                set {_conn} to mysql result of query "SELECT * FROM arena.test"
                if {_conn} is set:
                        return true
                else:
                        return false
                        broadcast "&b[&cERROR&b] &eNo Connection to Database, please report this to a Staff Member"
                        stop
```
Error:
```
> sk reload arenakits
[07:36:04 INFO]: [Skript] Reloading arenakits.sk...
[07:36:04 ERROR]: #!#!
[07:36:04 ERROR]: #!#! [Skript] Severe Error:
[07:36:04 ERROR]: #!#! Exception occurred in Skript's main command
[07:36:04 ERROR]: #!#! Used command: /sk reload arenakits
[07:36:04 ERROR]: #!#!
[07:36:04 ERROR]: #!#! Something went horribly wrong with Skript.
[07:35:12 ERROR]: #!#! This issue is NOT your fault! You can't probably fix it yourself, either.
[07:35:12 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[07:35:12 ERROR]: #!#! Here is full list of them:
[07:35:12 ERROR]: #!#! skRayFall (http://sk.rayfall.net/) WolvSK skUtilities (https://tim740.github.io/) SkStuff SkQuery Skellett (https://forums.skunity.com/resources/skellett-the-addon-with-a-beast-name.24/) MundoSK SharpSK TuSKe (github.com/Tuke-Nuke/TuSKe)
[07:35:12 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[07:35:12 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[07:35:12 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[07:35:12 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[07:35:12 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[07:35:12 ERROR]: #!#! Only if the author tells you to do so, report it as Skript issue (url below)
[07:35:12 ERROR]: #!#! Issue tracker: https://github.com/bensku/Skript/issues (only if you know what you're doing!)
[07:35:12 ERROR]: #!#!
[07:35:12 ERROR]: #!#! Stack trace:
[07:35:12 ERROR]: #!#! java.lang.NullPointerException
[07:35:12 ERROR]: #!#!     at ch.njol.skript.lang.function.Functions.registerCaller(Functions.java:96)
[07:35:12 ERROR]: #!#!     at ch.njol.skript.lang.function.FunctionReference.validateFunction(FunctionReference.java:167)
[07:35:12 ERROR]: #!#!     at ch.njol.skript.lang.function.Functions.validateFunctions(Functions.java:302)
[07:35:12 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.unloadScript(ScriptLoader.java:790)
[07:35:12 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:186)
[07:35:12 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[07:35:12 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[07:35:12 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:666)
[07:35:12 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:629)
[07:35:12 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:462)
[07:35:12 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:425)
[07:35:12 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[07:35:12 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[07:35:12 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[07:35:12 ERROR]: #!#!
[07:35:12 ERROR]: #!#! Version Information:
[07:35:12 ERROR]: #!#!   Skript: 2.2-dev30b (latest)
[07:35:12 ERROR]: #!#!   Bukkit: 1.12.1-R0.1-SNAPSHOT
[07:35:12 ERROR]: #!#!   Minecraft: 1.12.1
[07:35:12 ERROR]: #!#!   Java: 1.8.0_131 (OpenJDK 64-Bit Server VM 25.131-b11)
[07:35:12 ERROR]: #!#!   OS: Linux amd64 4.10.0-22-generic
[07:35:12 ERROR]: #!#!
[07:35:12 ERROR]: #!#! Running CraftBukkit: false
[07:35:12 ERROR]: #!#! Running Spigot (or compatible): true
[07:35:12 ERROR]: #!#! Running Paper (or compatible): true
[07:35:12 ERROR]: #!#!
[07:35:12 ERROR]: #!#! Current node: checkdb() (duel.sk, line 51)
[07:35:12 ERROR]: #!#! Current item: null
[07:35:12 ERROR]: #!#! Thread: Server thread
[07:35:12 ERROR]: #!#!
[07:35:12 ERROR]: #!#! Language: english
[07:35:12 ERROR]: #!#! Link parse mode: DISABLED
[07:35:12 ERROR]: #!#!
[07:35:12 ERROR]: #!#! End of Error.
[07:35:12 ERROR]: #!#!
```
I only get this error when reloading that particular Skript. when i do /sk reload all there is no error

**Comment by melinstagibson** [comment]
For the last, the large error:
I tried to place the function in a seperate skript now which seems to work. i only had this error when trying to reload a skript where this function was defined AND called.
if i used /sk reload all it works. If i have the function and all the calls in a seperate skripts and reload individually it works.

**Comment by bensku** [comment]
Good information about this function error. I think I have an idea what causes it.

Other errors, will need to investigate.

**Comment by bensku** [comment]
Other errors fixed, now the exception.

**Comment by bensku** [comment]
Anything of these still happens?
