### ISSUE TITLE
Exception occurred in Skript's main command

### ISSUE THREAD

**Issue by LuckyBowers** [bensku/Skript#78]
`
[21:16:33] [Server thread/ERROR]: #!#! 
[21:16:33] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[21:16:33] [Server thread/ERROR]: #!#! Exception occurred in Skript's main command
[21:16:33] [Server thread/ERROR]: #!#! Used command: /sk reload core
[21:16:33] [Server thread/ERROR]: #!#! 
[21:16:33] [Server thread/ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[21:16:33] [Server thread/ERROR]: #!#! If you're a server admin however please go to http://dev.bukkit.org/server-mods/skript/tickets/
[21:16:33] [Server thread/ERROR]: #!#! and check whether this error has already been reported.
[21:16:33] [Server thread/ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it,
[21:16:33] [Server thread/ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[21:16:33] [Server thread/ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[21:16:33] [Server thread/ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[21:16:33] [Server thread/ERROR]: #!#! 
[21:16:33] [Server thread/ERROR]: #!#! Stack trace:
[21:16:33] [Server thread/ERROR]: #!#! java.lang.NullPointerException
[21:16:33] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.Functions.clearFunctions(Functions.java:196)
[21:16:33] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.removeTriggers(SkriptEventHandler.java:255)
[21:16:33] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.unloadScript_(ScriptLoader.java:615)
[21:16:33] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.unloadScript(ScriptLoader.java:609)
[21:16:33] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:159)
[21:16:33] [Server thread/ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[21:16:33] [Server thread/ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[21:16:33] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645)
[21:16:33] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1350)
[21:16:33] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1185)
[21:16:33] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[21:16:33] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[21:16:33] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[21:16:33] [Server thread/ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[21:16:33] [Server thread/ERROR]: #!#!     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[21:16:33] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45)
[21:16:33] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721)
[21:16:33] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
[21:16:33] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660)
[21:16:33] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559)
[21:16:33] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)
[21:16:33] [Server thread/ERROR]: #!#! 
[21:16:33] [Server thread/ERROR]: #!#! Version Information:
[21:16:33] [Server thread/ERROR]: #!#!   Skript: 2.2-dev14c
[21:16:33] [Server thread/ERROR]: #!#!   Bukkit: 1.9.2-R0.1-SNAPSHOT
[21:16:33] [Server thread/ERROR]: #!#!   Minecraft: 1.9.2
[21:16:33] [Server thread/ERROR]: #!#!   Java: 1.8.0_77 (Java HotSpot(TM) 64-Bit Server VM 25.77-b03)
[21:16:33] [Server thread/ERROR]: #!#!   OS: Linux amd64 3.14.32-xxxx-grs-ipv6-64
[21:16:33] [Server thread/ERROR]: #!#! 
[21:16:33] [Server thread/ERROR]: #!#! Running CraftBukkit: false
[21:16:33] [Server thread/ERROR]: #!#! 
[21:16:33] [Server thread/ERROR]: #!#! Current node: null
[21:16:33] [Server thread/ERROR]: #!#! Current item: null
[21:16:33] [Server thread/ERROR]: #!#! 
[21:16:33] [Server thread/ERROR]: #!#! Thread: Server thread
[21:16:33] [Server thread/ERROR]: #!#! 
[21:16:33] [Server thread/ERROR]: #!#! End of Error.
[21:16:33] [Server thread/ERROR]: #!#! 
`

**Comment by bensku** [comment]
Do you have allow functions before definations turned on?

**Comment by LuckyBowers** [comment]
no, should it be turned on? I haven't ever had ti enabled previously and everything worked fine.

**Comment by LuckyBowers** [comment]
I enabled `functions before definitions` and that stopped the error from occurring, but all my functions stopped working correctly

**Comment by bensku** [comment]
Hmm, then it is a bug with Skript. Please fall back to the older version until I have fixed this.

**Comment by bensku** [comment]
Fixed, I think.
