### ISSUE TITLE
Error while starting the server

### ISSUE THREAD

**Issue by Fargus5** [bensku/Skript#787]
[16:48:17] [Server thread/INFO]: [Skript] Enabling Skript v2.2-dev30b
[16:48:17] [Server thread/ERROR]: Error occurred while enabling Skript v2.2-dev30b (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at ch.njol.skript.registrations.Classes.registerClass(Classes.java:98) ~[?:?]
	at ch.njol.skript.classes.data.BukkitClasses.<clinit>(BukkitClasses.java:590) ~[?:?]
	at ch.njol.skript.Skript.onEnable(Skript.java:280) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-8cbfc85-202da97]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-Spigot-8cbfc85-202da97]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.IllegalArgumentException: ch.njol.skript.util.Timespan
	at ch.njol.skript.config.Option.<init>(Option.java:69) ~[?:?]
	at ch.njol.skript.SkriptConfig.<clinit>(SkriptConfig.java:80) ~[?:?]
	... 14 more

**Comment by bensku** [comment]
Are you running Spigot/Paper?

**Comment by Fargus5** [comment]
Spigot obvusly

**Comment by bensku** [comment]
Try without addona if you have any.

**Comment by Fargus5** [comment]
Ok u are right. It works without the addon wildskript! thanks
