### ISSUE TITLE
Potions aliases

### ISSUE THREAD

**Issue by melinstagibson** [bensku/Skript#803]
so im trying to store items in a mysql database but it seems to be unable to use potion aliases. I know this has been reported some time long ago but i thought it has been fixed already, so sorry for if im duplicating.

the #-ed line is my workaround which works well btw but using IDs is discouraged is what i learned :p 

here is what i did:

```
command /clone:
        permission: *
        trigger:
                set {_type} to "%player's tool%"
                set {_id} to "%id of player's tool%:%data value of player's tool%"
                set {_nbt} to "%nbt of player's tool%"
#                give player 1 of {_id} parsed as item with nbt {_nbt}
                give player 1 of {_type} parsed as item with nbt {_nbt}
```

and this is the result:

[12:51:58] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[12:51:58] [Server thread/ERROR]: #!#!
[12:51:58] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[12:51:58] [Server thread/ERROR]: #!#! This issue is NOT your fault! You can't probably fix it yourself, either.
[12:51:58] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[12:51:58] [Server thread/ERROR]: #!#! Here is full list of them:
[12:51:58] [Server thread/ERROR]: #!#! skRayFall (http://sk.rayfall.net/) skript-mirror TuSKe (github.com/Tuke-Nuke/TuSKe) skUtilities (https://tim740.github.io/) WolvSK SkStuff SkQuery MundoSK Skellett (https://forums.skunity.com/resources/skellett-the-addon-with-a-beast-name.24/) SharpSK
[12:51:58] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[12:51:58] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[12:51:58] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[12:51:58] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[12:51:58] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[12:51:58] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it as Skript issue (url below)
[12:51:58] [Server thread/ERROR]: #!#! Issue tracker: https://github.com/bensku/Skript/issues (only if you know what you're doing!)
[12:51:58] [Server thread/ERROR]: #!#!
[12:51:58] [Server thread/ERROR]: #!#! Stack trace:
[12:51:58] [Server thread/ERROR]: #!#! java.lang.NullPointerException
[12:51:58] [Server thread/ERROR]: #!#!     at me.TheBukor.SkStuff.expressions.ExprItemNBT.get(ExprItemNBT.java:48)
[12:51:58] [Server thread/ERROR]: #!#!     at me.TheBukor.SkStuff.expressions.ExprItemNBT.get(ExprItemNBT.java:15)
[12:51:58] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:104)
[12:51:58] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.ConvertedExpression.getArray(ConvertedExpression.java:158)
[12:51:58] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:268)
[12:51:58] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[12:51:58] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[12:51:58] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[12:51:58] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
[12:51:58] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:220)
[12:51:58] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:182)
[12:51:58] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:269)
[12:51:58] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:164)
[12:51:58] [Server thread/ERROR]: #!#!     at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35)
[12:51:58] [Server thread/ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[12:51:58] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[12:51:58] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514)
[12:51:58] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499)
[12:51:58] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1417)
[12:51:58] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1230)
[12:51:58] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[12:51:58] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[12:51:58] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[12:51:58] [Server thread/ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[12:51:58] [Server thread/ERROR]: #!#!     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[12:51:58] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[12:51:58] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843)
[12:51:58] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424)
[12:51:58] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[12:51:58] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[12:51:58] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[12:51:58] [Server thread/ERROR]: #!#!
[12:51:58] [Server thread/ERROR]: #!#! Version Information:
[12:51:58] [Server thread/ERROR]: #!#!   Skript: 2.2-dev30d (latest)
[12:51:58] [Server thread/ERROR]: #!#!   Bukkit: 1.12.1-R0.1-SNAPSHOT
[12:51:58] [Server thread/ERROR]: #!#!   Minecraft: 1.12.1
[12:51:58] [Server thread/ERROR]: #!#!   Java: 1.8.0_131 (OpenJDK 64-Bit Server VM 25.131-b11)
[12:51:58] [Server thread/ERROR]: #!#!   OS: Linux amd64 4.10.0-22-generic
[12:51:58] [Server thread/ERROR]: #!#!
[12:51:58] [Server thread/ERROR]: #!#! Running CraftBukkit: false
[12:51:58] [Server thread/ERROR]: #!#! Running Spigot (or compatible): true
[12:51:58] [Server thread/ERROR]: #!#! Running Paper (or compatible): true
[12:51:58] [Server thread/ERROR]: #!#!
[12:51:58] [Server thread/ERROR]: #!#! Current node: null
[12:51:58] [Server thread/ERROR]: #!#! Current item: add ([[long:1]] of {_type}(as java.lang.String) parsed as an item stack with custom NBT {_nbt}(as java.lang.String) >> ch.njol.skript.classes.data.DefaultConverters$14@1ca5b42b: org.bukkit.inventory.ItemStack->ch.njol.skript.aliases.ItemType) to the player
[12:51:58] [Server thread/ERROR]: #!#! Thread: Server thread
[12:51:58] [Server thread/ERROR]: #!#!
[12:51:58] [Server thread/ERROR]: #!#! Language: english
[12:51:58] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[12:51:58] [Server thread/ERROR]: #!#!
[12:51:58] [Server thread/ERROR]: #!#! End of Error.
[12:51:58] [Server thread/ERROR]: #!#!

**Comment by TheBentoBox** [comment]
I don't see what this has to do with storing anything in a database. This is entirely an error with SkStuff, not Skript. Make sure you're using a version of SkStuff that works on 1.12 (you'll need to use Tuke's fork).

Also as a side note, why not just make your command like this?

```
command /clone:
    trigger:
        give player 1 of player's tool
```

**Comment by melinstagibson** [comment]
can you please not mark this as invalid because it is not. 

I know i can do %player's tool% but i cant save an item type object in a database so i have to save it as a string...
and as i said in the description the part where i put the "#" is working as a workaround, the nbt part of the code is just a leftover from my tests, removing it has the same result... its not skStuff's fault.
just try the code i posted, remove the nbt part and see what happens. 
```
command /clone:
        permission: *
        trigger:
                set {_type} to "%player's tool%"
                give player 1 of {_type} parsed as item
```
here it is. it just wont throw an error if you use it with a potion (lingering or splash but the result is the same. you don't receive an item or get a water bottle. the error happens because there is nothing to apply/get the nbt from.

thanks

**Comment by TheBentoBox** [comment]
The error and the way you described it were definitely misleading IMO but that may just be my fault for misreading it. Either way, the issue with potion aliases not working is reported already in #589 .
