### ISSUE TITLE
Erro skript

### ISSUE THREAD

**Issue by RafsJR1** [bensku/Skript#814]
[13:08:15] [Server thread/ERROR]: #!#! Stack trace:
[13:08:15] [Server thread/ERROR]: #!#! java.util.ConcurrentModificationException
[13:08:15] [Server thread/ERROR]: #!#!     at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
[13:08:15] [Server thread/ERROR]: #!#!     at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
[13:08:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.EntityTracker.track(EntityTracker.java:32)
[13:08:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.WorldManager.a(WorldManager.java:18)
[13:08:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.World.a(World.java:1066)
[13:08:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.WorldServer.a(WorldServer.java:970)
[13:08:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.World.addEntity(World.java:1059)
[13:08:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.World.addEntity(World.java:987)
[13:08:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerList.moveToWorld(PlayerList.java:608)
[13:08:15] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport(CraftPlayer.java:471)
[13:08:15] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.teleport(CraftEntity.java:226)
[13:08:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.EffTeleport.execute(EffTeleport.java:97)
[13:08:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:54)
[13:08:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:65)
[13:08:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93)
[13:08:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.Delay$1.run(Delay.java:84)
[13:08:15] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[13:08:15] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[13:08:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
[13:08:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[13:08:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[13:08:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[13:08:15] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)

**Comment by TheBentoBox** [comment]
This fork isn't compatible with versions of Minecraft below 1.9.
