### ISSUE TITLE
ERROR SKRIPT

### ISSUE THREAD

**Issue by RafsJR1** [bensku/Skript#821]
[15:14:16] [Server thread/ERROR]: #!#!
[15:14:16] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[15:14:16] [Server thread/ERROR]: #!#!
[15:14:16] [Server thread/ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[15:14:16] [Server thread/ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[15:14:16] [Server thread/ERROR]: #!#! and check whether this error has already been reported.
[15:14:16] [Server thread/ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[15:14:16] [Server thread/ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[15:14:16] [Server thread/ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[15:14:16] [Server thread/ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[15:14:16] [Server thread/ERROR]: #!#!
[15:14:16] [Server thread/ERROR]: #!#! Stack trace:
[15:14:16] [Server thread/ERROR]: #!#! java.util.ConcurrentModificationException
[15:14:16] [Server thread/ERROR]: #!#!     at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
[15:14:16] [Server thread/ERROR]: #!#!     at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
[15:14:16] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.EntityTracker.track(EntityTracker.java:32)
[15:14:16] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.WorldManager.a(WorldManager.java:18)
[15:14:16] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.World.a(World.java:1066)
[15:14:16] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.WorldServer.a(WorldServer.java:970)
[15:14:16] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.World.addEntity(World.java:1059)
[15:14:16] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.World.addEntity(World.java:987)
[15:14:16] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerList.moveToWorld(PlayerList.java:608)
[15:14:16] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport(CraftPlayer.java:471)
[15:14:16] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.teleport(CraftEntity.java:226)
[15:14:16] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.EffTeleport.execute(EffTeleport.java:97)
[15:14:16] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:54)
[15:14:16] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:65)
[15:14:16] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93)
[15:14:16] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.Delay$1.run(Delay.java:84)
[15:14:16] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[15:14:16] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[15:14:16] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
[15:14:16] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[15:14:16] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[15:14:16] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[15:14:16] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)
[15:14:16] [Server thread/ERROR]: #!#!
[15:14:16] [Server thread/ERROR]: #!#! Version Information:
[15:14:16] [Server thread/ERROR]: #!#!   Skript: 2.2-dev20
[15:14:16] [Server thread/ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[15:14:16] [Server thread/ERROR]: #!#!   Minecraft: 1.8.8
[15:14:16] [Server thread/ERROR]: #!#!   Java: 1.8.0_121 (Java HotSpot(TM) 64-Bit Server VM 25.121-b13)
[15:14:16] [Server thread/ERROR]: #!#!   OS: Linux amd64 4.4.30-mod-std-ipv6-64
[15:14:16] [Server thread/ERROR]: #!#!
[15:14:16] [Server thread/ERROR]: #!#! Running CraftBukkit: false
[15:14:16] [Server thread/ERROR]: #!#!
[15:14:16] [Server thread/ERROR]: #!#! Current node: null
[15:14:16] [Server thread/ERROR]: #!#! Current item: teleport the player to [[direction:at]] {set.spawn}(as org.bukkit.Location)
[15:14:16] [Server thread/ERROR]: #!#!
[15:14:16] [Server thread/ERROR]: #!#! Thread: Server thread
[15:14:16] [Server thread/ERROR]: #!#!
[15:14:16] [Server thread/ERROR]: #!#! End of Error.
[15:14:16] [Server thread/ERROR]: #!#!

**Comment by HYPExMon5ter** [comment]
Nothing past dev26(I think, I know dev25 works on 1.8, never used 26) works on 1.8

**Comment by TheBentoBox** [comment]
They're not using something past dev25 @HYPExMon5ter, the error says dev20. However, we can't provide support for old versions since the error you're reporting might have already been fixed in a newer version, and given that the new versions aren't compatible with 1.8, you can consider this fork's support for 1.8 officially "dropped". Your best bet is to update to dev25 and hope it fixes any issues you're having, but past that you're on your own as long as you use 1.8.
