### ISSUE TITLE
size of list variable broken

### ISSUE THREAD

**Issue by melinstagibson** [bensku/Skript#826]
Edit: might have to do something with this issue: https://github.com/bensku/Skript/issues/811

The size of syntax seems to be broken in dev30d for list variables (it works with item stack size tho):
this:
```
command /arenatest:
        permission: *
        trigger:
                clear {arenakits::*}
                add "CUSTOM", "noob" and "test" to {arenakits::*}
                send "%size of {arenakits::*}%"
```
produces this:

[20:25:13 ERROR]: #!#! Stack trace:
[20:25:13 ERROR]: #!#! ch.njol.skript.SkriptAPIException: Invalid call to getSingle
[20:25:13 ERROR]: #!#!     at ch.njol.skript.lang.Variable.getSingle(Variable.java:548)
[20:25:13 ERROR]: #!#!     at com.pie.tlatoani.WorldBorder.ExprPropertyOfBorder.get(ExprPropertyOfBorder.java:69)
[20:25:13 ERROR]: #!#!     at com.pie.tlatoani.WorldBorder.ExprPropertyOfBorder.get(ExprPropertyOfBorder.java:16)
[20:25:13 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:104)
[20:25:13 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.toUnformattedString(VariableString.java:470)
[20:25:13 ERROR]: #!#!     at ch.njol.skript.lang.VariableString.getMessageComponents(VariableString.java:485)
[20:25:13 ERROR]: #!#!     at ch.njol.skript.effects.EffMessage.execute(EffMessage.java:86)
[20:25:13 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[20:25:13 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[20:25:13 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[20:25:13 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
[20:25:13 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:220)
[20:25:13 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:182)
[20:25:13 ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:269)
[20:25:13 ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:164)
[20:25:13 ERROR]: #!#!     at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35)
[20:25:13 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[20:25:13 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[20:25:13 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514)
[20:25:13 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499)
[20:25:13 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1417)
[20:25:13 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1230)
[20:25:13 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[20:25:13 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[20:25:13 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[20:25:13 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[20:25:13 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[20:25:13 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[20:25:13 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843)
[20:25:13 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424)
[20:25:13 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[20:25:13 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[20:25:13 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[20:25:13 ERROR]: #!#!
[20:25:13 ERROR]: #!#! Version Information:
[20:25:13 ERROR]: #!#!   Skript: 2.2-dev30d (latest)
[20:25:13 ERROR]: #!#!   Bukkit: 1.12.1-R0.1-SNAPSHOT
[20:25:13 ERROR]: #!#!   Minecraft: 1.12.1
[20:25:13 ERROR]: #!#!   Java: 1.8.0_131 (OpenJDK 64-Bit Server VM 25.131-b11)
[20:25:13 ERROR]: #!#!   OS: Linux amd64 4.10.0-22-generic
[20:25:13 ERROR]: #!#!
[20:25:13 ERROR]: #!#! Running CraftBukkit: false
[20:25:13 ERROR]: #!#! Running Spigot (or compatible): true
[20:25:13 ERROR]: #!#! Running Paper (or compatible): true
[20:25:13 ERROR]: #!#!
[20:25:13 ERROR]: #!#! Current node: null
[20:25:13 ERROR]: #!#! Current item: send "%diameter of {arenakits::*}%" to event-player/console
[20:25:13 ERROR]: #!#! Thread: Server thread

**Comment by TheBentoBox** [comment]
The error is showing `diameter of {arenakits::*}` which leads me to believe you have an addon installed that has syntax conflicting with the `size of` expression. Try without addons and report back.

**Comment by melinstagibson** [comment]
Oh, MundoSk caused this, my bad, shouldve checked myself, closing this, thank you and ill let the addon dev know

**Comment by Blueyescat** [comment]
It works with Skript 2.2-dev29.
