### ISSUE TITLE
Crazy Skript error

### ISSUE THREAD

**Issue by IceMeltt** [bensku/Skript#831]
> [10:56:07] [Server thread/ERROR]: #!#! 
[10:56:07] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[10:56:07] [Server thread/ERROR]: #!#! Could not load srCars.sk
[10:56:07] [Server thread/ERROR]: #!#! 
[10:56:07] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[10:56:07] [Server thread/ERROR]: #!#! This issue is NOT your fault! You can't probably fix it yourself, either.
[10:56:07] [Server thread/ERROR]: #!#! You should report it at https://github.com/bensku/Skript/issues. Please copy paste this report there (or use paste service).
[10:56:07] [Server thread/ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[10:56:07] [Server thread/ERROR]: #!#! 
[10:56:07] [Server thread/ERROR]: #!#! Stack trace:
[10:56:07] [Server thread/ERROR]: #!#! java.lang.UnsupportedOperationException
[10:56:07] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.ExpressionList.getSingle(ExpressionList.java:87)
[10:56:07] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.LiteralList.getSingle(LiteralList.java:53)
[10:56:07] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.ExprArgument.init(ExprArgument.java:109)
[10:56:07] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:251)
[10:56:07] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:178)
[10:56:07] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:491)
[10:56:07] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:808)
[10:56:07] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1517)
[10:56:07] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1447)
[10:56:07] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1447)
[10:56:07] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1513)
[10:56:07] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[10:56:07] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:178)
[10:56:07] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:491)
[10:56:07] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:808)
[10:56:07] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1517)
[10:56:07] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1474)
[10:56:07] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[10:56:07] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:178)
[10:56:07] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Condition.parse(Condition.java:81)
[10:56:07] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:921)
[10:56:07] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:54)
[10:56:07] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Conditional.<init>(Conditional.java:44)
[10:56:07] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:928)
[10:56:07] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:471)
[10:56:07] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:526)
[10:56:07] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:333)
[10:56:07] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:345)
[10:56:07] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:275)
[10:56:07] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:305)
[10:56:07] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript$2.run(Skript.java:410)
[10:56:07] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
[10:56:07] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[10:56:07] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
[10:56:07] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[10:56:07] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[10:56:07] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[10:56:07] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[10:56:07] [Server thread/ERROR]: #!#! 
[10:56:07] [Server thread/ERROR]: #!#! Version Information:
[10:56:07] [Server thread/ERROR]: #!#!   Skript: 2.2-dev30d (latest)
[10:56:07] [Server thread/ERROR]: #!#!   Bukkit: 1.12.1-R0.1-SNAPSHOT
[10:56:07] [Server thread/ERROR]: #!#!   Minecraft: 1.12.1
[10:56:07] [Server thread/ERROR]: #!#!   Java: 1.8.0_144 (Java HotSpot(TM) 64-Bit Server VM 25.144-b01)
[10:56:07] [Server thread/ERROR]: #!#!   OS: Linux amd64 3.13.0-126-generic
[10:56:07] [Server thread/ERROR]: #!#! 
[10:56:07] [Server thread/ERROR]: #!#! Running CraftBukkit: false
[10:56:07] [Server thread/ERROR]: #!#! Running Spigot (or compatible): true
[10:56:07] [Server thread/ERROR]: #!#! Running Paper (or compatible): false
[10:56:07] [Server thread/ERROR]: #!#! 
[10:56:07] [Server thread/ERROR]: #!#! Current node: if distance between the player and player-arg is less than 10: (srCars.sk, line 182)
[10:56:07] [Server thread/ERROR]: #!#! Current item: null
[10:56:07] [Server thread/ERROR]: #!#! Thread: Server thread
[10:56:07] [Server thread/ERROR]: #!#! 
[10:56:07] [Server thread/ERROR]: #!#! Language: english
[10:56:07] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[10:56:07] [Server thread/ERROR]: #!#! 
[10:56:07] [Server thread/ERROR]: #!#! End of Error.
[10:56:07] [Server thread/ERROR]: #!#!

**Comment by bensku** [comment]
Interesting... What exactly are you trying to do?

**Comment by IceMeltt** [comment]
Well, so - I'm trying to create a script that runs minecarts without rails.
In the line that is listed in the fixcode - line 182, I'm creating a command that player Z, who stands near 10 blocks of player X - can sit with player X in minecarts, and travel the world toghether.
But... It's crazy. Because, it looks like that:
**1.** I'm running on your skript with version dev26c. Script works.
**2.** I'm updating your skript to version dev30d. It works.
**3**. After a few reloads of server - skript crashes. And you can't repair it, even on pasting new downloaded version.

**Comment by bensku** [comment]
Are there other errors before this in console?

**Comment by IceMeltt** [comment]
Nope, only some errors of my scripts, that I must repair.
By the Way - scripts. I don't know how is this happen, but what is crazier - skript drops me the errors on BASIC WORKING scraps of codes, like "on rightclick on air:".

**Comment by bensku** [comment]
I need a script which can be used to reproduce this to debug. Have never seen anything like this.

You don't seem to have any addons installed, so it is likely a Skript bug. But... how? I don't know what could cause this, if no exceptions before this have appeared.

**Comment by IceMeltt** [comment]
Before sending this report I removed all addons from the server, because I was not sure that this is skript bug. Even if I add this addons to my server again, report would be the same, and the lines of crash will start by "ch.njol.skript".
Can I send you my script in other way of contact? 
I don't want to publish this script, so I would rather leave this script as my private stuff.

**Comment by bensku** [comment]
bensku#5185 on Discord, or bensku on IRC (Freenode). Please use a paste service if it is a long script.

Do note that I can't debug it if it uses syntaxes from addons. In that case you'll need to create clean Skript-only example which points out this issue.

**Comment by IceMeltt** [comment]
Ok, I sent the invite on discord.

**Comment by IceMeltt** [comment]
Oh, I saw that this isn't only fault of the script srCars.sk side.
If I removed from the server this script, skript shows me again the same code - but... Of the other script.
https://pastebin.com/nRDiv0eJ
I removed mentioned in the link script (Policja.sk), and - to my surpise, skript shows other, really crazy, really different plant of code.
https://pastebin.com/ww2qhBCH

**Comment by IceMeltt** [comment]
So, is there a solution for this error?

**Comment by bensku** [comment]
No. Seems to be extremely rare (you're only one having it this far) so it is sadly not very high priority. Not to mention that I'm still not even sure where to start debugging.

**Comment by IceMeltt** [comment]
Ok. It's understandable. So, I'll try to repair this problem myself.
Anyway, thanks for helping me with this ;)
