### ISSUE TITLE
Error teleport

### ISSUE THREAD

**Issue by RafsJR1** [bensku/Skript#834]
[00:28:37] [Server thread/ERROR]: #!#! 
[00:28:37] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[00:28:37] [Server thread/ERROR]: #!#! 
[00:28:37] [Server thread/ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[00:28:37] [Server thread/ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[00:28:37] [Server thread/ERROR]: #!#! and check whether this error has already been reported.
[00:28:37] [Server thread/ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[00:28:37] [Server thread/ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[00:28:37] [Server thread/ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[00:28:37] [Server thread/ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[00:28:37] [Server thread/ERROR]: #!#! 
[00:28:37] [Server thread/ERROR]: #!#! Stack trace:
[00:28:37] [Server thread/ERROR]: #!#! java.util.ConcurrentModificationException
[00:28:37] [Server thread/ERROR]: #!#!     at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
[00:28:37] [Server thread/ERROR]: #!#!     at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
[00:28:37] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.EntityTracker.track(EntityTracker.java:32)
[00:28:37] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.WorldManager.a(WorldManager.java:18)
[00:28:37] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.World.a(World.java:1070)
[00:28:37] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.WorldServer.a(WorldServer.java:1003)
[00:28:37] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.World.addEntity(World.java:1063)
[00:28:37] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.World.addEntity(World.java:991)
[00:28:37] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerList.moveToWorld(PlayerList.java:624)
[00:28:37] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport(CraftPlayer.java:568)
[00:28:37] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.teleport(CraftEntity.java:236)
[00:28:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.EffTeleport.execute(EffTeleport.java:97)
[00:28:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:54)
[00:28:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:65)
[00:28:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93)
[00:28:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.Delay$1.run(Delay.java:84)
[00:28:37] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[00:28:37] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352)
[00:28:37] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783)
[00:28:37] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[00:28:37] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[00:28:37] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[00:28:37] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)
[00:28:37] [Server thread/ERROR]: #!#! 
[00:28:37] [Server thread/ERROR]: #!#! Version Information:
[00:28:37] [Server thread/ERROR]: #!#!   Skript: 2.2-dev25
[00:28:37] [Server thread/ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[00:28:37] [Server thread/ERROR]: #!#!   Minecraft: 1.8.8
[00:28:37] [Server thread/ERROR]: #!#!   Java: 1.8.0_121 (Java HotSpot(TM) 64-Bit Server VM 25.121-b13)
[00:28:37] [Server thread/ERROR]: #!#!   OS: Linux amd64 4.4.30-mod-std-ipv6-64
[00:28:37] [Server thread/ERROR]: #!#! 
[00:28:37] [Server thread/ERROR]: #!#! Running CraftBukkit: false
[00:28:37] [Server thread/ERROR]: #!#! 
[00:28:37] [Server thread/ERROR]: #!#! Current node: null
[00:28:37] [Server thread/ERROR]: #!#! Current item: teleport the player to [[direction:at]] {set.spawn}(as org.bukkit.Location)
[00:28:37] [Server thread/ERROR]: #!#! 
[00:28:37] [Server thread/ERROR]: #!#! Thread: Server thread
[00:28:37] [Server thread/ERROR]: #!#! 
[00:28:37] [Server thread/ERROR]: #!#! End of Error.
[00:28:37] [Server thread/ERROR]: #!#! 
[00:28:37] [Server thread/ERROR]: Encountered an unexpected exception

**Comment by TheBentoBox** [comment]
We can't provide support for old versions of Skript since the error you're reporting might have already been fixed in a newer version, and given that the new versions aren't compatible with 1.8, you can consider this fork's support for 1.8 officially "dropped". Sorry but we can't help you with this unless you update your server.
