### ISSUE TITLE
error skriPT

### ISSUE THREAD

**Issue by RafsJR1** [bensku/Skript#836]
[08:26:47] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[08:26:47] [Server thread/ERROR]: #!#! 
[08:26:47] [Server thread/ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[08:26:47] [Server thread/ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[08:26:47] [Server thread/ERROR]: #!#! and check whether this error has already been reported.
[08:26:47] [Server thread/ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[08:26:47] [Server thread/ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[08:26:47] [Server thread/ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[08:26:47] [Server thread/ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[08:26:47] [Server thread/ERROR]: #!#! 
[08:26:47] [Server thread/ERROR]: #!#! Stack trace:
[08:26:47] [Server thread/ERROR]: #!#! java.util.ConcurrentModificationException
[08:26:47] [Server thread/ERROR]: #!#!     at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
[08:26:47] [Server thread/ERROR]: #!#!     at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
[08:26:47] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.EntityTracker.track(EntityTracker.java:32)
[08:26:47] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.WorldManager.a(WorldManager.java:18)
[08:26:47] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.World.a(World.java:1070)
[08:26:47] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.WorldServer.a(WorldServer.java:1003)
[08:26:47] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.World.addEntity(World.java:1063)
[08:26:47] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.World.addEntity(World.java:991)
[08:26:47] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerList.moveToWorld(PlayerList.java:624)
[08:26:47] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport(CraftPlayer.java:568)
[08:26:47] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.teleport(CraftEntity.java:236)
[08:26:47] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.EffTeleport.execute(EffTeleport.java:95)
[08:26:47] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[08:26:47] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[08:26:47] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[08:26:47] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.Delay$1.run(Delay.java:94)
[08:26:47] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[08:26:47] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352)
[08:26:47] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783)
[08:26:47] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[08:26:47] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[08:26:47] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[08:26:47] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)
[08:26:47] [Server thread/ERROR]: #!#! 
[08:26:47] [Server thread/ERROR]: #!#! Version Information:
[08:26:47] [Server thread/ERROR]: #!#!   Skript: 2.2-dev27
[08:26:47] [Server thread/ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[08:26:47] [Server thread/ERROR]: #!#!   Minecraft: 1.8.8
[08:26:47] [Server thread/ERROR]: #!#!   Java: 1.8.0_121 (Java HotSpot(TM) 64-Bit Server VM 25.121-b13)
[08:26:47] [Server thread/ERROR]: #!#!   OS: Linux amd64 4.4.30-mod-std-ipv6-64
[08:26:47] [Server thread/ERROR]: #!#! 
[08:26:47] [Server thread/ERROR]: #!#! Running CraftBukkit: false
[08:26:47] [Server thread/ERROR]: #!#! 
[08:26:47] [Server thread/ERROR]: #!#! Current node: null
[08:26:47] [Server thread/ERROR]: #!#! Current item: teleport the player to [[direction:at]] {set.spawn}(as org.bukkit.Location)
[08:26:47] [Server thread/ERROR]: #!#! 
[08:26:47] [Server thread/ERROR]: #!#! Thread: Server thread
[08:26:47] [Server thread/ERROR]: #!#! 
[08:26:47] [Server thread/ERROR]: #!#! End of Error.
[08:26:47] [Server thread/ERROR]: #!#!

**Comment by Blueyescat** [comment]
You are using dev27 in 1.8 :slightly_smiling_face:  Already dev26-dev28 are broken, you have to use **dev25** or below in 1.8

**Comment by Snow-Pyon** [comment]
Stop reporting errors when you're using an outdated version, this fork doesn't support anything below 1.9.
