### ISSUE TITLE
IllegalStateException: Asynchronous player kick!

### ISSUE THREAD

**Issue by dandan02** [bensku/Skript#868]
Im currently starting on the development of an anticheat.
I know what the problem is but do not know how to solve it.
The error occurs when the function is ran so many times

Error:

[16:57:33 ERROR]: #!#! 
[16:57:33 ERROR]: #!#! [Skript] Severe Error:
[16:57:33 ERROR]: #!#! 
[16:57:33 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[16:57:33 ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[16:57:33 ERROR]: #!#! and check whether this error has already been reported.
[16:57:33 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[16:57:33 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[16:57:33 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[16:57:33 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[16:57:33 ERROR]: #!#! 
[16:57:33 ERROR]: #!#! Stack trace:
[16:57:33 ERROR]: #!#! java.lang.IllegalStateException: Asynchronous player kick!
[16:57:33 ERROR]: #!#!     at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
[16:57:33 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.kickPlayer(CraftPlayer.java:214)
[16:57:33 ERROR]: #!#!     at ch.njol.skript.effects.EffKick.execute(EffKick.java:84)
[16:57:33 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:54)
[16:57:33 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:65)
[16:57:33 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93)
[16:57:33 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
[16:57:33 ERROR]: #!#!     at ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:91)
[16:57:33 ERROR]: #!#!     at ch.njol.skript.lang.function.Function.execute(Function.java:109)
[16:57:33 ERROR]: #!#!     at ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:191)
[16:57:33 ERROR]: #!#!     at ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:55)
[16:57:33 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:54)
[16:57:33 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:65)
[16:57:33 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93)
[16:57:33 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
[16:57:33 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:152)
[16:57:33 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:112)
[16:57:33 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[16:57:33 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[16:57:33 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[16:57:33 ERROR]: #!#!     at com.gmail.thelimeglass.Utils.Packets.PacketListener$1.channelRead(PacketListener.java:50)
[16:57:33 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[16:57:33 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[16:57:33 ERROR]: #!#!     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[16:57:33 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[16:57:33 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[16:57:33 ERROR]: #!#!     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[16:57:33 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[16:57:33 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[16:57:33 ERROR]: #!#!     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[16:57:33 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[16:57:33 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[16:57:33 ERROR]: #!#!     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[16:57:33 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[16:57:33 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[16:57:33 ERROR]: #!#!     at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
[16:57:33 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[16:57:33 ERROR]: #!#!     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[16:57:33 ERROR]: #!#!     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
[16:57:33 ERROR]: #!#!     at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722)
[16:57:33 ERROR]: #!#!     at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326)
[16:57:33 ERROR]: #!#!     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264)
[16:57:33 ERROR]: #!#!     at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[16:57:33 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[16:57:33 ERROR]: #!#! 
[16:57:33 ERROR]: #!#! Version Information:
[16:57:33 ERROR]: #!#!   Skript: 2.2-dev22f
[16:57:33 ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[16:57:33 ERROR]: #!#!   Minecraft: 1.8.8
[16:57:33 ERROR]: #!#!   Java: 1.8.0_131 (OpenJDK 64-Bit Server VM 25.131-b11)
[16:57:33 ERROR]: #!#!   OS: Linux amd64 4.4.0-53-generic
[16:57:33 ERROR]: #!#! 
[16:57:33 ERROR]: #!#! Running CraftBukkit: false
[16:57:33 ERROR]: #!#! 
[16:57:33 ERROR]: #!#! Current node: null
[16:57:33 ERROR]: #!#! Current item: kick {_p}(as org.bukkit.entity.Player) on account of "Bad Packets"
[16:57:33 ERROR]: #!#! 
[16:57:33 ERROR]: #!#! Thread: Netty Epoll Server IO #1
[16:57:33 ERROR]: #!#! 
[16:57:33 ERROR]: #!#! End of Error.
[16:57:33 ERROR]: #!#! 

Code:

options:
    timecheck: 7 seconds
on disconnect:
    set {join.%player%} to now
    set {lastdamage.%player%} to now
    set {Packets.%player%} to 0
    delete {Kicking.%player%}
on join:
    delete {Kicking.%player%}
on damage:
    victim is a player
    attacker is a entity
    set {lastdamage.%attacker%} to now

function SupervisorKick(p: player, hack: text):
    if {Kicking.%{_p}%} is not set:
        if {_p} is online:
            set {Kicking.%{_p}%} to true
            kick {_p} due to "Bad Packets"
        else:
            wait 5 seconds
            clear {Kicking.%{_p}%}

on packet:
    check [difference between {join.%event-player%} and now > {@timecheck}]->[event-string is "PacketPlayInFlying"]->[ground state of event-player is false]
    if difference between {LastBadPacket.%player%} and now < 1 seconds:
        difference between {lastdamage.%player%} and now > 2 seconds
        block at event-player is not ladder or vines or barrier
        add 1 to {Packets.%player%}
        if {Packets.%player%} = 10:
            SupervisorKick(player, "Bad Packets")
    else:
        clear {Packets.%player%}
        set {LastBadPacket.%player%} to now

Thanks for any help i appreciate it

**Comment by TheBentoBox** [comment]
You're using an old version (22f while we're on 31b) and since you're still using MC 1.8 you'll be unable to update to see if this issue is resolved in newer versions. As a result, we can't help you unless you update your server since this fork is no longer compatible with versions below 1.9. It's pointless for us to address bugs reported by people using out-of-date Skript versions as the issue may have been fixed in a more recent version.

**Comment by Syst3ms** [comment]
Also, that's an addon issue.

**Comment by TheBentoBox** [comment]
I don't see anything about an addon and the error points to a vanilla Skript effect but with an issue like this it's not like I'm looking very carefully either heh
