### ISSUE TITLE
Particles Error On Enable

### ISSUE THREAD

**Issue by EazyFTW** [bensku/Skript#874]
[01:02:35] [Server thread/ERROR]: Error occurred while enabling Skript v2.2-dev31c (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/Particle
	at ch.njol.skript.util.VisualEffect$Type.<clinit>(VisualEffect.java:86) ~[?:?]
	at ch.njol.skript.util.VisualEffect.<clinit>(VisualEffect.java:255) ~[?:?]
	at ch.njol.skript.classes.data.SkriptClasses.<clinit>(SkriptClasses.java:889) ~[?:?]
	at ch.njol.skript.Skript.onEnable(Skript.java:282) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
Caused by: java.lang.ClassNotFoundException: org.bukkit.Particle
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[minecraft_server.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_141]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_141]
	... 15 more

**Comment by TheBentoBox** [comment]
This fork is no longer compatible with Minecraft versions older than 1.9 past dev25. Downgrade to dev25 and follow #847 for any possible updates on 1.8 support but I wouldn't hold my breath.
