### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Sallomy** [bensku/Skript#881]
When I added an addons for this plugin is just happened 5000+ Errors saying the addons is wrong blablablabla I cant even disable no one of them is in the scripts plugin....

**Comment by TheBentoBox** [comment]
Server version? Skript version? Sample code? Specific errors? Addons used & their versions? You can't just show up and say "I got a lot of errors" and expect it to be remotely possible for us to do anything.

**Comment by Sallomy** [comment]
@TheBentoBox server type is spigot            Server version is 1.12.2 Skript version is 2.2-dev30d addons used SkRayFall ,        skutilities , wildskript , skellett

Server error log

[14:49:20 ERROR]: #!#! [Skript] Severe Error:
[14:49:20 ERROR]: #!#! 
[14:49:20 ERROR]: #!#! Something went horribly wrong with Skript.
[14:49:20 ERROR]: #!#! This issue is NOT your fault! You can't probably fix it yourself, either.
[14:49:20 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[14:49:20 ERROR]: #!#! Here is full list of them:
[14:49:20 ERROR]: #!#! skRayFall (http://sk.rayfall.net/) skUtilities (https://tim740.github.io/) WildSkript (http://www.dzikoysk.net/) Skellett (https://forums.skunity.com/resources/skellett-the-addon-with-a-beast-name.24/) 
[14:49:20 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[14:49:20 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[14:49:20 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[14:49:20 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[14:49:20 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[14:49:20 ERROR]: #!#! Only if the author tells you to do so, report it as Skript issue (url below)
[14:49:20 ERROR]: #!#! Issue tracker: https://github.com/bensku/Skript/issues (only if you know what you're doing!)
[14:49:20 ERROR]: #!#! 
[14:49:20 ERROR]: #!#! Stack trace:
[14:49:20 ERROR]: #!#! java.lang.NullPointerException
[14:49:20 ERROR]: #!#!     at net.rayfall.eyesniper2.skrayfall.scoreboard.EffRemoveScoreboard.execute(EffRemoveScoreboard.java:38)
[14:49:20 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[14:49:20 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[14:49:20 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[14:49:20 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
[14:49:20 ERROR]: #!#!     at ch.njol.skript.events.EvtPeriodical.execute(EvtPeriodical.java:90)
[14:49:20 ERROR]: #!#!     at ch.njol.skript.events.EvtPeriodical$1.run(EvtPeriodical.java:104)
[14:49:20 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
[14:49:20 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[14:49:20 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
[14:49:20 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[14:49:20 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[14:49:20 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[14:49:20 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)
[14:49:20 ERROR]: #!#! 
[14:49:20 ERROR]: #!#! Version Information:
[14:49:20 ERROR]: #!#!   Skript: 2.2-dev30d
[14:49:20 ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[14:49:20 ERROR]: #!#!   Minecraft: 1.12.2
[14:49:20 ERROR]: #!#!   Java: 1.8.0_112 (Java HotSpot(TM) 64-Bit Server VM 25.112-b15)
[14:49:20 ERROR]: #!#!   OS: Linux amd64 3.14.32-xxxx-grs-ipv6-64
[14:49:20 ERROR]: #!#! 
[14:49:20 ERROR]: #!#! Running CraftBukkit: false
[14:49:20 ERROR]: #!#! Running Spigot (or compatible): true
[14:49:20 ERROR]: #!#! Running Paper (or compatible): false
[14:49:20 ERROR]: #!#! 
[14:49:20 ERROR]: #!#! Current node: null
[14:49:20 ERROR]: #!#! Current item: null
[14:49:20 ERROR]: #!#! Thread: Server thread
[14:49:20 ERROR]: #!#! 
[14:49:20 ERROR]: #!#! Language: english
[14:49:20 ERROR]: #!#! Link parse mode: DISABLED
[14:49:20 ERROR]: #!#! 
[14:49:20 ERROR]: #!#! End of Error.

**Comment by TheBentoBox** [comment]
That's an issue with skRayFall, not Skript itself. Make sure you have an up-to-date version that's meant to work on 1.12.
