### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Sallomy** [bensku/Skript#882]
Server Version 1.8 Server Type Spigot  i didnt develop any addon

Error:
[04:17:56 ERROR]: #!#! 
[04:17:56 ERROR]: #!#! [Skript] Severe Error:
[04:17:56 ERROR]: #!#! 
[04:17:56 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[04:17:56 ERROR]: #!#! If you're a server admin however please go to http://dev.bukkit.org/server-mods/skript/tickets/
[04:17:56 ERROR]: #!#! and check whether this error has already been reported.
[04:17:56 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it,
[04:17:56 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[04:17:56 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[04:17:56 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[04:17:56 ERROR]: #!#! 
[04:17:56 ERROR]: #!#! Stack trace:
[04:17:56 ERROR]: #!#! java.lang.NullPointerException
[04:17:56 ERROR]: #!#!     at net.rayfall.eyesniper2.skrayfall.scoreboard.EffRemoveScoreboard.execute(EffRemoveScoreboard.java:38)
[04:17:56 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:50)
[04:17:56 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:63)
[04:17:56 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:91)
[04:17:56 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
[04:17:56 ERROR]: #!#!     at ch.njol.skript.events.EvtPeriodical.execute(EvtPeriodical.java:94)
[04:17:56 ERROR]: #!#!     at ch.njol.skript.events.EvtPeriodical$1.run(EvtPeriodical.java:120)
[04:17:56 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
[04:17:56 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[04:17:56 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:709)
[04:17:56 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[04:17:56 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634)
[04:17:56 ERROR]: #!#!     at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537)
[04:17:56 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)
[04:17:56 ERROR]: #!#! 
[04:17:56 ERROR]: #!#! Version Information:
[04:17:56 ERROR]: #!#!   Skript: 2.1.2
[04:17:56 ERROR]: #!#!   Bukkit: 1.8-R0.1-SNAPSHOT
[04:17:56 ERROR]: #!#!   Minecraft: 1.8
[04:17:56 ERROR]: #!#!   Java: 1.8.0_112
[04:17:56 ERROR]: #!#! 
[04:17:56 ERROR]: #!#! Running CraftBukkit: false
[04:17:56 ERROR]: #!#! 
[04:17:56 ERROR]: #!#! Current node: null
[04:17:56 ERROR]: #!#! Current item: null
[04:17:56 ERROR]: #!#! 
[04:17:56 ERROR]: #!#! Thread: Server thread
[04:17:56 ERROR]: #!#! 
[04:17:56 ERROR]: #!#! End of Error.

**Comment by Snow-Pyon** [comment]
1. You aren't using this fork so this doesn't belong here.
2. The above stack trace is due to an addon (skRayFall), not of Skript so there is another reason to not report this here.
3. You're using 1.8 (for the love of God, at least update to 1.8.8), which isn't supported by this fork so with this there are three reasons to not report this here.

**Comment by bensku** [comment]
See #847 considering 1.8. Also this is not Skript issue.
