### ISSUE TITLE
error start server

### ISSUE THREAD

**Issue by SkelletonX** [bensku/Skript#889]
error log:

[14:03:12] [Server thread/ERROR]: Error occurred while enabling Skript v2.2-dev31c (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.Effect.getName()Ljava/lang/String;
	at ch.njol.skript.util.VisualEffect$Type.<init>(VisualEffect.java:196) ~[?:?]
	at ch.njol.skript.util.VisualEffect$Type.<clinit>(VisualEffect.java:63) ~[?:?]
	at ch.njol.skript.util.VisualEffect.<clinit>(VisualEffect.java:255) ~[?:?]
	at ch.njol.skript.classes.data.SkriptClasses.<clinit>(SkriptClasses.java:889) ~[?:?]
	at ch.njol.skript.Skript.onEnable(Skript.java:282) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[craftbukkit-1.9-R0.1-SNAPSHOT-latest.jar:git-Bukkit-44216f1]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [craftbukkit-1.9-R0.1-SNAPSHOT-latest.jar:git-Bukkit-44216f1]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit-1.9-R0.1-SNAPSHOT-latest.jar:git-Bukkit-44216f1]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:346) [craftbukkit-1.9-R0.1-SNAPSHOT-latest.jar:git-Bukkit-44216f1]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:318) [craftbukkit-1.9-R0.1-SNAPSHOT-latest.jar:git-Bukkit-44216f1]
	at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:403) [craftbukkit-1.9-R0.1-SNAPSHOT-latest.jar:git-Bukkit-44216f1]
	at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:368) [craftbukkit-1.9-R0.1-SNAPSHOT-latest.jar:git-Bukkit-44216f1]
	at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:323) [craftbukkit-1.9-R0.1-SNAPSHOT-latest.jar:git-Bukkit-44216f1]
	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:241) [craftbukkit-1.9-R0.1-SNAPSHOT-latest.jar:git-Bukkit-44216f1]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:506) [craftbukkit-1.9-R0.1-SNAPSHOT-latest.jar:git-Bukkit-44216f1]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]

**Comment by Blueyescat** [comment]
You are using CraftBukkit :interrobang: Skript doesn't support it... And many plugins? Please use PaperSpigot (Skript supports Paper Timings) or Spigot.

**Comment by supertassu** [comment]
Please provide us the full error log.

**Comment by bensku** [comment]
Please use Spigot.
