### ISSUE TITLE
Skquery Chest Menu

### ISSUE THREAD

**Issue by omermarvel** [bensku/Skript#890]
`[22:11:57] [Server thread/ERROR]: #!#! 
[22:11:57] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[22:11:57] [Server thread/ERROR]: #!#! 
[22:11:57] [Server thread/ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[22:11:57] [Server thread/ERROR]: #!#! If you're a server admin however please go to http://dev.bukkit.org/server-mods/skript/tickets/
[22:11:57] [Server thread/ERROR]: #!#! and check whether this error has already been reported.
[22:11:57] [Server thread/ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it,
[22:11:57] [Server thread/ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[22:11:57] [Server thread/ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[22:11:57] [Server thread/ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[22:11:57] [Server thread/ERROR]: #!#! 
[22:11:57] [Server thread/ERROR]: #!#! Stack trace:
[22:11:57] [Server thread/ERROR]: #!#! java.lang.IllegalArgumentException: Title cannot be longer than 32 characters
[22:11:57] [Server thread/ERROR]: #!#!     at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
[22:11:57] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R1.inventory.CraftInventoryCustom$MinecraftInventory.<init>(CraftInventoryCustom.java:59)
[22:11:57] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R1.inventory.CraftInventoryCustom.<init>(CraftInventoryCustom.java:32)
[22:11:57] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R1.CraftServer.createInventory(CraftServer.java:1512)
[22:11:57] [Server thread/ERROR]: #!#!     at org.bukkit.Bukkit.createInventory(Bukkit.java:934)
[22:11:57] [Server thread/ERROR]: #!#!     at com.w00tmast3r.skquery.elements.expressions.ExprBlankInventories.get(ExprBlankInventories.java:36)
[22:11:57] [Server thread/ERROR]: #!#!     at com.w00tmast3r.skquery.elements.expressions.ExprBlankInventories.get(ExprBlankInventories.java:1)
[22:11:57] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:103)
[22:11:57] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getSingle(SimpleExpression.java:61)
[22:11:57] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.EffOpenInventory.execute(EffOpenInventory.java:78)
[22:11:57] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:54)
[22:11:57] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:63)
[22:11:57] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:91)
[22:11:57] [Server thread/ERROR]: #!#!     at ch.njol.skript.effects.Delay$1.run(Delay.java:84)
[22:11:57] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
[22:11:57] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[22:11:57] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:697)
[22:11:57] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[22:11:57] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:627)
[22:11:57] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:530)
[22:11:57] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:745)
[22:11:57] [Server thread/ERROR]: #!#! 
[22:11:57] [Server thread/ERROR]: #!#! Version Information:
[22:11:57] [Server thread/ERROR]: #!#!   Skript: 2.2-SNAPSHOT
[22:11:57] [Server thread/ERROR]: #!#!   Bukkit: 1.8-R0.1-SNAPSHOT
[22:11:57] [Server thread/ERROR]: #!#!   Minecraft: 1.8
[22:11:57] [Server thread/ERROR]: #!#!   Java: 1.8.0_101 (Java HotSpot(TM) 64-Bit Server VM 25.101-b13)
[22:11:57] [Server thread/ERROR]: #!#!   OS: Linux amd64 4.4.26-nitradoV3-MC-1000-nH-dP-d-a
[22:11:57] [Server thread/ERROR]: #!#! 
[22:11:57] [Server thread/ERROR]: #!#! Running CraftBukkit: false
[22:11:57] [Server thread/ERROR]: #!#! 
[22:11:57] [Server thread/ERROR]: #!#! Current node: null
[22:11:57] [Server thread/ERROR]: #!#! Current item: open inventory to the player
[22:11:57] [Server thread/ERROR]: #!#! 
[22:11:57] [Server thread/ERROR]: #!#! Thread: Server thread
[22:11:57] [Server thread/ERROR]: #!#! 
[22:11:57] [Server thread/ERROR]: #!#! End of Error.
[22:11:57] [Server thread/ERROR]: #!#! 
`

**Comment by bensku** [comment]
Not Skript issue.
