### ISSUE TITLE
java.lang.NoSuchMethodError: org.bukkit.Effect.getName()Ljava/lang/String;

### ISSUE THREAD

**Issue by josephtingiris** [bensku/Skript#902]
```[21:55:05 ERROR]: Error occurred while enabling Skript v2.2-dev31c (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.Effect.getName()Ljava/lang/String;
        at ch.njol.skript.util.VisualEffect$Type.<init>(VisualEffect.java:196) ~[?:?]
        at ch.njol.skript.util.VisualEffect$Type.<clinit>(VisualEffect.java:63) ~[?:?]
        at ch.njol.skript.util.VisualEffect.<clinit>(VisualEffect.java:255) ~[?:?]
        at ch.njol.skript.classes.data.SkriptClasses.<clinit>(SkriptClasses.java:889) ~[?:?]
        at ch.njol.skript.Skript.onEnable(Skript.java:282) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[craftbukkit-1.12.2.jar:git-Bukkit-a3b3a42]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) [craftbukkit-1.12.2.jar:git-Bukkit-a3b3a42]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:401) [craftbukkit-1.12.2.jar:git-Bukkit-a3b3a42]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:370) [craftbukkit-1.12.2.jar:git-Bukkit-a3b3a42]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:331) [craftbukkit-1.12.2.jar:git-Bukkit-a3b3a42]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.reload(CraftServer.java:732) [craftbukkit-1.12.2.jar:git-Bukkit-a3b3a42]
        at org.bukkit.Bukkit.reload(Bukkit.java:534) [craftbukkit-1.12.2.jar:git-Bukkit-a3b3a42]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [craftbukkit-1.12.2.jar:git-Bukkit-a3b3a42]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) [craftbukkit-1.12.2.jar:git-Bukkit-a3b3a42]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:631) [craftbukkit-1.12.2.jar:git-Bukkit-a3b3a42]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:617) [craftbukkit-1.12.2.jar:git-Bukkit-a3
b3a42]
        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:408) [craftbukkit-1.12.2.jar:git-Bukkit-a3b3a42]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:372) [craftbukkit-1.12.2.jar:git-Bukkit-a3b3a42]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:651) [craftbukkit-1.12.2.jar:git-Bukkit-a3b3a42]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:555) [craftbukkit-1.12.2.jar:git-Bukkit-a3b3a42]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_73]
```

**Comment by Snow-Pyon** [comment]
Skript doesn't support CraftBukkit, use either Spigot or PaperSpigot.
