### ISSUE TITLE
Skript cannot load scripts

### ISSUE THREAD

**Issue by CBM1014** [bensku/Skript#909]
> skript reload all
[23:57:27 INFO]: [Skript] Reloading the config and all scripts...
[23:57:30 INFO]: Loaded a total of 79112 english aliases
[23:57:30 ERROR]: #!#!
[23:57:30 ERROR]: #!#! [Skript] Severe Error:
[23:57:30 ERROR]: #!#! Could not load command with cooldown.sk
[23:57:30 ERROR]: #!#!
[23:57:30 ERROR]: #!#! Something went horribly wrong with Skript.
[23:57:30 ERROR]: #!#! This issue is NOT your fault! You can't probably fix it yourself, either.
[23:57:30 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[23:57:30 ERROR]: #!#! Here is full list of them:
[23:57:30 ERROR]: #!#! skRayFall (http://sk.rayfall.net/) SkyAddon_PapiFormat (http://www.15imc.com/index.html) SkQuery Skellett (https://forums.skunity.com/resources/skellett-the-addon-with-a-beast-name.24/) TuSKe
[23:57:30 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[23:57:30 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[23:57:30 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[23:57:30 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[23:57:30 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[23:57:30 ERROR]: #!#! Only if the author tells you to do so, report it as Skript issue (url below)
[23:57:30 ERROR]: #!#! Issue tracker: https://github.com/bensku/Skript/issues (only if you know what you're doing!)
[23:57:30 ERROR]: #!#!
[23:57:30 ERROR]: #!#! Stack trace:
[23:57:30 ERROR]: #!#! java.lang.NullPointerException
[23:57:30 ERROR]: #!#!     at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.currencyNameSingular(Economy_Craftconomy3.java:114)
[23:57:30 ERROR]: #!#!     at ch.njol.skript.hooks.economy.classes.Money.parse(Money.java:159)
[23:57:30 ERROR]: #!#!     at ch.njol.skript.hooks.economy.classes.Money$1.parse(Money.java:57)
[23:57:30 ERROR]: #!#!     at ch.njol.skript.hooks.economy.classes.Money$1.parse(Money.java:1)
[23:57:30 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:421)
[23:57:30 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.parse(Classes.java:460)
[23:57:30 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:364)
[23:57:30 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:623)
[23:57:30 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:798)
[23:57:30 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1517)
[23:57:30 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1513)
[23:57:30 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[23:57:30 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:178)
[23:57:30 ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:59)
[23:57:30 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:848)
[23:57:30 ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:471)
[23:57:30 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:532)
[23:57:30 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:339)
[23:57:30 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:351)
[23:57:30 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:281)
[23:57:30 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:311)
[23:57:30 ERROR]: #!#!     at ch.njol.skript.Skript.reload(Skript.java:701)
[23:57:30 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:161)
[23:57:30 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[23:57:30 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[23:57:30 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:676)
[23:57:30 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:639)
[23:57:30 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:462)
[23:57:30 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:425)
[23:57:30 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[23:57:30 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[23:57:30 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[23:57:30 ERROR]: #!#!
[23:57:30 ERROR]: #!#! Version Information:
[23:57:30 ERROR]: #!#!   Skript: 2.2-dev31c (latest)
[23:57:30 ERROR]: #!#!   Bukkit: 1.12.1-R0.1-SNAPSHOT
[23:57:30 ERROR]: #!#!   Minecraft: 1.12.1
[23:57:30 ERROR]: #!#!   Java: 1.8.0_144 (OpenJDK 64-Bit Server VM 25.144-b01)
[23:57:30 ERROR]: #!#!   OS: Linux amd64 4.13.3-1.el7.elrepo.x86_64
[23:57:30 ERROR]: #!#!
[23:57:30 ERROR]: #!#! Running CraftBukkit: false
[23:57:30 ERROR]: #!#! Running Spigot (or compatible): true
[23:57:30 ERROR]: #!#! Running Paper (or compatible): true
[23:57:30 ERROR]: #!#!
[23:57:30 ERROR]: #!#! Current node: set {_waited} to difference between {cake.%player%.lastused} and now (command with cooldown.sk, line 16)
[23:57:30 ERROR]: #!#! Current item: null
[23:57:30 ERROR]: #!#! Thread: Server thread
[23:57:30 ERROR]: #!#!
[23:57:30 ERROR]: #!#! Language: english
[23:57:30 ERROR]: #!#! Link parse mode: DISABLED
[23:57:30 ERROR]: #!#!
[23:57:30 ERROR]: #!#! End of Error.
[23:57:30 ERROR]: #!#!
[23:57:30 INFO]: All scripts loaded without errors.
[23:57:30 INFO]: Loaded 1 script with a total of 0 triggers and 0 commands in 0.08 seconds
[23:57:30 INFO]: [Skript] Successfully reloaded the config and all scripts.

**Comment by CBM1014** [comment]
All commands can not be loaded, including example sk.

**Comment by Auswahluhr60042** [comment]
I have the same problem!

**Comment by CBM1014** [comment]
After I configured the crafteconomy3，It returns normal.
（Perhaps that error is caused by not configured economy plugin.

**Comment by Auswahluhr60042** [comment]
My problem is, that i haven't any economy plugins on my Server....

Plugins: WorldEdit, Skript, MundoSK, PermissionsEx, skUtilities, SkQuery, Vault, WorldGuard, Multiverse-Core, Skellett, LargeSK, skRayFall, WildSkript, Umbaska, TuSKe

My Error: https://pastebin.com/8RbcK7QA

**Comment by Snow-Pyon** [comment]
@Auswahluhr60042 that isn't the same error, report it elsewhere. Pretty sure it's due to Umbaska or WildSkript anyways (bad addons, you shouldn't use them).

**Comment by TheBentoBox** [comment]
Duplicates #885.

**Comment by Auswahluhr60042** [comment]
I deleted the two plugins... it don't worked! :(
