### ISSUE TITLE
Massive error

### ISSUE THREAD

**Issue by claudiog14** [bensku/Skript#931]
Hi there, i have the following error everytime that a players join the server! What do i do?

[16:56:46] [Server thread/ERROR]: #!#! 
[16:56:46] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[16:56:46] [Server thread/ERROR]: #!#! 
[16:56:46] [Server thread/ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[16:56:46] [Server thread/ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[16:56:46] [Server thread/ERROR]: #!#! and check whether this error has already been reported.
[16:56:46] [Server thread/ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[16:56:46] [Server thread/ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[16:56:46] [Server thread/ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[16:56:46] [Server thread/ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[16:56:46] [Server thread/ERROR]: #!#! 
[16:56:46] [Server thread/ERROR]: #!#! Stack trace:
[16:56:46] [Server thread/ERROR]: #!#! java.lang.NullPointerException
[16:56:46] [Server thread/ERROR]: #!#!     at net.rayfall.eyesniper2.skrayfall.generaleffects.EffMaxHealth.execute(EffMaxHealth.java:34)
[16:56:46] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:54)
[16:56:46] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:65)
[16:56:46] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93)
[16:56:46] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
[16:56:46] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:152)
[16:56:46] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:112)
[16:56:46] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[16:56:46] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[16:56:46] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[16:56:46] [Server thread/ERROR]: #!#!     at com.w00tmast3r.skquery.elements.effects.EffInvoke.execute(EffInvoke.java:29)
[16:56:46] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:54)
[16:56:46] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:65)
[16:56:46] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93)
[16:56:46] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
[16:56:46] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:152)
[16:56:46] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:112)
[16:56:46] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[16:56:46] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[16:56:46] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[16:56:46] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:298)
[16:56:46] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:157)
[16:56:46] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144)
[16:56:46] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54)
[16:56:46] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231)
[16:56:46] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148)
[16:56:46] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:814)
[16:56:46] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[16:56:46] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[16:56:46] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[16:56:46] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[16:56:46] [Server thread/ERROR]: #!#! 
[16:56:46] [Server thread/ERROR]: #!#! Version Information:
[16:56:46] [Server thread/ERROR]: #!#!   Skript: 2.2-dev19
[16:56:46] [Server thread/ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[16:56:46] [Server thread/ERROR]: #!#!   Minecraft: 1.8.8
[16:56:46] [Server thread/ERROR]: #!#!   Java: 1.8.0_144 (Java HotSpot(TM) 64-Bit Server VM 25.144-b01)
[16:56:46] [Server thread/ERROR]: #!#!   OS: Linux amd64 3.14.32-xxxx-std-ipv6-64
[16:56:46] [Server thread/ERROR]: #!#! 
[16:56:46] [Server thread/ERROR]: #!#! Running CraftBukkit: false
[16:56:46] [Server thread/ERROR]: #!#! 
[16:56:46] [Server thread/ERROR]: #!#! Current node: null
[16:56:46] [Server thread/ERROR]: #!#! Current item: null
[16:56:46] [Server thread/ERROR]: #!#! 
[16:56:46] [Server thread/ERROR]: #!#! Thread: Server thread
[16:56:46] [Server thread/ERROR]: #!#! 
[16:56:46] [Server thread/ERROR]: #!#! End of Error.
[16:56:46] [Server thread/ERROR]: #!#!

**Comment by supertassu** [comment]
SkRayfall issue.

**Comment by TheBentoBox** [comment]
It's an error caused by you using skRayFall's entity max health effect. Stop using `rf max health` (skRayFall's expression) when setting max health in your scripts and just use `max health` (Skript's max health expression) and see if the error goes away (and the scripts continue to work).

If that doesn't work, I'm afraid we can't provide more help here since you're using an old version and are on 1.8. You could update to dev25 since it's (I believe) the newest version that works on 1.8, but we can't provide support for people that aren't on the latest version, which is impossible for 1.8 users. You could always ask on the forums.

Also, I'd really recommend learning how to read stack traces! It's super useful and you'll need to ask for help less often. This one is really obvious, the cause is in the first line of the actual stack trace:

```
[16:56:46] [Server thread/ERROR]: #!#! Stack trace:
[16:56:46] [Server thread/ERROR]: #!#! java.lang.NullPointerException
[16:56:46] [Server thread/ERROR]: #!#! at net.rayfall.eyesniper2.skrayfall.generaleffects.EffMaxHealth.execute(EffMaxHealth.java:34)
```
Note the **skrayfall.generaleffects.EffMaxHealth**.
