### ISSUE TITLE
Error in startup

### ISSUE THREAD

**Issue by xbxymax** [bensku/Skript#932]
I use Skript v2.2-dev31c
server: Thermos 1.7.10-R0.1-SNAPSHOT | 1.7.10-1614.58 (MC: 1.7.10)
These errors occurred at startup
Although the plugin can still be used
But I worry about the follow-up will be a problem
I tried to disable the feature in 'features.sk'
but I do not know how
Hope to get help
[code]
[13:14:47 INFO]: [Skript] Loading Skript v2.2-dev31c
[13:14:47 INFO]: Loading dimension 0 (world) (net.minecraft.server.dedicated.DedicatedServer@7286eb)
[13:14:47 INFO]: Adding world access to world net.minecraft.world.WorldServer@63bffc5e
[13:14:47 INFO]: Preparing start region for level 0
[13:14:47 INFO]: [Skript] Enabling Skript v2.2-dev31c
[13:14:47 INFO]: [Skript] Successfully generated the config, the example scripts and the aliases files.
[13:14:48 ERROR]: Error occurred while enabling Skript v2.2-dev31c (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/Particle
        at ch.njol.skript.util.VisualEffect$Type.<clinit>(VisualEffect.java:86) ~[?:?]
        at ch.njol.skript.util.VisualEffect.<clinit>(VisualEffect.java:255) ~[?:?]
        at ch.njol.skript.classes.data.SkriptClasses.<clinit>(SkriptClasses.java:889) ~[?:?]
        at ch.njol.skript.Skript.onEnable(Skript.java:282) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1614.58]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1614.58]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1614.58]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438) [CraftServer.class:1.7.10-1614.58]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372) [CraftServer.class:1.7.10-1614.58]
        at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:519) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:493) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:453) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337) [lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
Caused by: java.lang.ClassNotFoundException: org.bukkit.Particle
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:440) ~[PluginClassLoader.class:1.7.10-1614.58]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:1.7.10-1614.58]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_141]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_141]
        ... 15 more
[13:14:48 INFO]: Server permissions file permissions.yml is empty, ignorin
[/code]

**Comment by Pikachu920** [comment]
Anything below 1.9 is unsupported

**Comment by TheBentoBox** [comment]
Yeah, I'm not sure how well any versions of this fork will work on 1.7, let alone the latest. Try downgrading to dev25, but we can't help you past that.

Think about updating your server -- that version of Minecraft is three and a half years old!
