### ISSUE TITLE
On teleport doesn't work and Bug with Skript 2.2 V8-V8b

### ISSUE THREAD

**Issue by ZeTioZ** [bensku/Skript#95]
Sometime when I restart the server the on teleport event doesn't work (I use the Skript 2.2 V7b on PaperSpigot 1.8.8 Latest Build)

Skript 2.2 V8 or V8b doesn't let other plugin load because of his "suppressUnknownMessageCommand"
Here is a log issue for one of the plugins who does not loaded because of this version:

`java.lang.IllegalAccessError: tried to access field ch.njol.skript.command.Commands.suppressUnknownCommandMessage from class ch.njol.skript.mirre.FilterPrintStream
	at ch.njol.skript.mirre.FilterPrintStream.println(FilterPrintStream.java:27) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.command.ColouredConsoleSender.sendMessage(ColouredConsoleSender.java:60) ~[paperspigot.jar:git-PaperSpigot-8b18730]
	at com.comze_instancelabs.minigamesapi.Arena.init(Arena.java:139) ~[?:?]
	at com.comze_instancelabs.mgskywars.Main.initArena(Main.java:118) ~[?:?]
	at com.comze_instancelabs.mgskywars.Main.loadArenas(Main.java:109) ~[?:?]
	at com.comze_instancelabs.mgskywars.Main.onEnable(Main.java:59) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[paperspigot.jar:git-PaperSpigot-8b18730]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [paperspigot.jar:git-PaperSpigot-8b18730]
	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:145) [PerWorldPlugins.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [paperspigot.jar:git-PaperSpigot-8b18730]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [paperspigot.jar:git-PaperSpigot-8b18730]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [paperspigot.jar:git-PaperSpigot-8b18730]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [paperspigot.jar:git-PaperSpigot-8b18730]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [paperspigot.jar:git-PaperSpigot-8b18730]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [paperspigot.jar:git-PaperSpigot-8b18730]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [paperspigot.jar:git-PaperSpigot-8b18730]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [paperspigot.jar:git-PaperSpigot-8b18730]
	at java.lang.Thread.run(Thread.java:745) `[?:1.8.0_72]

**Comment by bensku** [comment]
1. V7, V8 and V8b are ancient builds, no longer supported. Please use latest version, and then if this persists, I'll take look at it.

The bug is caused by MinigamesLib trying to send colored message to console. Skript filters log using some hacks to prevent console spamming; that causes problems here.

**Comment by ZeTioZ** [comment]
I've tried the latest build but it don't work on 1.8.8 can you give me a build who work on it ?

**Comment by bensku** [comment]
Oh, that explains a lot. I'm surprised that biome mappings actually broke that... Will fix if possible.

**Comment by Arcrimonia** [comment]
Is this going to be fixed anytime soon? I'm needing some of the new features introduced since v10.

**Comment by bensku** [comment]
I'm a bit late, but... Done.
