### ISSUE TITLE
broken database support in dev32

### ISSUE THREAD

**Issue by melinstagibson** [bensku/Skript#955]
I know this is most likely a skellett issue but this code worked in dev31c and now breaks everything in dev32.
Is there any sort of good database support in skript yet? because im happy to switch it just seemed to not work very well in the past.

anyways here is the code:
```
function isonline(p: string) :: boolean:
        set {_r} to mysql result of query "SELECT server FROM playerdata.status WHERE ign='%{_p}%' and (faction=true or safe=true or vanilla=true or lobby=true)"
        set {_rr} to first element of mysql string "server" in {_r}
        if {_rr} is set:
                return true
        else:
                return false
```
and here is the new error. as i said this worked in dev31c
```
[20:21:04 ERROR]: #!#!
[20:21:04 ERROR]: #!#! [Skript] Severe Error:
[20:21:04 ERROR]: #!#! Could not load duel.sk
[20:21:04 ERROR]: #!#!
[20:21:04 ERROR]: #!#! Something went horribly wrong with Skript.
[20:21:04 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[20:21:04 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[20:21:04 ERROR]: #!#! Here is full list of them:
[20:21:04 ERROR]: #!#! skRayFall (http://sk.rayfall.net/) skript-mirror TuSKe (github.com/Tuke-Nuke/TuSKe) skUtilities (https://tim740.github.io/) SkStuff SkQuery Skellett (https://forums.skunity.c
om/resources/skellett-the-addon-with-a-beast-name.24/) MundoSK (https://forums.skunity.com/resources/mundosk.69/) SharpSK
[20:21:04 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[20:21:04 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[20:21:04 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[20:21:04 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[20:21:04 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[20:21:04 ERROR]: #!#! Only if the author tells you to do so, report it as Skript issue (url below)
[20:21:04 ERROR]: #!#! Issue tracker: https://github.com/bensku/Skript/issues (only if you know what you're doing!)
[20:21:04 ERROR]: #!#!
[20:21:04 ERROR]: #!#! Stack trace:
[20:21:04 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for resultset
[20:21:04 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.createExprInfo(SkriptParser.java:1786)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1753)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1501)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1474)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1513)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1447)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1447)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:178)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:491)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:808)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1517)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1447)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1447)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1474)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:178)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:491)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:808)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1517)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1513)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:178)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:59)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:919)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.function.ScriptFunction.<init>(ScriptFunction.java:52)
[20:21:04 ERROR]: #!#!     at ch.njol.skript.lang.function.Functions.loadFunction(Functions.java:134)
[20:21:56 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:584)
[20:21:56 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:347)
[20:21:56 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:359)
[20:21:56 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:392)
[20:21:56 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:188)
[20:21:56 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[20:21:56 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[20:21:56 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:676)
[20:21:56 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:639)
[20:21:56 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:464)
[20:21:56 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427)
[20:21:56 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[20:21:56 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[20:21:56 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[20:21:56 ERROR]: #!#!
[20:21:56 ERROR]: #!#! Version Information:
[20:21:56 ERROR]: #!#!   Skript: 2.2-dev32 (latest)
[20:21:56 ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[20:21:56 ERROR]: #!#!   Minecraft: 1.12.2
[20:21:56 ERROR]: #!#!   Java: 1.8.0_131 (OpenJDK 64-Bit Server VM 25.131-b11)
[20:21:56 ERROR]: #!#!   OS: Linux amd64 4.10.0-22-generic
[20:21:56 ERROR]: #!#!
[20:21:56 ERROR]: #!#! Running CraftBukkit: false
[20:21:56 ERROR]: #!#! Running Spigot (or compatible): true
[20:21:56 ERROR]: #!#! Running Paper (or compatible): true
[20:21:56 ERROR]: #!#!
[20:21:56 ERROR]: #!#! Current node: set {_rr} to first element of mysql string "server" in {_r} (duel.sk, line 7)
[20:21:56 ERROR]: #!#! Current item: null
[20:21:56 ERROR]: #!#! Thread: Server thread
[20:21:56 ERROR]: #!#!
[20:21:56 ERROR]: #!#! Language: english
[20:21:56 ERROR]: #!#! Link parse mode: DISABLED
[20:21:56 ERROR]: #!#!
[20:21:56 ERROR]: #!#! End of Error.
```

**Comment by Pikachu920** [comment]
This doesn't really seem like a skript issue. While skript could be failing to register the type, i think it's more likely a skellett issue. Bensku would know more than me on that though.

**Comment by TheBentoBox** [comment]
Yeah definitely looks like an addon issue to me; @TheLimeGlass any input you can give?

**Comment by Blueyescat** [comment]
He say "worked in dev31c"... If that is right then probably a Skript change or bug.

**Comment by TheLimeGlass** [comment]
I have no clue why this happens, only thing I could think of is you're using an old SkQuery on newer versions of spigot, which causes Skellett to not register that type. I fixed SkQuery up a bit in my edit.

In the latest SkQuery edit I posted a few days ago, I made it so if an enum classinfo is already registered, forget about it, I don't think that is the issue though as it's not registering at all.

Try updating your SkQuery if you haven't, and if that still doesn't work, Skript did some weird things this update.

I plan on making a Skellett extension (which are like Umbaska modules for Skellett 2.0), making a MySQL add-on or add MySQL back to SkQuery. Never the less.

**Comment by melinstagibson** [comment]
i updated skquery too since it caused an error on load. now that i think of it it might work if i remove skquery entirely but i didnt try that. 
removing it isnt an option either way soo..

**Comment by melinstagibson** [comment]
did anyone try this code on dev32 with skquery and skellett?
because im sure its the same issue for everyone. it broke all skripts which use this syntax on all servers when i updated

**Comment by Snow-Pyon** [comment]
This looks like an issue of Skellett/sQuery rather than Skript itself, closing.

**Comment by TheLimeGlass** [comment]
But yet it broke without the addon updating. It broke from Skript updating.

**Comment by bensku** [comment]
I generally do not allow other people than the addon devs themself to report addon issues. That is because we need more details in those cases than scripters are usually able to provide. Basically, details on how the addon works internally.
