### ISSUE TITLE
Latest 1.12.2 Compile with Skript throws error

### ISSUE THREAD

**Issue by hazycraft** [bensku/Skript#964]
[10:48:47 ERROR]: Error occurred while enabling Skript v2.2-dev32 (Is it up to date?)
java.lang.NoSuchFieldError: SHEEP_EAT
	at ch.njol.skript.util.VisualEffect$Type.<clinit>(VisualEffect.java:80) ~[?:?]
	at ch.njol.skript.util.VisualEffect.<clinit>(VisualEffect.java:255) ~[?:?]
	at ch.njol.skript.classes.data.SkriptClasses.<clinit>(SkriptClasses.java:889) ~[?:?]
	at ch.njol.skript.Skript.onEnable(Skript.java:282) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-95dd097-326c2e6]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-95dd097-326c2e6]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-95dd097-326c2e6]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:384) [spigot-1.12.2.jar:git-Spigot-95dd097-326c2e6]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:333) [spigot-1.12.2.jar:git-Spigot-95dd097-326c2e6]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2.jar:git-Spigot-95dd097-326c2e6]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2.jar:git-Spigot-95dd097-326c2e6]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2.jar:git-Spigot-95dd097-326c2e6]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar:git-Spigot-95dd097-326c2e6]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-95dd097-326c2e6]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by bloggy** [comment]
I have the same problem:
https://hastebin.com/foyepewaqa.vbs

Skript does not even start :-(

**Comment by Snow-Pyon** [comment]
This happens only in the latest Spigot 1.12.2 releases, such as the SHEEP_EAT enum value has been removed from the EntityEffect enum as [this commit](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/11f70ddb4786ada16e597a86bd43af50ccaefdb7#src/main/java/org/bukkit/EntityEffect.java) says.

**Comment by bensku** [comment]
Spigot removed functionality from their API without deprecating it first. Besides, as far as I know, no replacement was added.

Not a Skript bug. I'll try talking with Spigot folks, but it'll probably take a few days at least to figure out what is going on.

**Comment by samueleycw** [comment]
latest Bensku's edit dev-32.

[01:02:38] [Server thread/ERROR]: Error occurred while enabling SkQuery v3.5.9a-Lime (Is it up to date?)
java.lang.NoClassDefFoundError: ch/njol/skript/classes/Parser
	at com.w00tmast3r.skquery.SkQuery.onEnable(SkQuery.java:25) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1250]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.2.jar:git-Paper-1250]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [patched_1.12.2.jar:git-Paper-1250]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:386) [patched_1.12.2.jar:git-Paper-1250]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:335) [patched_1.12.2.jar:git-Paper-1250]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.2.jar:git-Paper-1250]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.2.jar:git-Paper-1250]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.2.jar:git-Paper-1250]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292) [patched_1.12.2.jar:git-Paper-1250]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1250]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.ClassNotFoundException: ch.njol.skript.classes.Parser
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_151]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:105) ~[patched_1.12.2.jar:git-Paper-1250]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:90) ~[patched_1.12.2.jar:git-Paper-1250]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
	... 12 more

**Comment by samueleycw** [comment]
Error too. Any hotfix ? Thanks.

[01:02:31] [Server thread/ERROR]: Error occurred while enabling Skript v2.2-dev31c (Is it up to date?)
java.lang.NoSuchFieldError: SHEEP_EAT
	at ch.njol.skript.util.VisualEffect$Type.<clinit>(VisualEffect.java:80) ~[?:?]
	at ch.njol.skript.util.VisualEffect.<clinit>(VisualEffect.java:255) ~[?:?]
	at ch.njol.skript.classes.data.SkriptClasses.<clinit>(SkriptClasses.java:889) ~[?:?]
	at ch.njol.skript.Skript.onEnable(Skript.java:282) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1250]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.2.jar:git-Paper-1250]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [patched_1.12.2.jar:git-Paper-1250]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:386) [patched_1.12.2.jar:git-Paper-1250]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:335) [patched_1.12.2.jar:git-Paper-1250]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.2.jar:git-Paper-1250]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.2.jar:git-Paper-1250]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.2.jar:git-Paper-1250]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292) [patched_1.12.2.jar:git-Paper-1250]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1250]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
[01:02:31] [Server thread/INFO]: [Skript] Disabling Skript v2.2-dev31c

**Comment by bensku** [comment]
Spigot folks were helpful, but couldn't actually resolve the issue. I hope my workaround works, no time for testing today.

**Comment by comonier** [comment]
no stress, no need to worry about more than 1,000 minecraft servers, and 1 million players depending on that solution to work again, because 99% of minecraft server owners prefer to use small skript scripts when use heavy plugins. you're the guy, we love you and your job, and we'll wait for you to get back to skript again

**Comment by Pikachu920** [comment]
I'm not sure if you are trying to be toxic but your sentence comes across like bensku owes the people using the free software he maintains in his own free time continued support (again, for free). If this is what you think, you need to reevaluate whether or not Skript is for you.

**Comment by HYPExMon5ter** [comment]
Yeah I was gonna reply to him but my reply wouldn’t of been the nicest so I just kept my mouth shut

**Comment by comonier** [comment]
fixed on git-Spigot-d21162c-61e0c69 dont need to repair.

**Comment by Pikachu920** [comment]
I'm almost certain you were trying to be toxic, this isn't the first time you've said something like that then deleted it (https://github.com/Rocologo/MobHunting/issues/322). Could be your bad english.

**Comment by bensku** [comment]
Please do not spam the issue tracker.
