### ISSUE TITLE
Problem with loading mc skript

### ISSUE THREAD

**Issue by AnjoYT** [bensku/Skript#972]
[11:15:56 ERROR]: #!#! [Skript] Severe Error:
[11:15:56 ERROR]: #!#! Could not load buc.sk
[11:15:56 ERROR]: #!#!
[11:15:56 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[11:15:56 ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[11:15:56 ERROR]: #!#! and check whether this error has already been reported.
[11:15:56 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[11:15:56 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[11:15:56 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[11:15:56 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[11:15:56 ERROR]: #!#!
[11:15:56 ERROR]: #!#! Stack trace:
[11:15:56 ERROR]: #!#! java.lang.IllegalStateException: Cannot use classinfos until registration is over
[11:15:56 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.checkAllowClassInfoInteraction(Classes.java:240)
[11:15:56 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfoFromUserInput(Classes.java:335)
[11:15:56 ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:370)
[11:15:56 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:409)
[11:15:56 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:243)
[11:15:56 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:200)
[11:15:56 ERROR]: #!#!     at ch.njol.skript.Skript.reload(Skript.java:722)
[11:15:56 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:161)
[11:15:56 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[11:15:56 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140)
[11:15:56 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:631)
[11:15:56 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:617)
[11:15:56 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:408)
[11:15:56 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:372)
[11:15:56 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:651)
[11:15:56 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:555)
[11:15:56 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[11:15:56 ERROR]: #!#!
[11:15:56 ERROR]: #!#! Version Information:
[11:15:56 ERROR]: #!#!   Skript: 2.2-dev29
[11:15:56 ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[11:15:56 ERROR]: #!#!   Minecraft: 1.12.2
[11:15:56 ERROR]: #!#!   Java: 1.8.0_151 (Java HotSpot(TM) 64-Bit Server VM 25.151-b12)
[11:15:56 ERROR]: #!#!   OS: Linux amd64 3.16.0-4-amd64
[11:15:56 ERROR]: #!#!
[11:15:56 ERROR]: #!#! Running CraftBukkit: false
[11:15:56 ERROR]: #!#!
[11:15:56 ERROR]: #!#! Current node: command /dropchest [<text>] [<offlineplayer>]: (buc.sk, line 105)
[11:15:56 ERROR]: #!#! Current item: null
[11:15:56 ERROR]: #!#!
[11:15:56 ERROR]: #!#! Thread: Server thread
[11:15:56 ERROR]: #!#!
[11:15:56 ERROR]: #!#! End of Error.
[11:15:56 ERROR]: #!#!
[11:15:56 WARN]: No scripts were found, maybe you should write some ;)
[11:15:56 INFO]: [Skript] Encountered 1 error while reloading the config and all scripts!

**Comment by bensku** [comment]
You use old Skript version. Please try with latest one.
