### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by BallisticDev** [bensku/Skript#973]
[23:57:37 INFO]: [Skript] Enabling Skript v2.1.2
[23:57:37 INFO]: [Skript] Successfully generated the config, the example scripts and the aliases files.
[23:57:37 ERROR]: Error occurred while enabling Skript v2.1.2 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.DyeColor.getData()B
at ch.njol.skript.util.Color.(Color.java:82) ~[?:?]
at ch.njol.skript.SkriptCommand.(SkriptCommand.java:60) ~[?:?]
at ch.njol.skript.Skript.onEnable(Skript.java:254) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-d21162c-61e0c69]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-d21162c-61e0c69]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-d21162c-61e0c69]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:384) [spigot-1.12.2.jar:git-Spigot-d21162c-61e0c69]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:333) [spigot-1.12.2.jar:git-Spigot-d21162c-61e0c69]
at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2.jar:git-Spigot-d21162c-61e0c69]
at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2.jar:git-Spigot-d21162c-61e0c69]
at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2.jar:git-Spigot-d21162c-61e0c69]
at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar:git-Spigot-d21162c-61e0c69]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-d21162c-61e0c69]
at java.lang.Thread.run(Unknown Source) [?:?]

**Comment by TheBentoBox** [comment]
You're not even using this fork. You shouldn't make an issue report here unless you're using the latest version from [this page](https://github.com/bensku/Skript/releases).
