### ISSUE TITLE
Craftbukkit 1.12.1 error...

### ISSUE THREAD

**Issue by MalexTP** [bensku/Skript#980]
[18:39:46 INFO]: This server is running CraftBukkit version git-Bukkit-8f47214 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)
[18:39:46 INFO]: [Skript] Loading Skript v2.2-dev32b
[18:39:59 INFO]: [Skript] Enabling Skript v2.2-dev32b
[18:40:00 INFO]: [Skript] Successfully generated the config, the example scripts and the aliases files.
[18:40:00 ERROR]: Error occurred while enabling Skript v2.2-dev32b (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.Effect.getName()Ljava/lang/String;
	at ch.njol.skript.util.VisualEffect$Type.<init>(VisualEffect.java:196) ~[?:?]
	at ch.njol.skript.util.VisualEffect$Type.<clinit>(VisualEffect.java:63) ~[?:?]
	at ch.njol.skript.util.VisualEffect.<clinit>(VisualEffect.java:269) ~[?:?]
	at ch.njol.skript.classes.data.SkriptClasses.<clinit>(SkriptClasses.java:889) ~[?:?]
	at ch.njol.skript.Skript.onEnable(Skript.java:282) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[craftbukkit-1.12.1.jar:git-Bukkit-8f47214]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) [craftbukkit-1.12.1.jar:git-Bukkit-8f47214]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:401) [craftbukkit-1.12.1.jar:git-Bukkit-8f47214]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:370) [craftbukkit-1.12.1.jar:git-Bukkit-8f47214]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:331) [craftbukkit-1.12.1.jar:git-Bukkit-8f47214]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:412) [craftbukkit-1.12.1.jar:git-Bukkit-8f47214]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:373) [craftbukkit-1.12.1.jar:git-Bukkit-8f47214]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:328) [craftbukkit-1.12.1.jar:git-Bukkit-8f47214]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:248) [craftbukkit-1.12.1.jar:git-Bukkit-8f47214]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:522) [craftbukkit-1.12.1.jar:git-Bukkit-8f47214]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]

**Comment by HYPExMon5ter** [comment]
This fork doesn’t support craftbukkit, switch to spigot or paperspigot
