### ISSUE TITLE
Error on Spigot 1.12.2.

### ISSUE THREAD

**Issue by TheIntelloBox** [bensku/Skript#986]
[22:08:57] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'sk' in plugin Skript v2.2-dev32b
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at us.Myles.PWP.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:95) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:651) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1392) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1227) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.NoSuchMethodError: ch.njol.skript.command.Commands.loadCommand(Lch/njol/skript/config/SectionNode;Z)Lch/njol/skript/command/ScriptCommand;
	at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:571) ~[?:?]
	at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:347) ~[?:?]
	at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:359) ~[?:?]
	at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:289) ~[?:?]
	at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:319) ~[?:?]
	at ch.njol.skript.Skript.reload(Skript.java:700) ~[?:?]
	at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:161) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.12.2.jar:git-Spigot-5695bca-53fccdf]
	... 15 more

**Comment by bensku** [comment]
Interesting. Try without PerWorldPlugins.

**Comment by TheIntelloBox** [comment]
I think this is the fault of PWP because the plugins generates error with every plugin.

**Comment by bensku** [comment]
Ok, good to know.
