### ISSUE TITLE
Bug in my skript

### ISSUE THREAD

**Issue by kimidu1609** [bensku/Skript#989]
Hello, I have a problem with my skript, it does not work anymore but yesterday it worked well sorry for the spelling I am French. I send you the critical errors. I also use spigot 1.9

[14:54:32] [Server thread/ERROR]: Error occurred while enabling Skript v2.2-dev32b (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/event/entity/EntityToggleGlideEvent
	at ch.njol.skript.events.SimpleEvents.<clinit>(SimpleEvents.java:383) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_25]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_25]
	at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:108) ~[?:?]
	at ch.njol.skript.Skript.onEnable(Skript.java:290) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[Spigot.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [Spigot.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [Spigot.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [Spigot.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [Spigot.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.reload(CraftServer.java:745) [Spigot.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.Bukkit.reload(Bukkit.java:539) [Spigot.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [Spigot.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [Spigot.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) [Spigot.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchServerCommand(CraftServer.java:631) [Spigot.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.DedicatedServer.aL(DedicatedServer.java:437) [Spigot.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:401) [Spigot.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655) [Spigot.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554) [Spigot.jar:git-Spigot-7d15d07-c194444]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
Caused by: java.lang.ClassNotFoundException: org.bukkit.event.entity.EntityToggleGlideEvent
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[Spigot.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[Spigot.jar:git-Spigot-7d15d07-c194444]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_25]
	... 21 more
[14:54:32] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[14:54:32] [Server thread/INFO]: CONSOLE: [0;32;1mReload complete.[m
[14:55:22] [Server thread/INFO]: [0;37;22m[[0;33;22mSkript[0;37;22m][m Reloading [0;33;22mBedwars.sk[m...[m
[14:55:23] [Server thread/ERROR]: #!#! 
[14:55:23] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[14:55:23] [Server thread/ERROR]: #!#! Could not load Bedwars.sk
[14:55:23] [Server thread/ERROR]: #!#! 
[14:55:23] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[14:55:23] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[14:55:23] [Server thread/ERROR]: #!#! You should report it at https://github.com/bensku/Skript/issues. Please copy paste this report there (or use paste service).
[14:55:23] [Server thread/ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[14:55:23] [Server thread/ERROR]: #!#! 
[14:55:23] [Server thread/ERROR]: #!#! Stack trace:
[14:55:23] [Server thread/ERROR]: #!#! java.lang.IllegalStateException: Cannot use classinfos until registration is over
[14:55:23] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Classes.checkAllowClassInfoInteraction(Classes.java:241)
[14:55:23] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfos(Classes.java:246)
[14:55:23] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:415)
[14:55:23] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Classes.parse(Classes.java:450)
[14:55:23] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:563)
[14:55:23] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:808)
[14:55:23] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1517)
[14:55:23] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1207)
[14:55:23] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1183)
[14:55:23] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:603)
[14:55:23] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:347)
[14:55:23] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader$$Lambda$2/9651482.run(Unknown Source)
[14:55:23] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:359)
[14:55:23] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:392)
[14:55:23] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:188)
[14:55:23] [Server thread/ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[14:55:23] [Server thread/ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[14:55:23] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645)
[14:55:23] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchServerCommand(CraftServer.java:631)
[14:55:23] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R1.DedicatedServer.aL(DedicatedServer.java:437)
[14:55:23] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:401)
[14:55:23] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655)
[14:55:23] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554)
[14:55:23] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[14:55:23] [Server thread/ERROR]: #!#! 
[14:55:23] [Server thread/ERROR]: #!#! Version Information:
[14:55:23] [Server thread/ERROR]: #!#!   Skript: 2.2-dev32b
[14:55:23] [Server thread/ERROR]: #!#!   Bukkit: 1.9-SNAPSHOT
[14:55:23] [Server thread/ERROR]: #!#!   Minecraft: 1.9
[14:55:23] [Server thread/ERROR]: #!#!   Java: 1.8.0_25 (Java HotSpot(TM) Client VM 25.25-b02)
[14:55:23] [Server thread/ERROR]: #!#!   OS: Windows 8.1 x86 6.3
[14:55:23] [Server thread/ERROR]: #!#! 
[14:55:23] [Server thread/ERROR]: #!#! Running CraftBukkit: false
[14:55:23] [Server thread/ERROR]: #!#! Running Spigot (or compatible): true
[14:55:23] [Server thread/ERROR]: #!#! Running Paper (or compatible): false
[14:55:23] [Server thread/ERROR]: #!#! 
[14:55:23] [Server thread/ERROR]: #!#! Current node: every {@fer} seconds: (Bedwars.sk, line 25)
[14:55:23] [Server thread/ERROR]: #!#! Current item: null
[14:55:23] [Server thread/ERROR]: #!#! Thread: Server thread
[14:55:23] [Server thread/ERROR]: #!#! 
[14:55:23] [Server thread/ERROR]: #!#! Language: english
[14:55:23] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[14:55:23] [Server thread/ERROR]: #!#! 
[14:55:23] [Server thread/ERROR]: #!#! End of Error.
[14:55:23] [Server thread/ERROR]: #!#!

**Comment by bensku** [comment]
It seems 1.9 is missing that particular event. My mistake not to check it exists.

**Comment by kimidu1609** [comment]
Hello ! Thank you for your reply ! It seems to me that all my skripts are infected even small simple skripts: / In all versions this bug comes back, I also want to say that I did not touch the skript, it did not start to walk any more alone

**Comment by kimidu1609** [comment]
UP pleese it’s urgent

**Comment by bensku** [comment]
Well, I fixed it a bit before you commented. And pushed and released a bit after that.

**Comment by kimidu1609** [comment]
Hello, the problem persist

**Comment by bensku** [comment]
Post full console log. It is probably a different problem.

Also: try without any addons, compile latest Spigot and see what happens.
