### ISSUE TITLE
Force Respawn error

### ISSUE THREAD

**Issue by Sodies** [bensku/Skript#997]
[19:17:14 ERROR]: #!#! If the error doesn't disappear even after disabling all l
isted plugins, it is probably Skript issue.
[19:17:14 ERROR]: #!#! In that case, you will be given instruction on how should
 you report it.
[19:17:14 ERROR]: #!#! On the other hand, if the error disappears when disabling
 some plugin, report it to author of that plugin.
[19:17:14 ERROR]: #!#! Only if the author tells you to do so, report it as Skrip
t issue (url below)
[19:17:14 ERROR]: #!#! Issue tracker: https://github.com/bensku/Skript/issues (o
nly if you know what you're doing!)
[19:17:14 ERROR]: #!#!
[19:17:14 ERROR]: #!#! Stack trace:
[19:17:14 ERROR]: #!#! java.lang.NullPointerException
[19:17:14 ERROR]: #!#!     at com.gmail.thelimeglass.Effects.EffForceRespawn.exe
cute(EffForceRespawn.java:32)
[19:17:14 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[19:17:14 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.j
ava:61)
[19:17:14 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.j
ava:89)
[19:17:14 ERROR]: #!#!     at ch.njol.skript.effects.Delay$1.run(Delay.java:101)

[19:17:14 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTas
k.run(CraftTask.java:71)
[19:17:14 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftSch
eduler.mainThreadHeartbeat(CraftScheduler.java:353)
[19:17:14 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(Mi
necraftServer.java:739)
[19:17:14 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(De
dicatedServer.java:406)
[19:17:14 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(Mi
necraftServer.java:679)
[19:17:14 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(

[19:17:14 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[19:17:14 ERROR]: #!#!
[19:17:14 ERROR]: #!#! Version Information:
[19:17:14 ERROR]: #!#!   Skript: 2.2-dev32c (latest)
[19:17:14 ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[19:17:14 ERROR]: #!#!   Minecraft: 1.12.2
[19:17:14 ERROR]: #!#!   Java: 1.8.0_111 (Java HotSpot(TM) 64-Bit Server VM 25.1
11-b14)
[19:17:14 ERROR]: #!#!   OS: Windows 7 amd64 6.1
[19:17:14 ERROR]: #!#!
[19:17:14 ERROR]: #!#! Running CraftBukkit: false
[19:17:14 ERROR]: #!#! Running Spigot (or compatible): true
[19:17:14 ERROR]: #!#! Running Paper (or compatible): false
[19:17:14 ERROR]: #!#!
[19:17:14 ERROR]: #!#! Current node: null
[19:17:14 ERROR]: #!#! Current item: [skellett] [force] respawn %player%
[19:17:14 ERROR]: #!#! Thread: Server thread
[19:17:14 ERROR]: #!#!
[19:17:14 ERROR]: #!#! Language: english
[19:17:14 ERROR]: #!#! Link parse mode: DISABLED
[19:17:14 ERROR]: #!#!
[19:17:14 ERROR]: #!#! End of Error.
[19:17:14 ERROR]: #!#!
>

**Comment by Blueyescat** [comment]
This is an addon issue. As you have Skript 2.2-dev21+, you can do it with only Skript: https://bensku.github.io/Skript/effects.html#EffRespawn

**Comment by TheBentoBox** [comment]
Yeah as @Blueyescat just use the vanilla effect, and you generally don't report issues with addons here.
