### ISSUE TITLE
No class info found for resultset.

### ISSUE THREAD

**Issue by SzymoonDev** [bensku/Skript#998]
Hi,
Last, i decided to update Skript plugin. Recently, i used dev31, with Skellett and SkQuery. I updated to dev32, newest version. My script use Skellett mysql, and when it starts, console shows this error:
```
[14:46:37] [Server thread/ERROR]: #!#! 
[14:46:37] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[14:46:37] [Server thread/ERROR]: #!#! Could not load hub.sk
[14:46:37] [Server thread/ERROR]: #!#! 
[14:46:37] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[14:46:37] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[14:46:37] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[14:46:37] [Server thread/ERROR]: #!#! Here is full list of them:
[14:46:37] [Server thread/ERROR]: #!#! skRayFall (http://sk.rayfall.net/) SkQuery Skellett (https://forums.skunity.com/resources/skellett-the-addon-with-a-beast-name.24/) TuSKe (github.com/Tuke-Nuke/TuSKe) 
[14:46:37] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[14:46:37] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[14:46:37] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[14:46:37] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[14:46:37] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[14:46:37] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it as Skript issue (url below)
[14:46:37] [Server thread/ERROR]: #!#! Issue tracker: https://github.com/bensku/Skript/issues (only if you know what you're doing!)
[14:46:37] [Server thread/ERROR]: #!#! 
[14:46:37] [Server thread/ERROR]: #!#! Stack trace:
[14:46:37] [Server thread/ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for resultset
[14:46:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[14:46:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.createExprInfo(SkriptParser.java:1786)
[14:46:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1753)
[14:46:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1501)
[14:46:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1474)
[14:46:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1513)
[14:46:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1447)
[14:46:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1440)
[14:46:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[14:46:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:178)
[14:46:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:491)
[14:46:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:808)
[14:46:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1517)
[14:46:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1513)
[14:46:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[14:46:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:178)
[14:46:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:59)
[14:46:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:919)
[14:46:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:54)
[14:46:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Conditional.<init>(Conditional.java:44)
[14:46:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1005)
[14:46:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.ScriptFunction.<init>(ScriptFunction.java:52)
[14:46:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.function.Functions.loadFunction(Functions.java:134)
[14:46:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:584)
[14:46:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:347)
[14:46:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:359)
[14:46:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:289)
[14:46:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:319)
[14:46:37] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript$2.run(Skript.java:409)
[14:46:37] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
[14:46:37] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[14:46:37] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738)
[14:46:37] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405)
[14:46:37] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
[14:46:37] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
[14:46:37] [Server thread/ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[14:46:37] [Server thread/ERROR]: #!#! 
[14:46:37] [Server thread/ERROR]: #!#! Version Information:
[14:46:37] [Server thread/ERROR]: #!#!   Skript: 2.2-dev32b
[14:46:37] [Server thread/ERROR]: #!#!   Bukkit: 1.12-R0.1-SNAPSHOT
[14:46:37] [Server thread/ERROR]: #!#!   Minecraft: 1.12
[14:46:37] [Server thread/ERROR]: #!#!   Java: 1.8.0_144 (Java HotSpot(TM) 64-Bit Server VM 25.144-b01)
[14:46:37] [Server thread/ERROR]: #!#!   OS: Linux amd64 3.13.0-132-generic
[14:46:37] [Server thread/ERROR]: #!#! 
[14:46:37] [Server thread/ERROR]: #!#! Running CraftBukkit: false
[14:46:37] [Server thread/ERROR]: #!#! Running Spigot (or compatible): true
[14:46:37] [Server thread/ERROR]: #!#! Running Paper (or compatible): false
[14:46:37] [Server thread/ERROR]: #!#! 
[14:46:37] [Server thread/ERROR]: #!#! Current node: set {_final::*} to skellett mysql string "%{_id}%" in {_result} (hub.sk, line 13)
[14:46:37] [Server thread/ERROR]: #!#! Current item: null
[14:46:37] [Server thread/ERROR]: #!#! Thread: Server thread
[14:46:37] [Server thread/ERROR]: #!#! 
[14:46:37] [Server thread/ERROR]: #!#! Language: english
[14:46:37] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[14:46:37] [Server thread/ERROR]: #!#! 
[14:46:37] [Server thread/ERROR]: #!#! End of Error.
[14:46:37] [Server thread/ERROR]: #!#! 
```

My script:
```
function mysql_checkData(p: text, id: text, type: text) :: text:
	set {_result} to mysql result of query "SELECT * FROM data WHERE playername = '%{_p}%';"
	if {_type} is "string":
		set {_final::*} to skellett mysql string "%{_id}%" in {_result}
	if {_type} is "number" or "integer":
		set {_final::*} to skellett mysql integer "%{_id}%" in {_result}
	if {_type} is "boolean":
		set {_final::*} to skellett mysql boolean "%{_id}%" in {_result}
	return "%{_final::*}%"
```

Whats the problem? Can you help me, idk whats happend. Now, i must use dev31, but the scripts load very long.
Sorry for english. Hold on.

**Comment by melinstagibson** [comment]
dev32 breaks skellett and it doesnt seem like there will be a fix for it.
skript-db might be an alternative altho it wont work if you use mariadb...

**Comment by SzymoonDev** [comment]
Eh, @bensku or @TheLimeGlass have to fix it, couse Skellett loses one of the most important features...
Come on, they'll make it.

**Comment by Snow-Pyon** [comment]
LimeGlass is recoding his addons so he won't release any release of the current Skellett unless it's a security issue I guess.

Anyways this has nothing to do with Skript therefore it should be closed, just do what the guy above me said and use skript-db.

**Comment by SzymoonDev** [comment]
Why you close it? Its skript problem, not Skellett or SkQuery. On previous versions of Skript, all works correctly.

**Comment by Snow-Pyon** [comment]
>Why you close it? Its skript problem, not Skellett or SkQuery. On previous versions of Skript, all works correctly.

It isn't, it's a conflict Skellett has with the latest version of Skript, that's something the addon developer should fix on their side.

**Comment by bensku** [comment]
The error message clearly lists the plugins you should remove before reporting there. It offers and alternative of contacting addon author, then perhaps reporting there. You should do that.
